### ISSUE TITLE
slider updates too fast for a slow dimmer

### ISSUE THREAD

**Issue by eprst** [openhab/openhab-android#1008]
I have a zwave dimmer which is slow to change it's brightness, "Command Poll Period" is set to 3 seconds in device settings. Corresponding Slider works correctly in PaperUI but jumps back after being adjusted in the Android app (and in IOS app too BTW), I guess it polls for a state update too soon.

### Actual behavior
Slider value jumps back after being adjusted and only receives correct value after about a minute

### Expected behavior
Slider should keep the value it was set to, or at least reflect the correct value once the device is polled (after 3 second)
 
### Steps to reproduce
Not sure how to simulate an item with a slow update. In my particular case this happens with Evolve LRM-AS dimmers.

### Can you reproduce the issue in demo mode?
no

#### Client
* Android version: 8.0.0, 
* Device model: OnePlus 3T
* Stock or customized ROM: Stock Oxygen 5.0.0
* App version: 2.2.0 
* Build flavor: Full 
* Device language: en_us 

#### Server
* Server version: 2.3.0-1
* Reverse Proxy: no
* Authentication method: None

**Comment by mueller-ma** [comment]
Can you check if the issue is still present in the latest beta?

**Comment by sam2b** [comment]
I have the same problem with the same Evolve dimmer.  Notr the problem is not specific to the Android app.

**Comment by mueller-ma** [comment]
I don't own a device to test this. And since it's not android client specific, can you open an issue in the addons repo?
