### ISSUE TITLE
Spam when installing openhab from playstore

### ISSUE THREAD

**Issue by lukasb01** [openhab/openhab-android#1009]
### Actual behaviour
Describe us what happens
When I install openhab2 from play Store My phone start to get spam from things to install.
In play store there is only 2 openhab2 programs to download , one is the beta
When I uninstall openhab2 it stop. openhab2 is the only program i use from play store.
I even tried the beta version and I get the same spam
![image](https://user-images.githubusercontent.com/40789411/45789230-e04f6180-bc7e-11e8-9d85-3fe25620ef6e.png)

### Expected behaviour
Describe us what should happen
No spam
 
### Steps to reproduce
1. Describe us how to reproduce the issue
2. Use a list for it

#### Client
* Android version: 
* Device model: 
* Stock or customized ROM: 
* App version : 
* Build flavor : 
* Device language: 

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: 
* Authentication method : 

#### App log
```
Insert your log here
```

#### openHAB Server log
```
Insert your log here. If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here.
For nginx: `/var/log/nginx/error.log`
For Apache 2: `/var/log/apache2/error.log`
```
```
Insert your reverse proxy access log here
For nginx: `/var/log/nginx/access.log`
For Apache 2: `/var/log/apache2/access.log`
```

**Comment by kaikreuzer** [comment]
For such overlays, an app requires a special permission, which is not requested by the openHAB app - I am thus pretty sure that the openHAB app is NOT the culprit.

Please search in your android settings for "overlay" and you should find a menu where you can see all apps that have the overlay permission. Deactivate it one by one to find out which app spams you.

**Comment by mueller-ma** [comment]
I can confirm that the app does **not** show adds. Please check all other installed apps for the "Draw over other apps" permission.
I would never install apps that don't come from Google Play (They try their best to remove such apps) or F-Droid (It's fully opensource and transparent).
