### ISSUE TITLE
Target Android Oreo (API level 26)

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-android#1010]
I've received the following e-mail from Google:

> Hello Google Play Developer,
>
> This is a reminder that starting November 1, 2018, updates to apps and games on Google Play will be required to target Android Oreo (API level 26) or higher. After this date, the Play Console will prevent you from submitting new APKs with a targetSdkVersion less than 26.
>
> Configuring your app to target a recent API level ensures that users benefit from significant security and performance improvements, while still allowing your app to run on older Android versions (down to the minSdkVersion).
>
> Action required
>
> Please ensure that your apps are configured to target at least Android 8.0 (API level 26) by November 1, 2018. For technical advice on how to change your app's target API level to meet these requirements, refer to the migration guide.
>
> Affected apps
>
> The apps included below have one or more APKs—in production or testing tracks—that aren't currently targeting API level 26 or higher. Apps are listed with the maximum version code and corresponding targetSdkVersion. If you have more than 20 apps that could be affected in your account, please check the Play Console for a full list.
>
> org.openhab.habdroid   59   25

Sounds as if we need to do a release before Nov 1 that addresses this (if this is already addressed, then simply please ignore and close this issue :-))

**Comment by mueller-ma** [comment]
Thanks to @maniac103 the beta version is already targetApi 27. We want to have one PR merged (and one for the translations) before a new version will be released: https://github.com/openhab/openhab-android/issues/549

**Comment by kaikreuzer** [comment]
Wonderful, thank you both 👍
