### ISSUE TITLE
Crowdin export of Chinese translation broken

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1036]
@kaikreuzer Can you add a mapping of Chinese Simpliefied to `zh-rCN`, like it's done for Portuguese, Brazilian?

**Comment by mueller-ma** [comment]
We should also add Spanish United States and a mapping to es-rUS.

**Comment by kaikreuzer** [comment]
Sorry, it took me a while, but both languages should now be set up!
