### ISSUE TITLE
2.3.0 isn't available on Google Play

### ISSUE THREAD

**Issue by Misiu** [openhab/openhab-android#1038]
### Actual behaviour

When going to https://play.google.com/store/apps/details?id=org.openhab.habdroid I see that 2.2.0 is the latest release:
![screenshot_20](https://user-images.githubusercontent.com/1741838/46811970-11015300-cd74-11e8-9805-b2d7ea2b0b7d.png)

current version: 2.2.0
release date: 24 September 2018

but on release tab, I see that the latest stable release it 2.3.0 - https://github.com/openhab/openhab-android/releases/tag/2.3.0-release

### Expected behaviour
Version 2.3.0 should be available do download from Google Play

**Comment by mueller-ma** [comment]
The distribution of 2.3.0 has been paused because of #1018

**Comment by Misiu** [comment]
@mueller-ma sorry, I didn't notice that issue. Thanks for the update.
