### ISSUE TITLE
Class AbstractConnection overrides hashCode but not equals.

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1039]
@maniac103 @FlorianSW 
LGTM reports that AbstractConnection overrides hashCode, but not equals. I haven't found a usage of hashCode in the app, so should I delete it or implement an equals function?
https://lgtm.com/projects/g/openhab/openhab-android/snapshot/efa4b6914c955d27b32be61e15b94c3aa6cfe924/files/mobile/src/main/java/org/openhab/habdroid/core/connection/AbstractConnection.java?sort=name&dir=ASC&mode=heatmap&showExcluded=false#xa57451efcbb6caec:1

**Comment by maniac103** [comment]
You won't find it as it's used mostly by the Map and  Set implementations. As Connections aren't put in any of those (anymore), I think we don't need it anymore.
