### ISSUE TITLE
"Info ssl client cert" tooltip has bright background in dark themes

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1058]
### Actual behaviour
"Info ssl client cert" tooltip has bright background in dark themes, which makes the tooltip hard to read.

### Expected behaviour
"Info ssl client cert" tooltip should have a dark background.

#### Client
* Android version: 5.1.1

**Comment by mueller-ma** [comment]
Still happens in API 25

**Comment by maniac103** [comment]
I'll check it.
