### ISSUE TITLE
Show a hint on a subpage containing no elements

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1062]
I have a subpage that contains items that are visible under some conditions. It may happen that no item is shown. Whenever this happens my first thought is: "Oh, the app didnt load the page." until I realise that nothing should be shown on this page.
I don't think that I'm the only one who has this thought, so maybe we should add some hint:
1. Just display a hint: "This page contains no elements"
2. Display a hint and a material like image, e.g. from Signal: https://github.com/signalapp/Signal-Android/blob/master/res/drawable-xxxhdpi/conversation_list_empty_state.png
3. Display a funny "Nothing to see here" meme: https://duckduckgo.com/?q=nothing+to+see+here+meme&t=ffab&iar=images&iax=images&ia=images

**Comment by maniac103** [comment]
1 and 2 sound good to me ... I'd prefer 2 if we found a good image. Not a fan of 3 ;-)

**Comment by mueller-ma** [comment]
3 is also problematic because of copyright claims and apk size.
