### ISSUE TITLE
Svg icons not scaling

### ISSUE THREAD

**Issue by erhapp** [openhab/openhab-android#1069]
Some Svg icons are not scaled correctly. This results in icons that are only partially displayed.

**Comment by mueller-ma** [comment]
Please do not remove the issue template. Can you add a screenshot and the svg file?

**Comment by erhapp** [comment]
Here are two examples ([icons.zip](https://github.com/openhab/openhab-android/files/2516067/icons.zip))

ps: I'm sorry about the template. It seems to be missing from the mobile version of github.

![data-screenshot](https://user-images.githubusercontent.com/602331/47518660-e347fe00-d88b-11e8-94a3-af4214298863.png)

![printer-screenshot](https://user-images.githubusercontent.com/602331/47518662-e3e09480-d88b-11e8-9070-2b0dfeeacf8a.png)

**Comment by mueller-ma** [comment]
This sounds like https://github.com/openhab/openhab-android/issues/913. Which version do you use?

**Comment by erhapp** [comment]
2.2.0 - 22 May 2018 20:29:52

(The current version in the Android app-store)

**Comment by mueller-ma** [comment]
This has been fixed in 2.2.5-beta. You can wait until 2.4.0 in the stable channel or download the beta.
