### ISSUE TITLE
Notifications can't be scrolled anymore

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#1072]
### Actual behaviour
I noticed in 2.3.8 and verified with 2.3.0 (both installed on same phone) that pagination of the notification activity is not working anymore. Scrolling to the bottom does not cause loading of more events.

### Expected behaviour
When in Notifications, the page may be scrolled and events were being loaded screen-by-screen.
 
### Steps to reproduce
1. Open app, goto notifications
2. Scroll down (more events should be loaded)

### Can you reproduce the issue in demo mode?
No, as there is no notifications activity.

#### Client
* Android version: 6.0.1
* Device model: Xiaomi Redmi 4 Prime
* Stock or customized ROM: Stock
* App version : 2.3.8 and 2.3.0
* Build flavor : Full
* Device language: German

#### Server
* Server version:
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method : user+pass

**Comment by Jochen1980** [comment]
How can we reproduce this bug? Would it be appropriate try to add such notifications to the demo?

Best regards,
Jochen

**Comment by maniac103** [comment]
This is an myopenhab issue: https://github.com/openhab/openhab-cloud/issues/222

**Comment by mueller-ma** [comment]
> How can we reproduce this bug?

I need to connect your openhab server to https://myopenhab.org or setup your own openhab cloud instance.

> Would it be appropriate try to add such notifications to the demo?

For the demo server it might be a solution to add some static api responses for the notification api.

**Comment by maniac103** [comment]
This will be fixed via https://github.com/openhab/openhab-cloud/pull/245 once the new code base is deployed to myopenhab.org.

**Comment by Landstad** [comment]
Hello @maniac103,

 do you know apprx when this will happen (i e deployment to myopenhab)?

**Comment by maniac103** [comment]
> do you know apprx when this will happen (i e deployment to myopenhab)?

Unfortunately I don't; deploying is up to @digitaldan ... hence your question in https://github.com/openhab/openhab-cloud/pull/222 probably was at the right place.

**Comment by Landstad** [comment]
@maniac103 alright, thanks.

**Comment by mueller-ma** [comment]
The fix has been deployed.
