### ISSUE TITLE
RTL language phone icons/text alignment

### ISSUE THREAD

**Issue by gargamelonly** [openhab/openhab-android#1076]
running https://github.com/openhab/openhab-android/tree/2.3.9-beta 
screen capture attached.
icons/text/> appear not in correct location when mixing Hebrew and English sitemap.
In the capture, the green tree is in the correct location the submenu mark "<" should be in the opposite direction "<"
other items written in English should be near icons, currently left aligned.
@mueller-ma 
![screenshot_20181102-171733_openhab beta](https://user-images.githubusercontent.com/29747434/47924438-5ffa5e00-dec4-11e8-8d86-8e9dd8f66b63.jpg)

**Comment by maniac103** [comment]
I don't think we can change the text alignment. The text covers all space between icon and value (or '>' mark) and Android decides about left or right alignment based on the content. Also, where do you see misplaced icons in that screenshot?
Agree about the '>' mark though. Achieving that probably is as easy as adding an android:autoMirrored attribute to the drawable.

**Comment by mueller-ma** [comment]
I guess the graph icon itself is incorrect, because the arrows go from left to right? A change of this is out of scope of the app. A parameter should be added to the icon request to indicate RTL if that's an issue.

@gargamelonly Can you post your sitemap for testing purposes?

**Comment by mueller-ma** [comment]
Setting `autoMirrored` works for the arrows. The textview direction can be forced to be the systems default by setting `android:textDirection="locale"`. I added this attribute to all item labels and values, but now also numbers are mirrored `C° 7.0`. @gargamelonly Is that or `7.0 °C` correct?

LTR:
![de 1](https://user-images.githubusercontent.com/22525368/47944102-eaa98000-def9-11e8-837d-ce432a3d7c9f.png)
![de 2](https://user-images.githubusercontent.com/22525368/47944103-eb421680-def9-11e8-9022-1e85140f704f.png)

RTL:
![iw 1](https://user-images.githubusercontent.com/22525368/47944105-eed59d80-def9-11e8-934c-e3995cb7d561.png)
![iw 2](https://user-images.githubusercontent.com/22525368/47944106-eed59d80-def9-11e8-915f-f560766aca2e.png)

**Comment by mueller-ma** [comment]
@gargamelonly Are there any icons in the settings or about page that should be mirrored?

**Comment by gargamelonly** [comment]
> 
> 
> @gargamelonly Are there any icons in the settings or about page that should be mirrored?

About page and settings look ok.
See attached captures.

![screenshot_20181103-103048_openhab beta](https://user-images.githubusercontent.com/29747434/47949963-ec079680-df53-11e8-8484-55ba4181762e.jpg)
![screenshot_20181103-103054_openhab beta](https://user-images.githubusercontent.com/29747434/47949964-ec079680-df53-11e8-9833-d0c4de40b1ec.jpg)
![screenshot_20181103-103107_openhab beta](https://user-images.githubusercontent.com/29747434/47949965-ec079680-df53-11e8-9f66-7b7029606516.jpg)

**Comment by mueller-ma** [comment]
I'll upload my code, open a PR and attach a debug apk, so you can test it.
About the settings screen: Shouldn't "Eclipse Public License..." be on the right site?
About the about screen: Shouldn't the demo mode icon be mirrored? In which direction does progress bars go?

**Comment by gargamelonly** [comment]
Hi,
The text "Eclipse Public License..." can be on the right. Personally it is not major.
About screen, "Demo mode" icon mirrored, also not major. It looks ok as it is.
Progress bars can be on the left side of the window.

**Comment by mueller-ma** [comment]
I've created https://github.com/daniel-stoneuk/material-about-library/issues/89 for the issues in the About screen.
