### ISSUE TITLE
Default sitemap is set to "default" when enabling demo mode.

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1083]
### Actual behaviour
The default sitemap is "default" after using demo mode.

### Expected behaviour
The default sitemap for demo mode and for regular connections should be different.

 
### Steps to reproduce
1. Have a server with at least two sitemaps. One must be "default", the other one e.g. "foo".
2. Connect to your server
3. Select "foo" as default sitemap
4. Enable demo mode
5. The demo server contains only one sitemap, so this one is saved as default
6. Disable demo mode
7. Your default sitemap isn't "foo" anymore

**Comment by JohannesPtaszyk** [comment]
I'll can have a look to this.
