### ISSUE TITLE
Webview no longer displays Grafana panels

### ISSUE THREAD

**Issue by tobiasisenberg** [openhab/openhab-android#1087]
### Actual behaviour
Starting with version 2.3.7-beta, Webview items no longer display Grafana panels. In versions up to 2.3.6-beta, a Webview items such as this one

`Webview url="https://snapshot.raintank.io/dashboard-solo/snapshot/y7zwi2bZ7FcoTlB93WN7yWO4aMiz3pZb?from=1493369923321&to=1493377123321&panelId=4&orgId=2" height=15
`

were displayed correctly, with the panel extending to the entire horizontal space and to the vertical space determined by the height parameter. With 2.3.7-beta and later, I only see an empty page, no Grafana graphs are visible.

### Expected behaviour
In the release notes for 2.3.7-beta you state that you made the change "Treat "height" parameter in webview as max height (#1056)"; I realize the reason for the change (websites larger than the specified height), and the change indeed fixes this scrolling issue I had also noticed. However, I would expect that those pages that naturally extend to the full specified height and width (such as embedded Grafana panels) to expand to the full specified height as they do in a regular browser (like the behavior in 2.3.6-beta and before). It would be great if this could be fixed, as people likely use a lot of embedded Grafana panels in an OpenHAB context.
 
### Steps to reproduce
1. Add the Webview item as above to a sitemap.
2. Open the sitemap in versions 2.3.7-beta or later.

#### Client
* Android version: Reproduced on various version; e.g. 8.1.x (Oreo, API 27)
* Device model: Reproduced on various devices; e.g. Samsung Galaxy S5
* Stock or customized ROM: Reproduced on both; e.g. LineageOS
* App version : 2.3.7-beta or later
* Build flavor : Can be reproduced on both; e.g. F-Droid version.
* Device language: English, but I suspect this does not make a difference

#### Server
* Server version: 2.3.0-1
* Reverse Proxy: Nginx
* Authentication method : SSL Client certificate

#### openHAB Cloud
* openHAB Cloud version: n/a
* Self hosted cloud or myopenhab.org: hosted on own server
* Authentication method : SSL Client certificate

#### App log
```
n/a
```

#### openHAB Server log
```
n/a
```

#### Reverse Proxy log
```
n/a
```
```
n/a
```

**Comment by albertbrufau** [comment]
Same issue here in openHAB Android 2.3.10-beta and openHAB Android 2.4.0
