### ISSUE TITLE
HABdroid 2.4 Error 500

### ISSUE THREAD

**Issue by deladus** [openhab/openhab-android#1088]
### Actual behaviour
Describe us what happens
Remote-URL is not available after update. HTTP Status Code 500

### Expected behaviour
Describe us what should happen
Open Sitemap

 
### Steps to reproduce
1. Describe us how to reproduce the issue
2. Use a list for it

#### Client
* Android version: 8.0 and 9.0
* Device model: Lenovo Moto G6 & Nokia 7 Plus
* Stock or customized ROM:  Stock
* App version : 2.4
* Build flavor : 
* Device language: German and English

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: 
* Authentication method : 

#### App log
```
Insert your log here
```

#### openHAB Server log
```
Insert your log here. If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here.
For nginx: `/var/log/nginx/error.log`
For Apache 2: `/var/log/apache2/error.log`
```
```
Insert your reverse proxy access log here
For nginx: `/var/log/nginx/access.log`
For Apache 2: `/var/log/apache2/access.log`
```

**Comment by inis1981** [comment]
I have this issue as well after recent openhabian update I can not connect anymore. PC or android

**Comment by mueller-ma** [comment]
Can you enable debug mode and post a screenshot of the error including the stacktrace?

**Comment by cribskip** [comment]
When on mobile, app is not working for me too. I've just tried several builds from the releases down to 2.3.3. The most I got is notifications listed in the side menu. No sitemaps with this and newer builds.

As I'm using myopenhab.org service, has myopenhab changed something which may affect connectivity?

**Comment by inis1981** [comment]
Just to be clear, I do get local access but after I recently updated openhabian I do not get remote or access through myopenhab.

**Comment by cribskip** [comment]
I've uninstalled Cloud Connector 2.4.0.201811031157 and installed the [jar from 2.3.0 build ](https://bintray.com/openhab/rpm-repo2/openhab2-addons/2.3.0). **No change**

So, I assume, either this is related to the core (I'm on testing, openhab-build 2.4.0~20181103124646-1) or the cloud service.

**Comment by maniac103** [comment]
All of this somehow sounds like the community postings linked in #1095.
tl,dr: cloud service issue

**Comment by inis1981** [comment]
I don't believe this is related, it's not loading slow. It's not loading at all.

**Comment by mueller-ma** [comment]
It probably does: 
> 504 Gateway Timeout
> The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.

from https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_errors
