### ISSUE TITLE
Remote Access is slow (Android app 2.4)

### ISSUE THREAD

**Issue by gargamelonly** [openhab/openhab-android#1095]
https://community.openhab.org/t/remote-access-is-slow/55909

### Actual behaviour
Remote Access via App ist very slow. Connection fails sometimes.
Access via Browser (same Phone) or Laptop is fine.

### Expected behaviour
Normal access time to main sitemap

 
### Steps to reproduce
Open main sitemap in app

#### Client
* Android version: Oreo 8.0
* Device model: Samsung S8
* Stock or customized ROM: Stock
* App version : 2.4
* Build flavor : 2.4 M5
* Device language: Hebrew

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : user and password

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method : user and password

#### App log
```
Insert your log here
```

#### openHAB Server log
```
Insert your log here. If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here.
For nginx: `/var/log/nginx/error.log`
For Apache 2: `/var/log/apache2/error.log`
```
```
Insert your reverse proxy access log here
For nginx: `/var/log/nginx/access.log`
For Apache 2: `/var/log/apache2/access.log`
```

**Comment by maniac103** [comment]
All of the information in that linked thread suggests this is a myopenhab issue though.

**Comment by maniac103** [comment]
> It seems like it but myopenhab is working fine when connecting through a PC browser.

The web frontend might use a different way to connect to the OH server than the app.

**Comment by mueller-ma** [comment]
There are multiple reports of a slow myopenhab access. @digitaldan deployed an additional server to improve performance.
