### ISSUE TITLE
Voice Control Widget not working 

### ISSUE THREAD

**Issue by BeistleA** [openhab/openhab-android#1096]
Since the update to 2.4.0 the voice Control Widget is not working anymore. Voice Control in app is still OK.

**Comment by mueller-ma** [comment]
Does this happen both via local and remote connection?

**Comment by BeistleA** [comment]
yes, both connection. and only by using the widget, in app is working. BTW...the popup: recognized command... is also missing (also only by using the widget)

**Comment by cribskip** [comment]
Hey, it's working for me. tested with beta 2.5.2. Are you using VoiceCommand or built-in parser, maybe there is a problem

**Comment by BeistleA** [comment]
thanks for the hint, it is working with beta version of the app. hope it will be fixed in next stable :-)
greetings Andy

**Comment by mueller-ma** [comment]
There shouldn't be a difference for the voice widget between 2.5.0 and 2.5.2-beta.
