### ISSUE TITLE
Setpoint opens on Setpoint's minValue, not on item's current value

### ISSUE THREAD

**Issue by tobiasisenberg** [openhab/openhab-android#1097]
### Actual behaviour
When I open a Setpoint element to set a new value, it opens with the Setpoint's minValue displayed, not with the current value of the connected/controlled item. I am not sure this is a bug, but it is certainly a usability issue.

### Expected behaviour
When I open a Setpoint element to set a new value, the current value (of the connected item) should be shown so that, for example, setting a temperature to one or two degrees lower than currently does not require lots of scrolling.

 
### Steps to reproduce
1. Use a Setpoint in a Sitemap
2. Change the value using the Setpoint

### Can you reproduce the issue in demo mode?
There does not seem to be a Setpoint widget in the demo sitemap. I searched through the entire demo of the current regular version (2.4.0) but did not find a Setpoint widget. Another bug of sorts, maybe? Or did I overlook it?

#### Client
* Android version: any; e.g., 8.1 Oreo (API 27)
* Device model: any; e.g., Samsung Galaxy S5
* Stock or customized ROM: both I suspect; e.g., LineageOS
* App version : 2.4.0 and 2.4.1 beta (and several prior to that)
* Build flavor : both
* Device language: English

#### Server
* Server version: n/a
* Reverse Proxy: n/a
* Authentication method : n/a

#### openHAB Cloud
* openHAB Cloud version: n/a
* Self hosted cloud or myopenhab.org: n/a
* Authentication method : n/a

#### App log
```
n/a
```

#### openHAB Server log
```
n/a
```

#### Reverse Proxy log
```
n/a
```
```
n/a
```

**Comment by mueller-ma** [comment]
The behavior you describe is a bug, since the Setpoint widget should show the current value if you open it: https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java#L824-L835

I cannot reproduce this with my local server or the demo server (Widget Overview => Temperature). Can you try the demo mode?

**Comment by tobiasisenberg** [comment]
Ok, this is very interesting now. Here is an overview (in all cases app installed from the PlayStore):
My normal server: Setpoint starts on minimum value
Demo server: no bug, works as expected
Could replicate it for both 2.4.0 and 2.4.1 beta, both tablet and phone, both official OS (7.1.1) and LineageOS (8.x)
My server runs 2.3.0-1 stable, and I connect via reverse proxy. Currently (during the tests) I was connected in local mode. But a test showed no difference when I forced my phone to connect via my data plan.

If I can test anything else please let me know.

Tobias

PS: sorry for not finding the Setpoint widget in the demo sitemap.

**Comment by mueller-ma** [comment]
Can you post the relevant parts of your sitemap and items file?

**Comment by tobiasisenberg** [comment]
Now it gets really interesting. Through some more thorough testing I found that, for some of my Setpoints in my sitemap, the interaction works as expected, while for others it does not. Here are examples:

Does not work (opens with min value):
`Setpoint item=Thermostat_Kueche_Soll_Temp label="Zieltemp." icon="temperature" minValue=10 maxValue=30 step=0.5
`
*.items excerpt:
`Number:Temperature  Thermostat_Kueche_Soll_Temp  "Soll Temp. Küche [%.1f °C]"  <temperature>   (gFritzSHome, gChartChange)  {channel="avmfritz:Comet_DECT:mainfritzbox:118619753464:set_temp"}
`

As far as I can see, all items where it does not work are from the avmfritz binding.

Does work (opens with current value):
`Setpoint item=MQTT_DeDietrich_LivingRoom_SollD_Temp_Normal label="Zieltemp. (Tag)" icon="temperature" minValue=10 maxValue=30 step=0.5
`
*.items excerpt:
`Number  MQTT_DeDietrich_LivingRoom_SollD_Temp_Normal   "Wohnzimmer Soll (Tag, normal) [%.1f °C]"          <temperature>
`
(this item is used by a rule to set an MQTT-based item).

In the regular BasicUI web interface all my setpoints work as expected.

Thanks for the help!

Tobias

**Comment by mueller-ma** [comment]
I guess I know the reason: I've seen that the fritzbox sometimes sends values like 10,10000001 instead of 10,1 and than the value is not reachable by the step size you entered.

**Comment by tobiasisenberg** [comment]
Hmmm. If I check the mentioned item via REST API, then I currently see "state":"22.0 ℃" or, if I explicitly ask for the state, "22.0 â„ƒ". So the rounding issue does not seem to be the problem. But one difference I just noticed is that I defined the temperatures of the avmfritz binding as Number:Temperature as opposed to a pure Number. So I did a quick test: I removed the ":Temperature" from the item and, indeed, immediately the Setpoint for that item opens with the current value as it should, no longer the min value. After changing it back it again opens incorrectly with the min value. So that is the bug: for items with units attached the Setpoint does not work correctly in the app. Could this be fixed? ;-)

**Comment by SteWers** [comment]
I can confirm the behaviour. When I set the dimension to "Temperature", the setpoint start with the min value. Setting to nothing and it works. I manage this item in PaperUI.

**Comment by maniac103** [comment]
> If I check the mentioned item via REST API, then I currently see "state":"22.0 ℃" or, if I explicitly ask for the state, "22.0 â„ƒ".

Can you provide the JSON output, please? If the response is what you're describing, this will surely break the [parsing code](https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/model/Item.java#L134), leading to the current value being treated as '0'.

IMHO that's a bug on the server side (introduced with the units support), as response format for 'state' for a given item type was changed ('22.0' -> '22.0 °C') in a backwards incompatible way when there would have been better ways (e.g. introducing a 'unit' field in JSON). @kaikreuzer Got thoughts on this?

One workaround I could think of is looking for spaces in the state string and doing the float conversion only using the substring up to the space, if present. Thoughts?

**Comment by tobiasisenberg** [comment]
Sure, here we go (local IP slightly obfuscated): `http://192.168.X.Y:8080/rest/items/Thermostat_Kueche_Soll_Temp` yields
`{"link":"http://192.168.X.Y:8080/rest/items/Thermostat_Kueche_Soll_Temp","state":"22.0 ℃","stateDescription":{"pattern":"%.1f °C","readOnly":false,"options":[]},"editable":false,"type":"Number:Temperature","name":"Thermostat_Kueche_Soll_Temp","label":"Soll Temp. Küche","category":"temperature","tags":[],"groupNames":["gFritzSHome","gChartChange"]}
`
while `http://192.168.212.76:8080/rest/items/Thermostat_Kueche_Soll_Temp/state` interestingly yields `22.0 â„ƒ`. Same browser in both cases (Chrome 64bit under Windows 10). Hope this helps to figure out the bug.

**Comment by maniac103** [comment]
We use the former endpoint, so the encoding issue is not relevant for us (but still is a bug). The actual root cause is what I already assumed in my last comment: parsing '22.0 °C' as float fails and the fallback value of 0.0 is used. Now we just need judgement from server side people whether adding the unit to the state really is intentional (it somehow feels wrong to me, especially as the unit also is part of 'pattern') ... if it is, we need to relax the parsing; if it isn't, we should fix this server side.

**Comment by tobiasisenberg** [comment]
Any news on this issue in the meantime? A fix would be much appreciated.

**Comment by maniac103** [comment]
The fix is in #1146 ... it's mostly there, just need to get around fixing the unit tests.

**Comment by tobiasisenberg** [comment]
Thanks a lot for yhe update, much appreciated!

**Comment by tobiasisenberg** [comment]
This issue can be closed, with 2.5.9-beta the setpoint works again as expected. Thanks a lot to all who helped!
