### ISSUE TITLE
Network problem, miss chosing between local and remote 

### ISSUE THREAD

**Issue by dmachtey** [openhab/openhab-android#1098]
### Actual behaviour
My openhab server is locate on my lan on 10.13.4.13/16
When I'm at home my phone ip are in a range between 10.13.15.0-100/16 and some times, the android app  get to my server by "Connecting to Remote URL" at myopenhab. But the connections is slower than it should

Now I'm connected to a hotspot that gave me 10.59.9.171/20 and now the app try to get to my server by "Connecting to Local URL" and obviously fails.

### Expected behaviour
I expect it connect directly when at home wich is by far faster and through myopenhab.org when not at home or better (when the network I'm connected to is not the same as the one I've at home)

I thing it could be fixed by adding the local netmask. 

#### Client
* Android version: 8.0.0
* Device model: Samsung S8
* Stock or customized ROM: Standard ROM
* App version: 2.4.0 - 6 Nov 2018 15:27:53 
* Build flavor: Play Store 
* Device language: English UK

#### Server
* Server version: 2.1
* Reverse Proxy: myopenhab.org
* Authentication method: None 

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org myopenhab.org: 
* Authentication method: None

**Comment by dmachtey** [comment]
I just did a nmap to my openhab server, from the network I'm now (10.59.9.171/20) and some thing is there

nmap 10.13.4.13 

```
Starting Nmap 7.60 ( https://nmap.org ) at 2018-11-14 21:40 -04
Nmap scan report for 10.13.4.13
Host is up (0.43s latency).
Not shown: 988 filtered ports
PORT     STATE  SERVICE
25/tcp   open   smtp
53/tcp   open   domain
110/tcp  open   pop3
113/tcp  closed ident
2000/tcp open   cisco-sccp
3128/tcp open   squid-http
5060/tcp open   sip
8000/tcp open   http-alt
8008/tcp open   http
8010/tcp open   xmpp
8080/tcp open   http-proxy
8100/tcp open   xprint-server

Nmap done: 1 IP address (1 host up) scanned in 107.99 seconds

```

May be this is why OH try to connect to local network. but:

```
curl -v --max-time 2 http://10.13.4.13:8080/
*   Trying 10.13.4.13...
* TCP_NODELAY set

* Connected to 10.13.4.13 (10.13.4.13) port 8080 (#0)
> GET / HTTP/1.1
> Host: 10.13.4.13:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Operation timed out after 2000 milliseconds with 0 bytes received
* stopped the pause stream!
* Closing connection 0
curl: (28) Operation timed out after 2000 milliseconds with 0 bytes received

```
there is not OH server on that address.

Is it possible to check if there is an OH server at the address and if there isn't go to remote.

Best Regards.

**Comment by mueller-ma** [comment]
> When I'm at home my phone ip are in a range between 10.13.15.0-100/16 and some times, the android app get to my server by "Connecting to Remote URL" at myopenhab.

https://github.com/openhab/openhab-android/issues/1030

> Now I'm connected to a hotspot that gave me 10.59.9.171/20 and now the app try to get to my server by "Connecting to Local URL" and obviously fails.

The app tries to local connection, because a TCP socket was opened successfully at the openHAB server ip. See https://github.com/openhab/openhab-android/issues/146
