### ISSUE TITLE
get openhab url via autodicovery

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-android#11]
It would be great to get the URL of your openhab server via autodiscovery.

The app already does discover the server via mDNS, I think.
But you still have to type in the URL if you want to save this in the setting.

In case there is more than one openhab server, the app should display all discovered servers to let the user choose one.
##

**Comment by lolodomo** [comment]
Using mDNS, it should be possible to discover openHAB servers in the local network and build the local URL. But it would not be possible to set the remote URL and login/password, and this would require that HABdroid  saves these data per server rather than globally.

**Comment by kaikreuzer** [comment]
It is clear that this feature won't fill remote url or credentials.

But as @CWempe; I would very much like to see selection options being offered for the local url, which can be provided through discovery. It would save a lot of (error-prone) typing and would make it easy to switch between different local instances.
