### ISSUE TITLE
Temperature setpoint sends update in incorrect unit

### ISSUE THREAD

**Issue by dan-saba** [openhab/openhab-android#1107]
My temperature setpoint is in Fahrenheit units. When adjusting the setpoint, the selected number is interpreted as Celsius, resulting in the completely wrong temperature. For example, if I set 72 as the setpoint, the app sends 72 Celsius to the server, which is 161.6 Fahrenheit, which is what then shows in the app. The app properly displays the current and setpoint temperatures in Fahrenheit units. The issue is just with adjusting the setpoint. This issue does not occur in the web interface.

**Comment by tobiasisenberg** [comment]
Is this maybe related to the issue #1097? See the comments there about (a) the encoding of the unit and (b) the problem of Setpoints to properly deal with units.

**Comment by dan-saba** [comment]
I'm not sure if it's directly related, but I am also affected by that issue and observed the same behavior with regards to changing from Number:Temperature to Number.

**Comment by dan-saba** [comment]
Just a note in case anyone else has this issue - I created a workaround rule for the time being.
`rule "Correct Set Point"
when
  Item Nest_Temperature_Set_Point received command
then
  if (!receivedCommand.toString.contains("°F")) {
    Nest_Temperature_Set_Point.sendCommand(receivedCommand + " °F")
  }
end`

**Comment by lolodomo** [comment]
I have not implemented UoM on the server side. @htreu did it.

**Comment by mueller-ma** [comment]
@htreu Friendly poke

**Comment by htreu** [comment]
Sorry for the late reply: In the client you have to parse the item state to see if it carries a unit. In Paper UI I do it like this to separate the unit from the scalar value:

https://github.com/htreu/smarthome/blob/96678e2217c72d4abe1ac83b29179b6b98b3b44f/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/number/component.control.number.js#L50-L62

Once this is done your internal model should keep track of the unit and send commands with this unit attached. In Paper Ui this is done like this:

https://github.com/htreu/smarthome/blob/96678e2217c72d4abe1ac83b29179b6b98b3b44f/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/number/component.control.number.js#L44-L48

Be aware that this is the NumberItem specific implementation.

**Comment by maniac103** [comment]
Hmm, that ... doesn't seem like an optimal interface :-/
I'll make the app conform to that.
