### ISSUE TITLE
No notifications in 2.5.0 but ok in Beta2.5.1

### ISSUE THREAD

**Issue by gargamelonly** [openhab/openhab-android#1112]
This could be related to [https://github.com/openhab/openhab-android/issues/1090](https://github.com/openhab/openhab-android/issues/1090)

**Comment by mueller-ma** [comment]
2.5.0 and 2.5.1 are quite equal: https://github.com/openhab/openhab-android/compare/2.5.0-release...2.5.1-beta
Can you check the push notification status in the about page?

**Comment by gargamelonly** [comment]
It is registered for the service.
There is some noticeable random delay until notifications are received. Probably not related specifically to the app. I will close this issue.

Thanks!
