### ISSUE TITLE
Dynamic sitemaps are broken since 2.3.1-beta build

### ISSUE THREAD

**Issue by renstat** [openhab/openhab-android#1113]
### Actual behaviour
I very often use the visibility parameter in my sitemap. With release 2.4, every use case of **visibility** stopped working in my sitemap.
Out of curiosity, I tested also that there is the same issue with the **labelcolor** and **valuecolor** parameters.

I reproduced the issue in the following simple test. This test works fine with Classic UI, Basic UI and Android App 2.3 : when you switch on/off, the text of the second line and the colors of the third line change.

Beginning with 2.3.1-beta build, nothing happens when you switch. Only if I go back and forth to the first page (Let's test), the changes can now be seen on the second page. 
It seems to be a generalization of the bug #1094. Whatever is the type of the item (chart, text, switch and probably others) the three dynamic parameters work no more.

Dynamic **icons** are the exception : one could think that this is due to the fact that the update of the icon of a given item does not depend on the state of another item. But even in this case the labelcolor on the 4th line is not updated.

 
### Steps to reproduce
Use the following example :

test.items

> Switch    my_switch <light>
String    my_string_1
String    my_string_2
String    my_string_3
Switch    my_switch_whose_color_is_autoupdated <switch>

test.rules

> rule "init"
when System started
then    
    my_switch.postUpdate(OFF)
    my_string_1.postUpdate("Bonjour")
    my_string_2.postUpdate("Au revoir")
    my_string_3.postUpdate("Merci")
    my_switch_whose_color_is_autoupdated.postUpdate(OFF)
end

test.sitemap

> sitemap test label="my test"
{
    Text label="Let's test !" {
        Switch item=my_switch label="flip-flop" 
        Text item=my_string_1 label="Greetings [%s]"  visibility=[my_switch==ON]
        Text item=my_string_2 label="Greetings [%s]"  visibility=[my_switch==OFF]
        Text item=my_string_3 label="Thanks [%s]" labelcolor=[my_switch==ON="green",my_switch==OFF="red"] 
                                                 valuecolor=[my_switch==ON="orange",my_switch==OFF="blue"]
        Switch item=my_switch_whose_color_is_autoupdated label="My color should change"      
            labelcolor=[my_switch_whose_color_is_autoupdated==ON="blue",my_switch_whose_color_is_autoupdated==OFF="red"]                                           
    }
}

#### Client
* Android version: 1/ 6.0   2/7.0
* Device model: 1/ LG G3   2/ Samsung Galaxy Tab A
* Stock or customized ROM:  stock
* App version : 2.3 (=OK),   2.4, 2.5, 2.3.1-beta (=bad)
* Build flavor : Full
* Device language: French

#### Server
* Server version: 2.3
* Reverse Proxy: no
* Authentication method : None

#### openHAB Cloud
* openHAB Cloud version:  Was tested on local network
* Self hosted cloud or myopenhab.org: 
* Authentication method :

**Comment by boc-tothefuture** [comment]
I am seeing the same issue.  In my case I hide the visibility of audio controls in a room unless the zone is on.  Switching the audio zone on no longer results in the audio controls bring visible.

**Comment by mueller-ma** [comment]
This should be fixed in the latest beta version.
