### ISSUE TITLE
Allow connect when WiFi not available

### ISSUE THREAD

**Issue by IvanI3** [openhab/openhab-android#1116]
Please, disable check for WiFi availability on app start. I use VPN over LTE for accessing home network, and cannot use app with current restrictions :(

**Comment by mueller-ma** [comment]
Which android version?

**Comment by IvanI3** [comment]
7.1.1, MIUI

**Comment by agibson** [comment]
I would say make it an option to enable/disable use of WiFi check on
startup.
With that said.
I would say to also make it an option to enable/disable use of
Cell(LTE,3G,etc) check on startup.
I only use WiFi and no cell.

**Comment by maniac103** [comment]
If you always want to connect to the same server, just enter it as remote server and leave local one empty ... or am I missing something?

**Comment by IvanI3** [comment]
> If you always want to connect to the same server, just enter it as remote server and leave local one empty ... or am I missing something?

Yes, it helps! Thanks for the option, I thought it for openhabcloud server

**Comment by IvanI3** [comment]
App successfully connects with remote server set in settings. Local server I think just for local LAN connection - that's ok. Issue could be closed.
