### ISSUE TITLE
Buttonhandles are missing

### ISSUE THREAD

**Issue by schinken** [openhab/openhab-android#112]
The button handles are missing, only the background is visible. It's hard to distinguish between the on and off state. On my phone (Android 5.0.2) everything works correctly.

APP version: 1.7.0.1
Android version: 4.2.2 tablet.

![screenshot_2015-05-28-19-45-41](https://cloud.githubusercontent.com/assets/187176/7871356/aac055d2-058f-11e5-9ff4-9e3a52732711.png)
##

**Comment by belovictor** [comment]
Can you make a screenshot on the device itself please?

**Comment by schinken** [comment]
Updated issue with screenshot

**Comment by sjcliffe** [comment]
I just updated to 1.7.0.1 and have the same issue.

**Comment by belovictor** [comment]
@sjcliffe , which version of Android do you have and which device?

**Comment by sjcliffe** [comment]
I'm running 4.4.4 on a Nexus 7.

**Comment by sjcliffe** [comment]
I've just installed an update on my Nexus 7 (CyanogenMod 12 / Android 5.0.2) and the buttons are now working again.

**Comment by schinken** [comment]
Can't confirm this ... still missing button handles

**Comment by schinken** [comment]
This bug is still present on our tablets. Any fix in the future?

**Comment by jenious** [comment]
+1 experiencing this on a galaxy tab 4 (7 inches) running Android 4.4.

The light background at least shows a different color, but the switch states are identical on the dark background.

**Comment by joefrank25** [comment]
Looks like this is an Android issue with SwitchCompat:

https://code.google.com/p/android/issues/detail?id=78262

**Comment by mueller-ma** [comment]
@joefrank25 @schinken @jenious Is this bug still present? And if so, can you try the workaround posted by @joefrank25 ?
