### ISSUE TITLE
Webview shows nothing, only white boxes

### ISSUE THREAD

**Issue by Sp34rmint** [openhab/openhab-android#1120]
Could not finde a related issue, but maybe #1087 

### Actual behaviour
Since the two last versions off the app the webviews only show empty white boxes with the defind hight.
If i access my sitemap from IOS or throug the browser everything works fine.
Also with the the app version 2.2.0 als Webviews are shown correctly in the android app.

### Expected behaviour
I just expect that after the fix off issue #1087 the problem would be solfed, but it is not.
I expect that if i open a frame which includes a webview i could see the provided content of the webview.

 
### Steps to reproduce
1. Use the app version 2.5.0
2. openhab with nginx and ssl (with openssl) and user authentication 
3. add an webview like this: `Webview url="https://*address*/static/input.html?item=DevHtmlInput&label=Input" height=1`

### Can you reproduce the issue in demo mode?
i give this no try

#### Client
* Android version: 8.1.0
* Device model: Xiaomi Mi A1
* Stock or customized ROM: Stock
* App version: 2.5.0 (and also the new beta)
* Device language: german

#### Server
* Server version: 2.4.0.M7
* Reverse Proxy: nginx
* Authentication method : user and password, SSL (OpenSSL)  

#### App log
```
Insert your log here
```

#### openHAB Server log
```
Insert your log here. If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here.
For nginx: `/var/log/nginx/error.log`
For Apache 2: `/var/log/apache2/error.log`
```
```
Insert your reverse proxy access log here
For nginx: `/var/log/nginx/access.log`
For Apache 2: `/var/log/apache2/access.log`
```

**Comment by mueller-ma** [comment]
Sounds like #948
