### ISSUE TITLE
Switch labeled buttons are cut with older Android revisions (4.4.x)

### ISSUE THREAD

**Issue by steisslinger** [openhab/openhab-android#1121]
### Actual behaviour
Switch labeled buttons are cut with older Android revisions (4.4.x)

### Expected behaviour
Full visibility of labeled buttons

 
### Steps to reproduce
1. Use labeled buttons on sitemap (mapping)
2. E.G.: Switch item=<itemname> [label="<labelname>"] [icon="<iconname>"] [mappings="<mapping definition>"]

#### Client
* Android version: 4.4.2
* Device model: Lenovo, Samsung Note 10.1
* Stock or customized ROM: Stock
* App version : 2.5.0
* Build flavor : Full
* Device language: German

![screenshot_2018-12-04-06-24-11_small](https://user-images.githubusercontent.com/19800372/49657155-49a16e00-fa3f-11e8-926d-cdb76a4e3a49.png)
![screenshot_2018-12-04-06-23-24_small](https://user-images.githubusercontent.com/19800372/49657191-66d63c80-fa3f-11e8-9f27-c7cc6fbd0f11.png)

**Comment by steisslinger** [comment]
Hi,
thanks for fixing. I checked it in openHAB beta.
Buttons are shown now in full size but active buttons are not highlighted (see attached screenshots).
Not OK in openHAB beta (openHAB 2.5.9-beta):
![screenshot_openhab_beta_nok](https://user-images.githubusercontent.com/19800372/51788606-33cb4200-2180-11e9-81e8-887c1c7356b7.png)
This is like it should be displayed (openHAB 2.3.0):
![screenshot_openhab_ok](https://user-images.githubusercontent.com/19800372/51788609-46de1200-2180-11e9-82b4-b00cdfef4fcb.png)

**Comment by mueller-ma** [comment]
It's also broken for newer Android versions.

**Comment by maniac103** [comment]
I'll check it, probably a simple fix.
