### ISSUE TITLE
Check and discuss if icon format setting of basic ui can be used in the app

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1136]
> @mueller-ma I found my issue. I didn’t realize the openhab Android App itself had a bitmap/vector option. I was setting up everything server side.

https://community.openhab.org/t/android-app-not-updating-icons/39139/22

@kaikreuzer The icon format setting in the app causes a lot of issues with custom icons. Do you think the app should use the same setting than the basic ui?

**Comment by maniac103** [comment]
How exactly does Basic UI work in that regard?

**Comment by mueller-ma** [comment]
It's possible to fetch the default icon format, but not the currently set one: http://openhab/rest/config-descriptions/ui%3Abasic

**Comment by mueller-ma** [comment]
The icon format setting has been removed from Basic UI in favor for `anyFormat`. See #1507
