### ISSUE TITLE
missing images

### ISSUE THREAD

**Issue by wrosenauer** [openhab/openhab-android#1144]
### Actual behaviour
I'm using a sitemap with an external image reference.
This is displaying fine in OH's BasicUI but does not load in the Android App.
This worked when I integrated it many months ago but in the meantime it stopped to work.

### Expected behaviour
I should see an image from a Grafana graph as in BasicUI

 
### Steps to reproduce
1. my sitemap contains
Image refresh=60000 url="http://smart-controller:3000/render/dashboard-solo/db/internet-speed?orgId=1&panelId=1&width=1000&height=500&tz=UTC%2B01%3A00"

#### Client
* Android version: 8.0.0
* Device model:  Galaxy S9 (SM-G960F)
* Stock or customized ROM: Stock
* App version: 2.5.0 - 24.11.2018
* Build flavor: Full 
* Device language:  German

#### Server
* Server version: openHAB 2.4.0 Build #1454
* Authentication method: none

**Comment by mueller-ma** [comment]
I have working image items with images from a webcam, but I haven't tested a grafana graph. Can you get a url like yours from a public grafana server (https://play.grafana.org/) for testing?

**Comment by wrosenauer** [comment]
I tried to include one from play.grafana.org but it seems due to the proxying nature of openHAB it fails to display targets using SSL. (My openHAB is not using https.)
Is there a way in the app to get debug information like a browser's web console?

**Comment by wrosenauer** [comment]
I tried to include one from play.grafana.org but it seems due to the proxying nature of openHAB it fails to display targets using SSL. (My openHAB is not using https.)
Is there a way in the app to get debug information like a browser's web console?

(Just noticed that it works on another device which is a 10inch tablet but fails on my Galaxy S9.

**Comment by mueller-ma** [comment]
With 2.5.3-beta or newer (available in the play store as extra app) you can display the app log: Settings => View log

**Comment by wrosenauer** [comment]
After I tried the beta which worked I completely wiped the app from my phone and reinstalled it.
Now it's working again. No idea how it came into the non-working state. So this might be closed while there seems to be a glitch somewhere that it can break under certain circumstances.
