### ISSUE TITLE
Setpoint contains wrong values if stepsize is a decimal number

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1148]
### Actual behaviour
Have a setpoint with `min=1` and `step=0.2`. You can see the following values for selection in a setpoint:
````
1.0
1.2
1.4000001
...
````

### Expected behaviour
````
1.0
1.2
1.4
...
````

### Can you reproduce the issue in demo mode?

No

#### Client
* Android version: 8
* App version : 2.5.3-beta
* Build flavor : Both
* Device language: EN

**Comment by maniac103** [comment]
The question boils down to 'how many decimals do we want to use for formatting' ... 'step' could become 1.4000001 as well, so we can't use it as base :-/ Only can think of ugly stuff like hand-parsing min/max/step strings and using the largest number of decimals of those 3. Or is there something in the API response we can use?
