### ISSUE TITLE
Custom notification ring tone

### ISSUE THREAD

**Issue by bruman** [openhab/openhab-android#1156]
I see mention in the code that I should be able to select a custom ring tone but that option is not showing up in the preferences. I have enabled myopenhab, and I see successfully registered with gcm i the about, which appears to be a requirement for the custom notification option. I have tried the main openhab app in Google play and the beta version. Notifications show up correctly, I would just like to change the notification sound.

**Comment by bruman** [comment]
Android 8.1.0

**Comment by maniac103** [comment]
OK, then the setting is part of notification channels now. In Android settings, go to Apps -> openHAB -> Notifications -> Standard and choose the ringtone there.

I'll see whether we can add a shortcut to that page to our settings page.

**Comment by bruman** [comment]
@maniac103 Excellent, Thanks, I didn't know that was there :) I have change the notification and that works. I am also getting the alert playing twice, the alert only shows up once in the android notifications, and myopenhab, i only have my phone listed once in myopenab in the devices. This  was what started me down this path, to change to an alert that was less annoying since the alert played twice for each alert.

**Comment by mueller-ma** [comment]
Working on this.
