### ISSUE TITLE
Double notification sounds after installing and uninstalling beta app

### ISSUE THREAD

**Issue by m4rky-m4rk** [openhab/openhab-android#1176]
Hi,
I started to use the beta app alongside the regular app when the the Grafana chart issue popped up. After installing the beta I then had for each openhab notofication two audible alerts. I thought that was because I had the two apps installed at the same time.

The Grafana issue was fixed and I uninstalled the beta version but annyoingly I still get the double audible alerts and have, so far, not found a way to prevent it. Has anyone else experienced the same issue?

Phone is Galaxy Note 8

**Comment by maniac103** [comment]
If you look at the device list in openhab-cloud I guess your phone is listed twice? If so, you can try clearing out both entries and starting the app again; this should fix the duplicate.

We still should differentiate between stable and beta in the cloud registration though.

**Comment by m4rky-m4rk** [comment]
Its listed once but will try removing it anyway.

**Comment by abedwardsw** [comment]
I also am always getting double notification sounds.  Not sure when it started, but just decided to finally look into it today.   I've tried the following:
- deleting device from myopenhab cloud.  my "old" phone was listed there, I deleted both my old and new phone.
- restarting the app / force stop
- cleared cache
- restarting the device

can't seem to figure out how to stop the double notifications.   I'll note that I am using the mainline version 2.5.0

**Comment by mueller-ma** [comment]
Could it be that the sound comes from the notification itself and from the channel?

**Comment by maniac103** [comment]
I doubt it. I'm pretty sure that on Oreo+, where the channel settings are used, the individual notification settings are disregarded. I also do not see this issue myself (using Android 9)

**Comment by mueller-ma** [comment]
> We still should differentiate between stable and beta in the cloud registration though.

The latest beta registers itself as "\<device name\> (Beta)". When you get the update to 2.5.12-beta, can you try again to remove all registrations in myopenHAB and open both app versions, so they can re-register themself?

**Comment by m4rky-m4rk** [comment]
I tired removing my phone from the devices listed in Openhab cloud. I no longer have the  beta app installed so I cant open that app but after opening the std app I still get double notifications. Do I need to reinstall the beta and try removing my phone again and open both apps?

**Comment by maniac103** [comment]
No, you don't. It's likely a generic issue on Android 8+, I can reproduce now. Log of the platform notification service:
```
03-01 14:21:20.463  3760  4350 V NotificationService: enqueueNotificationInternal: pkg=org.openhab.habdroid id=7 notification=Notification(channel=default pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x11 color=0xffff5722 category=event groupKey=gcm vis=PRIVATE publicVersion=Notification(channel=default pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x11 color=0xffff5722 category=event groupKey=gcm vis=PUBLIC))
03-01 14:21:20.464  3760  3760 D NotificationService: EnqueueNotificationRunnable.run for: 0|org.openhab.habdroid|7|null|10088
03-01 14:21:20.465  3760  3760 V NotificationService: pkg=org.openhab.habdroid canInterrupt=true intercept=false
03-01 14:21:20.465  3760  3760 V NotificationService: Interrupting!
03-01 14:21:20.465  3760  3760 V NotificationService: Playing sound content://settings/system/notification_sound with attributes AudioAttributes: usage=5 content=4 flags=0x0 tags= bundle=null
03-01 14:21:20.466  3760  6323 V NotificationService: Delaying vibration by 500ms
03-01 14:21:20.472  3760  4350 V NotificationService: enqueueNotificationInternal: pkg=org.openhab.habdroid id=0 notification=Notification(channel=default pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x211 color=0xffff5722 category=event groupKey=gcm vis=PRIVATE publicVersion=Notification(channel=default pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x211 color=0xffff5722 category=event groupKey=gcm vis=PUBLIC))
03-01 14:21:20.472  3760  3760 D NotificationService: EnqueueNotificationRunnable.run for: 0|org.openhab.habdroid|0|null|10088
03-01 14:21:20.472  3760  3760 V NotificationService: pkg=org.openhab.habdroid canInterrupt=true intercept=false
03-01 14:21:20.473  3760  3760 V NotificationService: Interrupting!
03-01 14:21:20.473  3760  3760 V NotificationService: Playing sound content://settings/system/notification_sound with attributes AudioAttributes: usage=5 content=4 flags=0x0 tags= bundle=null
03-01 14:21:20.476  3760  6326 V NotificationService: Delaying vibration by 500ms
```

... which means the double notification sound comes from both the individual notification and the summary notification. I'll see how we can avoid that.

**Comment by m4rky-m4rk** [comment]
It used to play as expected but after installing and removing the beta app I then got double notifications. Maybe its coincidence, maybe not.

**Comment by maniac103** [comment]
It's probably a coincidence with an update of the app that added the summary notification handling.
