### ISSUE TITLE
Select panel configuration from Server not possible 

### ISSUE THREAD

**Issue by Matthias2841** [openhab/openhab-android#1177]
When trying to select a panel configuration, which is saved on the server (rasperry) this is displayed, but it cannot be selected on tablet using current beta Version.

**Comment by mueller-ma** [comment]
I created a second panel configuration and switching between those works fine. The selected config is still active after restarting the app. Can you please test if this works in a browser and fill out the issue template?

**Comment by mueller-ma** [comment]
Which Android version? Open the app, go to `Settings` => `View log` and insert the log here.

**Comment by Matthias2841** [comment]
It's Android 7.0.

Log of App is empty.

**Comment by Matthias2841** [comment]
Finally i manage to open the panel configuration, which is stored on the server: first i created a New one and saved that one locally. Now it's possible to open the remote one. So considder this topic as closed.
