### ISSUE TITLE
Application (2.5.9) crashed if you use zoom  icon

### ISSUE THREAD

**Issue by besolvedde** [openhab/openhab-android#1197]
Hey Community, im using the 2.5.9 beta application. If i choose in the sitemap the frame with the "zoom" icon the application crashed. Thanks for your commitment

!!! Update:

Fix crash with MapView if item has no state #1195

Sorry i read this now. Thats the Problem, i have a frame with the zoom icon, and into this there is only one mapview item... Nothing works insight (6 items), because of the missing state, if it inactive, of the gps. If i activate the gps, the state was Active, the frame works fine. I think you can close this issue and put it to mapview item issue.

Some tip, like for the visibility. If state null, show in the application, no active datas (for example) - Thats better than the bug and the app crashes.

**Comment by mueller-ma** [comment]
The crash is fixed in #1195. Further discussions how to improve the ui in this case is in https://github.com/openhab/openhab2-addons/issues/4848.
