### ISSUE TITLE
Slider element ignores min/maxValue

### ISSUE THREAD

**Issue by CrazyIvan359** [openhab/openhab-android#1209]
### Actual behaviour
Slider elements ignore the `minValue` and `maxValue` specified in sitemap file and always operate in the range 0-100. In BasicUI on desktop sliders behave as expected and respect `minValue` and `maxValue`.

### Expected behaviour
Sliders should respect specified values

 
### Steps to reproduce
1. Create a sitemap slider element and specify a `minValue` other than 0 or `maxValue` other than 100

#### Client
* Android version: 8.1.0
* Device model: HTC One M8
* Stock or customized ROM: crDroid 4.7
* App version: 2.5.0 Nov 24, 2018 5:13:38AM
* Build flavor : Full
* Device language: English

#### Server
* Server version: 2.5.0 snapshot 1512
* Reverse Proxy: nginx
* Authentication method : local-none, remote-basicauth

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: Self hosted
* Authentication method :

**Comment by mueller-ma** [comment]
Can you check the beta version? This should be fixed there

**Comment by maniac103** [comment]
This was fixed with https://github.com/openhab/openhab-android/pull/1146, in particular commit https://github.com/openhab/openhab-android/commit/abf593eeb0bb90dfef863f3194ddb3f2f783f173 ... it'll be part of the next release.

**Comment by CrazyIvan359** [comment]
Perfect guys, I'll get the beta installed this evening.

For reference, when is the next release expected to hit the Play store?

**Comment by mueller-ma** [comment]
We're tracking new releases in #549. I want to merge two PRs before and wait some time for the translator. Maybe about a week.
