### ISSUE TITLE
Does not show images via remote reverse proxy

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-android#1213]
### Actual behaviour
Images are not being displayed when using a SSL reverse proxy with Basic Auth (Apache). The same images work fine when using the local URL (without reverse proxy) or the myopenhab cloud.
The images also work fine behind the reverse proxy when showing the Basic UI in the Chrome browser.

### Expected behaviour
Images should be displayed. 
 
### Steps to reproduce
1. Set up reverse proxy with Apache and Basic Authentication
2. Point the app to that remote URL

### Can you reproduce the issue in demo mode?
No.

#### Client
* Android version: Pie
* Device model: Xiaomi Redmi Note 5
* Stock or customized ROM: Custom, Pixel Experience
* App version : 2.5.0
* Build flavor : Play Store
* Device language: German

#### Server
* Server version: 2.4.0
* Reverse Proxy: Apache
* Authentication method : Basic Auth

#### openHAB Cloud
N/A

#### App log
```
Can't find.
```

#### openHAB Server log
```
Nothing related there.
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here.
For nginx: `/var/log/nginx/error.log`
For Apache 2: `/var/log/apache2/error.log`
```
Nothing related there.
```
Insert your reverse proxy access log here
For nginx: `/var/log/nginx/access.log`
For Apache 2: `/var/log/apache2/access.log`
```
Nothing related there.

**Comment by sidamos** [comment]
This is the entry in the sitemap:

Image item=FrontDoorCameraNestHello_Camera_SnapshotURL label="Nest Snapshot" refresh=60000

**Comment by sidamos** [comment]
Also happens with 2.5.14-beta.

**Comment by mueller-ma** [comment]
Do you have any interesting log messages from the reverse proxy?

**Comment by sidamos** [comment]
No, sorry. Could not find anything related.

**Comment by mueller-ma** [comment]
Is this still an issue?

**Comment by sidamos** [comment]
Sorry, I do not use this setup anymore.
