### ISSUE TITLE
adding authentication with PIN and/or fingerprint for app

### ISSUE THREAD

**Issue by witek1308** [openhab/openhab-android#1216]
**Is your feature request related to a problem? Please describe.**
Hey, this is not a problem but pure feature request. Smart home in my case (but I conclude from forums that others' too) contains many sensitive settings for example heating unit control or gate/garage gate control. In this case anyone having access to the phone can play with it and accidentally change important setting or even get compromised by malicious behaviour of stranger. This is quite common for people with kids who take parents' phone to play

**Describe the solution you'd like**
Application should open only after entering PIN or fingerprint (depends which solution is chosen by developer).  This is known behavior from any bank apps

**Describe alternatives you've considered**
Alternative is to delete password from the app for remote and local links after using the app and entering it again for any new access but this is very inconvenient and one day will get forgotten for sure.

**Comment by Jochen1980** [comment]
Dear Community,

first of all, I am quite new here, so I have no idea what kind of discussions and opinions have been around here. 

In my opinion, dealing with access control is a thing which should happen on the backend side. Currently there is no access control system in the main system, so for me it makes no sense to implement it in the app. 

By the way - how does the app behave, if you activated the reverse proxy idea to manage access control? Maybe that is an idea people should strive for, if they want to enable some kind of access control on every device.

Best regards, 
Jochen

**Comment by witek1308** [comment]
Jochen
You misunderstood my point. Backend is for authenticating user of the cloud.
Frontend PIN is to secure your GUI that if you go to the toilet in the bar 
and leave your phone on the table (assuming it doesn't get stolen) nobody 
turns lights in your home or moreover can't open your gate.
For sensitive app like this it should be secured in the frontend as well as 
backend

--- Wiadomość oryginalna ---
Od: Jochen notifications@github.com
Data: 22 lutego 2019 21:18:12
Do: openhab/openhab-android openhab-android@noreply.github.com
DW: witek1308 witek_1308@poczta.onet.pl, Author author@noreply.github.com
Temat: Re: [openhab/openhab-android] adding authentication with PIN and/or 
fingerprint for app (#1216)

**Comment by Jochen1980** [comment]
Thanks for clarification, @witek1308 . Anyway, I just can speak for myself and I need to say, that for this purpose I would use 99% the default 'lock screen' feature of my cell phone.

**Comment by witek1308** [comment]
I guess you don't have kids :)
With kids often they take the phone (or force it to be given) to watch 
youtube or so and then run across possible apps like crazy when bored with 
films :)

--- Wiadomość oryginalna ---
Od: Jochen notifications@github.com
Data: 22 lutego 2019 21:46:39
Do: openhab/openhab-android openhab-android@noreply.github.com
DW: witek1308 witek_1308@poczta.onet.pl, Mention mention@noreply.github.com
Temat: Re: [openhab/openhab-android] adding authentication with PIN and/or 
fingerprint for app (#1216)

**Comment by Jochen1980** [comment]
Good point! Anyway I got Alexa in my home and so I am lost anyway. 

A) Should we discuss the idea an the community?
B) Idea for implementation:
* add a button under Settings - Misc with the text "Lock Screen ..."
* first we can offer to set and edit four digits
* more advanced would be to offer the same options like the default screen lock mechanism

What do you think?

Cheers,
Jochen

**Comment by witek1308** [comment]
Jochen,

*	Good point! Anyway I got Alexa in my home and so I am lost anyway.

Now you are right…

 

Regarding your points below I think what you proposed is absolutely enough.  Lock screen as optional setting with ability to set PIN. When application gets out of the first window it asks for PIN and as long as stays open, the PIN is not needed. When it gets put to background and requested again then PIN is asked.

---

pozdrawiam/best regards,

Witek

**Comment by mueller-ma** [comment]
Here's how it's done in Signal: https://github.com/signalapp/Signal-Android/commit/d28dc670ea58867e97336434d31c7003e5cf9c54.

I see three different ways to implement a screen lock:
1. Add a simple switch to prefs that enables screenlock. Every time the app is opened the Android screenlock (pattern or fingerprint) is shown.
2. Same as 1, but with a configurable timeout. The timeout should be a ListPreference with a few options: 0, 1 minute, 15 minutes, 1 hour or similar options.
3. Same as 2, but with a custom implementation of an unlock pattern, so the openhab pattern can be different from the device pattern.

IMO 3 seems a bit overkill for me. 2 seems the best option for me.
@Jochen1980 Do you want to give it a try?

**Comment by witek1308** [comment]
@mueller-ma, indeed 3 is an overkill an unnecessary complexity. Option 2 looks like a perfect fit with even more flexibility than I expected.

**Comment by mueller-ma** [comment]
Can you please test the following apk?

- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk

[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/3050340/mobile-foss-beta-debug.zip)

**Comment by witek1308** [comment]
hi,
app crashes each time there is enhanced security screen entered (either fingerprint or Android defined sign). Can I capture any logs to send you ?

**Comment by mueller-ma** [comment]
Yes, open the log (settings, view log) and look for the stacktrace, copy it and post it here.

**Comment by witek1308** [comment]
I need to find the log from filesystem as I can't get into the application (it displays the security screen which causes crash and over again).

**Comment by mueller-ma** [comment]
No, you cannot find the log as file on your device. You can use adb get to it.
What android version are you using?

Note to self: Check if device is supporting this feature.

**Comment by witek1308** [comment]
Hi I am on 7.0. will try to see how to get it through the adb otherwise I am in deadlock even if I reinstall

**Comment by maniac103** [comment]
Reinstalling (as in uninstall + install again) should kill the app settings though, so I'd expect it to help?

**Comment by mueller-ma** [comment]
You can also clear app data in the android settings, but that might clear adb log as well

**Comment by witek1308** [comment]
The point is I want to capture log for crash caused by enhanced security so need to enable it after reinstall. If I do it however it doesn't let me in to the app anymore. The only way is the adb but I need to learn how to do that

**Comment by witek1308** [comment]
Hi, quick update - I learned how to collect logs through adb, sat down to do this but then application run properly in both local and remote modes (using myopenhab.org) and it is stable. I didn't do anything with my phone (not even restarted it, not sure what could have caused it). It properly displays my sitemaps as of now, all icons etc. My sitemaps are pretty diverse (switches, text items, jpg's, charts, etc). It requires more testing for the production release but for the moment it looks stable and OK. Thanks for the great work.

**Comment by witek1308** [comment]
Hi after some more days of using the app I haven't noticed any bugs or unexpected behavior

**Comment by dr2okevin** [comment]
In my Case, I want to install the app on my Car Entertaiment system. This system is not locked itself by a pin or similar. I arm and disarm my house alarm with the openhab app, and it would be a security risk to have that in the car without any password protection. 
So +1 for a pin protection by the app itself.

**Comment by Sonic-Amiga** [comment]
I'd like to have pin protection for settings only. I have a hacked Astrum Inspinia wall panel, and would be nice to protect settings from kids and/or experimenting guests. ;)

**Comment by mueller-ma** [comment]
In  #1449 you can choose to only lock preferences, about, write nfc tag, etc.

**Comment by mueller-ma** [comment]
If you want to test the lockscreen:

- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk

[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/3465053/mobile-foss-beta-debug.zip)

**Comment by witek1308** [comment]
After migrating from Galaxy A5 2016 to Xiaomi Mi9 the app works but doesn't open menu (after pressing 3 parallel lines in the top left corner nothing happens), don't know why. I don't think it is related to phone settings, rather something with the app. Android version on this phone is 9 PKQ1.181121.001

**Comment by mueller-ma** [comment]
Do you use the apk I provided above or the version from play store?

**Comment by witek1308** [comment]
Yes, I installed from the apk file

 

---

pozdrawiam/best regards,

Witek

**Comment by mueller-ma** [comment]
I posted two apk files here. Did you take the one from 4th August?
The issue you describe sounds like the drawer got locked, which is something I did in the first version, but not in the second.

**Comment by witek1308** [comment]
Spot on! I used previous version (simply copied apk from my old phone). I can confirm with the latest one from the 4th of Aug all works as expected. Thank you!
