### ISSUE TITLE
Enrich README for Contributers

### ISSUE THREAD

**Issue by Jochen1980** [openhab/openhab-android#1217]
Dear Developers,

I tried to get the app running, so that I'll be able to contribute to the project. Unfortunately I am not able to build and run the app. Maybe someone can describe the steps which are necessary for starting the app in the emulator in more detail. 

Best regards,
Jochen

**Comment by maniac103** [comment]
Well, normally it should suffice to open the project in Android Studio. What issues did you encounter exactly?

**Comment by Jochen1980** [comment]
What do I need to run / build that the app starts in the emulator?

**Comment by maniac103** [comment]
Open the project, press the 'play' shaped button ('Run'), select an emulator, press 'OK', wait a bit, done.

That's how it's supposed to be; if you hit issues in the process it would be good to have them listed ;-)

**Comment by Jochen1980** [comment]
Great - now it was working to start the emulator. Unfortunately I was not able to start the app on the emulator, the error message was "No matching client found for package name 'org.openhab.habdroid.beta'" The app was not sent to the emulator.

**Comment by Jochen1980** [comment]
UPDATE: the debugStable runs on the emulator. debugBeta seems to have some problems and the build stuck.

**Comment by Jochen1980** [comment]
I can see that there is another Issue already adressing this issue - see PR https://github.com/openhab/openhab-android/pull/1196

**Comment by mueller-ma** [comment]
> debugBeta seems to have some problems and the build stuck.

Yes, that's a know issue: https://github.com/openhab/openhab-android/issues/794. You should build fullStableDebug.
