### ISSUE TITLE
Live update not working well when in remote access mode

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#1229]
I am running server snapshot 1544 and Android app 2.5.

Live update (through SSE ?) when a page is opened is not working at all when I am in remote access mode.
Works apparentlmy as expected when I am in local access mode.

I will probably downgrade to an older version of the server to see if this is relative to snapshot 1544.

**Comment by lolodomo** [comment]
In fact, it does not work better with a server v1480.

**Comment by mueller-ma** [comment]
Maybe #1212? Are you using authentication locally?

**Comment by lolodomo** [comment]
Authentification of course when in remote access (myopenhab). No authorization in local mode.

**Comment by lolodomo** [comment]
Does it work for someone using myopenhab ? My setup is very classic. No reverse proxy, just HTTPS to myopenhab with login/password.
Android 5.

**Comment by lolodomo** [comment]
Ok I have more info to reproduce the issue. In fact, the live update is working during a short period.
I open a page and ask a refresh with a slide down. After that, the content is correctly updated (if I change it from another device).
Now I exit from this page and reopen it. The value is correct. But now any update from other device are not taken into account.
To reactivate the live update, I have to do a new slide down to refresh the page.

So to be clear, it looks like the page content update stops working when re-entering in a page but is reactivated if you request a full refresh using slide down.

**Comment by maniac103** [comment]
We'll need the application log here ... reproduce the problem, then go to the log viewer and attach the log here.

**Comment by lolodomo** [comment]
Where can I find the logs and where is this log viewer ?

**Comment by maniac103** [comment]
Install beta app; then it's the last item in the settings.

**Comment by maniac103** [comment]
Thinking about it, it's probably the issue https://github.com/openhab/openhab-android/pull/1231 will fix.

**Comment by lolodomo** [comment]
With the APK you provided, the app is crashing very often, even if I do nothing ! I just have to wait few seconds and it crashes.
But I have the feeling that the live update in remote access is restored with this version.

**Comment by maniac103** [comment]
The crashes are fixed with latest commit in PR #1234. But good thing the update is fixed, that means my suspicion is correct and the just released 2.6.0 should work fine in that regard :+1:

**Comment by lolodomo** [comment]
2.6 was released before being sure that my 2 critical issues are fixed ?
