### ISSUE TITLE
Icon cache apparently cleared when sliding down

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#1230]
In remote access mode, I can see that the icon cache is correctly handled. When I reopen a page, the icons are quickly displayed, faster than the first time.
Something I don't understand is why the handling is page per page. If I have the same icon in several pages, I would expect that loading is immediate when opening the second page.

I come to the real problem. When I slide down on any page, I get a message telling me that it is useless. Ok but then I can notice that the icon cache is apparently lost for all pages because I can see that the icon loading in any page (the first time) is slower again.
Is there a valid reason to clear the icon cache in this case ? Is there a valid reason to clear it for all pages and not only on the page I asked to refresh ?

**Comment by mueller-ma** [comment]
That's intended, but I agree it's not the best behavior: https://github.com/openhab/openhab-android/pull/929#issuecomment-401471842

**Comment by lolodomo** [comment]
The refresh can be triggered too much easily sliding down, while you just want to go to the top of your sitemap page !
Do you think a preference to disable refresh with slide down could be added ?

**Comment by maniac103** [comment]
I think what we should do instead is only trigger swipe to refresh if the swipe was started at the top of the page. I have done this in the past in another project, just need to dig out that code again.

**Comment by lolodomo** [comment]
Yes, good idea.
