### ISSUE TITLE
Crash due to missing class

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1247]
````
Unable to instantiate service org.openhab.habdroid.core.FcmInstanceIdListenerService: java.lang.ClassNotFoundException: Didn't find class "org.openhab.habdroid.core.FcmInstanceIdListenerService" on path: DexPathList[[zip file "/data/app/org.openhab.habdroid.beta-2/base.apk"],nativeLibraryDirectories=[/data/app/org.openhab.habdroid.beta-2/lib/arm, /vendor/lib, /system/lib]]
````

#### Client
* Android version: Multiple
* Device model: Multiple
* Stock or customized ROM: Multiple
* App version : 2.3.0-beta
* Build flavor : Full
* Device language: Multiple

@maniac103 https://github.com/siacs/Conversations/commit/c2067e3b56364317bc384b55e320b72326fb1de6 wasn't a good idea, I see less info about crashes now.

**Comment by maniac103** [comment]
I was about to ask about the full stacktrace, as this class was removed because it supposedly isn't needed anymore...so we don't have a stacktrave anymore now?

**Comment by mueller-ma** [comment]
It's still linked in the manifest: https://github.com/openhab/openhab-android/blob/master/mobile/src/full/AndroidManifest.xml#L21

**Comment by maniac103** [comment]
This ... explains things *facepalm* I wonder who reviewed this :-P
I'll fix this.
