### ISSUE TITLE
Value in page title is missing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#1248]
### Actual behaviour
The title of any page is a fixed text defined in the sitemap as label.

### Expected behaviour
The title of any page should include, when defined in the sitemap, an additional (dynamic) value.
This is already correctly handled by Basic UI.

![image](https://user-images.githubusercontent.com/10186704/53936721-27a1a100-40ab-11e9-9c4a-735e455395bf.png)

What I am talking about is the text "légère pluie" in the page title.

Example of sitemap to reproduce that:
```
Text item=OWMCondition label="Météo" icon="rain" {
}
```

Note that the value is already updated through SSE by the OH server.

**Comment by maniac103** [comment]
Filtering out the value of page titles has been around 'forever': https://github.com/openhab/openhab-android/commit/a58245c098c647f4d74429f11c59dd2f708c7131#diff-3f4712530de18c074e8f711b4e38483eR118 ... one could change that, reformatting the title like BasicUI does (remove [ and ]).

Updating the title seems to be done by sending SSE events with widgetId == pageId.

**Comment by lolodomo** [comment]
Yes, I am the one who implemented this SSE event for title on server side. So I can confirm.
