### ISSUE TITLE
webview does not send authentication information when security option is turned on (or external)

### ISSUE THREAD

**Issue by elisman** [openhab/openhab-android#127]
Hi,

I open a new issue, as the discussion in the other issue relates to more than one topic and the issue is not described very clear.

There is an issue with HABdroid loading webviews when the security option is turned on. It always returns HTTP ERROR 401. All other UIs (like openhab.app or greenT interface) work well.

After some research, i found out that HABdroid always tries to load widgets, without authenticating. No matter what webview I try to load, HABdroid requests it through proxy in the way:

```
GET /proxy?sitemap=default.sitemap&widgetId=02010400
```

The response is always code 401 as authentication is required. Then HABdroid stops.

GreenT i.e. sends the same request, probably with credentials, and gets code 200 as answer.

In my sitemap a webview defined like this (example url, in my config I have an apache2 server configured):

```
Webview label="Temperaturverlauf dieses Jahr" url="https://www.google.de/" height=8
```
##

**Comment by solucionesmipc** [comment]
Some news about this issue? i think it is a major bug.

Diego

**Comment by elisman** [comment]
Unfortunately not.

**Comment by solucionesmipc** [comment]
Hi;

the issue is related with android vewrsion, it works ok in android 4.4

**Comment by bodiroga** [comment]
Hi guys!

Any new about this problem? I have been looking in the source code how the GET request is done for the webview and I haven't found any interesting thing. Does anybody know where I should look at? @belovictor?

**Comment by bodiroga** [comment]
Hi @elisman and @solucionesmipc !

I have created a pull request that solves the problem (at least is working fine here), let's see if @belovictor can have a look at it and releases a new version with the fix!

Best regards,

Aitor

**Comment by BClark09** [comment]
After installing the latest build (74)  I still get error 401 when trying to view something in a WebView widget. Here's the log:

```
"GET /rest/bindings HTTP/1.1" 404 0 
"GET /rest/sitemaps HTTP/1.1" 200 306 
"GET /rest/sitemaps/default/default HTTP/1.1" 200 2091 
"GET /rest/sitemaps/default/default HTTP/1.1" 200 0 
"GET /rest/sitemaps/default/0001 HTTP/1.1" 200 596 
"GET /rest/sitemaps/default/0001 HTTP/1.1" 200 0 
"GET /proxy?sitemap=default.sitemap&widgetId=000100&baseUrl=http%3A%2F%2Fhostname%3A8080 HTTP/1.1" 401 1376 
"GET /weather?locationId=home&layout=default&iconset=colorful HTTP/1.1" 401 1378 
"GET /proxy?sitemap=default.sitemap&widgetId=000100&baseUrl=http%3A%2F%2Fhostname%3A8080 HTTP/1.1" 200 1378 
```

Android Version: 5.1.1
OpenHAB Server: 1.8.0

**Comment by eschizoid** [comment]
@belovictor this is still happening on iOS version 1.7.1. Should I create a ticket for this or you want to reopen this one?

**Comment by kaikreuzer** [comment]
Let's reopen then.

**Comment by dobrMAN** [comment]
I have some error with Android openHAB client and openHAB 1.8.2 with authorization enabled for external IPs.

**Comment by eschizoid** [comment]
@dobrMAN what error are you getting? is it the unauthorized?

**Comment by dobrMAN** [comment]
@eschizoid yes, this is screenshot - [https://s22.postimg.org/a8l96n5rl/Screenshot_2016-04-01-15-19-20.png](url)

**Comment by eschizoid** [comment]
@belovictor is there any update or workaround related to this?

**Comment by BClark09** [comment]
Unfortunately, still getting the above unauthorized error for webview when using authentication from an external IP.

Any updated information on this would be helpful, as webview is an important part of my own usage, it is completely inaccessible on the app, and using the phone web browser as a work around is difficult.

HABDroid Version 1.7.0.1
Android Version 5.1.1
OpenHAB version 1.8.2

**Comment by elisman** [comment]
@BClark09 have you tried one of the latest builds? Unfortunately the App in the Play Store wasn't updated since then.

**Comment by BClark09** [comment]
@elisman This also happens with HABDroid Version 1.8.0.0 from CloudBees

**Comment by mueller-ma** [comment]
Should be fixed by https://github.com/openhab/openhab-android/pull/1254.
