### ISSUE TITLE
Switch widget with dynamic options

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#1281]
The app is not handling correctly the switch widget with dynamic options.

It handles static options with mappings defined in the sitemap by displaying a button for each mapping.

In case of dynamic options, it should display a button for each option too. Of course, it should do it only if the number of options is low. In Basic UI and Classic UI, the limit is set to 4 options (4 buttons). If there are 5 options or more, the widget is rendered as a simple switch.

Current behavior: dynamic options are ignored and a simple switch is displayed.

**Comment by mueller-ma** [comment]
Can you give us an example? E.g. which binding produces dynamic options.

**Comment by lolodomo** [comment]
Search for DynamicStateDescriptionProvider in OH2 bindings.
