### ISSUE TITLE
Switches don't update correctly

### ISSUE THREAD

**Issue by aaronsutton** [openhab/openhab-android#129]
I know this issue has been discussed numerous times on both the openHAB page and here on the Android app page (issue appears to be closed), but I still have no resolution. Toggling a switch in the Android app does not cause its state to update. You are forced to reload the app/page before it will show "on" and the number of bulbs turned on. I see that this issue has something to do with long polling in openHAB itself, but I can't imagine all the Android users out there are simply OK with living with this issue. I'm using HABDroid 1.7.0.1 and openHAB 1.7. This issue does not occur on the demo site. How can I fix this already?
##

**Comment by xsnrg** [comment]
It might help to know what kind of switches you have.  I am using the Denon binding recently, which I have configured with a power switch.  I am also using a great many insteon devices, most all of which are switches.  Finally, I also have a couple switched z-wave devices.  All of these are updating immediately in the mobile app whether toggled from the app or from the switch itself.  I am using 1.7.0.1 as well.

**Comment by aaronsutton** [comment]
I'm using the Philips Hue binding to control approximately 20 bulbs. I have these configured as on/off switches in openHAB. Toggle switches do seem to update.

**Comment by belovictor** [comment]
@aaronsutton , sorry for delay, I was on a vacation. Can you please check events.log if status of your switches really update after you press the switch in the app? There should be a command first, and a status update then.

**Comment by aaronsutton** [comment]
Thanks for getting back to me. After pressing the switch I see the command being sent, but do not see a status update.

**Comment by belovictor** [comment]
If you don't see a status update in your events.log, the state of the switch should not change even after reload of the page?

**Comment by chjop** [comment]
Not sure but I'm probably observing the same bug. But in my view this is an UI problem only:

* '''Everything is fine in the back-end''', I use KNX binding, status of Switch or Setpoint is correctly updated on the KNX bus. 

* Problem: The UI does not show the updated status. Obviously '''only Items in a frame''' of the main screen are affected, for Items within groups I could not observe this issue. 

- Example 1: I've a Setpoint to specify desired temperature in main frame. Pressing +/- of the Setpoint in HABDroid results in correctly send messages over KNX bus but the number value is not updated in the UI

- Example 2: I've a switch in the main menu. Toggling the switch in HABDroid does not update the switch_on / switch_off (bulb) icon. 

- Example 3: The before mentioned Switch does not update if light was switched on/off from sowhere else (e.g. the physical switch in the room). 

- If the switch is not located in directly in a sitemap frame (thus showing up in main screen) but in a group the switch works correctly in the group's screen. 

- If main screen was left (e.g. opening a group screen) and going back or clearing image cache is done, values are displayed correctly on main screen

- '''Everything works fine using the web UI''' 

Several other users recently reported similar behavior at that closed (but not solved) issue: https://github.com/openhab/openhab/issues/902

I'm using openHAB 1.7.1, HABDroid 1.7.0.1 on Android 6.0 and Android 4.4.2

Configuration is attached. 


[haus.items.txt](https://github.com/openhab/openhab.android/files/33354/haus.items.txt)
[haus.rules.txt](https://github.com/openhab/openhab.android/files/33355/haus.rules.txt)
[haus.sitemap.txt](https://github.com/openhab/openhab.android/files/33356/haus.sitemap.txt)

**Comment by stefanst** [comment]
I have what I assume to be the same problem with 1.7.1 and Habdroid. Web UI works fine.
After some testing:

Running the server on my Win7 box results in the app updating properly.
Running the server with identical configuration on my Raspberry Pi2, running the latest Raspbian leads to the issue with the Android app not updating.
The Web UI works well for both servers- Win7 and Raspbian.

So in my case this is an issue with this specific combination: Android app with Raspberry Pi server. Replacing one of these components with something else seems to fix it. I may have time to try the server on a different Linux (Ubuntu) box this weekend for some more data.

**Comment by chjop** [comment]
@stefanst: Sorry, can not confirm this. I'm also running openHAB on raspbian and using Win7 (but native) es test system. But buggy behavior in HABDroid is the same, regardless to what runtime instance i connect.

**Comment by aaronsutton** [comment]
I also cannot confirm this. Have tried with openHAB 1.7.1 running on Ubuntu 14.04 and Windows 10. The switches do not update on HABDroid when connecting to either server.

**Comment by chjop** [comment]
I changed my sitemap a bit, thus the switches and setpoints are not in the top-level frame anymore but in a nested frame (and thus not appearing on the main screen). In the nested frames, the items get updated as expected. 

Thus, the bug only occurs for items in a top-level frame otherwise behavior is as expected.

**Comment by aaronsutton** [comment]
Confirmed! Everything works as expected when the switches aren't on the main page.

**Comment by bruxi** [comment]
It's the same for me. Since my sitemap became a little mor complex, switches do not update anymore. Same for contact items with motion detectors. OH 1.7 is running on a Raspi2, Habdroid on Lollipop.

**Comment by robertoinberlin** [comment]
After analyzing and debugging the habdroid code, I figured out that I simply used an invalid  "sitemap" id. Name of sitemap file and sitemap id (first line in file) must match.

For instance: file name = default.sitemap, first line must be:
<code>sitemap default label="XXX"{</code>

**Comment by ddt3** [comment]
I see this too! Every now and then I see this when I update my config, sometimes rolling back to previous config works (I use git to manage my config updates) :-)

**Comment by jvictorsoto** [comment]
as @robertoinberlin commented sitemap filename and sitemap id must be the same. But also, label must be space free.

This causes this issue:
`sitemap` default label="My Home"{

This works just fine
`sitemap` default label="MyHome"{

Weird behavior, took me a while find how to fix it. As everyone pointed out, only happening on Android App and with top level switches.

**Comment by lolodomo** [comment]
Was this issue fixed or do we have to take care about file name and sitemap ID matching ?

**Comment by mueller-ma** [comment]
Long polling is only used as fallback mode, so all switches should update correctly.
