### ISSUE TITLE
writing nfc tag for a switch crash the app

### ISSUE THREAD

**Issue by bogdanioanliviu** [openhab/openhab-android#13]
I´d like to add a new issue to the Android app.
 Writing a nfc tag with a toggle switch it force close the app.
 Steps to reproduce: open the app, long hold over a switch, popup appear and select toggle, awaiting for tag, trying to write tag , force close.
 If you try the same with a group of items (from the demo FF_Bedroom items) it is working with out glitch.
Tested with sony xperia tags http://www.sonymobile.com/global-en/products/accessories/xperia-smarttags/
If a logcat is needed please let me know.
Version 1.5.1 
Rom used: CM11
Phone :xperia sp 
Thank you
##

**Comment by mueller-ma** [comment]
#1302 changes the uri for item update tags to `openhabitem://?i=item&s=state`, which is shorter than the current uri.
