### ISSUE TITLE
SITEMAP_CHANGED SSE breaks two pane mode

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1314]
### Expected behaviour
Sitemaps should be reloaded.

### Actual behaviour
In two pane mode if the app receives a SITEMAP_CHANGED server sent event, the right pane becomes a copy of the left one.

Example with the demo package: I have "Main Menu" on the left side and "First Floor" on the right one. If the sitemap is changed server side, the app shows "Main Menu" on the left and right side.

**Comment by maniac103** [comment]
I can't seem to be able to reproduce this.

**Comment by mueller-ma** [comment]
I can't reproduce this anymore, but it seems that this event isn't sent every time the sitemap is changed: https://github.com/openhab/openhab-core/issues/1525

**Comment by mueller-ma** [comment]
I can't reproduce this anymore.
