### ISSUE TITLE
After installing voice recognition app, widgets still don't work

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1323]
### Actual behaviour
If no voice recognizer is installed at widget creation time, a click on the mic opens the play store with the Google app entry. After installing this app, the mic still opens the play store.

### Expected behaviour
The UX should be improved, e.g. by blocking the widget creation if no voice recognition app is installed. Open Play Store or a dialog instead.

**Comment by maniac103** [comment]
Could also disable the widget receiver in PackageManager, which should hide the widget from selection.
