### ISSUE TITLE
Bug found in ( openhab-android 2.6.20 ) When I use audio  mic , the application crashes

### ISSUE THREAD

**Issue by facebook-786** [openhab/openhab-android#1334]
# Project Information
* Repository: https://github.com/openhab/openhab-android
* Project Name:  openhab-android

# Expected behavior

The application should not crash when I use the audio mic option 

# Actual behavior

When I open mic option  and search  a sound, The application crashes And automatically closes the application

# How to reproduce

1-[Download ](https://github.com/openhab/openhab-android/releases)the latest application
2-install and open the application
3- Enable Demo Mode 
4- click on mic option
5- Search for anything by voice
* Browser/App version:   2.6.20
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190503_160505](https://user-images.githubusercontent.com/50115498/57134371-d801ed80-6d5a-11e9-9e26-a8f9cd036c3e.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(10775): FATAL EXCEPTION: main

E/AndroidRuntime(10775): Process: org.openhab.habdroid.beta, PID: 10775

E/AndroidRuntime(10775): android.content.res.Resources$NotFoundException: Resource ID #0xffff5722

E/AndroidRuntime(10775): 	at android.content.res.Resources.getValue(Resources.java:1542)

E/AndroidRuntime(10775): 	at android.content.res.Resources.getColor(Resources.java:1184)

E/AndroidRuntime(10775): 	at androidx.core.content.ContextCompat.getColor(ContextCompat.java:525)

E/AndroidRuntime(10775): 	at es.dmoral.toasty.ToastyUtils.getColor(ToastyUtils.java:59)

E/AndroidRuntime(10775): 	at es.dmoral.toasty.Toasty.custom(Toasty.java:275)

E/AndroidRuntime(10775): 	at org.openhab.habdroid.core.VoiceService.lambda$showToast$0$VoiceService(VoiceService.java:96)

E/AndroidRuntime(10775): 	at org.openhab.habdroid.core.-$$Lambda$VoiceService$vLaZu2FasChqZZb8OLY6AABbZ_s.run(lambda)

E/AndroidRuntime(10775): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(10775): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(10775): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(10775): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(10775): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(10775): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(10775): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(10775): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by mueller-ma** [comment]
Thanks for your report. This is a known bug in the Toasty library.

**Comment by mueller-ma** [comment]
Just found the reason for this crash. Thanks for testing the beta.
