### ISSUE TITLE
AlarmClock<->Tasker Issue

### ISSUE THREAD

**Issue by oehm2007** [openhab/openhab-android#1341]
### Actual behaviour
Describe us what happens:
The time of the alarmclock is not sent if you are using tasker at the same time. So you have to deactivate the tasker app and the Item AlarmClock is updated correctly.

Using the latest beta app 2.6.21-beta

**Comment by mueller-ma** [comment]
We should add a toast showing the alarm clock time whenever we receive the alarm clock changed broadcast. That should make it easier to debug.

**Comment by maniac103** [comment]
For debugging it should totally be sufficient to do a log message. As we already have a notification if alarm time upload is enabled and there's nothing to debug if it's disabled, I don't like the idea of showing a toast in that case.

**Comment by oehm2007** [comment]
It is possible to find out which app sets the alarm. So you could make options which apps should be allowed to send a alarmtimes to the OH app.

**Comment by maniac103** [comment]
> It is possible to find out which app sets the alarm.

How? Via the PendingIntent that's part of the AlarmClockInfo class instance?

> So you could make options which apps should be allowed to send a alarmtimes to the OH app.

How does that help with the problem in question?

**Comment by oehm2007** [comment]
I only know that it is possible, because I had a similar problem here:
https://community.openhab.org/t/android-alarm-and-openhab2/42283/24?u=oeo
> How does that help with the problem in question?
Because if you only allow alarms from the integrated android alarmclick, people who are using tasker to set the alarm cannot use tasker for generating alarmtimes.

**Comment by maniac103** [comment]
> I only know that it is possible

From that forum link I checked the source, and et voilà: https://github.com/ekahlenberger/HomeAutomationAlarmSender/blob/master/app/src/main/java/net/kahlenberger/eberhard/haas/background/AlarmChangedReceiver.kt#L22 ;-)

> people who are using tasker to set the alarm

I do not understand. Tasker has an integrated alarm clock? If it doesn't, where does it get the showIntent (IOW, the alarm UI) get from?

**Comment by oehm2007** [comment]
Maybe you are right, but I thought there is indeed just one central android alarmclock. But this alarmclock can be set by different apps including the original android app, tasker etc.

**Comment by mueller-ma** [comment]
> I do not understand. Tasker has an integrated alarm clock?

No. My guess is that it uses AlarmManager for making sure the app is restarted after it has been killed. I suggest to add a switch to the alarm clock item setting dialog that allows ignoring tasker and apps that behave similar.

**Comment by maniac103** [comment]
@mueller-ma What exactly is the issue here? I don't yet understand the problem (I'm not using Tasker myself).

**Comment by mueller-ma** [comment]
I have a single task ("Every 10h update one openHAB item", mainly for testing the item picker). However I receive every 10 to 30 seconds the alarm clock changed broadcast, set by Tasker.
FireOS (The Android fork by Amazon) displays an alarm clock icon in the notification bar when there's a pending alarm. As soon you install Tasker, it's shown.

**Comment by mueller-ma** [comment]
There should be a setting that allows enabling/disabling specific apps or we maintain a blacklist and simply ignore alarms from these apps.

**Comment by tarcus69** [comment]
Is it possible to read an alarm's label? E.g. in the standard alarm clock on Android 9 I can set an alarm and give it a label "wake up", can you filter on these? If so, surely this would be a better approach anyway for everyone as then users, even those who don't use Tasker, can have multiple alarms but have OpenHab trigger on specific ones, e.g. "wake up", "charge car", "put bins out" etc.

**Comment by mueller-ma** [comment]
> Is it possible to read an alarm's label?

No, the api is only aware of the app that created the alarm and the time.
