### ISSUE TITLE
Inconsistent web widget behavior

### ISSUE THREAD

**Issue by Sonic-Amiga** [openhab/openhab-android#1342]
I am running BasicUI on wall panel. I added Webview, displaying weather informer from one of local providers. When using this, i notice two problems:
1. The provider insists on having links to itself in the widget, it doesn't work if they are removed. These links have target="_blank" attribute, so they would open in a new browser window, but instead the WebWidget jumps to the new URL itself, breaking the UI.
2. The widget has a fixed width, which is smaller than panel display width. This leaves colored rectangle around the content, which looks ugly. Setting transparent background via CSS results in white color, apparently the WebView itself is not transparent

**Comment by Sonic-Amiga** [comment]
Here is the proposed fix: https://github.com/openhab/openhab-android/pull/1343
In the long run perhaps it would be nice to have preference item to enable or disable opening these links in external browser. Sometimes it can be handy, for instance my weather widget would open 2-week forecast. But even simple disable is better than current behavior.

**Comment by mueller-ma** [comment]
> _blank: Load the URL into a new browsing context. This is usually a tab, but users can configure browsers to use new windows instead.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

Links with `target="_blank"` should always be opened in a browser, no setting needed here.

**Comment by Sonic-Amiga** [comment]
I imagined a dedicated setup where HABDroid replaces the launcher. In this case perhaps you would not want the user to escape at all.
 OK, makes sense too. Let's do this first, then add preference item if really needed or requested.

**Comment by mueller-ma** [comment]
Even if a preference is requested, I still disagree. The website explicitly requests to be opened in a new tab/window.

**Comment by Sonic-Amiga** [comment]
I've tested it myself, and you know what... This isn't bad. Now i can tap on the informer and see 2 weeks forecast in the browser. This is convenient.

**Comment by Sonic-Amiga** [comment]
Since the patch has landed, i am closing this. There's a separate issue reported against core regarding transparency
