### ISSUE TITLE
MapView popup not fullscreen

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1346]
### Actual behaviour
MapView popup is not fullscreen on a ten inch device:
![5](https://user-images.githubusercontent.com/22525368/57241128-96aa6000-7030-11e9-94fa-bfe25dd8b70c.png)

### Can you reproduce the issue in demo mode?

Yes

#### Client
* Android version: Android P
* Device model: Nexus 10
* Stock or customized ROM: Stock
* Build flavor : Full
* Device language: EN

**Comment by maniac103** [comment]
I ... don't see what's wrong in that screenshot? The map opens in a dialog, as do other widgets.

**Comment by mueller-ma** [comment]
The popup could wider than it is. On phone and seven inch it is as wide as the screen.

**Comment by mueller-ma** [comment]
It's actually quite simple to fix:
````
@@ -135,6 +141,8 @@ public class MapViewHelper {
             });
             dialog.setCanceledOnTouchOutside(true);
             dialog.show();
+            dialog.getWindow().setLayout(FrameLayout.LayoutParams.MATCH_PARENT,
+ FrameLayout.LayoutParams.MATCH_PARENT);
````

Should I open a PR?

**Comment by maniac103** [comment]
The correct fix probably would be overriding the dialog width limitation in the  theme resources. I don't recall the details (need to look this up), but I'm pretty sire there's an `android:maxWidth` defined in the theme for the tablet case.

**Comment by mueller-ma** [comment]
I tried setting multiple attributes, but none fixed the issue.
