### ISSUE TITLE
AlarmClock sends timestamp on 5 minutes earlier than Alarm is actually configured

### ISSUE THREAD

**Issue by dimka-dk** [openhab/openhab-android#1363]
### Actual behaviour
Describe us what happens
AlarmClock sends timestamp on 5 minutes earlier than Alarm is actually configured

### Expected behaviour
AlarmClock should contain exactly same timestamp as configured Alarm on the phone

 
### Steps to reproduce
1. set alarm for exampl 14:30
2. check logs 
2019-05-23 11:17:52.734 [ome.event.ItemCommandEvent] - Item 'AlarmClock' received command 1558614301000
3. convert timestamp 
Timestamp Converter
1558614301
Is equivalent to:
05/23/2019 @ 12:25pm (UTC)
2019-05-23T12:25:01+00:00 in ISO 8601

my timezone UTC+2 : so 1558614301 equals to 14:25 NOT 14:30!

#### Client
* Android version: 9
* Device model: Samsung  @S9
![Screenshot_20190523-111745_Clock](https://user-images.githubusercontent.com/22378543/58241560-80e5ac00-7d4d-11e9-889e-e463dd375d9a.jpg)

* Stock or customized ROM: 
* App version : 
* Build flavor : 
* Device language: 

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: 
* Authentication method : 

#### App log
```
Open the app, go to `Settings` => `View log` and insert the log here.
```

#### openHAB Server log
```
Insert your log here. If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here.
For nginx: `/var/log/nginx/error.log`
For Apache 2: `/var/log/apache2/error.log`
```
```
Insert your reverse proxy access log here
For nginx: `/var/log/nginx/access.log`
For Apache 2: `/var/log/apache2/access.log`
```

**Comment by maniac103** [comment]
Blame Samsung's alarm clock app. The openHAB app can only the data provided by the alarm clock app, and if that's set too early for whatever reason (I'd suspect waking up from power-off mode), I don't really see what we could do about that.

**Comment by dimka-dk** [comment]
Aparently it's known issue with Samsung Clock after upgrade to Pie[1]. @maniac103 you can close this isssue - indeed it's not your bug. Thanks !

[1] https://eu.community.samsung.com/t5/Galaxy-S9-S9/Pie-Clock-app-bug/td-p/927333

**Comment by mueller-ma** [comment]
> Blame Samsung's alarm clock app. The openHAB app can only the data provided by the alarm clock app, and if that's set too early for whatever reason (I'd suspect waking up from power-off mode), I don't really see what we could do about that.

We should add this to the docs site.
