### ISSUE TITLE
Images flickering

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#1366]
### Actual behaviour
Image widget causes annoying flicker on refresh when item changes.
Additional, the divider between the items flickers on value change.

I'm using the ipcamera binding which updates the item each e.g. second. This is annoying when this causes flicker in the app. In Basic UI, the image is just replaced.

### Expected behaviour
Just show the new image.
 
### Steps to reproduce
1. Define image item
2. Use image widget in sitemap for item
3. Constantly update item
4. Watch android app flicker like crazy

App version: Current release 2.7.0

**Comment by mueller-ma** [comment]
The divider flicker can be fixed quite easy: https://stackoverflow.com/a/36437317.

**Comment by maniac103** [comment]
We already *do* call notifyItemChanged instead of notifyDataSetChanged though.

**Comment by mueller-ma** [comment]
Yes, but the change animation is enabled.

**Comment by maniac103** [comment]
@cribskip Is [this one](https://community.openhab.org/t/ipcamera-new-ip-camera-binding/42771) the binding you're talking about? If so, are you using the 'image' channel or one of the URL ones (e.g. 'imageUrl')?

(If that's the binding you're using, I'd assume that using the 'image' channel probably avoids the flicker. Is that correct?)

**Comment by mueller-ma** [comment]
>  Additional, the divider between the items flickers on value change.

This is fixed in #1402.
