### ISSUE TITLE
Advanced example of AlarmClock rule usage

### ISSUE THREAD

**Issue by dimka-dk** [openhab/openhab-android#1368]
Hey guys,

  I have looked into example that you provide for AlarmClock var usage and thought it's a bit not optimal - running crontab on each 10 seconds when we have native Timer object. 

  Here is my suggestion to have it as a bit more advanced example to be provided in USAGE.md 
```
var Timer timerAlarm = null

rule "alarms"
when
	Item AlarmClock changed
then
	logInfo("alarms", "start")
	if (AlarmClock.state as Number == 0) {
		if (timerAlarm !== null) {
			timerAlarm.cancel
			timerAlarm = null
		}
		logInfo("alarms", "All alarms are cancelled")
	} else {
		var epoch = new DateTime(( AlarmClock.state as Number  ).longValue )

		// temporary fix from Samsung clock on Pie
		epoch = epoch.plusMinutes(5)

		logInfo("alarms", "Scheduling alarm for " +  epoch.toString )


		if (timerAlarm !== null) {
			logInfo("alarms", "Reschedule alarm")
			timerAlarm.reschedule( epoch ) 
		} else {	
			logInfo("alarms", "New Alarm")
			timerAlarm = createTimerWithArgument( epoch, null,
				[ k |
					// ADD your custom commands here 

					// Office_Light.sendCommand(ON)

					// END of custom commands
					logInfo("alarms", "alarm is expired")
				]
			)
		}
	}
	logInfo("alarms", "stop")
end
```

**Comment by mueller-ma** [comment]
Hey @dimka-dk,
thanks for your suggestion. Did you test this rule?
And can you open a PR to change the example rule?

**Comment by JensErat** [comment]
Works great for me -- I had to change `createTimerWithArgument( epoch, null, lambda)` to `createTimer( epoch, lambda)` though. Not sure whether this was actually an issue or I just misobserved.

**Comment by Byter3** [comment]
Hi there!
Can someone upgrade this to OH3? I couldn't figure out myself... :(

**Comment by mueller-ma** [comment]
The rule should be up to date for oh3: https://www.openhab.org/docs/apps/android.html#alarm-clock
