### ISSUE TITLE
Behaviour speed regression of NFC tag when connection not yet established

### ISSUE THREAD

**Issue by tarilabs** [openhab/openhab-android#1370]
#### Current behaviour
I am reaching the front door of my house and I tap successfully the NFC tag. A toast message is displayed. The mobile will eventually connect to the WiFi. **_After a while, longer,_** the NFC action will trigger the switch correctly.

#### Previous behaviour
I am reaching the front door of my house and I tap successfully the NFC tag. As the connection to the OpenHAB on local network is not yet established, the activity page with the big "no signal" icon is displayed. The mobile eventually connects to the WiFi. **_Instantly_** as the WiFi is connected, the NFC action will trigger the switch correctly, the activity page with the "no signal" icon disappears immediately.
This behaviour was preferred for speedy performance on WiFi established connection.

### Describe the solution you'd like
To display a Toast as the NFC action is recognised is fine.
In the case the connection to OpenHAB are initially not successful, it would be ideal if, say for the first 60s/30s, the further attempts to connect to OpenHAB are done faster.

### Describe alternatives you've considered
- NFC action is triggered. If connection to OpenHAB is successful, display a Toast. If connection to OpenHAB is not initially successful, display the "no signal" icon activity; that is fallback to previous behaviour.
- A settings on the mobile app to choose between new Toast based for NFC action (new behaviour) or bring up Activity (old behaviour)

### Additional context
The use case is approaching the front door of the house and use the NFC tap to trigger some OpenHAB actions of Welcome: this used to be very responsive with the previous behaviour (Activity page with "no signal" icon) because really immediately after WiFi did connect, the action on OpenHAB was performed; with the current Toast-based behaviour, there is still a response, but this happening way delayed, I didn't clocked but definitely at least about 30s later.

Can you kindly consider either of the 3 solutions above, or additional, to resolve this regression in behaviour speed, please?

btw Thank You, OpenHAB is really awesome!! 🙏 :)

**Comment by mueller-ma** [comment]
> In the case the connection to OpenHAB are initially not successful, it would be ideal if, say for the first 60s/30s, the further attempts to connect to OpenHAB are done faster.

Yes, that sounds good, but the same code is used to change the alarm clock item and imagine the case where a user has no remote connection and the alarm clock time changes. If we retry 3 times with each 10 seconds delay, he get's an error notification after 30 seconds.

Maybe we should change the retry count and the time between retries:
https://developer.android.com/topic/libraries/architecture/workmanager/how-to/define-work#retries_backoff
https://developer.android.com/reference/androidx/work/WorkRequest.html#DEFAULT_BACKOFF_DELAY_MILLIS

**Comment by mueller-ma** [comment]
> The first retry is now after 10 seconds, the second one after 20, ...

from #1401
