### ISSUE TITLE
Label & Value Color not changing

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#1380]
Found the issue [here](https://community.openhab.org/t/label-text-color-does-not-change-on-update/75406) and added my POV :-)

### Actual behaviour
Using valuecolor or labelcolor settings, the setting is not applied to new values, thus requiring a manual refresh by pulling down or reopening the sitemap.

### Expected behaviour
Color should be applied to new values.

### Steps to reproduce
1. Text item=AlarmSystemStatus_Output label="[MAP(alarmstatus.map):%s]" valuecolor=[>4="red",>2="yellow",==1="green"] icon="alarm" 
2. Change the value and watch color to change

#### Client
* Android version: 9
* Device model: Xiaomi Poco Phone F1 / Mi 9
* Stock or customized ROM: stock / MIUI 10.3.4 based on Android 9
* App version : 2.6.9 & 2.7.1-beta
* Build flavor : Full
* Device language: ? / German

**Comment by maniac103** [comment]
Hmm, we currently don't parse the colors out of the SSE response: https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/model/Widget.java#L329 ... are they actually part of the SSE events?

**Comment by maniac103** [comment]
We probably also should parse the icon from the response. Full response: https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapWidgetEvent.java

**Comment by maniac103** [comment]
(BTW, @mueller-ma, should we/I do this before or after the Kotlin conversion? Same question applies to the chart scaling fix.)

**Comment by mueller-ma** [comment]
> (BTW, @mueller-ma, should we/I do this before or after the Kotlin conversion? Same question applies to the chart scaling fix.)

Makes sense for both, so we can release a version with shortcuts and tasker and after that merge #1347 and #1356.

**Comment by maniac103** [comment]
> Makes sense for both

What makes sense - add those fixes *before* or *after* Kotlin conversion? ;-)

**Comment by mueller-ma** [comment]
Fixing them before the kotlin merge.

**Comment by maniac103** [comment]
OK, I'll send some PRs.
