### ISSUE TITLE
Setpoint with step 0.5 not working after it has been changed in Basic UI

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1389]
### Actual behaviour
Item:
````
Number ASetpoint "Target Temperature [%.1f °C]"
````
Sitemap:
````
Setpoint item=ASetpoint minValue=23 maxValue=26 step=0.5
````
If I set the value to 24.5 via Basic UI and open the setpoint in the app, everything is working. If I change it via Basic UI to 24, the selectable values in the app are 23, 24, 24, 25, 25, 26, 26.
It's important to use Basic UI to change the item values. If I only use the app, everything is working.

### Can you reproduce the issue in demo mode?

Yes: Widget Overview => Temperature (http://demo.openhab.org:8080/basicui/app?w=0202&sitemap=demo)

**Comment by mueller-ma** [comment]
If set by Basic UI:
![doesnt work](https://user-images.githubusercontent.com/22525368/59148507-1e0d3980-8a0a-11e9-8db1-04981df68cb6.JPG)
If set by app:
![works](https://user-images.githubusercontent.com/22525368/59148508-1ea5d000-8a0a-11e9-954d-d77ebd4ec92d.JPG)

Please note: the state is `22` vs `22.0`.

**Comment by mueller-ma** [comment]
If step size is not an Integer, the state should be parsed as Float: https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/model/ParsedState.java#L195

**Comment by maniac103** [comment]
> If step size is not an Integer, the state should be parsed as Float

This certainly fixes the issue, but all of this feels like a huge mess. There seems to be no docs on what exactly we're supposed to do here, and we're left with guesswork, right?

**Comment by mueller-ma** [comment]
I think the "issue" here is, that Java makes a distinction between int and float/double, but JSON/JS doesn't:

> JSON's basic data types are:
>  * Number: a signed decimal number that may contain a fractional part and may use exponential E notation, but cannot include non-numbers such as NaN. The format makes no distinction between integer and floating-point. JavaScript uses a double-precision floating-point format for all its numeric values, but other languages implementing JSON may encode numbers differently.

from https://en.wikipedia.org/wiki/JSON#Data_types_and_syntax

**Comment by maniac103** [comment]
Well, yeah, almost: the *actual* issue is that we use the number format pattern provided by the server and BasicUI does not ;-) That's the reason for the int vs. float differentiation, because we need to match the format (`%d` vs. `℅f`) ... I wonder how core handles that, need to dig this up.
