### ISSUE TITLE
hide Action Bar when scrolling down

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-android#139]
It would be great if the action bar would hide when you scroll down the sietmap.
Like the address bar does in chrome.

This would save more screen space than the immersive mode you can enable in the app.

I am not a developer, but it looks easy to implement.
http://developer.android.com/guide/topics/ui/actionbar.html#Removing
##

**Comment by frode** [comment]
Good suggestion, +1 from me

**Comment by elisman** [comment]
I also think this is a good suggestion and should be implemented.

**Comment by CristianSarac** [comment]
I would like to try and implement this feature
@digitaldan  is this something of interest for the APP ?

**Comment by digitaldan** [comment]
Absolutely!

**Comment by mueller-ma** [comment]
@maniac103 I think this issue is a "won't fix" as you just added the elevation when scrolling (in https://github.com/openhab/openhab-android/releases/tag/2.23.5-beta)?

**Comment by maniac103** [comment]
It's not a problem to implement from a technical point of view, but IMO it's not really worth it, since screens have become much longer in the last 6 years.
