### ISSUE TITLE
Widgets do not disappear when Visibility changes to false

### ISSUE THREAD

**Issue by Sonic-Amiga** [openhab/openhab-android#1392]
I have air conditioner controls set up in my sitemap. Visibility of controls depends on state of the master power Switch. After i set the switch to ON, dependent controls appear on the screen. But when i set the switch back to OFF, widgets show "nil" values but don't disappear from the display. I have to refresh the sitemap in order for them to disappear.
Demo mode doesn't seem to have any dynamic visibility settings, so can't reproduce in demo mode. The following is a fragment of my sitemap:
--- cut ---
Switch item=LRAC_Power label="Power"
Selection item=LRAC_Mode label="Mode" mappings=["AUTO"="Auto", "COLD"="Cooling", "HEAT"="Heating", "FAN"="Fan", "DEHUMIDIFIER"="Dryer"] visibility=[LRAC_Power==ON]
Setpoint item=LRAC_SetPoint label="Set temperature [%.1f °C]" visibility=[LRAC_Power==ON]
 --- cut ---

**Comment by maniac103** [comment]
Yeah, that's right. Only the invisible -> visible direction is handled.
Related: #1174 ... I'll get at this again after #1356.
