### ISSUE TITLE
App force closes when navigating to notifications

### ISSUE THREAD

**Issue by frode** [openhab/openhab-android#143]
Using a Sony Xperia Z5 the notifications functionality does not work on my phone.

As soon I click on the notifications menu item, the app force closes. Reported a few of these errors by using the "REPORT" option when the app crashes, I assume these reports lands to the developers for this app?
##

**Comment by SoullessWaffle** [comment]
I am also experiencing this issue on my Sony Xperia Z2 (Android 5.0.2)

**Comment by petzlux** [comment]
Yep same here ! Nexus5 with Android 6

**Comment by mtitus83** [comment]
Can confirm, Samsung Galasy s6 Edge using HABDroid 1.7.0.1 from playstore

**Comment by dominicdesu** [comment]
I believe this has been fixed in the meanwhile, can anyone confirm?
