### ISSUE TITLE
Frame visibility in sitemap ignored

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-android#1437]
PR #1174 looks to be included in 2.7.10-beta, so it may have caused this, or it isn't included and may fix this issue.

### Actual behaviour
Sitemaps with items that should be hidden are always visible. Basic UI displays them properly.

### Expected behaviour
Sitemaps with items that should be hidden should be hidden.

### Steps to reproduce
1. Add Item1 to a sitemap inside a frame with visibility based on Item2.
2. Toggle Item2 and notice visibility of Item1 does not change.

Here is a snip from the sitemap where I see this occurring...
```
    Frame visibility=[Mode=="Morning"] {
        Switch item=Wakeup_Alarm
        Switch item=Wakeup_Alarm_Snooze
    }
```

#### Client
* Android version: 2.7.10-beta

#### Server
* Server version: S1627

**Comment by maniac103** [comment]
What seems to happen for me is that only the frame gets hidden, but not the items in the frame. Is that what you're seeing as well?

**Comment by openhab-5iver** [comment]
Yes, that is what I am seeing too. The Family Room Color is in one frame and the Wakeup Alarm and Snooze are in another, and both frames should be hidden...

![oh Android vis](https://user-images.githubusercontent.com/21967853/60880825-68a0f200-a212-11e9-9699-7ff5a4cf02c5.png)

**Comment by maniac103** [comment]
OK, then we're on the same page. The referenced PR should fix the issue.

**Comment by openhab-5iver** [comment]
This is still occurring with version 2.7.16-beta.

**Comment by mueller-ma** [comment]
I cannot reproduce this anymore.

**Comment by openhab-5iver** [comment]
Hmmm... I can. Currently on 2.7.17-beta, OH S1646. Multiple devices and multiple sitemaps.

```
sitemap Test label="Test" {
    Frame visibility=[Mode == "Morning"] {
        Text item=Mode
    }
}
```
![image](https://user-images.githubusercontent.com/21967853/62320551-72fb8800-b46e-11e9-8eea-8a11954e3577.png)

**Comment by maniac103** [comment]
@mueller-ma Are you on a 2.5 snapshot? If not, problem probably is in the visibility flag handling, which doesn't exist (properly) in 2.4.
@openhab-5iver I assume reported server API version in the about page is 2? If so, I'll recheck with my 2.5 test setup when I'm back from vacation next week.

**Comment by openhab-5iver** [comment]
> I assume reported server API version in the about page is 2?

Correct

**Comment by mueller-ma** [comment]
````bash
$ dpkg --list | grep openhab
ii  openhab2                              2.5.0~S1549-1                     all          openhab2
````

Api version is 2.

**Comment by mueller-ma** [comment]
````bash
# dpkg --list | grep openhab
ii  openhab2                              2.5.0~S1652-1                     all          openhab2
# cat /etc/apt/sources.list.d/openhab2.list
deb https://openhab.jfrog.io/openhab/openhab-linuxpkg unstable main
````

I'll updated to the latest version. Now frames don't hide automatically in both app and basic ui, but are hidden/shown after a manual reload.

**Comment by maniac103** [comment]
So it's a regression in the server?

**Comment by openhab-5iver** [comment]
I tested this too and it does seem that there is an issue with Basic UI too. The page needs to be refreshed for the visibility to update after a change. The only seems to affect the visibility of frames... Items changed without a refresh.

**Comment by maniac103** [comment]
Classic UI uses long polling, not SSE. From looking at debug logs, it looks like SSE events aren't sent out in the 'frame visibility changed' cases.

**Comment by openhab-5iver** [comment]
OK, thank you. I'll move the issue to core.

**Comment by maniac103** [comment]
@openhab-5iver In fact, it looks like the original issue setup (no core problem, but app and web UI problem) was correct. After https://github.com/openhab/openhab-core/pull/909 and https://github.com/openhab/openhab-core/pull/691 core doesn't fill out the 'item' field for SSE events which only indicate visibility or color changes anymore. Clients need to be able to deal with that. I'll submit a PR for the app to fix this, fix is trivial.

**Comment by openhab-5iver** [comment]
Alright... so I should close the core issue and reopen the one for Basic UI?

**Comment by maniac103** [comment]
I think so, yes.

**Comment by openhab-5iver** [comment]
Is #1466 included in 2.8.11-beta (29 Aug)? If so, it does not appear to have resolved this.

**Comment by maniac103** [comment]
Seems to work fine for me using a checkout of master as of today.

Items file:
```
Switch TestSwitch "Test [%s]"
```

Sitemap:
```
sitemap demo label="Demo Sitemap" {
    Frame label="Test" {	
	   Switch item=TestSwitch
	}
    Frame label="VisTest" visibility=[TestSwitch==ON] {
        Text item=TestSwitch
    }
}
```

Result: As soon as I flip the switch from on to off, the resulting sitemap disappears completely.
@openhab-5iver Does this demo setup behavior behave the same or differently for you? If it behaves the same way, we'd need to find a reproducer that doesn't depend on your local setup.

**Comment by openhab-5iver** [comment]
I setup the same and it works, but stops working if you remove the label from the frame...
```
sitemap demo label="Demo Sitemap" {
    Frame label="Test" {	
	   Switch item=TestSwitch
	}
    Frame visibility=[TestSwitch==ON] {
        Text item=TestSwitch
    }
}
```
... which is how I have it setup in production. Is the label required?!

**Comment by maniac103** [comment]
> Is the label required?

It looks like that's the case currently. We internally filter out frames without label for whatever reason. Since I don't understand the rationale for this either, I created #1502 which changes the behavior to just hide the label in that case, but keep the frame widget:

![Screenshot_1567418755](https://user-images.githubusercontent.com/781373/64107122-0a0f7480-cd7a-11e9-8ef4-e1f4a44328f9.png)
