### ISSUE TITLE
Sitemap shortcuts don't work if HABPanel is open

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1446]
### Steps to reproduce
1. Open HABPanel
2. Leave app via home button (HABPanel is still open and the app is in background)
3. Click on a sitemap shortcut on the home screen
4. The sitemap should be shown, but HABPanel is.

### Can you reproduce the issue in demo mode?

Yes

#### Client
* App version : 2.7.12-beta

**Comment by maniac103** [comment]
Probably just need to clear the temporary page in `ContentController.openPage`.
