### ISSUE TITLE
Unable to set non-boolean values

### ISSUE THREAD

**Issue by backinabit** [openhab/openhab-android#1492]
In the Android application (play store, current as of this bug report), only fields of boolean types can be adjusted. Other settable types (in particular; integer, enum) cannot be set.

Background:
Openhab version 2.4.0 stable from https://dl.bintray.com/openhab/rpm-repo2/stable on Fedora 30.
"Things" are compliant with homie 3.0.1.
All settings defined as settable are configurable in paperui, regardless of data type.

**Comment by mueller-ma** [comment]
Can you please fill out the issue template?
Which app version, android version, example item and sitemap file?

**Comment by maniac103** [comment]
@mueller-ma I guess it's the _default sitemap.

@backinabit What's the output of visiting http://<yourserver>:8080/rest/sitemaps/_default/_default in a browser? Feel free to redact to only include the items relevant here.

**Comment by maniac103** [comment]
@backinabit OK, thanks. And which of the items is the problematic one?

**Comment by maniac103** [comment]
What's the respective behavior in BasicUI? As PaperUI is mostly a management interface, we use BasicUI as behavior reference.
From a first look, the widget type for all 3 widgets is `Text`, which indicates that only the value should be shown, which means that AFAICT the current behavior is correct. For it to work as expected, the widget types should be `Setpoint` (for 000003) and `Selection` or `Switch` (for the other two).

**Comment by backinabit** [comment]
I'm not sure how to find "BasicUI"?
When I browse to localhost:8080, it offers me the choice of HABPANEL and PAPER UI. Nothing else.

Its sounding to me like the issue may be related to how the property datatypes in homie are being translated into OpenHAB. In particular, I would expect that Setpoint would be related to integer or float types in homie, that Selection would be related to enum in homie, and that Switch would be boolean in homie. Note that I am using enum for both 000004 and 000005 (On vs Auto, to be a little more accurate than On vs Off), yet somehow this is being translated into text in OpenHAB?

And this, of course, begs the question, why does it work correctly in PaperUI?

**Comment by backinabit** [comment]
I seem to have muddled my way through to finding BasicUI. Its behavior matches the Android application.

**Comment by maniac103** [comment]
> And this, of course, begs the question, why does it work correctly in PaperUI?

Because the app and BasicUI are sitemap based, while PaperUI is not (it only operates on items). The Homie integration (AFAIK, I haven't used it myself) creates the items, but no sitemap for it.
See here for docs on sitemaps:  https://www.openhab.org/docs/configuration/sitemaps.html ... the short version is: the sitemap is the presentation definition which defines how the items are shown to the user. If there is no sitemap, a default (fallback) one is used that just textually shows all items without a way to edit them.

**Comment by backinabit** [comment]
Ok, then from that point of view, its sounding like this is not a bug, but rather a case of expectations not being met.

My expectations were driven by this document; https://www.openhab.org/blog/2018-12-16-mqtt-arrives-in-the-modern-openhab-2-x-architecture.html and in particular, the line "If you setup your next DIY Home-Automation gadget, consider flashing it with a Homie 3.x compatible firmware and it will work with openHAB right away."

In any case, I appreciate your time.

**Comment by mueller-ma** [comment]
I suggest you ask for help in the forum: https://community.openhab.org/

**Comment by maniac103** [comment]
> "If you setup your next DIY Home-Automation gadget, consider flashing it with a Homie 3.x compatible firmware and it will work with openHAB right away."

But it does ;-)
The problem simply is the target audience for that document is existing openHAB users, who know the differences between items and sitemaps, because openHAB always has behaved like that. That's why this document doesn't talk about the sitemap aspect at all, it just describes that the process to create items in openHAB for your MQTT device became more simple.

**Comment by backinabit** [comment]
I appreciate the education on this software.

Unfortunately, it is looking like the burden of just setting openHAB up to do what I need it to do will be an order of magnitude greater than writing my own software from scratch that does precisely what I need it to do and nothing else.

**Comment by maniac103** [comment]
I ... somehow doubt that, especially given you'd also need to write the client(s) from scratch, but whatever ... just do what fits you best.

**Comment by backinabit** [comment]
I think you're looking at it from the wrong point of view. I don't mean to duplicate openHAB. I don't need the kitchen sink. I mostly just need to see what the current status is of all my devices, and be able to set settable attributes. I have absolutely NO need to interact with any non-homie devices (I don't use closed source iot -- I write my own firmware, and sometimes even print my own boards), so I don't need anything to act as a translator between a hundred different protocols and schemes. I can go straight to mqtt and homie.

There is also no need to write clients from scratch. There are well defined libraries for mqtt and homie on Android (the only client platform relevant to me), which means that the job of getting to 95% of what I need, is just presenting each homie node on all "ready" devices as a card, and each attribute with a widget that matches its datatype, enabled if settable, disabled if not.

And for that matter, there is also this as a starting point;
https://github.com/plugdio/homie-dash

The other 5% will just be logging to mysql and a few crons.
