### ISSUE TITLE
Handle new `anyFormat` parameter

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1507]
Basic UI: https://github.com/openhab/openhab-webui/pull/114
Classic UI: https://github.com/openhab/openhab-webui/pull/113
Server: https://github.com/openhab/openhab-core/pull/978

**Comment by maniac103** [comment]
I guess when implementing this we want to hide the icon format pref if anyFormat is supported and default to SVG in that case?

**Comment by mueller-ma** [comment]
Yes, I prefer that as well.

**Comment by mueller-ma** [comment]
What's the best way to implement this?
Add `anyFormat=true` to every icon fetch url. If the server doesn't support this, it will be ignored.
After fetching server props, if the server supports this flag, set the icon format pref to SVG and hide the pref.

This has the advantage that we don't have to pass around the server props, but use the current icon format logic. However if a user connects to an older server, the icon format pref might be changed (from png to svg).
