### ISSUE TITLE
Update an Item with the state of phone calls

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-android#1512]
### Describe the solution you'd like
Like the alarm clock, it would be great to know when one of our phones was on a cellular call so that the audio notifications in our home could be disabled. Bonus if VoIP and video calls were included, like when on a Skype call. When on a call, update the Item to ON. When the call ends, update the Item to OFF.

### Describe alternatives you've considered
Tasker could probably be used for this.

**Comment by mueller-ma** [comment]
Here's a list with all broadcasts that apps can still receive on Android 8 or above: https://developer.android.com/guide/components/broadcast-exceptions.html
Phone and sms broadcasts are on this list, but the question is if we would violate the Google Play policy: https://support.google.com/googleplay/android-developer/answer/9047303?hl=en

**Comment by openhab-5iver** [comment]
These look promising and don't seem intrusive at all (and look to pick up more than just telephony!).... 
https://developer.android.com/reference/android/telephony/TelephonyManager.html#ACTION_PHONE_STATE_CHANGED
https://developer.android.com/reference/android/telephony/TelephonyManager.html#getCallState()

I'm not sure how to confirm if they are in the SMS or Call Log permission groups though. I don't think we need to know CallerID info or anything like that... just whether a call is active or not.

**Comment by maniac103** [comment]
I think for the call state listener stuff, one only needs the READ_CALL_STATE permission ... it doesn't cover VoIP though.
