### ISSUE TITLE
(Bug) Android App Webview rendering issue

### ISSUE THREAD

**Issue by stefaanbolle** [openhab/openhab-android#1549]
The Android app has a rendering issue with below URL in Webview:
https://mapviewer-deredactie.be-mobile.biz/#/map?lang=nl_BE&@=50.98955680038983,4.395904541015624,9

In Android it gives a line of text displaying only
`/#/map?lang=nl_BE&@=50.98955680038983,4.395904541015624,9`

However, it does render correct (as supposed to be) when using the Sitemap in Safari or Firefox on a Mac.

**Comment by mueller-ma** [comment]
Can you post the WebView definition from the sitemap file?

**Comment by stefaanbolle** [comment]
Webview label="Verkeersinfo" icon="pressure" url="https://mapviewer-deredactie.be-mobile.biz/#/map?lang=nl_BE&@=50.98955680038983,4.395904541015624,9" height=19

**Comment by maniac103** [comment]
@mueller-ma I tested both Uri and HttpUrl classes with that URL, and both recognize the part after the hash in that URL as fragment. I wonder whether the issue https://github.com/openhab/openhab-android/pull/105 is about is still valid after all this time (and WebView updates).

**Comment by mueller-ma** [comment]
Currently no url with an anchor works for me. I guess the best way would be to remove the anchor code at all (and also rename `AnchorWebViewClient` as it does more than just jumping to the anchor).

**Comment by maniac103** [comment]
In a quick test using the URL 'https://www.heise.de/#startseite.newsticker.anrissliste.8' and removing the anchor handling code, the WebView jumps to the correct position for me ... so yeah, I also think removing the anchor specific code + renaming the class makes sense to me.

**Comment by stefaanbolle** [comment]
Fyi, only occurs with Android. ios version also renders correctly

**Comment by maniac103** [comment]
The problem is the code introduced in #105; the iOS app likely doesn't have such special handling.
