### ISSUE TITLE
Switch item [mappings] are not sized correct (OH2)

### ISSUE THREAD

**Issue by shorty707** [openhab/openhab-android#156]
using [mapping] eg for scenes do overlay in text and / or icon instead of resizing correct
on ios this works nice

this happens only with OH2
##

**Comment by digitaldan** [comment]
@shorty707  can you post a screen shot?  Is this the same as #169 ?

**Comment by mueller-ma** [comment]
@shorty707 Poke

**Comment by flaviocosta-net** [comment]
This screenshot should help understand the issue:

![2018-01-24_23-57-58](https://user-images.githubusercontent.com/35621323/35371552-cb158bfa-0162-11e8-83e4-59b6874fcd8f.png)

The sitemap definition for the displayed group is the following:
```
        Group item=gL {
            Switch item=gL label="Toutes les lumières"
            Switch item=GF_LivingRoomS_Light label="Escalier" mappings=[0="Off", 5="5%", 50="50%", 100="100%"]
            Switch item=GF_LivingRoomW_Light label="Fenêtre" mappings=[0="Off", 5="5%", 50="50%", 100="100%"]
            Switch item=FF_MasterBedroomF_Light label="Flavio" mappings=[0="Off", 5="5%", 50="50%", 100="100%"]
            Switch item=FF_MasterBedroomS_Light label="Sarah" mappings=[0="Off", 5="5%", 50="50%", 100="100%"]
        }
```

**Comment by mueller-ma** [comment]
What are the screen sizes of both devices?

**Comment by flaviocosta-net** [comment]
**iPhone 6s:** 4.7 inch display, 1334 x 750 pixel resolution at 326 ppi
**Samsung Galaxy S7:** 5.1 inch display, 2560 x 1440 pixel resolution at 576 ppi

**Comment by mueller-ma** [comment]
When we reduce the space for the mappings, it might be too small on smaller devices.

**Comment by flaviocosta-net** [comment]
This may be true, but if we don't reduce the space and font size then it won't be usable in any device as it is the case now. Let's stick to Android devices and see how big or small screens currently are:

**Tablet - Google Nexus 10:** 10"
**Phablet - Samsung Galaxy Note 8:**  6.3″
**Regular phone - Samsung Galaxy S7:** 5.1"
**Mini phone - Samsung Galaxy S5 mini:** 4.5"

I checked for LG, Google, Motorola, ASUS, HTC, and there are very few devices smaller than the 4.7 inch iPhone used on this test, and it is quite functional the way it appears on the iPhone.

The Samsung Galaxy S5 mini is slightly smaller, and on this one maybe it could be a bit too small, but if someone is using a smartphone labelled as "mini" then it might be expected that a few programs (including HABdroid) may not look at their best, I just don't think it makes sense to keep a layout option that don't look good on screens >= 4.7 inches, which is nearly 95% of all devices and nearly all recent devices.

**Comment by maniac103** [comment]
I've worked on this and reached - I think - a good compromise. Before-after:
![mapping-switch](https://user-images.githubusercontent.com/781373/35432952-0c6abeb6-0282-11e8-9385-97e04d15ddaa.png)

Will do a PR once #650 is merged.

**Comment by kaikreuzer** [comment]
Nice, but do you think this will be enough to address the case from above (with 4 buttons and a longer label text)? Imho, the main issue is the rather big padding left+right - if this could shrink if the number of buttons increases, it would probably be helpful.

**Comment by maniac103** [comment]
The padding is shrinked unconditionally now ;-) Previously, there was padding allocated for displaying a radio button circle (implementation detail, it was never displayed anyway), which I removed. Now, the padding consistently is 8dp, but the minimum button width is 48dp to still be a proper touch target. The buttons in the example above thus are 4x 48dp = 192dp, plus 50dp for the icon (I wonder whether we could/should shrink the icons a bit in general), which leaves ~60dp for the text. Not much, but probably enough to be recognizable.

**Comment by flaviocosta-net** [comment]
@maniac103, thanks for the quick response! What you achieved is certainly a great improvement over the way it is now, making Switch widgets much more useable.
In my case there are 4 buttons, but their texts are not so long, they should look better now in any case.

I think your suggestion of making the icons a bit smaller could be an additional Improvement. If you compare my Android and iOS screnshots, you may notice that everything on the Android client takes more space: icons, the orange sitemap navigation on the top, and the labels font size too.

**Comment by mueller-ma** [comment]
Reducing the size of the mappings only makes it inconsistent with the rest of the app. Maybe we should reduce the size of label, icons and mappings.

**Comment by maniac103** [comment]
The selection spinner font is different from the label font as well. IMHO that's fine, as it's different UI elements.
Doesn't mean shrinking label size wouldn't be worth a try, but it's independent from shrinking the mapping size.

**Comment by flaviocosta-net** [comment]
It looks like the iOS mapping font size is smaller than the label text, so it looks like the iOS developers did not this as a problem.

Still, in the side-by-side comparison we see that the same sitemap items take some 15%-20% more vertical space in the Android version, so tweaking a bit with padding, text and icon sizing may help optimize screen space usage without necessarily causing degradation in usability.

**Comment by maniac103** [comment]
Vertical screen space isn't that much of a problem though. The iOS app layout's touch targets are significantly smaller than mandated by the Material Design spec.

**Comment by flaviocosta-net** [comment]
True, I was testing the controls on iOS and the touch target is indeed limited to the visual boundaries of the buttons - so while it has a reasonable width (depending on text length), the height might a bit narrow for certain users. What has been changed here is anyway a nice improvement that I'd love to see released, thanks for the nice work!
