### ISSUE TITLE
Update license on F-Droid to EPL-2.0

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-android#1580]
The license got updated to EPL-2.0 (#1385) but on F-Droid it hasn't been updated and still shows EPL-1.0.

See: https://search.f-droid.org/?q=openhab&lang=en

F-Droid App screenshot:

![epl-1 0](https://user-images.githubusercontent.com/12213581/66108593-33166580-e5c3-11e9-954d-1a8e333c69fb.png)

**Comment by mueller-ma** [comment]
I already opened an issue for this: https://gitlab.com/fdroid/fdroiddata/issues/1695
Can you change the license [here ](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata%2Forg.openhab.habdroid.yml) and [here](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata%2Forg.openhab.habdroid.beta.yml) and open a MR?

**Comment by wborn** [comment]
I've updated the license in [!5619](https://gitlab.com/fdroid/fdroiddata/merge_requests/5619).
