### ISSUE TITLE
Update icon in Google Play Store for dark mode

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-android#1581]
When using dark mode on my Google Pixel with Android 10, the openHAB app icon in the Play Store app doesn't look very good with the dark background.

Maybe it can be updated to use the same icon used for the app and in the [F-Droid](https://f-droid.org/en/packages/org.openhab.habdroid/) and [Apple](https://apps.apple.com/us/app/openhab/id492054521) stores? That would fix this issue and also result in a more consistent "App identity". With the current icon the openHAB texts are also too small to read when the icon is used in lists of apps. :male_detective: 

Examples of the current app store icon in dark mode:

![play1](https://user-images.githubusercontent.com/12213581/66109505-1b3fe100-e5c5-11e9-857c-1b05313e1046.png)

![play2](https://user-images.githubusercontent.com/12213581/66109511-1e3ad180-e5c5-11e9-8f9f-2c772b1f51e9.png)

**Comment by wborn** [comment]
Maybe @kaikreuzer knows if there is also a full logo that works with dark backgrounds? 

If not there isn't any yet, using the same look and feel of the sticker might work. :wink: 

![sticker](https://user-images.githubusercontent.com/12213581/66120160-88aa3c80-e5da-11e9-84ee-d2d71b3fc1f0.jpg)

**Comment by kaikreuzer** [comment]
Try this!

![openHAB_darkBG_vertical](https://user-images.githubusercontent.com/3244965/66139238-e9268300-e5b4-11e9-9adf-8b4bad2ca80f.png)

**Comment by kaikreuzer** [comment]
> that works with dark backgrounds

But note that it ONLY works for dark backgrounds. Is it possible to have different versions for light and dark mode in the app stores? Then this should be fine, but please don't use this version on light backgrounds.

**Comment by mueller-ma** [comment]
> Is it possible to have different versions for light and dark mode in the app stores?

No, it's not. It should be fine to provide a png file with a white background, not a transparent one.

**Comment by mueller-ma** [comment]
Google applies corners to the icon, so it's not possible to use the exact same icon everywhere: https://developer.android.com/google-play/resources/icon-design-specifications
But I agree with @wborn, the text should be removed from the store entry icon.

**Comment by kaikreuzer** [comment]
> But I agree with @wborn, the text should be removed from the store entry icon.

Yes, I agree as well - it should just be the round logo, nothing else.
Just like on F-Droid, we would have to use the white circular background then. If that looks okayish on with the automatically added rounded corners, let's go for that.

**Comment by mueller-ma** [comment]
@kaikreuzer Is there any repo containing svg and png images of the icon and variations of the icon, e.g. with text or for a dark background?

**Comment by mueller-ma** [comment]
The icon without text:
> Final size: 512px x 512px
Format: 32-bit PNG
Color space: sRGB
Max file size: 1024KB

**Comment by wborn** [comment]
As fallback... I've exported a [512x512 PNG Icon](https://user-images.githubusercontent.com/12213581/66242684-63b0e900-e702-11e9-8370-498279f08daa.png) using Inkscape after creating a [SVG Icon](https://github.com/openhab/openhab-android/files/3692468/icon.zip) based on the [SVG logo](https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/7/7d388a86c95471f89b1bb911d96d7609a3e3a059.svg) posted by Kai in the [New logo for openHAB](https://community.openhab.org/t/new-logo-for-openhab/35140?u=wborn) announcement.

**Comment by kaikreuzer** [comment]
If we are talking about the app icon with a white background, you can use 
[openHAB_favicon.svg.zip](https://github.com/openhab/openhab-android/files/3692834/openHAB_favicon.svg.zip), which looks like this:

![openHAB_favicon](https://user-images.githubusercontent.com/3244965/66249256-3275f000-e6e5-11e9-8173-d96393a177dd.png)

**Comment by mueller-ma** [comment]
Based on the favicon with square background:
![fav](https://user-images.githubusercontent.com/22525368/66252028-f4191900-e756-11e9-837c-f92327de4c9c.png)

**Comment by mueller-ma** [comment]
Before:
![oh_old](https://user-images.githubusercontent.com/22525368/66252168-69d1b480-e758-11e9-87c7-a2d3acaab092.PNG)
Now:
![oh_new](https://user-images.githubusercontent.com/22525368/66252166-69d1b480-e758-11e9-826a-02a5addba85c.PNG)

**Comment by wborn** [comment]
Thanks the new logo fixes all issues and also looks nicer now it has a gradient! :+1: 

It's live now and this is what it looks like in dark mode:

![1](https://user-images.githubusercontent.com/12213581/66259883-9963d980-e7b7-11e9-865f-9e1db30be34d.png)

![2](https://user-images.githubusercontent.com/12213581/66259884-9ec12400-e7b7-11e9-9ef0-36f33f41f2dd.png)

**Comment by mueller-ma** [comment]
> If we are talking about the app icon with a white background, you can use
openHAB_favicon.svg.zip, which looks like this

@kaikreuzer Can you use this icon as icon for the openHAB organization and @openhab-bot on GitHub? I have the same issue with third-party GitHub client.
