### ISSUE TITLE
Support flexible color theming and/or a widened selection of accent colors

### ISSUE THREAD

**Issue by curlyel** [openhab/openhab-android#1591]
I understood, that the current coloring options of the android app match the official color scheme of some other openHAB-related UI's (BasicUI, PaperUI,..)

**I propose to extend the coloring options to provide a more flexible adoption to the users preferences/needs.**

Similar have been discussed for the BasicUI and have been decided against more color options in favour of more control over the appearance to match a given CI. 

@kaikreuzer stated there:

> I think this makes sense in terms of ensuring a "corporate identity", i.e. allowing solutions to make sure that their UIs carry their logo and match there general CI.
> 
> While I can understand that it can be useful to allow users to choose a light or dark theme, I am not so convinced, if we really need orange/blue/green color options (resp. rather allow solutions to add additional themes besides light/dark through a fragment).

See: https://github.com/eclipse/smarthome/pull/4137

While forcing a "CI compliant appearance" might have been needed for commercial uses of the Eclipse Smarthome, this is probably not fully neccessary for the _pure_ openHAB UI's as well as the openHAB Android app.

I aggree that it should still support the well known openHAB coloring schemes to get immediately recognized as "openHAB-related" when showcasing  it in the public like at conferences etc.

In the private use of openHAB, forcing the "openHAB colors" might limit the use if one does not like blue/pink or even orange accent colors on their Android wall tablet/desk phone/etc. ;-)

I suggest reconsidering a widened "color policy" in the Android app and discuss some kind of color selection or a full theme support.

(see also: https://community.openhab.org/t/android-app-beta/41382/128 )

**Comment by maniac103** [comment]
See relevant discussion and links in #1431 and #1547.
Arbitrary colors are only possible with third party libraries that make updating to newer androidx libraries and/or API levels harder. Adding more themes still won't be sufficient to please everyone.
(And IMHO, not using the app because the user neither likes orange nor blue nor gray (!) seems like an interesting choice of priorities. How many apps that allow selection of arbitrary accent colors do you know?)

**Comment by curlyel** [comment]
> Adding more themes still won't be sufficient to please everyone.

Aggree. But it increases the chance to please ;-)

> neither likes orange nor blue nor gray (!)

You know, I use (like!) the app even I don't like the colors... All fine ;-)

I understood, it's been decided against more color options because of consistency.
@kubawolanin had more color options prepared for BasicUI and @mueller-ma for the Android app. But they were not approved.

Just asking for reconsidering it. No more nor less ;-)

If the decision against more color choices may have been right for Eclipse Smarthome, its not neccesarily the same for openHAB.

You are perfectly right: We are talking just about appearance. But this is what the user is seeing.

**Comment by mueller-ma** [comment]
> @mueller-ma for the Android app

I didn't really prepare adding more themes, I just updated to a new theme library.

> How many apps that allow selection of arbitrary accent colors do you know?

@maniac103 is right. I know a few third party apps and tools (PDF reader, flashlight, etc.), that allow arbitrary colors, but not a single first party app.

I'm closing this issue for now. If there are new themes for basic ui, I'll add them to the app.
