### ISSUE TITLE
Outline of section switch blurred

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1615]
Like the new rendering of the section switch. Really appreciate the work on improving the design of the app ;-)

Unfortunately a tiny flaw has been introduced from 2.9.9-beta to 2.9.10-beta:

The outline of the first and the last section is thicker than inner sections (and thicker than a single button switch). I think, it's even visible in your screenshots posted above. At least these detail picts show the issue. The "inner" sections (as well as the single button) have a **sharp thin outline** while the first and the last section have a **thicker/blurred** outline. Seems there is something different.

![2 9 10-day](https://user-images.githubusercontent.com/11849305/67097060-a6ba9400-f1b9-11e9-83ed-f312fc7d071a.JPG)
![2 9 10-month](https://user-images.githubusercontent.com/11849305/67097058-a6ba9400-f1b9-11e9-89ce-3d73de5f701d.JPG)
![2 9 10-year](https://user-images.githubusercontent.com/11849305/67097059-a6ba9400-f1b9-11e9-9bde-e1482131b99f.JPG)

The effect is **clearly visible** here on two different tablets with different DPI. But on a Samsung phone (Galaxy S9) it's _not_ visible though. 
It's harder to see on the attached jpg-screenshots (same for your and mine jpg's ;-)), but immediately to notice on the _real_ devices display.

On the **2.9.9-beta it was rendered perfectly**.

_Originally posted by @curlyel in https://github.com/openhab/openhab-android/pull/1606#issuecomment-543746237_

**Comment by mueller-ma** [comment]
I can reproduce this on my 7 inch tablet.

**Comment by curlyel** [comment]
Thanks for picking this up. Just have corrected my initial posting. It seems to be limited to low-DPI devices.

**Comment by maniac103** [comment]
My guess would be rounding issues on hdpi devices, since that's the only density which yields a non-integer dp-to-px ratio (1.5 to be precise). This means e.g. 1dp becomes 1.5px, which can be displayed as 1px (too thin) or 2px (too wide).
Does the material components sample app (https://github.com/ricknout/android-mdc-theming) also reproduce this?
