### ISSUE TITLE
Support DateTime items as Alarm clock receiver

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1618]
See https://community.openhab.org/t/android-app-sends-alarm-time-as-long-not-datetime/83758/

**Comment by mueller-ma** [comment]
My suggestion is to add a flag to the input data of the worker. Based on this flag, the worker can make changes, e.g. convert the state to a datetime string.

**Comment by maniac103** [comment]
When I thought of a design for this, I came up with the idea of moving the determination of the value to be sent to a time the worker runs (as opposed to it being part of the input data). The worker could then pass the loaded item to the method, which then can decide on the format of data to return.
Biggest hurdle in that design probably is having a clean way of passing the method into the worker. I'd probably move the getter map to ItemUpdateWorker, introduce well-known keys for the entries and do the pref key -> map key conversion when scheduling the worker, passing the map key into input data.

**Comment by mueller-ma** [comment]
> My suggestion is to add a flag to the input data of the worker. Based on this flag, the worker can make changes, e.g. convert the state to a datetime string.

or just use the existing tags: (WIP!) https://github.com/mueller-ma/openhab.android/commit/26e488cf1330ebaeee5fe1190b4f520011eaf98c

**Comment by maniac103** [comment]
> > My suggestion is to add a flag to the input data of the worker. Based on this flag, the worker can make changes, e.g. convert the state to a datetime string.
> 
> or just use the existing tags: (WIP!) [mueller-ma@26e488c](https://github.com/mueller-ma/openhab.android/commit/26e488cf1330ebaeee5fe1190b4f520011eaf98c)

My suggestion (on top of that) would be passing the value type explicitly: https://github.com/maniac103/openhab.android/commit/5d27e9bd4ee962fdc8003c42ffe1a8b0a231dd83

**Comment by mueller-ma** [comment]
> I'd probably move the getter map to ItemUpdateWorker

I like the idea to be able to choose between setting the state when queuing the worker (e.g. for nfc tags) or at worker run time (e.g. for battery state or alarm clock).

**Comment by mueller-ma** [comment]
The docs should be updated.

**Comment by openhab-5iver** [comment]
The docs still could use an update :wink:

**Comment by mueller-ma** [comment]
I was actually working on this: https://community.openhab.org/t/alarmclock-doesn-t-fire/87202/6
