### ISSUE TITLE
Disable HTTP for remote connection

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1624]
### Is your feature request related to a problem? Please describe.
Some users use http instead of https to connect to a remote server. This leaks user name and password.

### Describe the solution you'd like
Change the url input pref to accept only https for remote connection or at least if connecting to myopenhab.org

### Additional context
https://community.openhab.org/t/secure-connection-in-android-app/80764/7

**Comment by jalalkhademi** [comment]
Can I take this one?

**Comment by mueller-ma** [comment]
Yes, go for it :)

**Comment by mueller-ma** [comment]
I'm dropping two files here to give you a hint:
https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/preference/UrlInputPreference.kt#L79
https://github.com/openhab/openhab-android/blob/master/mobile/src/main/res/xml/remote_connection_preferences.xml#L5
