### ISSUE TITLE
Use discrete sliders if only a few states are possible

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1626]
### Is your feature request related to a problem? Please describe.
By setting minValue, maxValue and/or step it's possible to create sliders, that can only have a few states. It's not visible to the user where the slider will accept the change of the state.
The slider might reject state changes if the new value isn't close to a valid state. The slider will than jump back unexpectedly.

### Describe the solution you'd like
Slider with less than, let's say 10, possible states, should be discrete ones: https://material.io/components/sliders/#discrete-slider

**Comment by mueller-ma** [comment]
This might be useful: https://stackoverflow.com/questions/35370671/how-to-show-tick-marks-for-discrete-slider

**Comment by maniac103** [comment]
We also already have a discrete slider in preferences.
