### ISSUE TITLE
Connecting to remote URL when on local network without internet connection

### ISSUE THREAD

**Issue by Andirs55** [openhab/openhab-android#1633]
### Actual behaviour
Recently my internet provider had some stability issues and i had no internet in my home network for some time. The bug I noticed is that when my Android phone knows that there is no internet via wifi (indicated by a small x in the wifi symbol) and I start the OpenHab App it directly wants to start a connection to my openHab server via remote URL.
For obvious reasons that does not work and the error I was given in the app was that "The cloud instance is working but no connection to the openHab server is possible" or something similar.
However I am not 100% sure if the problem could also have been caused by issue #1030.

### Expected behaviour
I expect the app to always try to connect to the local url while on the home network, wether the home network has internet or not.
 
### Steps to reproduce
Since my internet is working at the moment i can not reproduce.

#### Client
    Android version: 9.0.0
    Device model: Xiaomi Mi A1
    Stock or customized ROM: Lineage OS 16.0 (official)
    App version : 2.10.0
    Build flavor : Play Store
    Device language: German

#### Server
    Server version: 2.4.0 M4
    Reverse Proxy: No
    Authentication method : None

#### openHAB Cloud
    openHAB Cloud version: No idea
    Self hosted cloud or myopenhab.org: myopenhab.org
    Authentication method : User and password

**Comment by Andirs55** [comment]
Internet is down here again. I tested various things and i can tell that it is NOT caused or related to issue #1030

**Comment by maniac103** [comment]
Well, we explicitly require a network to provide internet access for considering it: https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt#L218
I don't remember off-hand why we do that, but I'm reasonably certain there's no other way to exclude 'background' connections ... when one is connected to e.g. (working) Wi-Fi, asking the system about active connections will yield two of them, namely the Wi-Fi one and the mobile data one, where the latter is kept in stand-by - we clearly want to return that we're connected to Wi-Fi in that case.

**Comment by Adityakush** [comment]
The same thing happens with me all the time. Isn't there something which can be done about it??

**Comment by joshproehl** [comment]
> Well, we explicitly require a network to provide internet access for considering it

As a user my instinct would be that if I have a defined local URL the app should always attempt to contact that URL, and automated discovery should always be attempted if I'm connected to a local network. In fact, my setup doesn't even have a remote URL setup, it's local only, which makes the fact that the app is requiring internet a bit puzzling from an experience standpoint.

I haven't dug into the code beyond an _extremely_ cursory glance, but I'd be curious why any network type of WiFi isn't automatically considered usable. I should be able to be connected to cellular, and connect to a fully-offline wifi network and access the OpenHAB server on that wifi. Instead, I have to put my phone into airplane mode, turn on wifi, and connect to the wifi network. (Or use the web interface rather than the app.)

Alternatively, if I have a local server IP defined, shouldn't the network be considered usable if my target local openhab IP is in the connection's subnet? Or perhaps certain SSIDs could be whitelisted?

**Comment by Adityakush** [comment]
Totally agreed

**Comment by maniac103** [comment]
> connect to a fully-offline wifi network and access the OpenHAB server on that wifi. Instead, I have to put my phone into airplane mode, turn on wifi, and connect to the wifi network

You lost me here. In that quoted scenario, are you connected to any WiFi or not? First sentence sounds like 'yes', second sentence sounds like 'no'.

**Comment by Adityakush** [comment]
Yes, he is saying that if his home wifi network has no internet access, then he has to disconnect his cellular internet and then connect to the home wifi to access OH through the app( if I understood him correctly). I can totally relate to all that he said above. 
I dont have a internet service at home. I just use cellular internet service on my phone. But for the sake of home wifi network for automation system, I have installed a wifi router( just to create home wifi network without any internet access). 
If I want to access OH through the app, I have to turn off the cellular internet and then connect to home wifi.

**Comment by joshproehl** [comment]
Adityakush is correct, but for posterity let me state my situation clearly:

**WHEN:**
1) My Android 10 Device is connected to T-Mobile Service
_and_
2) My Android 10 Device is connected to My home WiFi
_and_
3) My home ISP has an outage, causing Android to tag my home WiFi as "no internet".

**THEN:**
1) I am **unable** to access my OpenHAB server, running on the the same subnet as my home wifi, using my OpenHAB Android App. (I can post a screenshot of the exact error screen shown for this later if needed)
2) I am **able** to access my OpenHAB server via it's IP address/local-domain-name in the a web browser on my Android device.

**WORKAROUND:**
1) Force Android to be on the home WiFi only. This can be done either by turning on airplane mode and then re-enabling wifi only, or by simply turning off mobile data.  
Once the phone is no longer connected to mobile data and is only connected to the home WiFi the OpenHAB Android app connects to the OpenHAB instance on the local network correctly. (even though the local network has no access to the public internet.)

**Comment by Adityakush** [comment]
@joshproehl  can you please try the app and comment.
