### ISSUE TITLE
AlarmClock triggered by calendar

### ISSUE THREAD

**Issue by MofX** [openhab/openhab-android#1638]
On my pocophone f1, te calendar always sets alarms for midnight. I think the calendar should be ignored by IGNORED_PACKAGES_FOR_ALARM, but on this phone, sender is not "com.android.providers.calendar", but "com.android.calendar".

This should probably be added to the list. I would also be great to have the ability for the user to add ignored timersources.

**Comment by mueller-ma** [comment]
Do you want to open a PR and add the package?
