### ISSUE TITLE
A frame inside another frame confuses the android app

### ISSUE THREAD

**Issue by zero-24** [openhab/openhab-android#1639]
### Actual behaviour

When you have an sitemap with an frame inside an frame the items in that inner frame are not showed. The sitemap works perfectly fine with the ios client and basicui 

### Expected behaviour

When there is a frame inside the frame it should be displayed as group like this is done in the ios client and basicui 
 
### Steps to reproduce

create a new sitemap

```
sitemap default label="Demo"
{
    Frame label="Switches"
    {
        Frame label="Lights"
        {
            // Items go here.
        }
    }
}
    
```

### Can you reproduce the issue in demo mode?

No as i have not found such configuration of two frames in the demo mode.

#### Client
* Android version: Android 9
* Device model: TA-1021
* Stock or customized ROM: Stock
* App version: 2.10.0 
* Build flavor: Full 
* Device language: DE

**Comment by maniac103** [comment]
IIRC nested frames are *not* a supported scenario (as in: isn't tested by the server side) ... @kaikreuzer please correct me if I'm wrong here.
Besides that, what do you mean by 'displayed as a group'?

**Comment by zero-24** [comment]
> IIRC nested frames are not a supported scenario 

well it works with the iOS client and basicUI or what means not supported in that case?

> Besides that, what do you mean by 'displayed as a group'?

Example sitemap file
```
    Frame label="Frame 1"
    {
        Frame label="Frame 2"
        {
            Text item=NTPServerDateTime
        }
        Frame label="Frame 3"
        {
            Text item=NTPServerDateTime
        }
    }
    Frame label="Frame 4"
    {
        Text item=NTPServerDateTime
    }
```

basicui:
![image](https://user-images.githubusercontent.com/2596554/67636732-d3fef480-f8d3-11e9-85b3-7a92114e02e3.png)

iOS: 
<img width="375" alt="2019-10-27 16-07-50-1" src="https://user-images.githubusercontent.com/2596554/67636758-0b6da100-f8d4-11e9-9570-b29efd9b7773.png">

Android
![Screenshot_20191027-160936](https://user-images.githubusercontent.com/2596554/67636782-4a035b80-f8d4-11e9-9c2b-811e6a065770.png)

I hope this shows the issue?

**Comment by maniac103** [comment]
> well it works with the iOS client and basicUI or what means not supported in that case?

'Not supported' means 'you are not supposed to use frames like that'. The server even omits warnings for that, see e.g. https://community.openhab.org/t/frames-must-not-contain-other-frames/33136

BasicUI does them right 'by accident', but with the way our layouts work we simply can't do frame nesting. I would have expected them to be displayed similarly to how the iOS app displays them, even though I consider the outer frame pretty much useless in that case, as the nesting level isn't conveyed.
I'll have a look at it nevertheless.

**Comment by kaikreuzer** [comment]
> @kaikreuzer please correct me if I'm wrong here.

No, I fully agree - they should not be nested.

**Comment by kaikreuzer** [comment]
We should maybe log a warning when parsing sitemap files on the server, if we come across this situation.

**Comment by mueller-ma** [comment]
That should be already the case, see https://github.com/openhab/openhab-android/issues/324#issuecomment-336408540
Maybe the sitemap parsing should fail instead or remove support for nested frames from basic ui.

**Comment by kaikreuzer** [comment]
Ah, cool.
No, I would think a warning should be fine - it clearly tells the user that it is not correct/allowed, so that should perfectly suffice to close issues like this one :-)

**Comment by zero-24** [comment]
hmm ok worked around this issue on my side. Closing here. Thanks for the feedback.

**Comment by maniac103** [comment]
@kaikreuzer BTW, this issue also reminds me that it would be great to have two things:
- a list of who's responsible for what area in -core, so I don't have to nag *you* every time
- a place for discussion about standardization between sitemap based UIs, as implementations between BasicUI, our app and the iOS app often subtly differ and there's no officially blessed 'correct' way of implementation (see this issue, see #1640, see handling of number format with UoM etc.). That place could then also serve as documentation of why a given implementation is correct. I wonder what the best way for such a place could be though ... Issues in an (otherwise empty) 'openhab-ui-coordination' repo? Somewhere in the forums? Not sure..

**Comment by kaikreuzer** [comment]
> a list of who's responsible for what area in -core

You can always ping @openhab/core-maintainers for this.

> a place for discussion about standardization between sitemap based UIs

If it is on "how to interprete sitemaps", I would say that this could also be discussed as issues on openhab-core. Best invite @openhab/ios-maintainers, @openhab/webui-maintainers, @openhab/windows-maintainers and @openhab/android-maintainers to such issues then.

**Comment by maniac103** [comment]
Thanks ... guess TIL about those user lists on Github :-) Will open an issue on -core about the UoM handling at some point then; I see that one pop up every now and then in the forums.
