### ISSUE TITLE
HTML color names for labels, etc.

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab-android#1640]
In my sitemap I'm using different colors for the labels. The colors are somehow set by the application as it should be near by the standards. In my case I need a yellow, which is hardly readable. So I replace yellow by gold which this statement: 
 `labelcolor=["gold"]`
In the BasicUI in the webbrowser this works fine as the HTML color names are supported. 
[](https://html-color-codes.info/color-names/)
I would like to have the HTML color names also supported within the Android app.
Thanks!

I'm using app version 2.9.0 on Android 9.

**Comment by maniac103** [comment]
I don't think supporting HTML color names makes sense for us ... we don't render using HTML in the first place...
If the [supported color names](https://www.openhab.org/docs/configuration/sitemaps.html#label-and-value-colors) don't suffice, why don't you just use the `#rrggbb` syntax?

**Comment by UrsusS** [comment]
Well, I prefer a readable code. But if it will not be possible I'll change to the color codes in hex notation.

In iOS app the will change the behavior. And as you already raised the topic, an alignment between the different UIs is important.

**Comment by maniac103** [comment]
> In iOS app the will change the behavior. And as you already raised the topic, an alignment between the different UIs is important.

The (linked) docs already cover this sufficiently, I think: the table in the docs is what is guaranteed to work, besides that all bets are off. The problem I have with supporting all (~150!) HTML color names is that in order to support them properly, we'd need to test all of them with light & dark modes and adjust them accordingly, which is a time-consuming effort for little gain.

**Comment by mueller-ma** [comment]
I think we can find a good compromise by extending the current supported color list with "common" color names from the html color names list: https://htmlcolor-codes.com/color-names
IMO adding "gold" and "pink" is enough.

@openhab/ios-maintainers @openhab/webui-maintainers @openhab/core-maintainers

**Comment by mueller-ma** [comment]
I didn't get any feedback except a thumb up reaction by @kaikreuzer. I think it's save to add `gold` and `pink` to the app and the docs. They are both valid html colors, so the webuis display them correct.
The iOS app added handling for html color names as well.

**Comment by maniac103** [comment]
> The iOS app added handling for html color names as well.

They didn't, at least not yet. https://github.com/openhab/openhab-ios/pull/487 is still open.

Your approach sounds good to me though: select a sane subset of HTML colors and support those, leaving out the obscurely named ones.
