### ISSUE TITLE
Icons and Text do not resize correct

### ISSUE THREAD

**Issue by shorty707** [openhab/openhab-android#169]
Icons do not resize

Text can overlap from Label to Value
##

**Comment by shorty707** [comment]
![screenshot_2016-04-14-13-07-32](https://cloud.githubusercontent.com/assets/13987575/14526362/0871d650-0243-11e6-9743-b4c480703808.png)

**Comment by dominicdesu** [comment]
@shorty707 Which version of HABdroid are you using? The one from Play Store or a nightly build?

**Comment by shorty707** [comment]
latest nightly
overlap from above
the line with the "lock" icon still happens

**Comment by Flole998** [comment]
This is still an issue, switches and text is still not sized correctly. Can't we just add up the dimensions and if it's larger than the screen size start cutting off until it fits?

**Comment by mueller-ma** [comment]
Can you provide on these icons that do not resize correctly?

**Comment by wrosenauer** [comment]
I also have the overlapping texts for items which have a bit of longer label and value. Is it possible to fix this?

**Comment by mueller-ma** [comment]
@wrosenauer Something like https://github.com/openhab/openhab.android/issues/359? Can you post a screenshot?

**Comment by wrosenauer** [comment]
![screenshot_20171030-174257](https://user-images.githubusercontent.com/1312102/32183599-fdfb9666-bd99-11e7-8da3-61712de9db8c.png)

**Comment by mueller-ma** [comment]
I opened #435

**Comment by mueller-ma** [comment]
@shorty707 Can you provide on these icons that do not resize correctly?

**Comment by mueller-ma** [comment]
The issue with overlapping label and value is fixed, the icon issue can not be reproduced.
