### ISSUE TITLE
AbstractItemPickerActivity should call ConnectionFactory.waitForInitialization()

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1696]
https://community.openhab.org/t/solved-openhab-app-widget-loading-items-failed/86136/3

The widget item picker and tasker item picker can be opened when the app isn't started.

Also: `forceNonFullscreen` shouldn't be true in the nfc item picker as it's called from within the app.

**Comment by maniac103** [comment]
Since it's an activity, it should rather register a connection change listener.

**Comment by mueller-ma** [comment]
Well, the activity isn't really interested in connection changes since it only fetches the items once. A connection change listener seems a bit of an overkill here.
Instead I suggest to show a spinner until `waitForInitialization()` finished.

**Comment by maniac103** [comment]
I just found it pointless to spawn a new thread for that, since waitForInitialization is blocking. But I guess with coroutines it's not that much of an issue.
