### ISSUE TITLE
Problem with items that have autoupdate=false

### ISSUE THREAD

**Issue by jimmys01** [openhab/openhab-android#1698]
### Actual behaviour

A switch (in off possition for our example) item with autoupdate=false when you click it throught the app it will send the command normaly but it won't update the item state on the app. If you press the switch again then it will turn in the on possition. You click it again, it sends the off command but still the item state doesnt change in the APP. You click it again and it switches to te off state. 

In the web ui it works as intended so the problem is in the app

For reference this are the .items and .sitemap

This item 
`Switch SONOFF_heated_matress_auto "Heated Matress Auto Georgia" <double_bed>   	["Switchable"]			 {channel="mqtt:topic:heated_matress:PowerSwitch1",  autoupdate="false"}`

and this is the corresponding sitemap 
`Default  item=SONOFF_heated_matress labelcolor=[SONOFF_heated_matress_Unreach==CLOSED="red"]  visibility=[heated_matress_auto==OFF]`

### Expected behaviour
You press the switch item and when it receives the update it should switch to its supposed state.

#### Client
* Android version:  Android 9 (Xiaomi 4x) - Android 7 (android tv box) 
* Device model: Xiaomi 4x and android TV box
* App version 2.10.3
* Build flavor full
* Device language: 

#### Server
* Server version: 2.5 nightly i believe
* Reverse Proxy: nginx
* Authentication method user and password

**Comment by mueller-ma** [comment]
I tested a switch item with `autoupdate=false` in Basic UI and the Android app. If the switch is off and I click on it, the switch turns on and the server receives `ON`. If I then click on the switch again it goes back to the off state and the server receives `OFF`.
This works for me in both UIs. However if I refresh the page, the switch always goes back to off, but no command is sent.
AFAIK this is intended behavior. IMO switches without mapping aren't suited for `autoupdate=false` items. Can you try to add a mapping to the switch?
` Default item=SONOFF_heated_matress labelcolor=[SONOFF_heated_matress_Unreach==CLOSED="red"] visibility=[heated_matress_auto==OFF] mappings=[ON="On", OFF="Off"]`

**Comment by jimmys01** [comment]
I cant get it to glitch as often now but it still does it occasional. Seems to bug out when the node does not send the update fast enough (lag in the node or in the network)

> IMO switches without mapping aren't suited for autoupdate=false items. Can you try to add a mapping to the switch?

With the mapping works as expected.

**Comment by mueller-ma** [comment]
> With the mapping works as expected.

👍
