### ISSUE TITLE
HABDroid causes massive data volume in background

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-android#17]
I just noticed by chance that while I was away from home (and therefore Wifi), HABDroid causes almost 100MB data transfer over 3G. I was hardly using the app actively during this time, so this must have happened in the background.
Even if this were only long-polling requests, the amount of data feels to be too much. Anyhow, I would expect any long-polling activity to be stopped when the app goes into the background.

![screenshot_2014-09-03-22-43-06](https://cloud.githubusercontent.com/assets/3244965/4162425/33c4233a-34db-11e4-8bbb-d753c302874e.png)
##

**Comment by mueller-ma** [comment]
@kaikreuzer Do you still have this issue?

**Comment by kaikreuzer** [comment]
I didn't notice it over the past years at least (never had a closer look at the data usage though either) - but as it is pretty old, let us close it.
