### ISSUE TITLE
Alarm Clock and Call State not updating while openhab app reopen

### ISSUE THREAD

**Issue by 5kull** [openhab/openhab-android#1701]
When change alarm clock or phone ringing - nothing happens until openhab app opened again.
Android 9
Nokia 4.2
On my Moto X (Android 5.1) everything working like a charm.

**Comment by mueller-ma** [comment]
Can you fill out the issue template and post the log?

**Comment by 5kull** [comment]
### Actual behaviour
Alarm Clock and Call State updating to the server, only when click on openhab app.
When you change alarm clock or make a call, on app icon appears red dot (like new notifications) but they goes to server only when you click on the icon not automaticaly

### Expected behaviour
This items must be updated immediately after setting new alarm time or receive phone call 

 
### Steps to reproduce
On Nokia 4.2 (android 9)
1. just set a new alarm time and look at server log (nothing happen)
2. click on android app icon and look at log again (AlarmClock item updated)


### Environment data
#### Client
* Android version: 9
* Device model: Nokia 4.2
* App version : 2.10.3 
* Build flavor: Full 
* Device language: any

#### Server
* Server version: 2.4.0
* Reverse Proxy: 
* Authentication method: User and password 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method: user and password

### Logs


#### openHAB Server log
//Im calling from another device (CallState1), no any logs about CallState2 until i miss a call and open Habdroid, than it posted   " Item 'CallState2' received command IDLE"

2019-11-27 00:17:58.687 [ome.event.ItemCommandEvent] - Item 'CallState1' received command OFFHOOK                    
2019-11-27 00:17:58.704 [vent.ItemStateChangedEvent] - CallState1 changed from IDLE to OFFHOOK
2019-11-27 00:18:16.203 [ome.event.ItemCommandEvent] - Item 'CallState1' received command IDLE
2019-11-27 00:18:16.217 [vent.ItemStateChangedEvent] - CallState1 changed from OFFHOOK to IDLE
2019-11-27 00:18:16.379 [ome.event.ItemCommandEvent] - Item 'CallState2' received command IDLE

**Comment by mueller-ma** [comment]
> on app icon appears red dot (like new notifications)

Can you check if there's a new notification? The app tries to send the item update several times. After the first failure, a "Waiting for network" notification is displayed. It has low priority, so the app icon isn't displayed in the status bar.

Please have a look at https://dontkillmyapp.com/ and try to disable any battery savers.

**Comment by 5kull** [comment]
Yep, its power saver) Sorry and thanx!
