### ISSUE TITLE
MJPEG Stream is not visible

### ISSUE THREAD

**Issue by bib2** [openhab/openhab-android#1714]
### Actual behaviour
On my sitemap there are two IMAGE-Items. One showing a jpeg with refresh is working, another one with a mjpeg from my ip-cam is not visible. When i open basic ui with chrome on my android phone, both of the image-items are visible.

### Expected behaviour
mjpeg should be visible too

**Comment by maniac103** [comment]
I'm not aware of `Image` sitemap elements being supposed to support MJPEG streams; I guess in BasicUI it works 'by luck', in that a browser supports more image formats than Android does. The correct way (see [docs](https://www.openhab.org/docs/configuration/sitemaps.html#element-type-video)) is to use a `Video` element with `encoding="mjpeg"`. I've just tested that using the ['IP webcam' app](https://play.google.com/store/apps/details?id=com.pas.webcam), and it seems to work fine for me.

Can you double check whether using a `Video` element also works for you?

**Comment by bib2** [comment]
Video seems to do the job in my sitemap. Thanks! Now chrome browser and android app are showing the mjpeg-stream.
