### ISSUE TITLE
Alarmclock not working on Xiaomi MIUI (11)

### ISSUE THREAD

**Issue by daftndaze** [openhab/openhab-android#1721]
Hello,

on Xiaomi devices some app/service is misuseing the alarm clock function for some reason. Next alarm (next_alarm_formatted) is permanently changing. So sending alarmclock to openHAB isn't useful.

A workaround for that (on Xiaomi devices) would be to use next_alarm_clock_formatted (not  next_alarm_formatted)  to read alarmclock time (on rooted devices only?).

Please let this happen in the app. Thank you!
Greetings

**Comment by mueller-ma** [comment]
What do you mean with "next_alarm_clock_formatted" and "next_alarm_formatted"? Can you post the app log? The issue template exists for a reason.

**Comment by mueller-ma** [comment]
@daftndaze Can you respond to my questions above?
