### ISSUE TITLE
Home screen widget: Show state in custom label

### ISSUE THREAD

**Issue by doits** [openhab/openhab-android#1734]
Using 2.10.18-beta currently. I like the possibility to set an own label for a home screen widget, though afaik there is no way to add the current state to that label.

It would be nice if I could enter a placeholder to my custom label which is replaced by the current state, for example  `Battery level %state%/100` and it would display as `Battery level 67/100` if the item's state is `67`. Here `%state%` is replaced by current state of that item.

I don't know if `%state%` is a good placeholder name, but I think you get the idea.

**Comment by mueller-ma** [comment]
Displaying the current state in a reliable way is currently not supported, please see my comments in https://github.com/openhab/openhab-android/issues/6#issuecomment-462417659.

**Comment by doits** [comment]
Thanks for the info. Isn't it displaying the status if the automatic label is used though?

At least it writes `<Item-Bezeichnung>: <Status>` in the label box then, so I though it would display the state in the automatic label (without digging any further). Maybe it does not work at all and I got confused by this then?

**Comment by mueller-ma** [comment]
> OK I got it, "Status" is not the current state, it is what should happen when the widget is clicked ... I think the wording got me here.

Yes, you got it. Can you think of a better wording?

**Comment by doits** [comment]
`action` might be better in this case. What a press will do. For a switch "on", "off", "toggle" etc. is an `action`?

**Comment by mueller-ma** [comment]
Indeed, "Action" suits better here than "State".
