### ISSUE TITLE
Should send AlarmClock time of UNDEF instead of 0 when no alarm is active

### ISSUE THREAD

**Issue by gersilex** [openhab/openhab-android#1737]
### Actual behaviour
Disabling all alarms on an Android device makes the app update the alarm time of 0 (which is the valid time of 01.01.1970 at 12am UTC.

### Expected behaviour
Disabling all alarms on an Android device makes the app update the alarm time of UNDEF (which is indefined and no valid point in time, because the alarm is literally undefined)

 ### Steps to reproduce
1. Disable all alarms on an Android device

### Merry Christmas
to all of you and thank you so much for your hard work.

### Can you reproduce the issue in demo mode?
Yes.

#### Client
* App version : 2.10.3
* Build flavor : Full
* Device language: German

Skipping the rest of the environment data, because this is all about the app.

What do you think?

**Comment by gersilex** [comment]
As a bit of context: I aggregate all alarm clocks from all apps in a group, using the MIN aggregation to find out the earliest/next alarm time. Having one of these apps set their alarm clock time to `0` (01.01.1970 at 12am UTC) breaks this aggregation because is will always be the earliest wake up time of all alarms.

```
Group:Number:MIN alarm_clocks
DateTime alarm_clocks_datetime "Nächster Wecker [%1$tA %1$tH:%1$tM Uhr]" <time>
Number people_mobile_OnePlus6_alarm_clock "OnePlus A [%s]" (alarm_clocks)
Number people_mobile_heroltexx_alarm_clock "HeroLTExx A [%s]" (alarm_clocks)
```

**Comment by mueller-ma** [comment]
You're right, `0` is a valid and thus incorrect time stamp. I'll propose a PR.

**Comment by mueller-ma** [comment]
I wasn't able to send `UNDEF` to a `DateTime` item. I'll investigate.

````
2019-12-31 19:37:21.345 [WARN ] [rest.core.internal.item.ItemResource] - Received HTTP POST request at 'items/AlarmClock' with an invalid status value 'UNDEF'.
2019-12-31 19:37:34.008 [WARN ] [rest.core.internal.item.ItemResource] - Received HTTP POST request at 'items/AlarmClock' with an invalid status value 'NULL'.
````

**Comment by gersilex** [comment]
Maybe we send a string of "UNDEF" instead of UNDEF the UndefType?

**Comment by mueller-ma** [comment]
The app sends a `DateTime` string to the server if the item is `DateTime`. Actually `DateTime` accepts `UNDEF`, but only if it's sent as item update, not item command.
#1745 contains the fix.

**Comment by gersilex** [comment]
Thank you!
