### ISSUE TITLE
SVG files without proper xlink tag crash openhab app

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab-android#1739]
### Actual behaviour
Openhab Anroid app crashs when looking some pages of my sitemap.
I am running official version from google play store, 2.11.0.
See logs below.

**Analysis:** Actually this was caused by some custom SVG icons, I had used over the last years. 
<code>java.lang.RuntimeException: Undefined Prefix: xlink in org.kxml2.io.KXmlParser@4054f75</code> showed that the SVG files could not be parsed properly, and <code>com.caverock.androidsvg.SVG.getFromInputStream</code> somehow seems to throw RuntimeException instead of SVGParseException.

I know this is an edge case, but my recommendation would be to extend the catch blocks in <code>org.openhab.habdroid.util.ExtensionFuncsKt.svgToBitmap</code> to prevent the crash.  I did not create a PR because I don't not a good way to notify users.

Btw: I updated the SVG icons with Inkscape (which also complained during loading of the old SVG, but stored it in a newer format properly).

### Expected behaviour
It worked before with older versions from play store and openhab 2.4. With openhab 2.5 and app 2.11.0 it does not work anymore.

 
### Steps to reproduce
1. use old svg as custom icon

### Can you reproduce the issue in demo mode?

no

#### Client
* Android version: 8.1.0
* Device model: Nexus 5X
* App version 2.11.0
* Build flavor full
* Device language: DE

#### App log
<details>
  <summary>Click to expand</summary>
12-29 14:39:03.046 8452 8452 E AndroidRuntime: FATAL EXCEPTION: main
12-29 14:39:03.046 8452 8452 E AndroidRuntime: Process: org.openhab.habdroid, PID: 8452
12-29 14:39:03.046 8452 8452 E AndroidRuntime: java.lang.RuntimeException: Undefined Prefix: xlink in org.kxml2.io.KXmlParser@4054f75
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at org.kxml2.io.KXmlParser.adjustNsp(KXmlParser.java:260)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1153)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at org.kxml2.io.KXmlParser.nextToken(KXmlParser.java:317)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at com.caverock.androidsvg.SVGParser.parseUsingXmlPullParser(SVGParser.java:754)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at com.caverock.androidsvg.SVGParser.parse(SVGParser.java:603)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at com.caverock.androidsvg.SVG.getFromInputStream(SVG.java:150)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at org.openhab.habdroid.util.ExtensionFuncsKt.svgToBitmap(ExtensionFuncs.kt:135)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at org.openhab.habdroid.util.ExtensionFuncsKt.toBitmap(ExtensionFuncs.kt:125)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at org.openhab.habdroid.util.HttpClient$HttpResult$asBitmap$bitmap$1.invokeSuspend(HttpClient.kt:207)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-29 14:39:03.046 8452 8452 E AndroidRuntime: at kotlinx.coroutines.DispatchedTask.run

</details>

**Comment by mueller-ma** [comment]
> I know this is an edge case, but my recommendation would be to extend the catch blocks in org.openhab.habdroid.util.ExtensionFuncsKt.svgToBitmap to prevent the crash.

IMO the better solution is to open an issue at https://github.com/BigBadaboom/androidsvg and ask them to catch the exception and re-throw it as SvgParseException. Do you want to do that?

> It worked before with older versions from play store and openhab 2.4. With openhab 2.5 and app 2.11.0 it does not work anymore.

Have you been using the app with PNG or SVG before? This might be related to https://github.com/openhab/openhab-core/pull/978. Now the app picks the first icon available: custom svg, custom png, default svg, default png.

**Comment by mueller-ma** [comment]
The exception is now catched.
