### ISSUE TITLE
SSL Client certificates don't work in the webview widget

### ISSUE THREAD

**Issue by rcatolino** [openhab/openhab-android#1740]
### Actual behaviour
When a webview makes a request requiring SSL client authentication no certificate is sent and the requests fails.

### Expected behaviour
The user should be presented with the choice to use one of the certificate of the system store or to import a new one.

### Steps to reproduce
1. Describe us how to reproduce the issue
Add a webview with a url pointing to a site requiring SSL Client auth in the sitemap.
Try to load the sitemap. The webview fails to load.

### Can you reproduce the issue in demo mode?
SSL client auth is not supported in demo mode.

#### Client
* Android version: 9
* Device model: Fairphone 3
* App version 2.11.0
* Build flavor : tested on full and foss 
* Device language: fr

#### Server
* Server version : 2.5
* Reverse Proxy : nginx
* Authentication method : ssl client certificates

**Comment by mueller-ma** [comment]
I think the fix provided by you in #1741 is enough. I will merge a PR implementing the behavior you suggested, but IMO the percentage of web servers using SSL client certificates is too small to keep this issue open.

**Comment by rcatolino** [comment]
I'm fine with that. Frankly I've only done #1741 because it fits my use case but I don't foresee I'll ever need to do SSL client auth with a 3rd party server.
