### ISSUE TITLE
Basic UI group demo labels not updating

### ISSUE THREAD

**Issue by ewaldc** [openhab/openhab-android#1779]
### Actual behaviour
In the Group Demo, the label "_No. of Active Heatings (#)_" is not updated when heatings are selected/deselected using the ">" sub menu.
Only after a ~1 minute wait the label is refreshed.
In the web based UI (e.g. using Chrome or Firefox) the label is updated right away.

### Expected behaviour
the label "No. of Active Heatings (\#)" should reflect the actual amount of enabled _Heatings_ immediately, as happens in the web based UI
 
### Steps to reproduce
1. Select the "_Demo Mode_"
2. Select "_Group Demo_" page
3. Notice value of \# in label "_No. of Active Heatings (\#)_"
4. Go into sub page "_No of Active Heatings_" by selecting ">"
5. Select or deselect a number of _Heatings_ (changing the number of active ones)
6. Go back one level (up, back to Group Demo menu)
7. Notice that label has **not** changed
8. Wait one minute, notice the (correct) label as the page refresh happens 

### Can you reproduce the issue in demo mode?
Yes

#### Client
* Android version: 8.1
* Device model:  Le Eco Max 2
* App version : 2.11.0 (both also in 2.11.5-beta)
* Build flavor : Play Store
* Device language: English

When looking at the network packets coming from an OpenHab 2.4 server, it looks like:
- the Android app is still listening to the event stream for page 0201 (the Group Demo page)
- an event is being sent for page 0201 that updates the label properly
- there are also events for each of the updated _Heating_ switches (page 020101)
- the Android app seems to ignore the label update event since the active page is the sub page 020101 when the event comes in.

I wrote a lightweight [OpenHab 2 server for the ESP platform](https://github.com/ewaldc/OpenHAB-ESP) and it's while testing it that I noticed this issue first.  The issue did not occur on the web interface, so I suspected a defect in my code, but then I discovered that I could reproduce this behavior on the OpenHab Android app, both released and beta version, demo mode or server mode. 

Thanks for this wonderful Android client (it's the only issue I could find :-) ) and for taking the time to review this issue posting.
Ewald

**Comment by mueller-ma** [comment]
> Thanks for this wonderful Android client (it's the only issue I could find :-) ) and for taking the time to review this issue posting.

Thank you for the excellent bug report :)
