### ISSUE TITLE
Wifi must be enabled

### ISSUE THREAD

**Issue by adriankapka** [openhab/openhab-android#1788]
Wifi must be enabled to run applications.  You cannot use only the LTE connection

App version 2.11.9-beta
Samsung Galaxy 9+,  Android 9, Kernel 4.9.59-16947752

**Comment by mueller-ma** [comment]
Are you using remote or local server only?

**Comment by adriankapka** [comment]
I use local when I'm at home and I have my own wifi network, and I use remote when I use internet connection (LTE)

**Comment by maniac103** [comment]
And in what scenario does it not work? Please describe exactly
- what networks are active at that point
- what connection is expected to be used
- what happens exactly

That's what the issue template is for, BTW ;-)

**Comment by StefanSarzio** [comment]
For me remote access doesn't work any more. It says "Netzwerk nicht verfügbar" (meaning "network not accessable") when I'm not at home.

It works while at home on WiFi.

**Comment by maniac103** [comment]
Ah, I see, thanks. I'll look into it.

**Comment by adriankapka** [comment]
Sorry I use a translator.

After starting the application requires to enable the Wifi interface.
After turning on wifi and the lack of access to the network is the message "Network is unavailable" and still do not want to connect to an external server via an internet connection that is still on.
At the moment when we try to connect to any wifi network (even to no avail) and refresh the application, we connect to an external server via an internet connection.

**Comment by maniac103** [comment]
#1790 will fix this. Thanks for the quick testing and report.

**Comment by adriankapka** [comment]
Thank you :)
