### ISSUE TITLE
Downloadable resource item

### ISSUE THREAD

**Issue by tpham3783** [openhab/openhab-android#1842]
### Is your feature request related to a problem? Please describe.
Video widget behaves differently on mobile and desktop platforms.  Instead of working toward a solution, why not have a downloadable widget so that users can download the resource (hi-resolution image or video)?

### Describe the solution you'd like
Define a downloadable widget in basicui like this:

Download label="Hi-res mp4 video of webcam" url="http://domain.com/my-video.mp4"
this allows direct download of the video, and then allow the user to pause the video etc...Moreover, if URL points to a an high-res image, user would be able to download it and then zoom in, a feature that's OH android is lacking (zooming).

**Comment by mueller-ma** [comment]
> Define a downloadable widget in basicui like this

I suggest you request this in the openhab-core repo.

> high-res image, user would be able to download it and then zoom in, a feature that's OH android is lacking (zooming).

This is requested in #320 and was implemented for charts recently.
