### ISSUE TITLE
2 annoying refresh bugs

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#1862]
Here is a part of my sitemap to explain the 2 issues:
```
sitemap maison label="Accueil"
{
	Frame label="Audio & vidéo" {
		Text item=preamp_power label="Préampli Rotel [MAP(fr3.map):%s]" icon="player" {
			Default item=preamp_power
			Default item=preamp_source
		}
	}
}
```

When I am on the sub-page, I click on the first switch to update the item preamp_power, this is working and the title of the page is even correctly updated with the new value. But when I come back to the parent page (home page), the value is the old one. I need to force a full refresh of the main page to get the right value.

Additionally, I see another strange problem when my phone leaves its standby mode. It looks like the page is first reloaded with bad values and one or two seconds later I got the right values. To be clear, I open the sub-page, power is OFF. I click to switch it ON. Then I put my phone in standby. Few seconds later, I wake it off. Forst I see the power switch as OFF and one or two seconds later as ON as expected.

These two problems are not very new but I did not take time to create the issue. I think it was working correctly few months ago.

This makes no difference if I am on local connection or remote connection.

**Comment by lolodomo** [comment]
No answer ? This is easy to reproduce, I provided a sitemap example.

**Comment by mueller-ma** [comment]
Can you reproduce this with 2.12.2-beta?

**Comment by lolodomo** [comment]
I have now 2.12.1 installed and after a quick test, it seems to be resolved. I will check more in details later today.

**Comment by lolodomo** [comment]
I can confirm the 2 problems disappeared with 2.12.1. Thank you.
