### ISSUE TITLE
Theme navigation bar like the background

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1873]
### Is your feature request related to a problem? Please describe.
In some apps the navigation bar (where the back and home buttons are) is themed like the background of the app.

### Describe the solution you'd like
Also theme it in openHAB.

**Comment by maniac103** [comment]
FWIW, I hate this 'feature' of those apps, at least if those apps use the primary color (in our case orange) for coloring the navigation bar.
In case we only adapt it to the dark/light scheme (white-ish for light, black-ish for dark), like e.g. Gmail does it, I'd be OK with it though.

**Comment by mueller-ma** [comment]
I fully agree, also because the navigation bar used to be orange when the battery saver was on on older Android versions.
