### ISSUE TITLE
Dynamic icons do not work

### ISSUE THREAD

**Issue by stpgrund** [openhab/openhab-android#1874]
If an item has changed its state the dynamic icon of this item is expected to change its presentation immediately. But it does not in the Android app anymore. If the app's activity is left and got back again  the dynamic icon's presentation is shown as expected. 
_Version 2.11.24-beta_

**Comment by lolodomo** [comment]
That looks unbelievable but I just checked with 2.12.0 and you are absolutely right, this is broken !

I also noticed that value colors are not always updated now !

**Comment by lolodomo** [comment]
Color management is still partially broken with 2.12.1. I will open another issue later.
