### ISSUE TITLE
Option to login using basic auth authorization with local URL

### ISSUE THREAD

**Issue by anicos** [openhab/openhab-android#1875]
### Is your feature request related to a problem? Please describe.
I have Openhab in my home which I can access form public network (I have https so I added basic auth) and I need authorization. So my proposition is adding basic auth option in application settings, when I configure local URL

### Describe the solution you'd like
I would like to login to my Openhab using header   `Authorization: Basic {base64}`

**Comment by maniac103** [comment]
As far as I understand RFC 7617, HTTP basic auth essentially is a username password combination. So why don't you just fill out the username and password for the local server? ;-) Or am I missing something here?

**Comment by anicos** [comment]
ok, so maybe I do something wrong, but when I try to login as you said it dosen't work 
![obraz](https://user-images.githubusercontent.com/5099712/77372702-90b38f80-6d66-11ea-9d6b-e51072d9412f.png)
