### ISSUE TITLE
Cannot install app on Android 5 (error -504)

### ISSUE THREAD

**Issue by LinqLover** [openhab/openhab-android#1876]
### Steps to reproduce
Do one of the following:
 - Try to install openHAB via Play Store
 - Download APK from apkpure.com and try to install it

Error: Cannot install app. Error code in Play Store is: -504.

#### Client
* Android version: 5.0.1
* Device model: Telekom Puls (Tablet)
* App version: Play Store: 2.11.0
* Build flavor : ?
* Device language: German

### What I did try
- Reset Google Play Store, Google Service Manager and Download Manager data
- Readd Google account to the device

Can anyone reproduce this? Any ideas?

**Comment by mueller-ma** [comment]
Can you try 2.12.0 from github?
What kind of device is it? Smartphone, tablet,...?

**Comment by LinqLover** [comment]
Thank you for the reply! [This APK](https://github.com/openhab/openhab-android/releases/download/2.12.0-release/openhab-android.apk) fails as well as installation. Telekom Puls is a tablet (added above).

**Comment by mueller-ma** [comment]
Do you have multiple users on the tablet?

**Comment by LinqLover** [comment]
No (the tablet does not even support this afaik)
________________________________

**Comment by mueller-ma** [comment]
Did you try to install it over adb?

I'm closing this issue as I don't think it's the apk that causes the issue.

**Comment by LinqLover** [comment]
> Did you try to install it over adb?

What's the simplest way to do so?

**Comment by mueller-ma** [comment]
https://stackoverflow.com/questions/7076240/install-an-apk-file-from-command-prompt

**Comment by LinqLover** [comment]
Sorry, the issue still persists:
```
$ adb install '.\openhab-android.apk'
Performing Push Install
.\openhab-android.apk: 1 file pushed, 0 skipped. 4.1 MB/s (9979134 bytes in 2.314s)
        pkg: /data/local/tmp/openhab-android.apk
Failure [INSTALL_FAILED_DEXOPT]
```
What error details should I collect and how? :)

**Comment by maniac103** [comment]
Can you post the output of 'adb logcat' after that attempt? Googling for that error suggests there are different potential reasons for this, among which are disk space issues or issues in the tooling we use to build the app.

**Comment by LinqLover** [comment]
> Can you post the output of 'adb logcat' after that attempt?

That command does never terminate (I have been waiting a few hours). The output file is dozens of MBs large and contains sensitive information. How can I extract the relevant logs?

**Comment by maniac103** [comment]
Just
- start 'adb logcat'
- attempt install (from another terminal)
- wait until error message appears
- press Ctrl+C to stop 'adb logcat'
- post output that appeared in between

**Comment by LinqLover** [comment]
Ah, that's good to know :)

Here is what I found:
```logcat
W/PackageParser(26461): Problem in package /data/local/tmp/openhab-android.apk:
W/PackageParser(26461): Unknown element under <activity>: layout at /data/local/tmp/openhab-android.apk Binary XML file line #103
...
W/PackageManager(23117): Package org.openhab.habdroid desires unavailable shared library org.apache.http.legacy; ignoring!
...
I/PackageManager(23117): Perform pre-dex opt for package: org.openhab.habdroid
I/art     (23117): DexFile_isDexOptNeeded failed to open oat file '/data/dalvik-cache/arm/data@app@org.openhab.habdroid-1@base.apk@classes.dex' for file location '/data/app/org.openhab.habdroid-1/base.apk': Failed to open oat filename for reading: No such file or directory
...
W/PackageManager(23117): Package couldn't be installed in /data/app/org.openhab.habdroid-1
W/PackageManager(23117): com.android.server.pm.PackageManagerException: scanPackageLI
W/PackageManager(23117): 	at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:6309)
W/PackageManager(23117): 	at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:5615)
W/PackageManager(23117): 	at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:10744)
W/PackageManager(23117): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:11299)
W/PackageManager(23117): 	at com.android.server.pm.PackageManagerService.access$2800(PackageManagerService.java:243)
W/PackageManager(23117): 	at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:9193)
W/PackageManager(23117): 	at android.os.Handler.handleCallback(Handler.java:815)
W/PackageManager(23117): 	at android.os.Handler.dispatchMessage(Handler.java:104)
W/PackageManager(23117): 	at android.os.Looper.loop(Looper.java:194)
W/PackageManager(23117): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/PackageManager(23117): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
I/PackageManager(23117): Installation done for package: null
```
Does this include the relevant errors? Otherwise, I will have to through the whole 1.5 MB file to remove all private information.

**Comment by maniac103** [comment]
Yes, that's the relevant part, thanks. Now we 'just' need to make sense of it ... it doesn't obviously make sense to me. I'll google around a bit.
