### ISSUE TITLE
Support battery saver

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1898]
### Is your feature request related to a problem? Please describe.
Currently the app doesn't look for the current battery saver status.

### Describe the solution you'd like
It could do the same than in #1796.

**Comment by mueller-ma** [comment]
@maniac103 What do you think about changing `Context.isDataSaverActive()` to something like `Context.shouldLoadItem(usage: DataUsage)` where `DataUsage` is a `enum` consisting of `MEDIUM_DATA_USAGE` and `HIGH_DATA_USAGE`. medium is for images and charts and high is for autofresh of images and videos.

When battery saver is on, items with `HIGH_DATA_USAGE` aren't loaded.

**Comment by maniac103** [comment]
> What do you think about changing Context.isDataSaverActive() to something like Context.shouldLoadItem(usage: DataUsage) where DataUsage is a enum consisting of MEDIUM_DATA_USAGE and HIGH_DATA_USAGE

I think it should rather be something like `fun Context.determineDataUsagePolicy(): DataUsage`, as `shouldLoadItem` doesn't tell you whether you should/shouldn't load an image and should/shouldn't do refresh at the same time. `DataUsage` could also be a sealed class with some members like `val autoPlayVideos: Boolean` or `val canDoLargeTransfers: Boolean`, which the view holders then can use.
