### ISSUE TITLE
'Push notification registration failed' Error

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-android#1901]
Hi,

I am getting the above error. I checked on openhabcloud's nginx log file and never see any hits for `addAndroidRegistration?deviceId....`

I checked on the code :-  openhab-android/mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt line 102, could this be a problem and we should have a leading "/"? Thanks

**Comment by mueller-ma** [comment]
Can you fill out the issue template?

**Comment by lsafelix75** [comment]
### Actual behaviour
'Push notification registration failed' Error


### Expected behaviour
Whenever you launch openhabhab client android, and points to latest openhabcloud (self hosted)

 
### Steps to reproduce
Just launch openhab client


### Can you reproduce the issue in demo mode?
No, it does not happen on demo mode


### Environment data
#### Client
* Android version: 10
* Device model: Samsung S20+
* App version : 2.12.4-beta
* Build flavor : FULL
* Device language: English

#### Server
* Server version: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-104-generic x86_64)
* Reverse Proxy: Nginx
* Authentication method : user and password

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: Self Hosted
* openHAB Cloud version :  1.0.11
* Authentication method : user and password

### Logs
#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>


#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by lsafelix75** [comment]
My bad. I have  found out that the Push Notification is meant for Google Cloud Messaging or new Firebase Cloud Messaging which i need to subscribe on cloud and enable it. In my case, i have not subscribed and enabled it on openhabcloud.
