### ISSUE TITLE
Move background task prefs to subscreen

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#1918]
Currently there are five different device information you can send to the server. DND and location are requested. I also want to add a setting to change the schedule.
IMO these are enough preferences to move them to a settings subscreen. Then it's also possible to use preference categories to group them: Prefix and schedule in one category, the other prefs in another one.

@maniac103 WDYT?

**Comment by maniac103** [comment]
@mueller-ma This totally makes sense, I had a similar thought some days ago. We'll need to adapt the strings in that case (remove the '...to openHAB server' suffix).
