### ISSUE TITLE
Title of page incorrect on tablets (double-views), correct on phones (single views)

### ISSUE THREAD

**Issue by tobiasisenberg** [openhab/openhab-android#1938]
### Actual behaviour
Describe us what happens
When looking at a sitemap on a phone (i.e., the chosen level of the sitemap fills the entire screen), the shown title of the level matches that of the selected level. See screenshots looking at level 0, 1, and 2 of a test sitemap:
[phone top level](https://drive.google.com/file/d/1XLQ7FmAXw4mVT3YRev0ObNh4l_mmjfQk/view?usp=sharing)
[phone first level](https://drive.google.com/file/d/1XPCKrZbAqf2ogxcVjvdcSdD7BjHwekSu/view?usp=sharing)
[phone second level](https://drive.google.com/file/d/16N0Q6HFKhtBRdLWPbal67-64cGZVr5e5/view?usp=sharing)

When using the same sitemap on a tablet that shows a split view with a detailed level and the next-higher level on the left, the title is incorrect. It is the title/label of the next-higher level on the left that is only the context, yet as the focus is the level on the right it should be the title/label of that level that is shown. Examples:
[tablet top level](https://drive.google.com/file/d/1CvLEx3epuyyWimaxK7jdk_2Q1F6h1Et1/view?usp=sharing)
[tablet first level](https://drive.google.com/file/d/1BMljWiJ7Ew0dxq6eRmyfcIvOVUrYB6un/view?usp=sharing)
[tablet second level](https://drive.google.com/file/d/1Ko7hI9oKm-fXi_YLf68_XUduZVVwYl7i/view?usp=sharing)

Here, in "tablet top level" all is good. But then I selected the "First level item 1" and this is shown in "tablet first level" but the title is still the one of the top level, despite the fact that we now focus on the first level. Next, we click on "Second level item 1" shown in "tablet second level" and we see the second level in focus on the right side, yet the title is that of the first level.

### Expected behaviour
The behavior for tablets should be the same as for phones, the correct title of the level that one focuses on should be shown.

 
### Steps to reproduce
1. Use example sitemap below.
2. Observe using phone and tablet.

```
sitemap testmap label="Top level" {
    Text label="First level item 1" {
        Text label="Second level item 1" {
            Text label="Third level item 1"
            Text label="Third level item 2"
            Text label="Third level item 3"
        }
        Text label="Second level item 2" {
            Text label="Third level item 1"
            Text label="Third level item 2"
            Text label="Third level item 3"
        }
        Text label="Second level item 3" {
            Text label="Third level item 1"
            Text label="Third level item 2"
            Text label="Third level item 3"
        }
    }
    Text label="First level item 2" {
        Text label="Second level item 1" {
            Text label="Third level item 1"
            Text label="Third level item 2"
            Text label="Third level item 3"
        }
        Text label="Second level item 2" {
            Text label="Third level item 1"
            Text label="Third level item 2"
            Text label="Third level item 3"
        }
        Text label="Second level item 3" {
            Text label="Third level item 1"
            Text label="Third level item 2"
            Text label="Third level item 3"
        }
    }
    Text label="First level item 3" {
        Text label="Second level item 1" {
            Text label="Third level item 1"
            Text label="Third level item 2"
            Text label="Third level item 3"
        }
        Text label="Second level item 2" {
            Text label="Third level item 1"
            Text label="Third level item 2"
            Text label="Third level item 3"
        }
        Text label="Second level item 3" {
            Text label="Third level item 1"
            Text label="Third level item 2"
            Text label="Third level item 3"
        }
    }
}

```

### Can you reproduce the issue in demo mode?
Yes. For example, when I click on "First floor" and then "Bathroom", I expect the title to read "Bathroom" in tablet mode, yet it reads "First floor".

#### Client
* Android version: n/a
* Device model: n/a
* App version: 2.12.6 beta and 2.12.1 (normal release)
* Build flavor : Full
* Device language: English

#### Server
* Server version: n/a
* Reverse Proxy: n/a
* Authentication method : n/a

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: n/a
* openHAB Cloud version : n/a
* Authentication method : n/a

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by maniac103** [comment]
That's on purpose. The shown title relates to the list on the left, and the title of the list on the right is the title of the selected (and visibly highlighted) item on the left. Showing the title of the right side at the top would be redundant, and lose the context of what the list on the left actually is.

**Comment by tobiasisenberg** [comment]
I respectfully disagree. The only redundancy is because the higher-level item on the left is slightly highlighted. This is almost invisible to me. As I said, the focus is the part on the right, so the title shown should be for that part, like in the phone version. In the top level of the tablet version the title also refers to what is shown in focus. I feel that the UI on the phone and the one on the tablet thus do not match, which contradicts usability principles. Maybe this could be a setting for people to adjust according to their preference? Alternatively or in addition, an option also could be to provide a setting that allows one to force the phone interface even on a tablet?

**Comment by maniac103** [comment]
Providing options for every little aspect of the UI also (strongly) contradicts UI principles.
If the selection highlight is not visible enough, the most obvious fix in my view in making the selection highlight more visible (increase alpha).

**Comment by mueller-ma** [comment]
> If the selection highlight is not visible enough, the most obvious fix in my view in making the selection highlight more visible (increase alpha).

Indeed, it could be more visible, especially in the light theme.

**Comment by maniac103** [comment]
Maybe use `?attr/colorControlActivated` as tint color in `list_arrow_activated_tinted.xml`? Or is that too strong already?
We may also want to revisit the arrow itself; I can't think of something better at the moment though.

**Comment by tobiasisenberg** [comment]
I completely agree that too many options do not lead to better usability. But let me explain the usability problem I am referring to a bit more clearly maybe. The problem arises when someone (like me) often switches between phone and tablet to interact with the sitemap. In the phone I am used to looking for the title of a level (which often also contains a value) on the top, as one would expect it. Then, when I go to the tablet I look at the same place but see information I do not expect at all, which confuses me. Then to find the information of where I am I have to look to the left and sequentially search for a highlighted item, which can be anywhere from the top to the bottom and whose position changes depending on the displayed item.

So, an easy and IMHO useful addition to the settings would be to add the option to change the title behavior, to add the option to force phone mode on tablets, or both.

**Comment by maniac103** [comment]
> Then to find the information of where I am I have to look to the left and sequentially search for a highlighted item, which can be anywhere from the top to the bottom and whose position changes depending on the displayed item.

That's why this issue was reopened, to make the selected item stand out more.

> So, an easy and IMHO useful addition to the settings would be to add the option to change the title behavior, to add the option to force phone mode on tablets, or both.

As a (co-)maintainer I'd strongly oppose adding an option to change title behavior, because as mentioned before, it's (IMHO) one of the options that belong in the category 'options for little UI details only present to appease everyone, but clutter to 99.5% of users'. You'll probably disagree, but I suppose so would every user benefiting from one of those options ;-)
If anything, the 'force phone mode' option would be tolerable for me, even though I don't really see the need for that either. In e.g. Gmail one can understand the context of the right pane, even though the email subject isn't shown in the app bar...

**Comment by tobiasisenberg** [comment]
As I said, the force-phone-mode option would be a workaround that would be ok for me. An argument for it could be that, in a web browser on a relatively large laptop or PC screen with BasicUI, we also have essentially the phone behavior with only one hierarchy level shown (there with two columns, but still one level only). So if you could add this option I would much appreciate it.

**Comment by mueller-ma** [comment]
![grafik](https://user-images.githubusercontent.com/22525368/78895755-ab2c7f00-7a6f-11ea-98e4-38237555c9a5.png)

@maniac103 Is this what you mean or is the screenshot outdated?

I wouldn't add a "force phone" setting as I haven't seen it before in other apps.

**Comment by tobiasisenberg** [comment]
Why should this not be an option? The only effect would be to allow people to use the same view as on a phone, just with more space. It should be up to the viewers if they want to use a split-screen view or a single-level view, not the device they happen to use.

**Comment by maniac103** [comment]
@mueller-ma It's a bit outdated (app bar is white now), but the fragment layout is what I meant, yes.

**Comment by mueller-ma** [comment]
> Maybe use ?attr/colorControlActivated as tint color in list_arrow_activated_tinted.xml? Or is that too strong already?

`colorControlActivated` is the `colorSecondary` if not explicitly defined. IMO that's a bit too much. IMO it looks better without the arrow, so dropped it:

 
![Screenshot_2020-04-11-00-57-29](https://user-images.githubusercontent.com/22525368/79028306-ca223280-7b8f-11ea-91b3-a72849a35b04.png)
![Screenshot_2020-04-11-00-57-45](https://user-images.githubusercontent.com/22525368/79028307-cabac900-7b8f-11ea-87ab-5ab8af073618.png)
![Screenshot_2020-04-11-00-58-08](https://user-images.githubusercontent.com/22525368/79028308-cabac900-7b8f-11ea-8d89-94011efda06c.png)
![Screenshot_2020-04-11-00-58-24](https://user-images.githubusercontent.com/22525368/79028310-cbebf600-7b8f-11ea-9b6b-c7f298897672.png)

**Comment by mueller-ma** [comment]
`colorPrimary`, but with alpha:

![grafik](https://user-images.githubusercontent.com/22525368/79028726-816b7900-7b91-11ea-855d-8035c1c6d08f.png)
![grafik](https://user-images.githubusercontent.com/22525368/79028748-95af7600-7b91-11ea-9fb2-8a6aab820ca2.png)

**Comment by maniac103** [comment]
I agree alpha is needed ... how about colorSecondary with alpha? Since colorSecondary is used for highlighted items e.g. in section switches, I think that would blend in well.

**Comment by mueller-ma** [comment]
> Since colorSecondary is used for highlighted items e.g. in section switches, I think that would blend in well.

This is the reason I don't want to use `colorSecondary`. If a slider, switch or section switch is on the left side, it may be hard to see. Well, for the orange theme it doesn't make a difference.

**Comment by tobiasisenberg** [comment]
The version with alpha indeed looks better. I still would much appreciate the option to disable the split-screen view. I think that makes sense in cases such as mine when I use the tablet in portrait mode. In that case I feel it makes sense to have the UI more like the one on a phone. Thanks in advance for your work and help!

**Comment by mueller-ma** [comment]
With #1944 being merged, IMO it's visible enough to see which sub-page is opened. I'm also not a fan of adding preferences for "force phone view" or "app title is the title of the left/right page".

@maniac103 WDYT on this? IMO this issue should be closed as "won't fix".

**Comment by maniac103** [comment]
@mueller-ma Agreed. As mentioned above, the only thing I could see a pref for is a toggle between dual pane and dual column view, but short of that, I'd keep it as is for now as well.

**Comment by tobiasisenberg** [comment]
Could at least this toggle between dual pane and (single) column view be added for tablets?

**Comment by maniac103** [comment]
> Could at least this toggle between dual pane and (single) column view be added for tablets?

> Unfortunately that's not that easy to do...

From [here](https://github.com/openhab/openhab-android/issues/1938#issuecomment-611530244) ... I want to look at that at some point, but the implementation really isn't straightforward.

**Comment by mueller-ma** [comment]
I'm going to close this issue for now.

> As mentioned above, the only thing I could see a pref for is a toggle between dual pane and dual column view, but short of that, I'd keep it as is for now as well.

I'd keep it for now as is and see what openHAB 3 is bringing us.
