### ISSUE TITLE
Difficult to see some text when using dark theme

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-android#1947]
Maybe more of a bug than a feature, but it's very minor. I use a dark them on Android and the dark blue is hard to see on dark grey, especially on a small screen and old eyes :smile:...

![Color wheel](https://user-images.githubusercontent.com/21967853/79079140-4bd2a700-7cdb-11ea-9721-9e34165ebef1.png)
![Settings](https://user-images.githubusercontent.com/21967853/79079141-4d9c6a80-7cdb-11ea-9c67-29711ed79583.png)

**Comment by mueller-ma** [comment]
The default alert dialog theme should be overridden and replaced by the material components day/night dialog theme. I wanted to do so anyway to add rounded corner to all dialogs:

````diff
diff --git a/mobile/src/main/res/values/styles.xml b/mobile/src/main/res/values/styles.xml
index 2aaaf60f..650b9c3b 100644
--- a/mobile/src/main/res/values/styles.xml
+++ b/mobile/src/main/res/values/styles.xml
@@ -11,4 +11,8 @@
     <style name="WhiteText">
         <item name="android:textColor">#ffffff</item>
     </style>
+
+    <style name="Dialog" parent="@style/Theme.MaterialComponents.DayNight.Dialog.Alert">
+        <item name="dialogCornerRadius">16dp</item>
+    </style>
 </resources>
diff --git a/mobile/src/main/res/values/themes.xml b/mobile/src/main/res/values/themes.xml
index 5e77e722..bd48b244 100644
--- a/mobile/src/main/res/values/themes.xml
+++ b/mobile/src/main/res/values/themes.xml
@@ -5,6 +5,7 @@
         <item name="windowActionBar">false</item>
         <item name="windowActionBarOverlay">false</item>
         <item name="android:windowBackground">?android:colorBackground</item>
+        <item name="alertDialogTheme">@style/Dialog</item>
     </style>

     <style name="openHAB.DayNight" parent="openHAB.Base">
````

However the buttons are now colored with some default material color, disregarding of our defined colors, like `colorPrimary`.

**Comment by maniac103** [comment]
> However the buttons are now colored with some default material color, disregarding of our defined colors, like colorPrimary.

That's to be expected, since the alert dialog theme doesn't descent from our themes and thus doesn't know about our attributes. You'll need one dialog theme for each of our app themes, set colorPrimary etc. in each one and reference each one from the respective app theme.

**Comment by mueller-ma** [comment]
I thought these attributes are resolved at runtime and at runtime `?colorPrimary` is set to orange, blue or grey, right?

**Comment by maniac103** [comment]
Only for the app theme, but not for this (completely separate!) dialog theme.

**Comment by mueller-ma** [comment]
For the "cancel" button I opened #1950. The slider should be changed to pink in #1784.
@openhab-5iver Is there any other text that is hard to read?

**Comment by openhab-5iver** [comment]
@mueller-ma, I looked through every part of my sitemap in the Android app and this was the only place where the colors were hard to see.

Thank you both for looking into this! This one was minor but you have been putting a huge amount of effort into refining the app and it is noticed! :+1:
