### ISSUE TITLE
voicecommand widget not working with energysave

### ISSUE THREAD

**Issue by markusuidl** [openhab/openhab-android#1958]
if you close the app by "close all" on app overwiew and then try to send voicecommand with widget, google reacts to voice, but the command is not sent to openhab and  the popup generated by the app which displays the recognized text is not showing up.

if app is closed (same scenario as before) and energy saving options for openhab are disabled, then then voice command is always sent to openhab and the popup shows up with the spoken command.

possible solutions:
1. give user a hint to disable energy saving options for openhab in system settings (open settingspage automatically at install)
2. optimize background logic

tested on android 9

**Comment by mueller-ma** [comment]
The voice command should be reworked to use work manager and our failure notification infrastructure.

> energy saving options for openhab are disabled

What do you mean with that? Are you talking about the device wide battery saver mode or about the per-app battery optimization, which can be set to "Optimise" or "Not optimise"?

**Comment by markusuidl** [comment]
I talk about the optimizing option which can be set for each app individually.

**Comment by maniac103** [comment]
> The voice command should be reworked to use work manager and our failure notification infrastructure.

I'm not sure, since one wants voice commands to be sent *immediately*, which isn't guaranteed with work manager.
I thought when invoked via PendingIntent, the invoked app/service is temporarily whitrlisted for doze. Seemingly that's not the case...the app log after such a failed attempt would be interesting here.

**Comment by mueller-ma** [comment]
> I'm not sure, since one wants voice commands to be sent immediately, which isn't guaranteed with work manager.

Well, we have the same issue with NFC tags and widgets. I'd rather have all of these item updates (= launched from outside the app) in one solution and try to make it run more frequent, e.g. with https://developer.android.com/topic/libraries/architecture/workmanager/advanced/long-running

> Example use-cases for this new feature include [...] a task that's important to the user of the app.

Another solution would be to run a service on our own, try the item update and fall back to work manager if it fails.

**Comment by mueller-ma** [comment]
> Well, we have the same issue with NFC tags and widgets. I'd rather have all of these item updates (= launched from outside the app) in one solution and try to make it run more frequent.

#1973

**Comment by mueller-ma** [comment]
I tested sending item updates when battery saver is on by using the new quick tiles. These item updates make use of #1973 and are instantly send after clicking on the item. Tested on Android 9, mostly AOSP and with openHAB battery optimized.
