### ISSUE TITLE
Crash report on 1.8.0.2

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-android#196]
0       java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
1   at  java.net.URI.parseURI(URI.java:353)
2   at  java.net.URI.(URI.java:204)
3   at  org.openhab.habdroid.ui.OpenHABWriteTagActivity.onNewIntent(OpenHABWriteTagActivity.java:119)
4   at  android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1216)
5   at  android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2600)
6   at  android.app.ActivityThread.performNewIntents(ActivityThread.java:2613)
7   at  android.app.ActivityThread.handleNewIntent(ActivityThread.java:2622)
8   at  android.app.ActivityThread.access$1700(ActivityThread.java:163)
9   at  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
10  at  android.os.Handler.dispatchMessage(Handler.java:102)
11  at  android.os.Looper.loop(Looper.java:135)
12  at  android.app.ActivityThread.main(ActivityThread.java:5536)
13  at  java.lang.reflect.Method.invoke(Native Method)
14  at  java.lang.reflect.Method.invoke(Method.java:372)
15  at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
16  at  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
##

**Comment by mueller-ma** [comment]
https://github.com/openhab/openhab.android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWriteTagActivity.java#L121

Why does it crash on length() and not on startsWith("/rest/sitemaps") one line above?

**Comment by maniac103** [comment]
It crashes in line 119, not 121, so it looks like sitemapPage is null.

**Comment by mueller-ma** [comment]
Ok, I was confused by `Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference`

**Comment by mueller-ma** [comment]
I don't see this crash report in 2.4.0.
