### ISSUE TITLE
Send alarm with local timezone

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-android#1960]
When the alarm is being sent to a DateTimeItem, it comes through as UTC. I propose that it be sent in the local timezone to make them more useful in rules, without having to be converted. There are some more details in this forum topic...

https://community.openhab.org/t/conversion-of-millis-to-human-readable/96840

**Comment by maniac103** [comment]
The issue with that is that the local timezone of the phone and the OH server might differ...

**Comment by openhab-5iver** [comment]
In rules, the timezones will always need to be accounted for. However, I expect most use cases utilizing this feature will be centered around the home and automations using it will likely not run when the phone is not at home.

**Comment by mueller-ma** [comment]
> In rules, the timezones will always need to be accounted for.

The current example alarm clock doesn't need to account for the timezone:

````java
timerAlarm.reschedule(newState.toLocaleZone.zonedDateTime)
````

When displayed in the sitemap (e.g. `DateTime AlarmClock "Alarm Clock [%s]" <time>`), the time is automatically converted to the timezone of the server, so I'd say the current behavior is fine as it is.

**Comment by mueller-ma** [comment]
I created a new rule in Main UI for testing:

![grafik](https://user-images.githubusercontent.com/22525368/220942103-f067ed34-2eae-45cc-8e64-46816fc69728.png)

My Android device and the server are both in UTC+1 and the rule was triggered at the correct time. If the time isn't converted in Main UI you should open a feature request there.
