### ISSUE TITLE
Bug WebView and Textfields

### ISSUE THREAD

**Issue by DiKaY1969** [openhab/openhab-android#1969]
Hello developers,
with WebView it is no longer possible to scroll down with longer pages and with text fields the content is no longer broken so that long content is then no longer fully readable.
Please correct.
Unfortunately not reproducible in demo mode.
Webview hangs in demo mode!
Thank you

**Comment by mueller-ma** [comment]
Can you post the definition of the webview in your sitemap?

> text fields the content is no longer broken so that long content is then no longer fully readable.

Multi line text view aren't supported in basic UI and only "accidentally" in the app, so now all newline characters are removed. Also see https://github.com/eclipse/smarthome/issues/4789#issuecomment-354965762

**Comment by DiKaY1969** [comment]
Hello,


Thanks for the information.

Here is the sitemap.

Greeting Dierk

sitemap devices label="Devices"

{

    Webview item=Devices label="Devices" icon="text" url="./static/z-Wave-Devices.html" height=64

}

 

Von: mueller-ma [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. April 2020 18:40
An: openhab/openhab-android <openhab-android@noreply.github.com>
Cc: DiKaY1969 <Dikay1969@vodafonemail.de>; Author <author@noreply.github.com>
Betreff: Re: [openhab/openhab-android] Bug WebView and Textfields (#1969)

 

Can you post the definition of the webview in your sitemap?

text fields the content is no longer broken so that long content is then no longer fully readable.

Multi line text view aren't supported in basic UI and only "accidentally" in the app, so now all newline characters are removed. Also see eclipse/smarthome#4789 (comment) <https://github.com/eclipse/smarthome/issues/4789#issuecomment-354965762>

**Comment by mueller-ma** [comment]
Can you remove `height=64`?

**Comment by DiKaY1969** [comment]
Hello

I have removed the entry height = 64 which I entered because I could not scroll in the current version, which currently works again.

Unfortunately, scrolling is not possible without the entry height = 64 in the beta!

greeting

Dierk

 

Von: mueller-ma [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. April 2020 22:48
An: openhab/openhab-android <openhab-android@noreply.github.com>
Cc: DiKaY1969 <Dikay1969@vodafonemail.de>; Author <author@noreply.github.com>
Betreff: Re: [openhab/openhab-android] Bug WebView and Textfields (#1969)

 

Can you remove height=64?

**Comment by mueller-ma** [comment]
Without the height parameter the WebView height is set to `WRAP_CONTENT`, but it acts like `MATCH_PARENT`.

**Comment by mueller-ma** [comment]
Found the issue: https://github.com/openhab/openhab-android/pull/1979
