### ISSUE TITLE
Crash report on 1.8.0.2

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-android#197]
0       java.lang.RuntimeException: java.lang.NullPointerException
1   at  com.loopj.android.http.AsyncHttpResponseHandler.onUserException(AsyncHttpResponseHandler.java:304)
2   at  com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:395)
3   at  com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
4   at  android.os.Handler.dispatchMessage(Handler.java:102)
5   at  android.os.Looper.loop(Looper.java:136)
6   at  android.app.ActivityThread.main(ActivityThread.java:5146)
7   at  java.lang.reflect.Method.invokeNative(Native Method)
8   at  java.lang.reflect.Method.invoke(Method.java:515)
9   at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
10  at  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
11  at  dalvik.system.NativeStart.main(Native Method)
12      Caused by: java.lang.NullPointerException
13  at  org.openhab.habdroid.ui.OpenHABWidgetListFragment.processContent(OpenHABWidgetListFragment.java:452)
14  at  org.openhab.habdroid.ui.OpenHABWidgetListFragment$4.onSuccess(OpenHABWidgetListFragment.java:390)
15  at  com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
16      ... 9 more
17      java.lang.NullPointerException
18  at  org.openhab.habdroid.ui.OpenHABWidgetListFragment.processContent(OpenHABWidgetListFragment.java:452)
19  at  org.openhab.habdroid.ui.OpenHABWidgetListFragment$4.onSuccess(OpenHABWidgetListFragment.java:390)
20  at  com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
21  at  com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
22  at  android.os.Handler.dispatchMessage(Handler.java:102)
23  at  android.os.Looper.loop(Looper.java:136)
24  at  android.app.ActivityThread.main(ActivityThread.java:5146)
25  at  java.lang.reflect.Method.invokeNative(Native Method)
26  at  java.lang.reflect.Method.invoke(Method.java:515)
27  at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
28  at  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
29  at  dalvik.system.NativeStart.main(Native Method)
##

**Comment by mueller-ma** [comment]
I don't see this crash report in 2.4.0.
