### ISSUE TITLE
HABdroid connection to remote OH fails with a reverse proxy redirecting HTTPS to HTTP

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#199]
When using a reverse proxy, HABdroid fails to connect to the remote server when the proxy redirects HTTPS to HTTP.
If you redirect HTTPS to HTTPS, it works well.

To be clear, here is the URL I set in HABdroid: https://mydomain.org:443

Nginx is listening on port 443 and proxy pass to https://localhost:8443/
With this Nginx setup, HABdroid is able to connect to the server.

If I set the proxy pass to http://localhost:8080/ HABdroid fails to connect.

PS: not a major issue of course
##

**Comment by andrej-80** [comment]
Check the Reverse Proxy configuration on https://github.com/openhab/openhab/wiki/Security

Add this next to the proxy_pass line for nginx:
proxy_set_header X-Forwarded-Proto $scheme;

For Apache, add this to your <VirtualHost> block:
RequestHeader set X-Forwarded-Proto "https" env=HTTPS

**Comment by docbender** [comment]
For me HABdroid with nginx reverse proxy start working when I set **Host** header to **$http_host** instead **$host**

```
proxy_pass              http://127.0.0.1:8080;
proxy_set_header        Host $http_host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto $scheme;
proxy_buffering         off;
```

**Comment by igitti** [comment]
> Check the Reverse Proxy configuration on https://github.com/openhab/openhab/wiki/Security
> 
> Add this next to the proxy_pass line for nginx:
> proxy_set_header X-Forwarded-Proto $scheme;
> 
> For Apache, add this to your block:
> RequestHeader set X-Forwarded-Proto "https" env=HTTPS

This solved my problem with Apache. Thanks!
