### ISSUE TITLE
Fix url validation in UrlInputPreference #1843 invalidates short URI's

### ISSUE THREAD

**Issue by ewaldc** [openhab/openhab-android#2001]
### Actual behaviour
Until recently, OpenHab servers/services returning short URI's worked OK.
After changes implemented by #1843 like changing _url.toUri()_ to _url.toHttpUrlOrNull()_
short URI's are no longer accepted in all conditions.

Most of the time these code changes cause not problems, e.g. when the URI is based on the _localHost_ or _remoteHost_ (e.g. when testing if the OpenHab server can be reached) but in some case it does cause problems e.g. mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt :
```
               - val segments = url.toUri().pathSegments
              + val segments = url.toHttpUrlOrNull()?.pathSegments ?: emptyList()
```
In this case the URI comes out of JSON code returned by the server and when the URI is a short URI, it causes the value _segments_ to become _emptyList()_ and consequently the SSE EventHelper is no longer called.

### Expected behaviour
According to RFC 2396, an URI generic syntax consists of a hierarchical sequence of five components:
`URI = scheme:[//authority]path[?query][#fragment]`
where the (optional) authority component divides into three subcomponents:
`authority = [userinfo@]host[:port]`

Hence, I believe a short URI like _/rest/sitemaps/demo/demo_ should be considered valid.

Previously the code was just prepending the _localHost_ or _remoteHost_ string to URI to form a valid URI.   Maybe that is the best solution for cases where the URI comes out of server returned JSON code: if _toHttpUrlOrNull()_ returns null, redo the test with the current host (local or remote) prefixed to the URI.  In that case the URI will be valid.
 
### Steps to reproduce
Any OpenHab2 service (2.4 or 2.5 tested) returning short URI's.

### Can you reproduce the issue in demo mode?
have not tried, seems irrelevant

#### Client
* Android version:  _irrelevant_
* Device model: _irrelevant_
* App version: _any version after #1843 changes_
* Build flavor : 
* Device language: 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
logcat shows certain functions being skipped e.g. SSE Helper

**Comment by ewaldc** [comment]
Seems just 2 changes are needed.  I am new to Kotlin, so maybe this isn't coded in the best way...

1.  In HttpClient.kt 
```
 -     private val baseUrl: HttpUrl? = baseUrl?.toHttpUrlOrNull()
+     val baseUrl: HttpUrl? = baseUrl?.toHttpUrlOrNull()
```
2. In PageConnectionHolderFragment.kt
```
               - val segments = url.toHttpUrlOrNull()?.pathSegments ?: emptyList()
               + val uri = url.toHttpUrlOrNull()?: (httpClient.baseUrl.toString() + url).toHttpUrlOrNull()
               + val segments: List<String> = uri?.pathSegments ?: emptyList()
```

And all is working well like before now...

Happy to post a PR.

**Comment by maniac103** [comment]
> Any OpenHab2 service (2.4 or 2.5 tested) returning short URI's.

What does that mean? What do I need to configure to provoke the case that's broken for you?

> logcat shows certain functions being skipped e.g. SSE Helper

It would be helpful if you uploaded logcat, as the template asks for ;-)

**Comment by maniac103** [comment]
> val uri = url.toHttpUrlOrNull()?: (httpClient.baseUrl.toString() + url).toHttpUrlOrNull()

Probably rather `val segments = httpClient.buildUrl(url).pathSegments`

**Comment by ewaldc** [comment]
Sorry,  I should have been more clear.  I have ported OpenHab 2.4/2.5 server to some embedded platforms with small memory footprint (smallest platform is ESP8266, see [OpenHab2 for ESP8266](https://github.com/ewaldc/OpenHAB-ESP).  The great thing is that they all (used to) run perfectly with the Android Openhab Client, that is until recently.

To conserve memory, these OH servers return short URL's in their REST API responses, rather than full URI's.  According to RFC 3986 such a short, absolute URL is a valid URI, but of course that does not make it as an accepted URI.  
The attached example contains the JSON response of a rest call to  _http://OHserver:port/rest/sitemaps/demos_    If you feed this response to the OpenHab Android client, it skips the SSE event stream handler and consequently endlessly and continuously refreshes each sitemap page (to get updated items), ultimately crashing client and server...

Every other piece of the OpenHab Android client is totally fine with short URI's, it's just in this one location (PageConnectionHolderFragment) where it can't extract the segments (sitemap name and pageId) from the (short) URL.

I tested your suggestion `val segments = httpClient.buildUrl(url).pathSegments` and it works perfectly!

So I know this is an unusual request for a (one line) code change since the issue does not occur on a standard OpenHab2 Server.   However, this one change would allow me to continue to leverage the Android client with my small platform OH ports.

If you have an ESP8266, I can provide you with a sketch and data to run the OpenHab 2.5 demo (and reproduce the issue).
PS. The latest version even manages HabPanel on ESP8266 servers.

[demos.zip](https://github.com/openhab/openhab-android/files/4609338/demos.zip)
Thanks in advance,
Ewald

**Comment by ewaldc** [comment]
As requested, Logcat for a failed and successful (patched) session.
You can see the continuous reloading of /rest/sitemaps/demos/demos multiple times per second as a fallback to not have SSE eventstream.

[logcat_failed.zip](https://github.com/openhab/openhab-android/files/4609614/logcat_failed.zip)
[logcat_succes.zip](https://github.com/openhab/openhab-android/files/4609615/logcat_succes.zip)

**Comment by maniac103** [comment]
> I tested your suggestion val segments = httpClient.buildUrl(url).pathSegments and it works perfectly!

Great. Could you create a PR for that?

> So I know this is an unusual request for a (one line) code change since the issue does not occur on a standard OpenHab2 Server. However, this one change would allow me to continue to leverage the Android client with my small platform OH ports.

If supporting that use case is as trivial as it's the case here, IMHO it's totally reasonable to support it.

**Comment by ewaldc** [comment]
Done, thanks again for all the work on the Android client and your wonderful support!
