### ISSUE TITLE
Color picker send NULL when change brightness with slider

### ISSUE THREAD

**Issue by tribal2ua** [openhab/openhab-android#2002]
### Actual behavior
Changing the brightness value with slider sends the NULL value to Item

### Expected behavior
Item expects the value from 0 to 100

 
### Steps to reproduce
1. Set any value with brightness slider

### Can you reproduce the issue in demo mode?

dont know how to do this in this case

#### Client
* Android version: all beta versions with new color picker
* Device model: C106 (Coolpad Cool1)
* App version : 2.12.18-beta
* Build flavor : Full
* Device language: Russian

#### Server
* Server version: 2.5.4-1
* Reverse Proxy: none
* Authentication method : user and password

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab.org
* openHAB Cloud version : 
* Authentication method : user and password

#### App log
<details>
  <summary>Click to expand</summary>

```
-----------------------
Device information
Model: C106
Manufacturer: Coolpad
Brand: Coolpad
Device: cool_c1
Product: Cool1_CN
OS: 6.0.1
-----------------------

--------- beginning of system
05-10 13:38:14.612  6080  6080 I ActivityThreadEui: Handling launch of ActivityRecord{160d5b4 token=android.os.BinderProxy@49005dd {org.openhab.habdroid.beta/org.openhab.habdroid.ui.MainActivity}} startsNotResumed=false
--------- beginning of events
05-10 13:38:14.806  6080  6080 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity]
05-10 13:38:18.796  6080  6090 I ActivityThreadEui: schedulePauseActivity org.openhab.habdroid.ui.MainActivity finished=false userLeaving=true configChanges=0 dontReport=false
05-10 13:38:18.834  6080  6080 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity]
05-10 13:38:18.854  6080  6080 I ActivityThreadEui: Handling launch of ActivityRecord{3c9aa7e token=android.os.BinderProxy@a442bdf {org.openhab.habdroid.beta/org.openhab.habdroid.ui.AboutActivity}} startsNotResumed=false
05-10 13:38:18.902  6080  6080 I am_on_resume_called: [0,org.openhab.habdroid.ui.AboutActivity]
05-10 13:38:19.531  6080  6091 I ActivityThreadEui: scheduleStopActivity org.openhab.habdroid.ui.MainActivity show=false configChanges=0
05-10 13:38:19.565  6080  6080 I ActivityThread: Finishing stop of ActivityRecord{160d5b4 token=android.os.BinderProxy@49005dd {org.openhab.habdroid.beta/org.openhab.habdroid.ui.MainActivity}}: show=false win=com.android.internal.policy.PhoneWindow@1796613
05-10 13:38:42.005  6080  6137 I ActivityThreadEui: schedulePauseActivity org.openhab.habdroid.ui.AboutActivity finished=true userLeaving=false configChanges=0 dontReport=false
05-10 13:38:42.035  6080  6080 I am_on_paused_called: [0,org.openhab.habdroid.ui.AboutActivity]
05-10 13:38:42.038  6080  6137 I ActivityThreadEui: scheduleResumeActivity org.openhab.habdroid.ui.MainActivity
05-10 13:38:42.049  6080  6080 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity]
05-10 13:38:44.673  6080  6137 I ActivityThreadEui: schedulePauseActivity org.openhab.habdroid.ui.MainActivity finished=false userLeaving=true configChanges=0 dontReport=false
05-10 13:38:44.705  6080  6080 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity]
05-10 13:38:44.721  6080  6080 I ActivityThreadEui: Handling launch of ActivityRecord{39d8b17 token=android.os.BinderProxy@53f6b04 {org.openhab.habdroid.beta/org.openhab.habdroid.ui.PreferencesActivity}} startsNotResumed=false
05-10 13:38:44.900  6080  6080 I am_on_resume_called: [0,org.openhab.habdroid.ui.PreferencesActivity]
05-10 13:38:45.500  6080  6090 I ActivityThreadEui: scheduleStopActivity org.openhab.habdroid.ui.MainActivity show=false configChanges=0
05-10 13:38:45.505  6080  6080 I ActivityThread: Finishing stop of ActivityRecord{160d5b4 token=android.os.BinderProxy@49005dd {org.openhab.habdroid.beta/org.openhab.habdroid.ui.MainActivity}}: show=false win=com.android.internal.policy.PhoneWindow@1796613
05-10 13:38:48.099  6080  6090 I ActivityThreadEui: schedulePauseActivity org.openhab.habdroid.ui.PreferencesActivity finished=false userLeaving=true configChanges=0 dontReport=false
05-10 13:38:48.114  6080  6080 I am_on_paused_called: [0,org.openhab.habdroid.ui.PreferencesActivity]
05-10 13:38:48.121  6080  6080 I ActivityThreadEui: Handling launch of ActivityRecord{9d6dce4 token=android.os.BinderProxy@421b54d {org.openhab.habdroid.beta/org.openhab.habdroid.ui.LogActivity}} startsNotResumed=false
05-10 13:38:48.184  6080  6080 I am_on_resume_called: [0,org.openhab.habdroid.ui.LogActivity]
05-10 13:38:48.645  6080  6090 I ActivityThreadEui: scheduleStopActivity org.openhab.habdroid.ui.PreferencesActivity show=false configChanges=0
05-10 13:38:48.677  6080  6080 I ActivityThread: Finishing stop of ActivityRecord{39d8b17 token=android.os.BinderProxy@53f6b04 {org.openhab.habdroid.beta/org.openhab.habdroid.ui.PreferencesActivity}}: show=false win=com.android.internal.policy.PhoneWindow@cccb2a
05-10 13:39:54.677  6080  6090 I ActivityThreadEui: schedulePauseActivity org.openhab.habdroid.ui.LogActivity finished=false userLeaving=true configChanges=0 dontReport=false
05-10 13:39:54.685  6080  6080 I am_on_paused_called: [0,org.openhab.habdroid.ui.LogActivity]
05-10 13:39:55.150  6080  6137 I ActivityThreadEui: scheduleStopActivity org.openhab.habdroid.ui.LogActivity show=false configChanges=0
05-10 13:39:55.167  6080  6080 I ActivityThread: Finishing stop of ActivityRecord{9d6dce4 token=android.os.BinderProxy@421b54d {org.openhab.habdroid.beta/org.openhab.habdroid.ui.LogActivity}}: show=false win=com.android.internal.policy.PhoneWindow@2cbe30b
05-10 13:39:56.955  6080  6091 I ActivityThreadEui: scheduleResumeActivity org.openhab.habdroid.ui.LogActivity
05-10 13:39:56.964  6080  6080 I am_on_resume_called: [0,org.openhab.habdroid.ui.LogActivity]
05-10 13:39:58.914  6080  6137 I ActivityThreadEui: schedulePauseActivity org.openhab.habdroid.ui.LogActivity finished=true userLeaving=false configChanges=0 dontReport=false
05-10 13:39:58.950  6080  6080 I am_on_paused_called: [0,org.openhab.habdroid.ui.LogActivity]
05-10 13:39:58.954  6080  6397 I ActivityThreadEui: scheduleResumeActivity org.openhab.habdroid.ui.PreferencesActivity
05-10 13:39:58.965  6080  6080 I am_on_resume_called: [0,org.openhab.habdroid.ui.PreferencesActivity]
05-10 13:40:01.239  6080  6137 I ActivityThreadEui: schedulePauseActivity org.openhab.habdroid.ui.PreferencesActivity finished=true userLeaving=false configChanges=0 dontReport=false
05-10 13:40:01.265  6080  6080 I am_on_paused_called: [0,org.openhab.habdroid.ui.PreferencesActivity]
05-10 13:40:01.270  6080  6137 I ActivityThreadEui: scheduleResumeActivity org.openhab.habdroid.ui.MainActivity
05-10 13:40:01.285  6080  6080 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity]
--------- beginning of main
05-10 13:40:35.623  6080  6080 I chatty  : uid=10106(org.openhab.habdroid.beta) expire 11 lines
05-10 13:40:35.671  6080  6420 I chatty  : uid=10106(org.openhab.habdroid.beta) OkHttp Dispatch expire 1 line
05-10 13:40:35.671  6080  6420 D OkHttp  : User-Agent: openHAB client for Android
05-10 13:40:35.671  6080  6420 D OkHttp  : Cache-Control: max-stale=2147483647
05-10 13:40:35.671  6080  6420 D OkHttp  : --> END GET
05-10 13:40:35.677  6080  6429 D OkHttp  : --> GET http://<openhab-local-address>:8080/icon/myweather?format=SVG&anyFormat=true&state=cloudy
05-10 13:40:35.677  6080  6429 D OkHttp  : User-Agent: openHAB client for Android
05-10 13:40:35.678  6080  6429 D OkHttp  : Cache-Control: max-stale=2147483647
05-10 13:40:35.678  6080  6429 D OkHttp  : --> END GET
05-10 13:40:35.679  6080  6430 D OkHttp  : --> GET http://<openhab-local-address>:8080/icon/presence?format=SVG&anyFormat=true
05-10 13:40:35.679  6080  6430 D OkHttp  : User-Agent: openHAB client for Android
05-10 13:40:35.679  6080  6430 D OkHttp  : Cache-Control: max-stale=2147483647
05-10 13:40:35.679  6080  6430 D OkHttp  : --> END GET
05-10 13:40:35.680  6080  6429 D OkHttp  : <-- 200 OK http://<openhab-local-address>:8080/icon/myweather?format=SVG&anyFormat=true&state=cloudy (1ms)
05-10 13:40:35.680  6080  6423 D OkHttp  : --> GET http://<openhab-local-address>:8080/icon/switch?format=SVG&anyFormat=true&state=ON
05-10 13:40:35.680  6080  6429 D OkHttp  : Content-Type: image/png
05-10 13:40:35.680  6080  6423 D OkHttp  : User-Agent: openHAB client for Android
05-10 13:40:35.680  6080  6429 D OkHttp  : Last-Modified: Fri, 08 May 2020 20:16:10 GMT
05-10 13:40:35.680  6080  6423 D OkHttp  : Cache-Control: max-stale=2147483647
05-10 13:40:35.680  6080  6429 D OkHttp  : Transfer-Encoding: chunked
05-10 13:40:35.680  6080  6423 D OkHttp  : --> END GET
05-10 13:40:35.680  6080  6429 D OkHttp  : Server: Jetty(9.4.20.v20190813)
05-10 13:40:35.680  6080  6429 D OkHttp  : Warning: 110 HttpURLConnection "Response is stale"
05-10 13:40:35.680  6080  6429 D OkHttp  : Warning: 113 HttpURLConnection "Heuristic expiration"
05-10 13:40:35.680  6080  6429 D OkHttp  : <-- END HTTP
05-10 13:40:35.680  6080  6429 D OkHttp  : --> GET http://<openhab-local-address>:8080/icon/slider?format=SVG&anyFormat=true&state=99.60629921259842519685039370078740
05-10 13:40:35.680  6080  6429 D OkHttp  : User-Agent: openHAB client for Android
05-10 13:40:35.680  6080  6429 D OkHttp  : Cache-Control: max-stale=2147483647
05-10 13:40:35.680  6080  6429 D OkHttp  : --> END GET
05-10 13:40:35.681  6080  6430 D OkHttp  : <-- 200 OK http://<openhab-local-address>:8080/icon/presence?format=SVG&anyFormat=true (1ms)
05-10 13:40:35.681  6080  6430 D OkHttp  : Content-Type: image/svg+xml
05-10 13:40:35.681  6080  6423 D OkHttp  : <-- 200 OK http://<openhab-local-address>:8080/icon/switch?format=SVG&anyFormat=true&state=ON (1ms)
05-10 13:40:35.681  6080  6430 D OkHttp  : Last-Modified: Fri, 08 May 2020 20:16:10 GMT
05-10 13:40:35.681  6080  6423 D OkHttp  : Content-Type: image/svg+xml
05-10 13:40:35.681  6080  6430 D OkHttp  : Transfer-Encoding: chunked
05-10 13:40:35.681  6080  6423 D OkHttp  : Last-Modified: Fri, 08 May 2020 20:16:10 GMT
05-10 13:40:35.681  6080  6430 D OkHttp  : Server: Jetty(9.4.20.v20190813)
05-10 13:40:35.681  6080  6423 D OkHttp  : Transfer-Encoding: chunked
05-10 13:40:35.681  6080  6430 D OkHttp  : Warning: 110 HttpURLConnection "Response is stale"
05-10 13:40:35.681  6080  6423 D OkHttp  : Server: Jetty(9.4.20.v20190813)
05-10 13:40:35.681  6080  6430 D OkHttp  : Warning: 113 HttpURLConnection "Heuristic expiration"
05-10 13:40:35.681  6080  6430 D OkHttp  : <-- END HTTP
05-10 13:40:35.681  6080  6423 D OkHttp  : Warning: 110 HttpURLConnection "Response is stale"
05-10 13:40:35.681  6080  6423 D OkHttp  : Warning: 113 HttpURLConnection "Heuristic expiration"
05-10 13:40:35.681  6080  6423 D OkHttp  : <-- END HTTP
05-10 13:40:35.682  6080  6429 D OkHttp  : <-- 200 OK http://<openhab-local-address>:8080/icon/slider?format=SVG&anyFormat=true&state=99.60629921259842519685039370078740 (1ms)
05-10 13:40:35.682
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
2020-05-10 13:40:09.628 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-10 13:40:09.632 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-10 13:40:09.633 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-10 13:40:09.639 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-10 13:40:11.328 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-10 13:40:11.334 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-10 13:40:11.336 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-10 13:40:11.341 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
```

</details>

**Comment by mueller-ma** [comment]
Can you post the item and sitemap definition?

**Comment by mueller-ma** [comment]
The brightness is shown as integer, but send as float. This might be the issue here.

**Comment by tribal2ua** [comment]
> Can you post the item and sitemap definition?
<details>
  <summary>Things:</summary>
```
`Thing mqtt:topic:gZb_TrustLamps "Group RGB Lamps" (mqtt:broker:mosquitto) @"Освещение"{
    Channels:
        Type switch : gLightOnOff        [ stateTopic="zigbee2mqtt/Light_Room/state", 
                                            commandTopic="zigbee2mqtt/Light_Room/set", on="ON", off="OFF"] 
        Type dimmer : gLightBritness     [ stateTopic="zigbee2mqtt/Light_Room/brightness",
                                            commandTopic="zigbee2mqtt/Light_Room/set/brightness_percent", min=0, max=100, step=1 ] 
        Type string : gLightColor        [ stateTopic="zigbee2mqtt/Light_Room/color-hsb", 
                                            commandTopic="zigbee2mqtt/Light_Room/set", 
                                            formatBeforePublish="{\"color\":{\"hsb\": \"%s\"}}" ]
        Type number : gLightColorTemp    [ commandTopic="zigbee2mqtt/Light_Room/set/color_temp" ] 
}`
```
</details>

<details>
  <summary>Item:</summary>
```
`Switch gZb_Light_TrustRGB "Вкл/Выкл" <switch>               (gTrust) { channel="mqtt:topic:gZb_TrustLamps:gLightOnOff" }
Dimmer gZb_Light_TrustRGB_Britnese "Яркость [%d %%]"        (gTrust) { channel="mqtt:topic:gZb_TrustLamps:gLightBritness" }
Number gZb_Light_TrustRGB_ColorTemp "Температура [%.0f]"    (gTrust) { channel="mqtt:topic:gZb_TrustLamps:gLightColorTemp" }
String gZb_Light_TrustRGB_Color "Цвет [%s]"                 (gTrust) { channel="mqtt:topic:gZb_TrustLamps:gLightColor" }
Number gZb_Light_TrustRGB_Scene                             (gTrust)`
```
</details>

<details>
  <summary>Sitemap:</summary>
```
`Frame label="Свет" {
        Switch item=gZb_Light_TrustRGB label="Люстра"
        Slider item=gZb_Light_TrustRGB_Britnese label="Яркость" sendFrequency=500
        Text item=gZb_Light_TrustRGB_Scene label="Схема..[MAP(light.map):%s]" icon="colorlight" {
            Frame {
                Selection item=gZb_Light_TrustRGB_Scene label="Цветовая схема" mappings=[1="Белый", 2="Желтый", 3="Зеленый"] icon="colorlight"
                Colorpicker item=gZb_Light_TrustRGB_Color label="Цвет" 
            }
}`
```
</details>

**Comment by mueller-ma** [comment]
The log you posted doesn't contain any line about the color picker. There should be lines like: 
````
D/WidgetAdapter: handleChange(0, 0)
D/WidgetAdapter: Command '29' was sent successfully to http://openhab/rest/items/RGBLight
````

Can you clear the log, use the color picker and share the log afterwards?

**Comment by tribal2ua** [comment]
Maybe this helps:
https://pastebin.com/m32LdK80
https://pastebin.com/cLgKZU06

If not, i don't understand how to take useful for you log (

**Comment by mueller-ma** [comment]
Successfully updating the brightness: 
````
05-12 22:02:07.925 24972  4727 D OkHttp  : <-- 200 OK http://<openhab-local-address>:8080/rest/items/gZb_Light_TrustRGB_Color (16ms)
05-12 22:02:07.926 24972  4727 D OkHttp  : Content-Type: text/plain
05-12 22:02:07.926 24972  4727 D OkHttp  : Content-Length: 0
05-12 22:02:07.926 24972  4727 D OkHttp  : Server: Jetty(9.4.20.v20190813)
05-12 22:02:07.926 24972  4727 D OkHttp  : <-- END HTTP
05-12 22:02:07.927 24972  2441 D WidgetAdapter: Command '95' was sent successfully to http://<openhab-local-address>:8080/rest/items/gZb_Light_TrustRGB_Color
````

Successfully updating the color: 
````
05-12 21:30:39.797 24972 24972 D WidgetAdapter: onColorChanged(-11846)
05-12 21:30:39.797 24972 24972 D WidgetAdapter: handleChange(-11846, 100)
05-12 21:30:39.833 24972 24972 I ViewRootImpl: finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=37 eventTime = 315157285 downTime = 315157285 title= org.openhab.habdroid.beta/org.openhab.habdroid.ui.MainActivity
05-12 21:30:39.909 24972 24972 D WidgetAdapter: onColorSelected(-11846)
05-12 21:30:39.909 24972 24972 D WidgetAdapter: handleChange(-11846, 0)
05-12 21:30:39.921 24972 24972 D WidgetAdapter: New color HSV = 20.0, 0.27058825, 100.0
05-12 21:30:39.932 24972 30554 D OkHttp  : --> POST http://<openhab-local-address>:8080/rest/items/gZb_Light_TrustRGB_Color
05-12 21:30:39.932 24972 30554 D OkHttp  : Content-Type: text/plain;charset=UTF-8
05-12 21:30:39.932 24972 30554 D OkHttp  : Content-Length: 30
05-12 21:30:39.932 24972 30554 D OkHttp  : User-Agent: openHAB client for Android
05-12 21:30:39.932 24972 30554 D OkHttp  : Cache-Control: no-cache
05-12 21:30:39.932 24972 30554 D OkHttp  : --> END POST
05-12 21:30:39.964 24972 30554 D OkHttp  : <-- 200 OK http://<openhab-local-address>:8080/rest/items/gZb_Light_TrustRGB_Color (31ms)
05-12 21:30:39.964 24972 30554 D OkHttp  : Content-Type: text/plain
05-12 21:30:39.964 24972 30554 D OkHttp  : Content-Length: 0
05-12 21:30:39.964 24972 30554 D OkHttp  : Server: Jetty(9.4.20.v20190813)
05-12 21:30:39.964 24972 30554 D OkHttp  : <-- END HTTP
05-12 21:30:39.965 24972 25084 D WidgetAdapter: Command '20.000000,27.058825,100.000000' was sent successfully to http://<openhab-local-address>:8080/rest/items/gZb_Light_TrustRGB_Color
````

In both logs I only see successful updates of the color and the brightness. Are you sure the `null` state comes from the app?

**Comment by tribal2ua** [comment]
This one from stable version app:
`zigbee2mqtt/Light_Room/set {"color":{"hsb": "88.965515,60.669456,93.725494"}}
zigbee2mqtt/Light_Room/state ON
zigbee2mqtt/Light_Room/brightness 236.22
zigbee2mqtt/Light_Room/color-hsb 88.965515,60.669456,93.725494
`
and this from beta:
`zigbee2mqtt/Light_Room/set {"color":{"hsb": "79"}}
zigbee2mqtt/Light_Room/state ON
zigbee2mqtt/Light_Room/brightness null
zigbee2mqtt/Light_Room/color-hsb 79
`
I don't know why it sends different values white the same configuration of things/items

**Comment by mueller-ma** [comment]
Can you try to capture a longer log using adb? https://android.gadgethacks.com/how-to/android-basics-capture-logcat-for-detailed-bug-reports-0167774/

**Comment by tribal2ua** [comment]
Done.
[logcat.txt](https://github.com/openhab/openhab-android/files/4630465/logcat.txt)

**Comment by mueller-ma** [comment]
There's again not a single failed command. No "Sending command $command to $url failed": https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt#L1404

Can you post the server log?

**Comment by tribal2ua** [comment]
This is the part when i change brightness with color picker slider (beta):

2020-05-15 20:13:20.669 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:20.679 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:20.674 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:20.676 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:20.692 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:20.700 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:23.159 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:23.166 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:23.169 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:23.170 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:23.176 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:23.183 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:24.293 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:24.319 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:24.317 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:24.327 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:24.327 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!
2020-05-15 20:13:24.339 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!

this from mqtt server:
zigbee2mqtt/Light_Room/set {"color":{"hsb": "78"}}
zigbee2mqtt/Light_Room/state ON
zigbee2mqtt/Light_Room/brightness null
zigbee2mqtt/Light_Room/color-hsb 78
zigbee2mqtt/Light_Room/set {"color":{"hsb": "60"}}
zigbee2mqtt/Light_Room/state ON
zigbee2mqtt/Light_Room/brightness null
zigbee2mqtt/Light_Room/color-hsb 60
zigbee2mqtt/Light_Room/set {"color":{"hsb": "43"}}
zigbee2mqtt/Light_Room/state ON
zigbee2mqtt/Light_Room/brightness null
zigbee2mqtt/Light_Room/color-hsb 43

**Comment by maniac103** [comment]
> In both logs I only see successful updates of the color and the brightness. 

In https://pastebin.com/cLgKZU06 there's this:
05-12 22:02:07.927 24972  2441 D WidgetAdapter: Command '95' was sent successfully to http://<openhab-local-address>:8080/rest/items/gZb_Light_TrustRGB_Color

...where I don't understand how this could ever happen when using the color picker. It matches the output of the MQTT server though, and I understand the device not being happy with that.

**Comment by mueller-ma** [comment]
Color items also accept percentage (for brightness) and on/off: https://www.openhab.org/docs/concepts/items.html#a-note-on-items-which-accept-multiple-state-data-types
However this is a string item with a color picker. I need to check what basic ui does in this case: https://www.openhab.org/docs/configuration/sitemaps.html#element-type-colorpicker

**Comment by maniac103** [comment]
> However this is a string item with a color picker. I need to check what basic ui does in this case

It seems to unconditionally emit `h,s,b`: https://github.com/openhab/openhab-webui/blob/master/bundles/org.openhab.ui.basic/web-src/smarthome.js#L1407-1411

... and I think we should do that as well. Even if would be technically OK to also send brightness only, I don't see a strong reason for doing so (am I missing something there?), and it breaks people's expectations.

**Comment by mueller-ma** [comment]
> am I missing something there?

No, I don't think so. I'm ok with changing the value sent to hsb.

**Comment by Rossko57** [comment]
2020-05-15 20:13:20.669 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'PercentageValue': Unknown String!

You guys do realise this is a complaint from the MQTT binding, failing to do some transform? (probably an internal one)
A key proof of what is going on would be openHAB `events.log` to show what command actually arrives when using colorpicker in UI.

For a Dimmer percentage type, both decimal and integer values are perfectly acceptable.
As a historic matter, most of the UIs only sent integer commands - but they are not obliged to.
But the history means that several bindings expect only integer.  That's a deficiency in each binding.
I thought this had been fixed in MQTT, so version in use may be important.

**Comment by tribal2ua** [comment]
> I thought this had been fixed in MQTT, so version in use may be important.
I thought this are the latest:
```
239 x Active x  80 x 2.5.5                   x openHAB Add-ons :: Bundles :: MQTT Broker Binding
240 x Active x  81 x 2.5.5                   x openHAB Add-ons :: Bundles :: MQTT Things and Channels
```

**Comment by maniac103** [comment]
> You guys do realise this is a complaint from the MQTT binding, failing to do some transform? (probably an internal one)

Yes. Im pretty sure his MQTT setup expects values to be sent as `h,s,b` and tries to parse brightness from the 3rd element of that value, but that 3rd element simply isn't there, thus the result is null.

> For a Dimmer percentage type, both decimal and integer values are perfectly acceptable commands.

We're talking about a String Item bound to a Colorpicker widget here ;-)

**Comment by Rossko57** [comment]
> We're talking about a String Item bound to a Colorpicker widget here ;-)

Right, I skipped over that!

It remains true that `events.log` will show the command from the UI.

A Color Item is an enhanced Dimmer Item - you **can** send it "brightness" values i.e. a single numeric representing percentage, just like a Dimmer type.
A Dimmer Item is an enhanced Switch Item - you can send it ON/OFF commands, just like a switch.
Note that it follows that you **can** send a Color Item ON/OFF too.

In summary, you can send a Color Item commands H,S,B , or just brightness, or ON/OFF.   
**A UI colorpicker sending those commands is working as designed.**

There's nothing to stop a user linking a colorpicker widget to say a Location Item, but it's not going to do much useful.   
Likewise, you can link a colorpicker to a string Item, but ...

The trouble here remains with the MQTT binding, or rather the transformation which needs to parse and handle HSB differently to brightness differently to ON/OFF.

**Comment by mueller-ma** [comment]
> There's nothing to stop a user linking a colorpicker widget to say a Location Item, but it's not going to do much useful.

👍 

While this should/may be fixed in the MQTT binding, IMO it's worth to mitigate the issue in the client. It's quite easy to do so and then new color picker just behaves like the old one or the one of Basic UI.
