### ISSUE TITLE
Remove 'Miscellaneous' heading under 'Settings'

### ISSUE THREAD

**Issue by jainhemendrah** [openhab/openhab-android#2009]
Dear,
  I would like to remove all items under 'Miscellaneous'  heading under 'Settings'. Please guide

Rgds,
Hemendra

**Comment by mueller-ma** [comment]
Currently it's not possible hide the "Miscellaneous" section at runtime in the settings and it never will. What's the use case for this?

**Comment by jainhemendrah** [comment]
Mueller,
   No particular use case.
It is just that I want to Hide/Remove this information.

OR

Can you guide me which funtion populates the 'Miscellaneous' section ?

**Comment by mueller-ma** [comment]
https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt inflates the preferences from xml. Feel free to remove the misc section in a fork of this repo.
