### ISSUE TITLE
Mobile application connection error

### ISSUE THREAD

**Issue by Alendas67** [openhab/openhab-android#2043]
Hello! Disconnected from the mobile application to the cloud service myopenhab.org (error code 500). It works locally. By http, the browser logs in, but partially works. Does not display objects and others. What is the reason? How to fix?

**Comment by mueller-ma** [comment]
Can you fill out the issue template? 5XX codes indicate a server issue, but myopenhab is working for me.

**Comment by mueller-ma** [comment]
Got no response.
