### ISSUE TITLE
Wi-Fi name is UNDEF

### ISSUE THREAD

**Issue by pavel-kamaev** [openhab/openhab-android#2047]
### Actual behaviour
Wi-Fi name updates to the correct SSID name if openHAB client is in foreground, and to UNDEF in background.

### Expected behaviour
Wi-Fi name should always update to the correct SSID if Wi-Fi is connected and correct permissions are set.
 
### Steps to reproduce
1. Configure sending Wi-Fi name to OpenHAB server (both server and client).
1. Set update interval to 15 minutes (no need to wait for several hours).
1. Connect the device to Wi-Fi.
1. Run the OpenHAB app.
1. Check if server received correct SSID name.
1. Send the app to background.
1. Wait for 15 minutes.
1. Check item value at server.

### Can you reproduce the issue in demo mode?
No, since this feature is disabled in demo mode.

#### Client
* Android version: 10
* Device model: Samsung Galaxy A10 and Samsung Galaxy A40.
* App version : 2.13.0
* Build flavor : Full
* Device language: Russian

#### Server
* Server version: 2.5.5
* Reverse Proxy: nginx 1.14.2
* Authentication method : user and password (via nginx).

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: None
* openHAB Cloud version : None
* Authentication method : None

I believe that OpenHAB client should request background location access on Android 10.

**Comment by mueller-ma** [comment]
Thanks for the report. TIL that the background location permission is already a thing in Android 10 and not starting with Android 11: https://developer.android.com/about/versions/10/privacy/changes#app-access-device-location
