### ISSUE TITLE
Problems with visibility option

### ISSUE THREAD

**Issue by GitXodes** [openhab/openhab-android#2051]
### Actual behaviour

When using visibility in sitemap, in application items are flashing and jumping up or down

#### Client
* App version: 2.13.0

#### Server
* Server version: 2.5.4
* Reverse Proxy: 
* Authentication method : None

**Comment by mueller-ma** [comment]
It should be possible to assign unique ids to the view holders and have a smooth animation when items are hidden or shown.

**Comment by GitXodes** [comment]
On iOS is everything Ok!

**Comment by maniac103** [comment]
Can you make a screen recording of this issue? I am not yet sure what you mean by 'flashing'.

**Comment by GitXodes** [comment]
https://drive.google.com/file/d/1bGTPwUxHBf0Y4q5dSQYR6LugzpswYHgE/view?usp=drivesdk

**Comment by mueller-ma** [comment]
I just see the expected animations there. They should be the default recycler view animations, so I'm not sure if we can change them.

**Comment by mueller-ma** [comment]
Since I don't see any issues with the current animations here, I'm going to close this issue.
