### ISSUE TITLE
Incomplete credits of used libraries

### ISSUE THREAD

**Issue by nikothegreek** [openhab/openhab-android#2076]
If you take a look at the used libraries, you can see that there are some libraries without a given license and if you click on those entries nothing seems to happen. Furthermore the app isn't recognized correctly.
I know that you use the [AboutLibraries library](https://github.com/mikepenz/AboutLibraries) and it also has the same problem in my app.
But as far as I know licenses like (in this case) GNU Lesser General Public License v3.0 have to be included in the app and a link to the source has to be given (see the screenshot below).
Am I wrong? Otherwise you would have to include them manually...

<img src="https://user-images.githubusercontent.com/46033730/85875161-19155680-b7d4-11ea-9b54-0885d56f278e.png" width="800">

### Actual behaviour
<img src="https://user-images.githubusercontent.com/46033730/85874504-064e5200-b7d3-11ea-9b32-1b21d9beb951.jpg" width="350">

### Expected behaviour
<img src="https://user-images.githubusercontent.com/46033730/85874677-4e6d7480-b7d3-11ea-9897-277028fde584.jpg" width="350">

#### Client
* Android version: 8.0.0
* Device model: Samsung SM-G930F
* App version : 2.13.0
* Build flavor : Full
* Device language: de

**Comment by mueller-ma** [comment]
Thanks for your report. I also noticed that and opened https://github.com/GrenderG/Toasty/issues/137.
According to the output of the aboutlibraries gradle plugin this is the only missing lib.

**Comment by nikothegreek** [comment]
Ok, I think I know why AboutLibraries can't find any information:

If you search the databases ([direct search example 1](https://ossindex.sonatype.org/search?q=Toasty), [direct search example 2](https://search.maven.org/search?q=Toasty)), where normally every library should be found, for "Toasty", they don't find anything.

If you e.g. search for "AboutLibraries" ([direct search link](https://ossindex.sonatype.org/search?q=AboutLibraries)) or also for libraries with "com.github" in the beginning like "AppIntro" ([direct search link](https://ossindex.sonatype.org/search?q=AppIntro)), you find their entries.

But I don't know why it can't be found...

**Comment by cyb3rko** [comment]
@mueller-ma Just fyi:
I fixed it in [a pull request](https://github.com/GrenderG/Toasty/pull/154) a few months ago.
It should work if the android client will update to next version.
