### ISSUE TITLE
Using hacked basic UI in Android app

### ISSUE THREAD

**Issue by tflyx** [openhab/openhab-android#2077]
Hi,

I'm trying to change the view and the behavior of the ui with the following logic from the openhab forum:
[Hacking BasicUI: My current Theme](https://community.openhab.org/t/hacking-basicui-my-current-theme-oh2-setup-update-with-repo/45850)
So injecting a webview which hase all the needed js-code and css.
In Basicui in the Browsers it works perfect. In the App however it doesn't.
I belive this has something todo with the fact that the webview is included in an iframe and you're not able to use the parent statement of javascript to get from the iFrame to the main-document.

I belive it is some kind of security feature but I'm not quite shure. Maybe it is possible to make it work from within the app?

Regards flyx

**Comment by mueller-ma** [comment]
The app uses the rest api to display native sitemap elements. Webviews are only used for HABPanel and Webview elements in your sitemap.
So you need to modify the app source code as well.

> Maybe it is possible to make it work from within the app?

You can try it, but it won't make it in the official version of the app.

**Comment by tflyx** [comment]
Is there any other way to include css and JavaScript files from the openhab server?

**Comment by mueller-ma** [comment]
You cannot use CSS or JS to style the sitemap elements in the app.
