### ISSUE TITLE
MAP(my.map): prefix for setpoint entries

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-android#2081]
### Actual behaviour
When changing a setpoint all the options have a MAP(my.map): prefix when transformation is used.

### Expected behaviour
No prefix is shown.

 
### Steps to reproduce
1. Find an item with setpoint and transformation
2. Tap on it to open the picker dialog.

### Can you reproduce the issue in demo mode?

No, because no setpoints with a transformation are setup in the demo mode.

#### Client
* Android version: 9
* Device model:  
* App version 2.13.8-beta 
* Build flavor : Full
* Device language: German

#### Server
* Server version: 2.5.2
* Reverse Proxy: Yes
* Authentication method :  User/Password

**Comment by maniac103** [comment]
Can you please give us an example item, map file, and sitemap definition that reproduces this?

**Comment by Flole998** [comment]
Sitemap
`
Setpoint item=Thermostat_GF_Little_Temperature minValue=4.5 maxValue=30.5 step=0.5  label="Soll-Temperatur"
`

Item
`
Number            Thermostat_GF_Little_Temperature "Soll-Temperatur [MAP(max.map):%s]"  <temperature>   (GF_Little, RRDPersistence)`

Transform

```
4.50=OFF
5=5.0 °C
5.50=5.5 °C
6=6.0 °C
6.50=6.5 °C
7=7.0 °C
7.50=7.5 °C
8=8.0 °C
8.50=8.5 °C
9=9.0 °C
9.50=9.5 °C
10=10.0 ° 
```

**Comment by maniac103** [comment]
Well, yeah:
```json
       {
            "widgetId": "02",
            "type": "Setpoint",
            "visibility": true,
            "label": "Soll-Temperatur [5]",
            "icon": "temperature",
            "mappings": [

            ],
            "minValue": 4.5,
            "maxValue": 30.5,
            "step": 0.5,
            "item": {
                "link": "http://<ip>:8080/rest/items/TestThermostat",
                "state": "5.0",
                "stateDescription": {
                    "pattern": "MAP(my.map):%s",
                    "readOnly": false,
                    "options": [

                    ]
                },
                "type": "Number",
                "name": "TestThermostat",
                "label": "Soll-Temperatur",
                "category": "temperature",
                "tags": [

                ],
                "groupNames": [

                ]
            },
            "widgets": [

            ]
        },
```

I'm not sure how this is supposed to work from an API point of view. Since `pattern` in `stateDescription` is the only indication of possible number formatting that we have, how should we deal with that here? We could just ignore it (but by what criteria? Hardcoded list of keywords like `MAP`, `REGEX` etc.?). We could parse the map file (but that doesn't scale, as it doesn't make sense for `REGEX`, let alone `JS`).
FWIW, BasicUI uses the 'ignore' route, by not using `stateDescription` at all: https://github.com/openhab/openhab-webui/blob/master/bundles/org.openhab.ui.basic/web-src/smarthome.js#L926-L940

**Comment by Flole998** [comment]
For REGEX it might actually work aswell, for JS things get more complicated. It might still be better than the current implementation though. The actual state is represented properly in my case by the way (for example 4.5 is displayed as OFF), it's just the popup that has those issues.

I think the only real way this could work is by evaluating the expression for every possible value, implementing an endpoint in openhab core that goes through all possible values (which is difficult since there can be an infinite amount, or at least an amount only limited by the limits of the Number item). So ignoring it seems to be the only option for now, maybe OH3 will provide a better option or we should make then aware  of this so this can be considered when they work on that shiny new Webinterface and do API changes.

**Comment by maniac103** [comment]
> The actual state is represented properly in my case by the way (for example 4.5 is displayed as OFF), it's just the popup that has those issues.

Yes, as the actual state is rendered server side (returned as part of the `label` attribute in the JSON above).

> I think the only real way this could work is by evaluating the expression for every possible value, implementing an endpoint in openhab core that goes through all possible values (which is difficult since there can be an infinite amount, or at least an amount only limited by the limits of the Number item). So ignoring it seems to be the only option for now

I fully agree -> #2086
