### ISSUE TITLE
Enable AlwaysOnHotwordDetector for Wall Mounted Tablets

### ISSUE THREAD

**Issue by joefrank25** [openhab/openhab-android#210]
Starting with API 21, Android allows developers to use the "hotword" detector to determine when someone wants to execute a voice command.  This is the same functionality that powers the "OK Google" feature on most devices.  

We should add an optional hotword detector with a configurable phrase so that it is possible to speak commands to wall mounted tablets without having to touch the microphone button on the app.

The details are documented here: https://developer.android.com/reference/android/service/voice/AlwaysOnHotwordDetector.html

It's unclear if it is possible to tie directly into the hotword detector, so we may need to use the generic "voice actions" as documented here:

https://developers.google.com/voice-actions/system/

Does anyone have experience working with this functionality?
##

**Comment by joefrank25** [comment]
Upon further review, this may not be possible.

http://stackoverflow.com/questions/26834163/example-of-alwaysonhotworddetector-in-android

**Comment by cribskip** [comment]
Hey, I took a look at https://snowboy.kitt.ai which is supported by amazon, powered by a neutral network, enables custom keywords and works offline.

Shall I give it a go? 
Quick setup with tasker based activation seems promising.

**Comment by joefrank25** [comment]
Sure, @cribskip, give it a go!

**Comment by cribskip** [comment]
Just thoughts of today's night: Before I'm implementing this, is the Apache License from snowboy compatible to the Eclipse Public License of habdroid?

**Comment by prahubhatt** [comment]
Snowboy is awesome, go for it! I implemented my project here: https://play.google.com/store/apps/details?id=com.multiverse.jarvis&hl=en

**Comment by cribskip** [comment]
If time permits, I'll take a look at this tutorial and start working on it: https://itnext.io/how-to-easily-command-your-app-with-hotword-detection-1001e582c46e

**Comment by cribskip** [comment]
Ok, so I took a look at the [example](https://github.com/Kitt-AI/snowboy/tree/master/examples/Android) and it seems pretty straight-forward - beside my IDE being on Windows :-(
I'll try to implement it without swig and will test this way. Should take me about one week for a prototype... look forward ;-)

Btw, did someone notice [parsetron](https://github.com/Kitt-AI/parsetron)?

**Comment by Scherzin83** [comment]
Hi is there any plans to implement this feature or is they’re already a workaround for using a Hotword?

**Comment by mueller-ma** [comment]
I don't have any plans to implement this, but I'd review a PR implementing it.

**Comment by mueller-ma** [comment]
IMO the Google Assistant can do the same: https://github.com/openhab/openhab-android/issues/2394#issuecomment-767716581
