### ISSUE TITLE
Image scale / size / zoom not working

### ISSUE THREAD

**Issue by markusuidl** [openhab/openhab-android#2110]
### Actual behaviour
Image item does not show as expected.

It is shown pixel per pixel with the resolution of the image.

### Expected behaviour
Entire Image and its content is visible (as it was in 2.13.**15**-beta)

Picture must be zoomed to width and height must be applied to this screen width.
 
The example image (see next) is displayed with full height, but centered and left+right content is not visible.

### Steps to reproduce

Insert this to your sitemap, the Image has a 4k resolution.
Image url="http://4k.com/wp-content/uploads/2014/06/4k-image-tiger-jumping.jpg"

The other way does not work either. If you have an image that has lower resolution than the screen it will be shown smaller.
In the previous version it was always zoomed to the width of the screen (which I thought was good for most usecases).

#### Client
* Android version: 9
* Device model: LG G6  (screen resolution: 2880 × 1440)
* App version 2.13.**16**-beta

**Comment by maniac103** [comment]
> The other way does not work either. If you have an image that has lower resolution than the screen it will be shown smaller.

This actually is intentional and matches what BasicUI is doing. I agree that larger images should be scaled down though, I'll check it.

**Comment by mueller-ma** [comment]
On my device the linked picture isn't loaded at all: `W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (7680x4320, max=4096x4096)`

**Comment by maniac103** [comment]
I hit this instead: https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r40/graphics/java/android/graphics/RecordingCanvas.java#279

(7680x3840 x 4 byte per pixel is about 132 MB)
