### ISSUE TITLE
Cannot insert http remote address

### ISSUE THREAD

**Issue by fazioa** [openhab/openhab-android#2132]
### Actual behaviour
It Is a new installation, not upgrade.
Version is 2.13.0
Isn't possibile to add http address because textbox require only https address.
When I write my address http://* * *.m* * *loud.com:8095 buttton "OK" remain disabled.

#### Client
* Android version: 9
* Device model: Xiaomi Mix 3 and Huawei P9 lite
* App version : 2.13.0
* Device language: IT

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
No

**Comment by maniac103** [comment]
This is intended behavior (for security reasons), see #1624.
