### ISSUE TITLE
Prepare for Android 11

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2137]
The app needs to be prepared for Android 11. I'm on it.
https://developer.android.com/preview

**Comment by towo** [comment]
cf. #2210

**Comment by mueller-ma** [comment]
#2210 is about supporting a new feature of Android 11. This issue is about making the app compatible with 11.

**Comment by mueller-ma** [comment]
> The navigation bar still has white buttons on a white background in the main activity. I haven't figured out why. It's working in all the other activities and the code for that is shared between them.

The deprecated functions still work on Android 11. IMO we could use them instead, suppress the warnings and open an issue to keep track of that.
I'd like to merge this so I can use the new snackbar function in other PRs as well.

_Originally posted by @mueller-ma in https://github.com/openhab/openhab-android/pull/2140#issuecomment-694305018_

**Comment by Trysupe** [comment]
I don't know if this helps but I am using the App on Android 11 (on OnePlus 7T Pro) and I didn't notice anything not working but [this Issue](https://github.com/openhab/openhab-android/issues/2412)

**Comment by mueller-ma** [comment]
This is only open, because there's now a deprecation in the code and we want to get rid of it.
