### ISSUE TITLE
Feature proposal: Slideshow/clock screensaver

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab-android#215]
For most of my deployment, it would be amazing to show slideshow/clock/any other data-driven view from OH as a screensaver.

Any click/tap would dismiss the screen and show the last used view.
##

**Comment by digitaldan** [comment]
Yes that would be cool, what would be great is to use the daydream screen saver api since we already have support for this in the app

http://android-developers.blogspot.com/2012/12/daydream-interactive-screen-savers.html

**Comment by mueller-ma** [comment]
Is anyone still interested in seeing this implemented?

**Comment by nibi79** [comment]
This issue is closed and marked as completed... has it really been implemented?

Even though the question was asked a while ago, I'm really interested in using such a screensaver for my wall-mounted tablet.

**Comment by mueller-ma** [comment]
No, this hasn't been implemented. AFAIK when I closed the issue it wasn't possible to "close as not planned".

I reopen it and would review PRs for this feature.

**Comment by nibi79** [comment]
yes, that would be great. Thank you very much for your efforts.
