### ISSUE TITLE
Charts flashes with each item change

### ISSUE THREAD

**Issue by Seb-Maier** [openhab/openhab-android#217]
On the sitemap I show two charts:

```
Frame label="Letzten 24 Stunden:"   {   Chart item=gUGTechnik_Strom_Wirkleistung_W period=D     refresh=3600000     }
Frame label="Letzten 7 Tage:"       {   Chart item=gUGTechnik_Strom_Wirkleistung_W period=W     refresh=3600000     }
```

The item group _gUGTechnik_Strom_Wirkleistung_W_ belongs to the group _gUG_

In the rrd4j.persist file I have 

```
gUG*    : strategy = everyMinute
```

In the .items file

```
Number UG_TECHNIK_Strom_Wirkleistung_Gesamt_W   "Wirkleistung [%dW] (gUGTechnik_Strom_Wirkleistung_W)
```
## Current Behavior

The Item UG_TECHNIK_Strom_Wirkleistung_Gesamt_W refreshes very often about once a second.
Also the chart is flashing about once a second. I'm not sure if it's depending on the  item change, but it seems that the refresh time of 3600000ms (60min) have no influence.

It's only flashing when I open the sitemap with habdroid (Android). When I open the sitemap in a web-browser, the chart is stabel.

I also found another discussion about that problem
[https://community.openhab.org/t/chart-annoying-refreshing/5017]
## Expected Behavior

I think the chart should be stable in the habdroid view like in the web-broswer view.
It should refresh with the frequent of the refresh time (example 60min oder 30sec)
## Steps to Reproduce (for bugs)

The problem is always reproduceable when open the sitemap with charts
## Environment

On my system the following versions are running:
openhab: 1.8.0
habdroid: 1.8.0.2
##

**Comment by mueller-ma** [comment]
@lolodomo Is this related to #481 ?

**Comment by lolodomo** [comment]
No, that looks like a different issue specific to charts. But if due to this issue, the chart is refreshed too much fast, my fix will avoid flooding the app with refresh.

**Comment by 9a4gl** [comment]
This is quite annoying issue, when some value change in my webview grafana graph refresh which cause flashing the screen as loading graph takes some time. I am afraid to show WebRTC stream in webview.

**Comment by lolodomo** [comment]
Having a dynamic update of pages without any user action is very importan, the most important. We cannot break that.

**Comment by 9a4gl** [comment]
After some testing, just calling notifyDataSetChanged() on adapter refersh all visible items, talked to friend who is more experienced with android UI, and he suggested that RecycerView is the way to go, there you specify what has been changed. 

We can keep dynamic update of pages with some logic but that would require that id's received from ser ver do not change per item, is that true ?

**Comment by lolodomo** [comment]
Yes, that looks like a good proposal. That probably requires a massive change in the app.

**Comment by 9a4gl** [comment]
My approach was to refresh everything if:
- number of items changed since last refresh
- type of any item in list changed since last refresh
Otherwise:
- for each item check if something changed, if changed refresh otherwise not
=> This will require to implement shouldRefresh (or equalsForReqresh) method for each type

**Comment by maniac103** [comment]
Are charts actually still refreshing with latest code? I made the image items not update if their URL didn't change, which likely should fix flashing of image, chart and MJPEG items. Only web and video items should be left to fix.

**Comment by mueller-ma** [comment]
> Are charts actually still refreshing with latest code?

I have a text and a chart showing the same item. As soon as the text changes, the chart get's reloaded (but doesn't flash anymore).

**Comment by mueller-ma** [comment]
The question now is: Is the auto reloading chart a bug or a feature? :laughing:

**Comment by maniac103** [comment]
I'd say a bug, although (IMHO) not a bad one (as in: probably not overly important to fix)

**Comment by Senfglasdichtung** [comment]
Well, I'm playing with openhab and the Android App less than a week now. And honestly this bug is absolutly annoying. Let the update of the UI/charts run every second, but why have the charts to be disappearing during that update?

**Comment by mueller-ma** [comment]
Do you have set a refresh rate for your charts?

**Comment by Senfglasdichtung** [comment]
Of course, different charts with different refresh rates, but these refresh rates have no influence on the chart updates. Item changes on the other hand... I have temperature sensors which are polled every 5 seconds and the charts get updated every time the value changes.

**Comment by lolodomo** [comment]
This was recently enhanced on server side. I have not checked the specific impact on the Android app but if you are running a recent openhab snapshot I suppose it should no more happen.

**Comment by Senfglasdichtung** [comment]
I have installed the 2.3.0~20180516121953-1 snapshot of openhab now. Doesn't really change anything, when a value of an item changes the chart goes blank and appears again after some ms later. 
Are these actually two issues - not honoring the "refresh=" parameter and disappearing during update?

**Comment by Senfglasdichtung** [comment]
items
```
Group gTemperaturen

Number swTemperaturen 			"Zeitraum"

Number pilightTemperatur 		"Innen [%.1f °C]" (gTemperaturen) { pilight="rpi#temp,property=temperature" }
Number pilightAussenTemperatur 		"Aussen [%.1f °C]" (gTemperaturen) { pilight="rpi#temp_out,property=temperature" }
```

sitemap
```
sitemap sensoren label="Sensoren"
{

    Frame label="Temperaturen" {
	Switch item=swTemperaturen label="Zeitraum" mappings=[0="Stunde", 1="Tag", 2="Woche", 3="Monat"]
        Chart item=gTemperaturen period=h refresh=10000 visibility=[swTemperaturen==0]
	Chart item=gTemperaturen period=D refresh=10000 visibility=[swTemperaturen==1,swTemperaturen=="NULL"]
        Chart item=gTemperaturen period=W refresh=60000 visibility=[swTemperaturen==2]
	Chart item=gTemperaturen period=M refresh=60000 visibility=[swTemperaturen==3]
    }
 
}
```

**Comment by mueller-ma** [comment]
What's the version of the app you're using?

**Comment by Senfglasdichtung** [comment]
The one from the play store, 2.1.0, 20.04.2018

**Comment by mueller-ma** [comment]
I cannot reproduce this anymore.
