### ISSUE TITLE
Trim username and password fields

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2209]
### Is your feature request related to a problem? Please describe.
By accident a user may enter a white space in the username or password field which leads to a 401 error.

### Describe the solution you'd like
Trim the username and password fields when saving.

### Describe alternatives you've considered
Show a warning when a white space is entered.

**Comment by maniac103** [comment]
A space character is not allowed in passwords?

**Comment by mueller-ma** [comment]
Good point. Spaces are most likely allowed, but probably added by accident in most cases.

> Show a warning when a white space is entered.

This should be a good alternative.

**Comment by Gosunet** [comment]
If space character is allowed, i think it shouldn't even be a warning. I don't want a warning every time i enter my password, and i  don't want anyone looking at my phone to know that i have a space character in it.

**Comment by mueller-ma** [comment]
The issue is that users sometimes paste the password inside the password field and accidentally also paste a whitespace at the end of the password.

> I don't want a warning every time i enter my password, and i don't want anyone looking at my phone to know that i have a space character in it.

You only enter your password once the connection is configured and the warning is only visible if the password field is shown.

> But if you really want that feature i can do it if you like.

You need to edit https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/preference/CustomInputTypePreference.kt. You can have a look at https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/preference/UrlInputPreference.kt, because this preference already shows an error in some cases.

I haven't fully thought about this yet, but maybe there should be a warning in all `CustomInputTypePreference`s if the last character is a whitespace.
