### ISSUE TITLE
Error uploading latest version to Play Store

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2238]
I get the following error when uploading the latest beta version to Play Store:

> Du hast eine APK-Datei mit ungültiger Signatur hochgeladen ([weitere Informationen](https://developer.android.com/studio/publish/app-signing)). Fehler bei apksigner: ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme

**Comment by Flole998** [comment]
You need the full app signing (which is recommended anyways), that can be enabled in the build.gradle with a setting similar to this (notice the v2 signing is enabled):

```
signingConfigs {
    mySigningConfig {
        keyAlias 'theAlias'
        keyPassword 'thePassword'
        storeFile file('theKeystore.jks')
        storePassword 'thePassword'
        v1SigningEnabled true
        v2SigningEnabled true
    }
}
```

**Comment by mueller-ma** [comment]
The GitHub Action for signing the apk now uses apksigner.
