### ISSUE TITLE
Unable to enter password for local or remote server

### ISSUE THREAD

**Issue by mkukik** [openhab/openhab-android#2288]
### Actual behaviour
tapping on password field exits the settings and tries to connect to server

### Expected behaviour
popup to enter password should appear 

 
### Steps to reproduce
1. Go to settings
2. tap on existing server or add new
3. entering address and username works fine
4. tap on password field

#### Client
* Android version: 10
* Device model: HUAWEI P20 Pro
* App version : 2.15.12-beta 
* Build flavor : Play store
* Device language: EN

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab.org
* openHAB Cloud version : 
* Authentication method : user and password

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by mueller-ma** [comment]
Thanks for your report. I already saw this crash in Firebase and opened #2286 to fix it.
Let me know if this issue persists in https://github.com/openhab/openhab-android/releases/tag/2.15.13-beta for you.
