### ISSUE TITLE
Add shortcut to specific Habpanel panel

### ISSUE THREAD

**Issue by politas** [openhab/openhab-android#2289]
I have a default panel I always want to open, which has all the most frequently used controls. Having to find out along the list of panels adds a significant delay to the time to do anything, when I just want to hit one button to trigger a rules chain. 

There's a lovely "Pin to home" option, but unfortunately, it ignores the current panel, and just makes a shortcut to the panel selector

"Pin to home" should create a shortcut to the panel I'm looking at, not the level up from that.

**Comment by mueller-ma** [comment]
Instead of passing multiple arguments via a `Bundle` to `WebViewFragment`, it's probably better to make `WebViewFragment` abstract and use subclasses for every UI. This way things like this should be easier to implement.

**Comment by politas** [comment]
There doesn't seem to be any UI element to allow this to actually work? The pin icon goes away when I choose a panel.

**Comment by mueller-ma** [comment]
You're right. I tested my commit with openHAB 2.5 where app bar is always shown. Starting with openHAB 3 HABPanel is shown in fullscreen and therefore the button has to be added to its subpages as well.
This is tracked in #2506.
