### ISSUE TITLE
Offline voice recognition delays processing for 10 seconds 

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-android#229]
When using the voice recognition feature while being offline (i.e. the app cannot access the Internet, only the openHAB instance in the local network), it seems to wait for some timeout after the voice input ends. If I say "turn on the light", I have to wait about 10 seconds before the command is sent to the server. When Internet is available, it is much much faster.

I am aware that that might be an issue of the offline voice recognition in Android. But afair, in older versions of the app it was possible to hold the microphone button while speaking and once the button is released, the recognition process was immediately stopped. Could we have such a mechanism in order to solve the issue?
##

**Comment by kubawolanin** [comment]
Just wanted to add that delay seems to occur online as well. 
Tested same voice commands on my android phone and HABPanel via browser - the Android app needs quite some time to "process" the speech or there's some extended timeout after I finish my command.

**Comment by mueller-ma** [comment]
The voice recognition is done by the Google App. As soon as it returns the voice command (as text) to the app it is sent to the server.
Do you still have this issue?

**Comment by kaikreuzer** [comment]
Will have to test again, but I very much assume it is still there. Note that it only happens if the phone "thinks" it is online, while it isn't (it only has a access to a local network, but not to the Internet).

**Comment by mueller-ma** [comment]
As I said before the voice recognition is completely done by the Google app or any other app that registers as voice recognition app. There's nothing we can do about this issue.
