### ISSUE TITLE
OH3 UI Doesn't display using dark theme

### ISSUE THREAD

**Issue by MikeJMajor** [openhab/openhab-android#2299]
Phone and OH app is set to use dark theme, but the OH 3 UI always appears using the light theme.

Using Chrome to view the UI shows it using the dark theme

**Comment by mueller-ma** [comment]
When passing the app theme to the webview, the openHAB 3 UI should autoselect its theme, but I couldn't get it working: https://github.com/mueller-ma/openhab.android/tree/2299-oh3-ui-theme

**Comment by MikeJMajor** [comment]
Turns out by going to "Help and About" from the UI menu you can force the theme to dark which works, it's just the default auto theme that doesn't seem to work.

Is there a way of having the OH 3 UI be the default when starting the app without having to select it in the side menu?

**Comment by mueller-ma** [comment]
Should be mitigated by  #2328.
