### ISSUE TITLE
App casts the wrong AlarmClock when using DateTime item instead of Number

### ISSUE THREAD

**Issue by frest-de** [openhab/openhab-android#2304]
### Actual behaviour
I recently update my rules and tried to use a DateTime item for my alarmclock, to get rid of the translation. The rule in the Docs is working well, but I get the wrong time. If I set the alarm for 06:00, the app updates the DateTime item with 05:00. A summertime-wintertime problem?

#### Client
* Android version: 10
* Device model: Huawei P30 Pro NE
* App version 2.15.0
* Build flavor: Full
* Device language: German

#### Server
* Server version: 2.5.10-1 
* Reverse Proxy: 
* Authentication method : None

**Comment by mueller-ma** [comment]
The timestamp is sent in UTC and not the local time zone. I'm going to close this since it's quite similar to #1960.
