### ISSUE TITLE
State option without label should not break the rendering

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#2305]
### Actual behaviour
If you define with metadata (OH3) a state option for an item without a label, this breaks the page loading in Android app. The page is displayed until this item.

### Expected behaviour
State option without label should be supported. In this case, the state value should be considered as label.
 
### Steps to reproduce
Define such an item:
```
String Mode "Mode" (Salon) [ "Control", "Power" ] { stateDescription="" [options="TV,PS3,OFF=Eteint"] }
```
And in sitemap, each of these lines are breaking the page rendering:
```
		Switch item=Mode mappings=[TV="TV", PS3="Console", OFF="Eteint"]
		Default item=Mode
```
If the item definition is changed to the following, there is no problem:
```
String Mode "Mode" (Salon) [ "Control", "Power" ] { stateDescription="" [options="TV=TV,PS3=PS3,OFF=Eteint"] }
```

**Comment by lolodomo** [comment]
FYI, in Basic UI, it is working but buttons have no label when the label is not set. To be fixed too.

**Comment by lolodomo** [comment]
Or maybe it should rather be fixed on server side in order to always return a label ?

**Comment by lolodomo** [comment]
Here is what the API returns in the two cases:
![image](https://user-images.githubusercontent.com/10186704/99886739-275e8600-2c3f-11eb-8f86-5561b7fba345.png)

![image](https://user-images.githubusercontent.com/10186704/99886749-40673700-2c3f-11eb-972f-959a23f0b176.png)

Clearly the label field is missing.

**Comment by mueller-ma** [comment]
IMO the server should always provide a label, even if it isn't explicitly set by the user. WDYT?

**Comment by lolodomo** [comment]
The label has always be optional. Providing a label that is identical to the value looks a little stupid. IMHO, it has to be correctly handled by clients.

PS: It is now fixed in Basic UI.
