### ISSUE TITLE
OH 3 Item control widget doesn't work

### ISSUE THREAD

**Issue by MikeJMajor** [openhab/openhab-android#2320]
Item control widget isn't working with OH 3:

![Screenshot_20201130-214751](https://user-images.githubusercontent.com/24585489/100669972-18ba5200-3356-11eb-80f0-bab7ab568fae.jpg)

**Comment by mueller-ma** [comment]
I cannot reproduce this. Can you post the log?

**Comment by MikeJMajor** [comment]
Hopefully this is the right section

`0,org.openhab.habdroid.ui.ItemUpdateWidgetItemPickerActivity,topStateChangedWhenResumed]
12-01 08:06:33.890 26180 29607 I okhttp.OkHttpClient: --> GET https://<openhab-local-address-openHAB>:8443/rest/items
12-01 08:06:33.890 26180 29607 I okhttp.OkHttpClient: User-Agent: openHAB client for Android
12-01 08:06:33.890 26180 29607 I okhttp.OkHttpClient: Cache-Control: no-cache
12-01 08:06:33.890 26180 29607 I okhttp.OkHttpClient: --> END GET
12-01 08:06:34.440 26180 29607 I okhttp.OkHttpClient: <-- 200 OK https://<openhab-local-address-openHAB>:8443/rest/items (549ms)
12-01 08:06:34.440 26180 29607 I okhttp.OkHttpClient: Content-Type: application/json
12-01 08:06:34.440 26180 29607 I okhttp.OkHttpClient: Date: Tue, 01 Dec 2020 08:06:33 GMT
12-01 08:06:34.440 26180 29607 I okhttp.OkHttpClient: Transfer-Encoding: chunked
12-01 08:06:34.440 26180 29607 I okhttp.OkHttpClient: Server: Jetty(9.4.20.v20190813)
12-01 08:06:34.440 26180 29607 I okhttp.OkHttpClient: <-- END HTTP
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: Item response could not be parsed
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: org.json.JSONException: No value for label
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: 	at org.json.JSONObject.get(JSONObject.java:399)
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: 	at org.json.JSONObject.getString(JSONObject.java:560)
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: 	at org.openhab.habdroid.model.LabeledValueKt.toLabeledValue(LabeledValue.kt:27)
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: 	at org.openhab.habdroid.model.ItemKt.toItem(Item.kt:157)
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: 	at org.openhab.habdroid.ui.AbstractItemPickerActivity$loadItems$1.invokeSuspend(AbstractItemPickerActivity.kt:265)
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)`

**Comment by maniac103** [comment]
```
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: Item response could not be parsed
12-01 08:06:35.185 26180 26180 D AbstractItemPickerActivity: org.json.JSONException: No value for label
```

Looks like the same issue as #2305 ... I'll fix this.
