### ISSUE TITLE
Improve new openHAB 3 UI

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2321]
A JS interface has been implemented, so the app can interact with the UI: https://github.com/openhab/openhab-webui/pull/565

**Comment by mueller-ma** [comment]
@ghys I'm running openHAB 3 snapshot and added some code to the app, but the OH 3 UI doesn't react on this: https://github.com/mueller-ma/openhab.android/commits/2321-oh3-ui
````
[root@workplace ~]# dpkg --list | grep openhab
ii  openhab                               3.0.0~S2039-1                     all          openhab
````

Do I have the correct version of openHAB?

**Comment by ghys** [comment]
Yes 2039 looks ok to me. So there's something wrong...
Can you try remote debugging the WebView over USB with Chrome?
https://developers.google.com/web/tools/chrome-devtools/remote-debugging
After it's connected you should be able to see the OH App's WebView and click Inspect.
Then in the JS console try `window.OHApp` or simply `OHApp` to confirm the object is there (and try calling the functions).

**Comment by mueller-ma** [comment]
With remote debugging I was able to execute the "OHApp" interface in the webview:
![grafik](https://user-images.githubusercontent.com/22525368/100919698-6cee3f00-34da-11eb-82af-acdfe39ea1c2.png)

Both (theme and dark mode) are set to "Auto" in the UI settings, but it's still bright and there's no "Pin to home" button.

By the way: The pin to home button should be hidden if the device isn't capable of. Let's see what else is missing and then add a function for this.

**Comment by maniac103** [comment]
> The pin to home button should be hidden if the device isn't capable of. Let's see what else is missing and then add a function for this.

You don't need a dedicated function for that, but instead can just instantiate different JS interface classes with and without that method depending on whether pinning is supported or not. Capability is expressed implicitly by function presence.

**Comment by ghys** [comment]
The UI actually tests on `window.OHApp`, not simply `OHApp` but it should be equivalent.

> You don't need a dedicated function for that, but instead can just instantiate different JS interface classes with and without that method depending on whether pinning is supported or not. Capability is expressed implicitly by function presence.

Indeed - not seeing the pin to home button is to be expected with https://github.com/mueller-ma/openhab.android/commit/028077ccdea9dfd81f3331e964aa6cc94ce302bd since you didn't implement the function. But if you prefer we can add a `boolean canPinToHome()` and test on that instead function so you can better control the displaying of that button with a fixed interface.
Also I'm seeing a silly bug in the dark mode selection which I'll fix.

But - given `window.OHApp` is indeed defined - the "return to app" button should work?

**Comment by mueller-ma** [comment]
I implemented `pinToHome()` now and this works. Is it possible for the app to check whether the UI uses the `OHApp` interface? The status bar must be shown if `exitToApp()` cannot be called by the UI.
If not the `version` at `/rest` should be bumped.


Maybe the UI should hide the theme and dark mode settings if set by the app? Or replace it with a hint that the app settings are used.

**Comment by ghys** [comment]
> I implemented pinToHome() now and this works. Is it possible for the app to check whether the UI uses the OHApp interface? The status bar must be shown if exitToApp() cannot be called by the UI.

If it calls any function of your interface at all, then you know it's using it ;) You can then set a flag and adapt.

But to make things clear, I'll add a `string version()` function that the UI will call very early during its initialization.
The app should return with a string representing its name and version. It will likely be shown in the Help & About page of the web app.
By the way we could find a way to extend the menu on the left with items provided by the app, to invoke intents like the app's settings, or NFC, or even add the sitemaps which would be rendered natively. Not sure if it's a good idea at the moment but it's still confusing to have two menus and this "return to app" behavior.

> Maybe the UI should hide the theme and dark mode settings if set by the app? Or replace it with a hint that the app settings are used.

Not really sure about that, the app influences what the "auto" theme & color mode are (hence the names of the functions starting with "prefer" and not "set"), but it's a good thing IMO that the user can still override them - similar to when you're outside the app.

**Comment by mueller-ma** [comment]
What about a function `void preferFullscreen()` that tells the app that the UI may want to run in fullscreen and is capable of returning the user to the app? This would allow other UIs, e.g. HABPanel, to implement this JS interface without having to add buttons for pinToHome and exitToApp.
It would also make the implementation in the app a bit simpler, because it has to hide the action bar only on call of a specific function, instead of hiding it whenever one of these functions are called.

**Comment by ghys** [comment]
@mueller-ma good point, I'll fix the dark mode toggle and add `void preferFullscreen()` in the process.

**Comment by maniac103** [comment]
> add void preferFullscreen() in the process.

Was this ever added to the web UI? I don't see it implemented in the app JS interface implementation.

**Comment by mueller-ma** [comment]
It's called `goFullscreen()` and was added in https://github.com/openhab/openhab-webui/pull/633.

**Comment by bf8392** [comment]
I've realised that when you access OpenHab 3 UI over the OpenHab cloud and login, it takes ages until something is displayed (OH 3.0.1). Should I open a new issue for that?
