### ISSUE TITLE
Formatting label text output for Android app

### ISSUE THREAD

**Issue by Gibber** [openhab/openhab-android#233]
Hi,

I am using a the following item definitions to create a couple of switches:

Switch  LRBlindsetting  "Blinds are [MAP(blinds.map):%s]"   <rollershutter> (GF_Living) 
Switch  LRBlindmode "Auto [%s]" <light>

The web view of these switches look as desired:

![webpage](https://cloud.githubusercontent.com/assets/431797/19061494/86a73004-89ae-11e6-98ce-7ff5fcc08383.jpg)

However, the Android app view has square brackets around the output status (Open/Closed and Off/On):

![android](https://cloud.githubusercontent.com/assets/431797/19061515/c748d4f0-89ae-11e6-9c62-a9adda8e8887.jpg)

Can anyone explain how I can get rid of the square brackets on the Android app display without messing up the web view?

I am using OpenHAB 1.8.3 and Android 6.0.1

Thanks,
Gibber
##

**Comment by digitaldan** [comment]
Right now this is how its designed. I think it would be good to get a consensus if we want to match what the classic ui does or leave it how it is.

**Comment by lolodomo** [comment]
The basic UI uses something similar to the Classic UI. I agree with @Gibber that it would be better to have something similar to other UIs.
@digitaldan : can we decide to change that ?

**Comment by lolodomo** [comment]
Note that we have already the expected rendering with TYPE_SECTIONSWITCH with the state value displayed just at right of the buttons.
