### ISSUE TITLE
Add option to select default view

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2334]
### Is your feature request related to a problem? Please describe.
Some people only use the app for HABPanel or the new OH3 UI.

### Describe the solution you'd like
The default view when opening the app should be made selectable.

### Additional context
https://community.openhab.org/t/android-app-beta/41382/296

**Comment by giejay** [comment]
Is someone working on this? Otherwise I will make a PR since I'm also looking for a way to set the Openhab 3 UI as default.

**Comment by mueller-ma** [comment]
You can give it a try, if you want.

**Comment by tflyx** [comment]
Could you please add Support for notificatins.
If I Open the oh3 ui I canbot Switch Back top notificatins or preferences.
That should still bei accessible i think.

**Comment by mueller-ma** [comment]
In the top right hand corner there's a button called "Exit to app". With this you can go back to the app and open the notifications.

**Comment by tflyx** [comment]
I saw that nur If I only use oh3 Main ui it would be great to have it seamless. So maybe an overlay in the right side by klicking on the "Back to App" Button.

**Comment by WhiteSockedDancer** [comment]
I would really love this option, since i also just want to use the new MainUI.
Shortcuts already work on the android launcher homescreen, but i could not figure out how to open a/the mainui site from tasker so i could open it on special voice commands/buttons in my smarthome.
