### ISSUE TITLE
Unable to release new versions

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2336]
Travis CI introduced a credits system and we ran out of free credits. Thus the release pipeline doesn't work anymore.
I requested additional free "open source software" credits, but didn't get a response yet.

**Comment by JohannesPtaszyk** [comment]
Can we somehow donate credits?

**Comment by mueller-ma** [comment]
I wrote a mail to the support twice, but didn't get an answer. I'd rather port the job over to GitHub Actions or the openHAB Jenkins server. It'll be discussed by mail.

**Comment by mueller-ma** [comment]
One part of the release has been ported to GitHub Actions. F-Droid should now publish again the new releases.

**Comment by candiesdoodle** [comment]
Help
F-Droid still shows the last version at 2.15-15 beta. Latest ones haven't been published yet i suppose?
Thanks

**Comment by mueller-ma** [comment]
It usually takes a few days and AFAIK the release of a new index requires manual work (the signing keys are on a air gaped system), so it might be even more delayed currently.
3 days ago the F-Droid bot recognized the 2.15.18: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.openhab.habdroid.beta.yml

**Comment by candiesdoodle** [comment]
Looks like 2.15.18 is now live on F-Droid. great work!

on a seperate note, wanted to check that since the F-Droid versions are FOSS and hence do not support google FCM enabled notifications, is it possible to compile own debug version and use with FCM?
I tried but i keep getting error in the logs stating "FIS_AUTH_ERROR"
(sorry i am not very faimiliar with firebase)
Thanks in advance

**Comment by maniac103** [comment]
No, you can't, at least not with myopenhab.org. The signature of app must match what's specified in the settings of the FCM account specified in openhab-cloud configuration, which in case of myopenhab.org means the app needs to be signed with the private key of the official app.
If you want to use FCM against your own openhab-cloud instance using a self compiled version should be possible.

**Comment by Sprocket02** [comment]
Can you explain me how to compile the FCM version? When I upload and compile the project in Android Studio, it automatically builds the FOSS version. Where do I have to set what?

**Comment by maniac103** [comment]
Under 'build variants' you need to select 'fullStableRelease'.

**Comment by Sprocket02** [comment]
Thank you, that worked. I have created a signed version that basically runs as well. However, I get the message "Notification registration failed" in the notification menu. All existing notifications are displayed, however, only the push service does not work.

**Comment by mueller-ma** [comment]
Yes, this is intended:

> No, you can't, at least not with myopenhab.org. The signature of app must match what's specified in the settings of the FCM account specified in openhab-cloud configuration, which in case of myopenhab.org means the app needs to be signed with the private key of the official app.

https://github.com/openhab/openhab-android/issues/2336#issuecomment-756686938

**Comment by Sprocket02** [comment]
OK, too bad. Do you have any idea when beta updates for google play will be available again? Pulled notifications every 15 min are not an option for me. Or when will there be a release version with full OH3 support?

**Comment by mueller-ma** [comment]
Sorry, I don't have a ETA, but I'm on it.

**Comment by mueller-ma** [comment]
I just published the latest beta to GitHub and Play Store (needs some time to get reviewed by Google).

https://github.com/openhab/openhab-android/releases/tag/2.15.23-beta
