### ISSUE TITLE
Setpoint-Sitemap not working correctly (steps)

### ISSUE THREAD

**Issue by bf8392** [openhab/openhab-android#2338]
### Actual behaviour
Describe us what happens

When you set a setpoint (themostat z-wave in my case) with a step=0.5 than it works perfectly in any browser, but the dropdown of the app displays wrong numbers, and the pushbuttons do not work 
![openhub_bug](https://user-images.githubusercontent.com/45922770/102607183-20d10a80-4128-11eb-9a87-1f081c2e8f9a.jpg)

### Expected behaviour
Describe us what should happen

Displaying values with steps of 0,5 and working pushbuttons
 
### Steps to reproduce
1. Describe us how to reproduce the issue
2. Use a list for it

1) setup a setpoint like described here: https://www.openhab.org/docs/configuration/sitemaps.html#element-type-setpoint
2) Downlaod the Android-App and configure it with your remote link (connected to openhab cloud)
3) try to setup the temperature with the dropdown or the buttons (buttons do not respect step=0.5)

#### Client
* Android version: 10
* Device model: oneplus 6t
* App version : 2.15.0 (F-Droid)
* Build flavor : 
* Device language: German

#### Server
* Server version: 2.5.11 (docker)
* Reverse Proxy: Traefik 2.3 (docker)
* Authentication method: user and password (basic-auth), SSL Client certificate (letsencrypt) all handeled by traefik

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab.org

**Comment by maniac103** [comment]
Please show the respective Item and Sitemap widget configuration. I suspect the former is set up to be formatted as `%d`, IOW, without decimal digits.

**Comment by bd8392** [comment]
This is the Item from the Sitemap

```
    Frame label="Temperatursteuerung" {
        Default item=Thermostat_Fubodenheizung_mode
        Default item=Thermostat_Fubodenheizung_Temperatur_sensor
        Setpoint item=Thermostat_Fubodenheizung_Temperatur_setpoint label="Gewünschte Temperatur [%.1f °C]" icon="heating" minValue=10 maxValue=30 step=0.5
        }
```

**Comment by bd8392** [comment]
and this the item (cofigured over Paperui) 
![openhab_item](https://user-images.githubusercontent.com/45922770/102609846-73142a80-412c-11eb-9e52-0bdda37da398.jpg)

**Comment by mueller-ma** [comment]
> `[%.1f °C]`

This should be the correct format. I try to reproduce it.

**Comment by maniac103** [comment]
> This should be the correct format.

That's correct, but `stateDescription` (which the setpoint formatting is fed from, IIRC) is part of the Item, not the Sitemap widget.

**Comment by bd8392** [comment]
> That's correct, but `stateDescription` (which the setpoint formatting is fed from, IIRC) is part of the Item, not the Sitemap widget.

In the browser it's working correctly...only the app doesn't seem to get the step...

**Comment by maniac103** [comment]
I know, BasicUI works differently there. It's all about guessing the correct number of decimal digits. Unfortunately, when dealing with floating point numbers, a step of '0.5’ could very well be '0.5000000001’ or something in machine representation, which in this case would mean displaying the values with 10 decimal digits. We maybe should do that as a fallback, I guess; we'll need to see how to fit this in.

**Comment by mueller-ma** [comment]
> That's correct, but stateDescription (which the setpoint formatting is fed from, IIRC) is part of the Item, not the Sitemap widget.

I added the state format to the sitemap widget, not the item itself, and it's working for me:

````bash
$ grep Thermostat_Fubodenheizung_Temperatur_setpoint items/test.items sitemaps/demo2.sitemap
items/test.items:37:Number Thermostat_Fubodenheizung_Temperatur_setpoint "Gewünschte Temperatur"
sitemaps/demo2.sitemap:257:                Setpoint item=Thermostat_Fubodenheizung_Temperatur_setpoint label="Gewünschte Temperatur [%.1f °C]" icon="heating" minValue=10 maxValue=30 step=0.5
````

@bd8392 Can you try to change the label in PaperUI to `Gewünschte Temperatur [%.1f °C]`?

**Comment by bd8392** [comment]
Sorry for the delay

> @bd8392 Can you try to change the label in PaperUI to `Gewünschte Temperatur [%.1f °C]`?

Tried, and on first update of the sitemap it seemed to work, but on second load it didn't anymore and the same issue is persistent...

**Comment by bd8392** [comment]
Got the solution!!!. With openhab 3, you can easily set metadata...just set the steps like so: https://community.openhab.org/t/openhab-3-pages-number-format/112171

After that, the steps are showed correctly =)

**Comment by bf8392** [comment]
The bug reappeared again...the setpoint does not work anymore and is showing the exact same unwanted behaviour as described above...I have metadata with state-description in place, but it doesn't seem to be recognised by the app...in Basic-Ui everything works perfectly!

**Comment by maniac103** [comment]
What's the output of opening `http://<OPENHAB-IP>:8080/rest/items/Thermostat_Fubodenheizung_Temperatur_setpoint` (in a browser, or using curl)?
