### ISSUE TITLE
Demo mode not working anymore

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2340]
The demo server was updated to openHAB 3 and now the demo mode is broken.

**Comment by Jochen1980** [comment]
I try to solve it. 

Current connection in the app is https://demo.openhab.org:8443/ - got a 404er
Current working demo is https://demo.openhab.org - I need to figure out the port ....

**Comment by Jochen1980** [comment]
see PR #2344

**Comment by mueller-ma** [comment]
@kaikreuzer The demo server returns invalid urls on some api endpoints, e.g. https://demo.openhab.org/rest/items:
````
[
  {
    "link": "http://localhost:18080/rest/items/Shutter_GF_Living",
    "state": "100",
    "editable": true,
    "type": "Rollershutter",
    "name": "Shutter_GF_Living",
    "label": "Living Room Shutters",
    "tags": [
      "Blinds"
    ],
    "groupNames": [
      "GF_Living",
      "Shutters"
    ]
  },
....
````

Is there something wrong with the reverse proxy config? Other endpoints return valid urls, e.g. https://demo.openhab.org/rest/

**Comment by mueller-ma** [comment]
Poking @openhab/infrastructure-maintainers

**Comment by kaikreuzer** [comment]
@ghys As you helped on the setup of the demo server, do you maybe have an idea? Are we missing some settings in the reverse proxy or do we actually have a regression in openhab-core?

**Comment by wborn** [comment]
The SSE is also broken on the Demo server. You see "SSE subscription failed: running in fallback mode" when opening Basic UI: https://demo.openhab.org/basicui/app?sitemap=demo

**Comment by ghys** [comment]
> The SSE is also broken on the Demo server. You see "SSE subscription failed: running in fallback mode" when opening Basic UI: https://demo.openhab.org/basicui/app?sitemap=demo

For this problem at least, it's pretty clear:
```
{"error":{"message":"Max number of subscriptions is reached.","http-code":503}}
```
So it appears this server is a victim of its own success. Maybe it's configurable?
Not sure if it's the same problem with the Android app or if it's due to the internal URLs returned - why `/rest/` doesn't do that as well, I can't explain.

**Comment by mueller-ma** [comment]
The app issues are caused by the wrong urls returned. 
If sse fails in the app, a message is shown and long polling is used.

**Comment by ghys** [comment]
I fixed the URLs on demo.openhab.org.

**Comment by mueller-ma** [comment]
I can confirm that the demo mode is working with the latest Android beta.

**Comment by kaikreuzer** [comment]
Many thanks, @ghys!
