### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [openhab/openhab-android#2342]
### Actual behaviour
Describe us what happens
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
App version is 2.15.15, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="444" alt="bug-beta_342" src="https://user-images.githubusercontent.com/18572115/103147382-5791cb00-478f-11eb-84d9-28078f22230b.png">

### Expected behaviour
Describe us what should happen
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.

 
### Steps to reproduce
1. The font size and display size are the largest
2. In the first page

#### Client
* Android version: 8.0
* Device model:  Google nexus 6
* App version : 2.15.15
* Build flavor : Foss
* Device language: English

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: 
* openHAB Cloud version : 
* Authentication method : 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by mueller-ma** [comment]
Thanks for this report. We're using the default slide from the intro library, so can you open a issue there? https://github.com/AppIntro/AppIntro

**Comment by mueller-ma** [comment]
Let's see if  #2343 fixes it.

**Comment by franklinbill** [comment]
OK, I can open an issue there
