### ISSUE TITLE
Widget and nfc notification problem

### ISSUE THREAD

**Issue by viscovich** [openhab/openhab-android#2351]
On My Samsung S9+ , Openhab 2.15, Android 10 up to date I have notification problem. I create a widget with a simple light switch and an nfc tag. Most of the times in the notification toolbar i get a Waiting for connection. If i press the notification i Get into the app and the command gets executed. This happens with wifi on and even with wifi off (data on).

**Comment by viscovich** [comment]
The problem happens with nfc and with the widget, it seems it doesn't reach openhab app to notify what to do.

**Comment by viscovich** [comment]
Going on with retries, it seems that if it gets immediately response it works, if after 1 second doesn't get response, it raises a
waiting_for_item_upload (translation) in the notifitication toolbar. Then you have to open manually the app to have the commad executed.
Looking up the code, seems  hasEnqueuedWork is true, this because WorkInfo.State.ENQUEUED it's true.
Maybe a delay should be added?

hasEnqueuedWork = latestInfoByTag.any { (_, info) -> info.state == WorkInfo.State.ENQUEUED }

= latestInfoByTag.any { (_, info) -> info.state == WorkInfo.State.ENQUEUED }

**Comment by mueller-ma** [comment]
The update is retried several times and if it fails to update the item, a notification is shown. Can you post the log of the app after seeing this notification?

**Comment by viscovich** [comment]
I'm sorry. It turned out it it was some weird Samsung battery optimisation. Even if I got a 100% with don't kill my app there was still something to adjust.
Now it works fine.
Andrea
