### ISSUE TITLE
Alarm time not re-sent after repeating alarm

### ISSUE THREAD

**Issue by patmalcolm91** [openhab/openhab-android#2355]
### Actual behaviour
If I set a repeating alarm, say every morning at 8:00am, after the alarm goes off on the first day, the new alarm time is not sent to the openHAB server. I must open the clock app and disable then re-enable said alarm for the new time to be detected by the openHAB app and sent to the server.

### Expected behaviour
After each occurrence of a reapeating alarm, the next alarm time should automatically be sent to the server.

 
### Steps to reproduce
1. Create a repeating alarm
2. Wait until after the first alarm goes off and observe that the next alarm time is not sent.
3. Toggle the alarm off and then on again to see that it is then sent

### Can you reproduce the issue in demo mode?
Not checked.

#### Client
* Android version: 10 (Oxygen 10.0.1)
* Device model: OnePlus 5
* App version : 2.15.0
* Build flavor : Full
* Device language: German

#### Server
* Server version: 3.0.0
* Reverse Proxy: No
* Authentication method : user and password

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: N/A
* openHAB Cloud version : N/A
* Authentication method : N/A

#### App log
N/A

#### openHAB Server log
N/A

**Comment by mueller-ma** [comment]
Which alarm clock app do you use?

**Comment by patmalcolm91** [comment]
I'm just using the standard clock app that comes on the OnePlus. If I use a 3rd-party alarm time sync app, I don't experience this issue, so I don't suspect the problem is with the clock app itself.

**Comment by maniac103** [comment]
I suspect the alarm time is updated when you open the app manually?

@mueller-ma https://developer.android.com/reference/android/app/AlarmManager#ACTION_NEXT_ALARM_CLOCK_CHANGED ... the broadcast is only sent to registered receivers, not to manifest registered ones.

**Comment by patmalcolm91** [comment]
Opening the clock app was not sufficient to force an update. I had to manually turn the alarm off and then on again for the new value to be sent.

I went in to the preferences for the openHAB app and saw that I already had "event listener" enabled. I toggled it off and then on again, and I am not able to reproduce the issue with a test alarm. However, I also checked after turning it back off, and everything seems to work ok with a test alarm, so I'm not sure that I'm recreating all the necessary conditions to reproduce the problem. Perhaps the bug only happens after the app has been closed for a long time. I'll observe what happens after tomorrow's alarm and report back.

**Comment by mueller-ma** [comment]
The app should always receive `ACTION_NEXT_ALARM_CLOCK_CHANGED` broadcasts, because of https://developer.android.com/guide/components/broadcast-exceptions. The event listener doesn't listen for this event anyway: https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt#L288


@patmalcolm91 You can disable the event listener, it's only required for "schedule based" items. It's possible that the battery saver by Oneplus interferes here. Can you check https://dontkillmyapp.com/?

**Comment by patmalcolm91** [comment]
I'm no longer to reproduce the issue, so it seems very likely the problem was indeed with the OnePlus battery saving feature. I've followed the recommended actions to prevent the OpenHAB app from getting killed in the background, so hopefully that resolves the issue. Thanks for your help.
