### ISSUE TITLE
[UX] Settings->Connection->Local authentication failure resolution is not clear

### ISSUE THREAD

**Issue by 13rac1** [openhab/openhab-android#2359]
### Actual behaviour

1. Go to Settings->Connection->Local
2. Enter
    * Local server URL
    * Username
    * Password
3. Authentication Failed -> No Help Message
![Screenshot_20210109-194608](https://user-images.githubusercontent.com/195061/104113949-a2ddca80-52b3-11eb-99eb-e2cb4f3e56be.png)

### Expected behaviour

1. Go to Settings->Connection->Local
2. Enter
    * Local server URL
    * Username or API Token
    * Password
3. Authentication Failed -> Display help or something else containing the following information "Is Basic Authentication Enabled or have you provided an API Token as the Username?"

A summary of the Authentication section from the docs would be extremely helpful: https://github.com/openhab/openhab-docs/blob/b8c8ca28/configuration/restdocs.md#authentication

> ## Authentication
>  Starting with version 3, openHAB supports password protection for sensible contents such as parts of the semantic model. To access this kind of information, the REST API provides the common mechanism Basic authentication and OAuth authorization. Both mechanisms can be used out of the box by the most programming languages and frameworks, but with regard to the curl examples from above, there are two alternative ways of authenticating yourself:
> 
> ### With username/password
> To the complete command, add -u {USER_NAME}, then enter your password as prompted. You can also do this in a single, non-interactive command, in this case add -u {USER_NAME}:{PASSWORD} instead.
> Note: This approach uses basic authentication which needs to be enabled in the org.openhab.restauth settings (accessible under Main UI > Settings > API Security).
> 
> ### With an API token
> This method is often recommended in order to keep your passwords safe and avoid to store them without encryption in any public places. To authenticate with an API token, append -u '{API_TOKEN}:' to the commandline.
> 
> You can manage all access tokens in your profile settings in the Main UI.
 
### Steps to reproduce
See above

### Can you reproduce the issue in demo mode?
N/A

#### Client
* Android version: 10
* Device model: Google Pixel
* App version: 2.15.0
* Build flavor Play Store
* Device language: English

#### Server
* Server version: 3.0.0
* Reverse Proxy: N/A
* Authentication method: Username/Password

### Logs
N/A

### Related

This is similar to #2339 but different enough as a UX-specific bug report I thought it should be separate. Please close if you disagree. I wanted the issue specifically documented so people could resolve the authentication failure more easily.

**Comment by 13rac1** [comment]
The vscode extension contains this help:
![image](https://user-images.githubusercontent.com/195061/104116902-8ea8c600-52d1-11eb-831a-339a0ef5dee4.png)

**Comment by mueller-ma** [comment]
IMO the current error message is fine, but the UX for adding a new connection could be improved:
Have a text field to enter a hostname and try to establish a connection (#536). Then ask for credentials if required.

Also see  #2360.

**Comment by mueller-ma** [comment]
I updated  #2360. It now contains a short hint where to enter the api token and a link to the docs.

**Comment by mueller-ma** [comment]
In 2.15.26-beta there's a hint in the settings and a link to the docs.
