### ISSUE TITLE
OWM Icon to big

### ISSUE THREAD

**Issue by Wikibear** [openhab/openhab-android#2393]
Everytime, with different App Versions. Beta or Normal.

OWM weather icons will show to big in size.
 
No steps to reproduce. Its everytime.

* Android version: All Versions
* Device model: All Devices
* App version: 2.15.25-beta - all Versions

![grafik](https://user-images.githubusercontent.com/18314278/105842478-8ab9bb00-5fd6-11eb-95ac-e3b0ccf88abe.png)

_Edit by @mueller-ma: Moved MapView issue to a new issue: #2401_

**Comment by mueller-ma** [comment]
Can you post your sitemap?

**Comment by dkneisz** [comment]
At least the imge "bug" seems to be more like an CSS issue in BasicUI. It also happens when you resize your browser in with so it's smaller then 850px. In this case the image and the surrounding div get resized in widht to 100% by this code in "smarthome.css"
`@media screen and (max-width: 850px) {
    .mdl-form__image {
        width:100% 
    }

    .mdl-form__image.mdl-form__control {
        padding-left: 0;
        padding-right: 0
    }

    .mdl-form__image img {
        height: auto;
        width:100%;
    }
}`

If you remove both "width: 100%;" it displays like when the browser is wider than 850px. I tested this with the developer tools in Chrome.

**Comment by mueller-ma** [comment]
Basic UI is a completely different code base than the app. There's a setting in the app for scalling images.

**Comment by dkneisz** [comment]
The setting in the app has no effect in this case (at least for me). As I mentioned, this issue also occurs when you call BasicUI from the browser (desktop or mobile).

**Comment by mueller-ma** [comment]
Can you post the part of the sitemap, so I can test this myself?

**Comment by dkneisz** [comment]
In the sitemap I have this:
```
Image item=local24HourForecastConditionIcon
```
The item itself is this:
```
Image local24HourForecastConditionIcon "Icon" { channel="openweathermap:onecall:api:local:forecastTomorrow#icon" }
```

**Comment by Wikibear** [comment]
```
    Frame label="Umwelt" {
        Text item=WetterVerkehr label="WetterVerkehr" {
            Frame item=WetterVerkehr {
                Text item=WetterUndVorhersage_Current_LetzteMessung
                Text item=WetterUndVorhersage_Current_AuEntemperatur
                Text item=WetterUndVorhersage_Current_Luftfeuchtigkeit
                Text item=WetterUndVorhersage_Current_Luftdruck
                Text item=WetterUndVorhersage_Current_Windgeschwindigkeit
                Text item=WetterUndVorhersage_Current_Windrichtung
                Text item=WetterUndVorhersage_Current_Sichtweite
                Text item=WetterUndVorhersage_Current_Wetterlage
                Text item=WetterUndVorhersage_Current_Regen
                Text item=WetterUndVorhersage_Current_Schnee
                Text item=NetatmoOutsideTemp
                Text item=NetatmoOutsideHum
                Text item=GefTemperaturHitzeindex
                Text item=GefTemperaturHumidex
                Text item=UVIndex_Current_UVIndex
                Text item=SonnenaufgangStart
                Text item=SonnenuntergangStart
            }
         }
      }
```
Can't send the item. It's all OH3 related. Don't have any item file.

**Comment by mueller-ma** [comment]
Can you download and send my the icon?

**Comment by Wikibear** [comment]
Totally simple... This are the icons of owm itself: https://openweathermap.org/weather-conditions#Icon-list

**Comment by mueller-ma** [comment]
I tried http://openweathermap.org/img/wn/50n@2x.png and it behaves as intended. If `Scale images to fit screen` is turned on, the image is blurry and looks as on the screenshot above. If this setting is turned off, the image is much smaller, but sharp.

Also see https://github.com/openhab/openhab-android/issues/2183#issuecomment-683420470:

> I honestly think the discussion in #2072 simply shows a mis-use of the Image widget. This is not meant for displaying icons, but really only for images and as mentioned, any widget type is expected to scale to 100% width to provide a proper overall appearance.

**Comment by dkneisz** [comment]
If I include the image directly with the url, it is indeed not scaled when I set the option. However in this case the image is rendered from the item, that contains a base64 encoded image. This usage is exactly how it is described in the docs for the OpenWeatherMap binding (https://www.openhab.org/addons/bindings/openweathermap/), so I don't see a mis-use here.

**Comment by mueller-ma** [comment]
Thanks for this hint: Images without URL currently ignore the setting: #2400
