### ISSUE TITLE
App doen't find browser to show source code and other web ressources

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-android#2412]
### Actual behaviour
The app does not find a browser to show the source code under 'about' -> 'source code'. Same issue for 'Changelog (Änderungsprotokoll)', 'Report an Issue (Einen Fehler melden)' and 'Licence (Lizenz)' and all entries unter 'openHAB-Community'.

I do have the newest version of Google Chrome installed and set to my default browser. Furthermore Github is installed as well.
![Screenshot_20210129-120931](https://user-images.githubusercontent.com/45742226/106268816-e8931080-622b-11eb-8770-cffea8bb9a1c.jpg)

### Expected behaviour
Open Chrome or even better github

#### Client
* Android version: Android 11
* Device model: OnePlus 7 T Pro, HD1913
* App version : 2.15.25
* Build flavor : Full
* Device language: German

#### App log
[log.txt](https://github.com/openhab/openhab-android/files/5893497/log.txt)

**Comment by mueller-ma** [comment]
That's strange. Do links in other apps work?
I opened a PR to increase the logging here: #2413

**Comment by Trysupe** [comment]
> That's strange. Do links in other apps work?
Yes.
For example I opened the automatic mail from github and clicked on the link. Opened Github just as expected. All other links from other apps open as well

I just installed and tried the same thing in the not beta App (v2.5.10) and the issue does not appear there.

**Comment by mueller-ma** [comment]
Can you try to re-install the beta version?

**Comment by Trysupe** [comment]
Tried it. Doesn't help. Same error Message

**Comment by mueller-ma** [comment]
Did you turn on developer settings on your device or have any developer apps installed?

**Comment by Trysupe** [comment]
Indeed I do have developer setting enable. However the only thing I changed there are the window animation speeds:
![Screenshot_20210129-155629.jpg](https://user-images.githubusercontent.com/45742226/106290276-90b7d200-624a-11eb-9d24-943707c454fe.jpg)

Everything else is set to default.
I disabled the developer settings and tried again but with no luck.

**Comment by mueller-ma** [comment]
Ok, let's wait for #2413 being merged and released.

**Comment by maniac103** [comment]
The added log line seems a bit superfluous, since the intent is known (we construct it): action=ACTION_VIEW, data=<given URI>

The interesting question is why it can't be resolved. My guess is us missing an intent category (maybe CATEGORY_MAIN?)

**Comment by mueller-ma** [comment]
> The added log line seems a bit superfluous, since the intent is known 

I just wanted to make sure that the intent is correct.

I think I found the issue: https://developer.android.com/training/basics/intents/package-visibility
The beta version targets the latest API, the stable version not.

**Comment by maniac103** [comment]
Makes sense (as does your commit); adding CATEGORY_BROWSABLE seems like a good idea nevertheless though.

**Comment by Trysupe** [comment]
> Ok, let's wait for #2413 being merged and released.

I just downloaded v2.5.27 from the Play Store. Is #2413 already in this version?

**Comment by mueller-ma** [comment]
Yes, it is, but we already found the issue: #2417.

**Comment by mueller-ma** [comment]
@Trysupe Can you try 2.15.30-beta when it's available in the Play Store for you?

**Comment by Trysupe** [comment]
Sure. I'll keep you up to date

**Comment by Trysupe** [comment]
I downloaded the apk from the releases page directly. Installed it. Worked. All links do work now 👍🏻
