### ISSUE TITLE
Voice command support for OH2

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-android#242]
So far, voice commands are sent to an hard-coded String item "VoiceCommand".

OH2 now has a dedicated voice handling infrastructure and offers a rest endpoint for it (starting with OH2 distro 519).
HABDroid should be adapted to use this new endpoint, if it is available; otherwise it can use the current logic as a fallback.

Here is the documentation of the new endpoint:

<img width="973" alt="screen shot 2016-10-08 at 11 28 15" src="https://cloud.githubusercontent.com/assets/3244965/19212088/5de0693e-8d4a-11e6-80fd-897ad963d9f5.png">

**Comment by vorburger** [comment]
+1 - this sounds like a GREAT idea... ;-)

**Comment by lolodomo** [comment]
@kaikreuzer : if I understand, the UI will not choose the interpreter and the server will systematically use the default interpreter ?
But in the real life, I would like to be able from HABdroid to trigger either the Built-in interpreter for standard commands and of course the rule-based interpreter for my user specific commands.
Does it mean that the server should call all HLI when a REST request is received from HABdroid ?

**Comment by lolodomo** [comment]
For my use case, maybe the solution would be that my default HLI is set to "Rule-based interpreter"; HABdroid will request the rule-based interpreter; the rule-based interpreter will then set my item VoiceCommand and so trigger my rule; then in my rule, I could first call the built-in interpreter; if the built-in interpreter is not able to interpret my command, I will continue with my specific code in rule.
All this means we need in rules to be able to call interpret() specifying what HLI to be used and be able to check the result of interpret call.
@kaikreuzer : is it how you think ?

**Comment by kaikreuzer** [comment]
My idea was to simple migrate what is currently there to the new REST endpoints. There is no mechanism in HABDroid to choose different interpreters for different use cases and it would probably require quite some UI work to do this in some nice way.
I think for now it is ok if the app does not choose a specific hli, but uses the one specified on the runtime as the default. And yes, this leaves you the possibility to code any stuff you like within rules.

**Comment by lolodomo** [comment]
Ok for me with the change to implement in HABdroid that will just trigger the default HLI of the server.
