### ISSUE TITLE
App is not compliant with Google Play Policies 

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2438]
I had to record a video of how and when the app asks for location permissions. After a review by Google I got the following mail:

> Prominent disclosure not found
Your app must display a prominent disclosure through a pop-up alert before your app’s location runtime permission. Based on our review, a prominent disclosure did not appear before the runtime permission.
>
> Please add a prominent disclosure before the runtime permission.
>
> Remember, your prominent disclosure must:
>
> * Appear before your app’s location runtime permission.
>* Include at least the following sentence, adapted to include all the relevant features requesting access to location in the background in the app that are readily visible to the user: “This app collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use.” If you extend permitted usage to ads, please also include: “This data is also used to provide ads/support advertising/support ads.”
> * Include any other details necessary to make it clear to the user how and why you are using location in the background. While additional content is permitted, it should not cause the required content to not be immediately visible.

**Comment by mueller-ma** [comment]
Until this has been resolved all updates in the Play Store are on hold.

**Comment by maniac103** [comment]
@mueller-ma Isn't 2.16.6 supposed to appear in the Play Store, since it includes the fix for this issue? It looks like the latest version available for me still is 2.15.30.

**Comment by mueller-ma** [comment]
I just uploaded 2.16.6-beta together with a new video where the new permission request is shown. Let's see if that's enough.

**Comment by mueller-ma** [comment]
Both apps versions have been approved.
