### ISSUE TITLE
Asking for too many permissions, looking scary

### ISSUE THREAD

**Issue by vorburger** [openhab/openhab-android#244]
Love this app - tx for the great work! One small feedback:

On first install, I was reluctant due to what to appears to be too many system permissions requested:

![Screenshot of openHAB Android App Permissions](http://drive.google.com/uc?export=view&id=1KjM29-oDGLDRXVS00SGC7yHuWt_tk52vEw)

I really don't want to share which apps I'm running, my browsing history, and bookmarks with you! ;-)

I guess this is a little more complicated than just a PR against https://github.com/openhab/openhab.android/blob/master/mobile/src/main/AndroidManifest.xml to remove <uses-permission android:name für READ_LOGS & GET_TASKS ? There is certainly a reason why you have them in there.. probably because of some Crash Detector you're using it? Perhaps that thing, whatever it is, could be made to use optional temporarily user granted permissions somehow, if there is a such a thing in Android now?

Re. READ_LOGS it says on https://developer.android.com/reference/android/Manifest.permission.html it's "Not for use by third-party applications, because Log entries can contain the user's private information." 

Re. GET_TASKS it says "This constant was deprecated in API level 21. No longer enforced." ..

Re. READ_HISTORY_BOOKMARKS interestingly that permission, which I assume is what would cause the screenshot above, doens't even appear in your current latest AndroidManifest.xml, so I'm not sure what's going on there.
##

**Comment by mkotsbak** [comment]
Well, you could read the source code what it uses the permissions for.

**Comment by fat-tire** [comment]
Im curious what the location permission is for.  I removed it and didn't get any warnings and nothing from lint either.

**Comment by FlorianSW** [comment]
I think location is really unused. It was added in commit f2968a83186099552677588e1c31d22c4fa0876e, but I couldn't find any code, that uses this permission in this commit or in current master. I'll open a PR to remove the permission, we can re-add it later, if we want to (probably only requesting it, if the feature, which needs it, is used).
