### ISSUE TITLE
API Token Authorization Header not being sent

### ISSUE THREAD

**Issue by pauljdehmer** [openhab/openhab-android#2449]
Having an issue with an openHAB 3 server and using API Token authentication in the android app.

I setup a server in the app using "remote server url", set my API Token as the username, and leave the password field blank... watching logs of requests sent to my openhab server, there is no "Authorization" header sent in any of the requests, so it returns a 401 and i see the "Authentication Failed" message on my screen.

If I set a dummy password, I can see the "Authorization" header being sent with the request, but the request is rejected with a 401 as API Token authentication requires the password to be blank.

The help text says to "leave the password field empty" but that seems to cause the "Authorization" field not to be sent at all. Is anyone else experiencing this?

**Comment by pauljdehmer** [comment]
Looks like this line:

https://github.com/openhab/openhab-android/blob/1d165d913b70a6a36b3c8b234121cc75fd4616a4/mobile/src/main/java/org/openhab/habdroid/model/ServerConfiguration.kt#L37

allows the password to be empty if the username is over 50 character and includes the Authorization header, but this line:

https://github.com/openhab/openhab-android/blob/94b81689cfb3d7c55312a2850c1c5081751748b2/mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt#L46

doesnt include that check, and so it's not sending the Authorization header.

I hacked together a build that changed that line in HttpClient.kt and forced it to set some static credentials, and i was able to connect to my server so that seems to be where the issue is. 

I'll take a stab at getting a PR together, but i'm not really an android developer, so we'll see how that goes ¯\_(ツ)_/¯

**Comment by mueller-ma** [comment]
Yes, you're right. I didn't think about this when adding the hint for the API token. You can open a PR if you want, but I could do it as well.

**Comment by mueller-ma** [comment]
Can you try the latest beta by downloading it from the GitHub releases page?

**Comment by pauljdehmer** [comment]
Just tried it. It's working. Thanks.

**Comment by dastrix80** [comment]
Has this been published to the Google Store?

**Comment by mueller-ma** [comment]
The fix is included in 2.18.0 which is live in Play Store. 20% of all openHAB users received the update to 2.19.0. Maybe it introduced a regression?
Can you check your version and open a new issue?
