### ISSUE TITLE
SSL Client Certificate setting lost after changing WLAN

### ISSUE THREAD

**Issue by Jogobo** [openhab/openhab-android#2452]
### Actual behaviour
I'm on version 2.16.0 and I use openHAB behind an Apache reverse proxy. When connecting to openHAB from outside my local network I use a client certificate to access openHAB behind https. Every time I connect to a different WLAN the SSL client certificate setting is lost and I have to choose the certificate again in the settings. 
Sometimes the connection works though SSL client certificate says "none".

### Expected behaviour
The setting should be permanent as before

 
### Steps to reproduce
1. Disable WLAN
2. Enable WLAN again an wait until connection is established
3. Open openHAB on Android. No remote connection because the SSL certificate is missing in the settings.

#### Client
* Android version: 11
* Device model: Google Pixel 3a
* App version : 2.16.0
* Build flavor : Full
* Device language: German

#### Server
* Server version: 2.5.9
* Reverse Proxy: Apache 2.4
* Authentication method : SSL Client Certificate

**Comment by mueller-ma** [comment]
Do you have more than one server configured?

**Comment by Jogobo** [comment]
A local and a remote server, but under the same server entry in the settings. Same as in the older App versions.

**Comment by mueller-ma** [comment]
Did you enter a Wi-Fi name for this server?

**Comment by Jogobo** [comment]
No, I made the same settings as with the previous version of the App.

**Comment by mueller-ma** [comment]
I added some logging: #2481
After that PR has been merged and a new version has been released, I can have a look at the log of your device.

**Comment by mueller-ma** [comment]
Can you try it again in 2.16.9-beta and share the log?

**Comment by Jogobo** [comment]
I tested 2.16.9-beta. App starts with message "network not available" (translated from German "Kein Netzwerk verfügbar"). First log is using 4G, the second after switching from 4G to WLAN. After a short time sitemap is loaded without reconfiguring the server connection. If you open the menu in the app and go to settings while "network not available" is shown not client certificate is configured.

[Test1.txt](https://github.com/openhab/openhab-android/files/6180921/Test1.txt)
[Test2.txt](https://github.com/openhab/openhab-android/files/6180917/Test2.txt)

**Comment by mueller-ma** [comment]
All preference loading operations load a client cert called `openHAB`. There's also no connection issue except one where no network is available.

**Comment by mueller-ma** [comment]
Can you clear the log, change connection and post the log here with version 2.16.15-beta?

**Comment by mueller-ma** [comment]
Please reopen if the issue re-appears in https://github.com/openhab/openhab-android/releases/tag/2.17.2-beta.
