### ISSUE TITLE
App draws buffer on top of the first visible frame

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-android#2455]
The App draws little spaces (buffers) between the frames to differentiate them. So far so good
### Actual behaviour
However the app draws them between all frames and on top of the first one. I think it would look nicer if there would be no buffer on top of the first visible frame. Consequently the top bar (where the sitemap name is written) would line up with the first frame.

I've marked red what should disappear:
![Screenshot_20210213-174657](https://user-images.githubusercontent.com/45742226/107855603-b97fc000-6e23-11eb-9a1e-285c20f3c798.jpg)

I made a quick sketch and I think it looks way better:
![Screenshot_20210213-175014](https://user-images.githubusercontent.com/45742226/107855713-30b55400-6e24-11eb-82c2-8799dd6ecc3c.jpg)

#### Client
* Android version: 11
* Device model: OnePlus 7T Pro
* App version : 2.16.5-beta
* Build flavor : Full
* Device language: GER

**Comment by maniac103** [comment]
This may be a regression. 2.15.30 does not show the 'space' for the first frame, at least not for me.

**Comment by maniac103** [comment]
There is in fact code for specifically handling this case: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt#L205

However ... do you by any chance have an invisible frame before the 'Licht' one in your sitemap?

**Comment by Trysupe** [comment]
> However ... do you by any chance have an invisible frame before the 'Licht' one in your sitemap?

yes. I do. I have a first frame which most of the time doesn't show anything because of `visibility` contraints.

```
sitemap smartphone label="Felix"
{
    Frame
    {
        Text item=Netzwerk_DLANStatus label="DLAN muss wiederhergestellt werden" visibility=[Netzwerk_DLANStatus==OFF]
        Text item=System_Updates_OpenHAB label="OpenHAB Update verfügbar" visibility=[System_Updates_OpenHAB!="OFF"]
        Text item=Wecker_Formatiert visibility=[Wecker_Gestellt==ON]
    }

    Frame label="Licht"
    {
        Switch item=Licht_Alle label="Alle" mappings=[OFF="AUS", ON="AN"] icon=lightbulb
        Text label="Milights" icon=lightbulb visibility=[Netzwerk_MilightBridge1_Online==ON]
...
```
This is also the case in the screenshot provided above. None of the items are visible.

----


I recently opened an issue which might interact with this: [Issue](https://github.com/openhab/openhab-android/issues/2445) and [PR](https://github.com/openhab/openhab-android/pull/2447).
This issue is about frames not supposed to be shown when all of their children are invisible. 

----

So there is a check `if first frame, then don't draw the buffer`, right? I think this has to be changed to `if the first *visible* frame, then don't draw the buffer`. Because like it is now it checks for the first frame, however since the first frame is invisible the buffer should be invisible for the second frame as well

**Comment by maniac103** [comment]
> So there is a check if first frame, then don't draw the buffer, right? I think this has to be changed to if the first *visible* frame, then don't draw the buffer.

Yes, and yes ;-)

**Comment by Trysupe** [comment]
Okay. I'm afraid that I can't implement this. I don't have any kotlin knowledge whatsoever ^^

**Comment by mueller-ma** [comment]
I can give it a try.
