### ISSUE TITLE
Allow more color options

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-android#2456]
### Is your feature request related to a problem? Please describe.
I think it'd be nice to have more color options for the app. Currently there are only three ones:

A washed out blue. A kinda black and white themed grey and the (in my opinion) only viable option: the openHAB orange. I'd like to have more options to customize the app .

### Describe the solution you'd like
I like the color choosing dialog of ["Business Calendar 2"](https://play.google.com/store/apps/details?id=com.appgenix.bizcal&hl=de&gl=US). Here are some screenshots:
![Screenshot_20210213-174200](https://user-images.githubusercontent.com/45742226/107855823-f6988200-6e24-11eb-8186-fcf152f12279.jpg)
By clicking on "Individuelle Farbe auswählen" you can choose your own color:
![Screenshot_20210213-174202](https://user-images.githubusercontent.com/45742226/107855832-0b751580-6e25-11eb-8859-6b649089e1ba.jpg)

Maybe we could orientate the design of the openHAB App on the one of Business Calendar 2

I think this enhancement should do a great visual improvement to the app

**Comment by Trysupe** [comment]
I've noticed there are already some colors defined in the source code of the app. Maybe we could just make all of those available:

```
#b23939 <!-- maroon => use brighter maroon -->
#ff0000 <!-- red -->
#ffa500 <!-- orange -->
#808000 <!-- olive -->
#ffff00 <!-- yellow -->
#ce93d8 <!-- purple => use material purple 200 -->
#ff00ff <!-- fuchsia -->
#ffc0cb <!-- pink -->
#ffffff <!-- white -->
#00ff00 <!-- lime -->
#4CAF50 <!-- green => use material green 500 -->
#3F51B5 <!-- navy => use material indigo 500 -->
#2196F3 <!-- blue => use material blue 500 -->
#008080 <!-- teal -->
#00ffff <!-- aqua -->
#ffffff <!-- black => use white -->
#c0c0c0 <!-- silver -->
#808080 <!-- grey -->
#daa520 <!-- gold -->
```

**Comment by maniac103** [comment]
See #1591, #1547 and #1531 for previous discussion on this topic.

**Comment by Trysupe** [comment]
Hmmm. I'm thinking about reopening #1591 since this discussion is about one and a half years old. Moreover mobile apps are more customizable than ever. Android especially but even iOS moves to are more open style. The core design and values stay the same but the users want some customization.

Just as @curlyel said:
>I aggree that it should still support the well known openHAB coloring schemes to get immediately recognized as "openHAB-related" when showcasing it in the public like at conferences etc.
>
>In the private use of openHAB, forcing the "openHAB colors" might limit the use if one does not like blue/pink or even orange accent colors on their Android wall tablet/desk phone/etc. ;-)

**Comment by maniac103** [comment]
That discussion may be a year old, but AFAICT nothing has changed in the Android app landscape since then. Can you name any app affiliated to a larger project or company that allows theme color customization? Additionally, the 'need an external library for free customization, and the less external libraries the better' argument also still stands.

**Comment by mueller-ma** [comment]
The current themes we have are one that uses the openHAB orange, one looks like Basic UI and one is the successor from the old dark theme of the app. I agree with @maniac103 and wouldn't add a color picker (anymore).

I did see a change in how apps look: A few apps moved from "app bar in primary color" to "app bar in black/white based on theme", e.g. Google apps and Signal. This could be done for openHAB as well and replace the grey theme, I guess.

**Comment by Trysupe** [comment]
> Can you name any app affiliated to a larger project or company that allows theme color customization?

I guess the google calendar app where you can choose a specific color for calendars:
![Screenshot_20210214-123354](https://user-images.githubusercontent.com/45742226/107875603-3745d900-6ec1-11eb-8c25-628e9693f9a2.jpg)

-----

What if we don't add a color picker but instead just add some more predefined colors? This way there is no need for more external libraries. This is (IMO) the best of both worlds

**Comment by maniac103** [comment]
> I guess the google calendar app where you can choose a specific color for calendars

Not a good example. Thus selection allows selecting the color used for the appointments in the calendar view, the main theme colors can not be changed.

**Comment by maniac103** [comment]
> What if we don't add a color picker but instead just add some more predefined colors?

Do you have any concrete colors in mind *that have any relationship to the openHAB project*?

**Comment by Trysupe** [comment]
> Not a good example. Thus selection allows selecting the color used for the appointments in the calendar view, the main theme colors can not be changed.

You're right. I too can't come up with an app that lets the user change to theme off the top of my head.

-----



> that have any relationship to the openHAB project

with this constraint: no. I guess the only color that has *a relationship* to openHAB is the iconic orange #e64a19.

If all colors *have to have* a relationship to the openhab project then I guess we're limited to the existing three
