### ISSUE TITLE
Unable to swipe-to-refresh if first item is hidden

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2461]
### Actual behaviour
I have a hidden frame as first item (basically the same that caused #2455). Swipe-to-refresh isn't possible.

### Expected behaviour
Swipe-to-refresh is always possible.

**Comment by Trysupe** [comment]
> I have a hidden frame as first item (basically the same that caused #2455). Swipe-to-refresh isn't possible.


I also do have this issue
