### ISSUE TITLE
Choose own page for opening as default in OH3 instead of the default Overview Page

### ISSUE THREAD

**Issue by goofy1988** [openhab/openhab-android#2472]
Hello,

it would be nice to be able to choose wich page should be opened as default in the OH3 UI with the app. The originl overview page is too restricted. It would be nice to choose wich page should be openened for default. That way it would be possible just to use my own page as default page.

Thanks alot for this great app wich let me stick with Openhab

**Comment by mueller-ma** [comment]
I'd implement this similar to #2289, so as an shortcut option.
