### ISSUE TITLE
Help porting Rule to OH3

### ISSUE THREAD

**Issue by elcosomalo1** [openhab/openhab-android#2477]
### Actual behaviour
There is no information anywhere on how to port the OH2 Rule to OH3 apart from some vague pieces, no tutorial.
Is there a way to port the Alarm rule to OH3  using the new UI?  The code cannot simply be pasted into it since OH3 doesn't recognize it (doesn't save it). 

### Expected behaviour
To be able to port the Rule for the alarm used by the app (the example rule) to OH3

 
### Steps to reproduce
1. Chequed forums, and readme. No info or tutorials.

#### Client
* Android version:  Android 10
* Device model:  Samsung Note 10
* App version : 2.16.0
* Build flavor : 
* Device language:  Spanish

**Comment by elcosomalo1** [comment]
Went back into using text files and gave up on the modern UI. 
Still the rule is not working on OH3 for me, after copy-pasting from the latest version here in the hub.
Item was updated acordingly.
Help would be apreciated.

**Comment by mueller-ma** [comment]
I see you already asked at https://community.openhab.org/t/alarmclock-doesn-t-fire/87202/29. I'll answer there.
