### ISSUE TITLE
More than one discoverable server leads to requests to other server

### ISSUE THREAD

**Issue by watou** [openhab/openhab-android#248]
I have a 1.8.3 server on an RPi2 and a 2.0 nightly server on Mac.  When opening client to 1.8.3 server, I receive a few "HTTP Error: Unacceptable" popups and dismiss them.  When going to see charts on my 1.8.3 server, the 2.0 server's log reports "Illegal argument in chart: No Persistence service found."  So it appears that the client is addressing multiple servers, when obviously the user is trying to address just one server at a time.

**Comment by mueller-ma** [comment]
Did you enter the URL manually in the settings?
I have entered my productive oh server, but also running a night oh and it never sends requests to the nightly.
