### ISSUE TITLE
Automatically set alarm from openHAB item

### ISSUE THREAD

**Issue by LinqLover** [openhab/openhab-android#2480]
### Is your feature request related to a problem? Please describe.

For several automation projects, it would be helpful if the app could automatically set my phone's alarm whenever a certain openHAB item is changed. This would complement the existing alarm time sync which only sends updates to the server so far.

### Describe the solution you'd like. A clear and concise description of what you want to happen.

In the settings, the user could be allowed to enter a second optional item name for the "remote alarm time" (or however you name it). We could also reuse the existing item name for both directions of the sync and add a checkbox to turn on the pull direction. However, the first approach would be more powerful. Not sure about the details. :-)

### Describe alternatives you've considered

Tasker is probably able to do this, too. However, it requires a complex setup and is not free to use.

**Comment by mueller-ma** [comment]
Sending information server -> client are hard to implement, because it would require a permanent connection (wastes battery) or something like FCM. For the same reason widgets cannot show the current status of items or the Tasker plugin can react on item changes.
