### ISSUE TITLE
Publish app as Android App Bundle

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2496]
I'd like to publish this app as Android App Bundle to the Play Store to reduce the installation size. This requires Play App Signing to be active, but I'm not allowed to accept its TOS.

@kaikreuzer @digitaldan Can you accept it?
- Go to https://play.google.com/console/developers/7475306295333689578/app/4975171322762979862/keymanagement
- Select "Export and upload a key from Android Studio"
- Upload any file, e.g. empty txt file
- Click on save
- Accept TOS

**Comment by kaikreuzer** [comment]
@mueller-ma Done!

**Comment by mueller-ma** [comment]
Thanks. The beta versions are now published as App Bundle: https://github.com/openhab/openhab-android/releases/tag/2.16.13-beta
