### ISSUE TITLE
Remote connection not work

### ISSUE THREAD

**Issue by nurgaleevarman** [openhab/openhab-android#250]
Openhab 1.8.3 server with external security and user auth.
https port 32769
I have a static ip and configure roter to port forwarding.

Mobile app cant connect from Openhab app  to Server with remote url.
`https://xxx.xxx.xxx.xxx:32769`

From web browser in smartphone sitemap open correctly 
`https://xxx.xxx.xxx.xxx:32769/openhab.app?sitemap=SmartHome`

The router monitor does not show the any connection from internet when Openhab app try connect to remote url.

But monitor show connection when i connect to openhab server from web broswer.

Also I try simple openhab server configuration with 1 items and 1 sitemap, but mobile openhab app have not connect to remote url

I test it with android 4, 5, 6. Only browser openhab is work

**Comment by HerrBerg** [comment]
I'm seeing the same issue:

The problem is, that Openhab Android does not honor the `https` set in the remote-url setting for requesting sitemaps.
Even though that the remote url is set to something like `https://example.com` the sitemap requests are made against `http://example.com/rest/sitemaps/debug/debug`.

In my case this returns a `301` redirect to the https url but which doesn't work either.

**Comment by HerrBerg** [comment]
Looking at the andoid logs reveals the problem:
the first request for the list of sitemaps goes to the correct url, but the list returned by the api does not only return the names of the sitemaps but also links to them. These links have the wrong scheme.

```
D OpenHABMainActivity: onCreate()
D OpenHABMainActivity: App version = 1.8.0.5
I MemorizingTrustManager: getAppKeyStore(/data/user/0/org.openhab.habdroid/app_KeyStore/KeyStore.bks) - file does not exist
I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
D OpenHABMainActivity: Remote URL https://openhab.example.comis not a openhab domain, no GCM registration will be made
D OpenHABMainActivity: Intent != null
D OpenHABMainActivity: Intent action = android.intent.action.MAIN
D OpenHABMainActivity: onResume()
D OpenHABTracker: Connecting to remote URL https://openhab.example.com/
D MemorizingTrustManager: checkCertTrusted([Lcom.android.org.conscrypt.OpenSSLX509Certificate;@b63a114, ECDHE_RSA, true)
D MemorizingTrustManager: checkCertTrusted: trying appTrustManager
D MemorizingTrustManager: checkCertTrusted: trying defaultTrustManager
V AsyncHttpRH: Progress 1844 from 1844 (100%)
D OpenHABMainActivity: openHAB version 2
D OpenHABMainActivity: Loading sitemap list from https://openhab.example.com/rest/sitemaps
V AsyncHttpRH: Progress 661 from 661 (100%)
D OpenHABMainActivity: [{"name":"debug","label":"Debug sweet home","link":"http://openhab.example.com/rest/sitemaps/debug","homepage":{"link":"http://openhab.example.com/rest/sitemaps/debug/debug"
,"leaf":false,"widgets":[]}},{"name":"example","label":"Home sweet home","link":"http://openhab.example.com/rest/sitemaps/example","homepage":{"link":"http://openhab.example.com/rest/sitemaps/example/example
","leaf":false,"widgets":[]}},{"name":"_default","label":"Home","link":"http://openhab.example.com/rest/sitemaps/_default","homepage":{"link":"http://openhab.example.com/rest/sitemaps/_default/_default","leaf":false,"widgets":[
]}}]
D OpenHABMainActivity: [{"name":"debug","label":"Debug sweet home","link":"http:\/\/openhab.example.com\/rest\/sitemaps\/debug","homepage":{"link":"http:\/\/openhab.example.com\/rest\/sitemaps\/de
bug\/debug","leaf":false,"widgets":[]}},{"name":"example","label":"Home sweet home","link":"http:\/\/openhab.example.com\/rest\/sitemaps\/example","homepage":{"link":"http:\/\/openhab.example.com\/rest\/sitemaps\/scha
rrenberg\/example","leaf":false,"widgets":[]}},{"name":"_default","label":"Home","link":"http:\/\/openhab.example.com\/rest\/sitemaps\/_default","homepage":{"link":"http:\/\/openhab.example.com\/rest\/sitemaps\/_default\/_
default","leaf":false,"widgets":[]}}]
D OpenHABMainActivity: Configured sitemap is on the list
I OpenHABMainActivity: Opening sitemap at http://openhab.example.com/rest/sitemaps/example/example
D OpenHABFragmentPagerAdapter: openPage(http://openhab.example.com/rest/sitemaps/example/example)
D OpenHABWidgetListFragment: withPage(http://openhab.example.com/rest/sitemaps/example/example)
D OpenHABFragmentPagerAdapter: getItem(0)
...
```

In my case it was a missing header in the reverse-proxy configuration of the nginx
```proxy_set_header X-Forwarded-Proto    $scheme;```
which can now be found in the docs at http://docs.openhab.org/installation/security.html

with this header set it's now working for me.

@nurgaleevarman do you have a reverse-proxy too? For handling the ssl certificates?

**Comment by mueller-ma** [comment]
@nurgaleevarman Do you still have issues with remote connection?

**Comment by Mike-ML** [comment]
Because of the issues with the app, I'm not using the openhab android app
anymore. I've used the browser interface for some time. But now I have
disabled DynDNS, because of security concers. Next month I will setup VPN
and then I will see, if I will use the app or the web interface.

Best regards,
Michael

2017-12-05 21:24 GMT+01:00 mueller-ma <notifications@github.com>:

**Comment by mueller-ma** [comment]
@kaikreuzer Should the app support remote connections apart from openhab cloud?

**Comment by kaikreuzer** [comment]
Definitely yes, and it always did. That's why the remote url was configurable and not statically set to myopenhab.org.
We don't have to support GCM for notifications other than through myopenhab.org, tough (as this imho has to be baked into the app).

**Comment by mueller-ma** [comment]
> We don't have to support GCM for notifications other than through myopenhab.org, tough (as this imho has to be baked into the app).

What if someone wants to setup its own openhab cloud?

**Comment by maniac103** [comment]
AFAICT the notification registration happens via the app fetching a sender ID from the server, using that for GCM registration, and passing the registration ID to the server again. Did I understand that correctly (and/or is there documentation on the OpenHAB GCM flow)? If yes, I don't see why GCM wouldn't work with any server instance.

**Comment by kaikreuzer** [comment]
I'm no expert on GCM at all, you probably know it much better than I do. If it is easy for the app to register for notifications on any remote server, even better. Otherwise I would say, whoever sets up his personal openhab-cloud is probably also able to build his own custom app.

**Comment by mueller-ma** [comment]
It is possible to use GCM on his own openhab cloud: https://github.com/openhab/openhab.android/pull/288

But this issue is about a non-cloud remote server (which is in fact the local server with dyndns and portforwarding). The local server doesnt support GCM.

**Comment by kaikreuzer** [comment]
Yes, understood, and this is the situation for which I gave my answer above:

> Definitely yes, and it always did. That's why the remote url was configurable and not statically set to myopenhab.org.

I used the Android app in the past with a dyndns entry and no openhab-cloud being involved.

**Comment by dastrix80** [comment]
I have the same issue with the app using a local instance of openhab cloud. I can see the sitemaps visible as  a list in the app, but I just get the egg timer when trying to load them remotely.

The web browser access works just fine

Any help would be great!

**Comment by begleysm** [comment]
Same symptoms as dastrix80.  I have an Apache2 Reverse Proxy Server that acts as a go-between between the outside world and the OpenHAB server.  The outside world address (& Apache2 Server) uses HTTPS.  The OpenHAB server behind the LAN doesn't.

I can access the OpenHAB page on the LAN, with a web browser, at http://LANOpenHAB:8080
I can access the OpenHAB page remotely, with a web browser, at https://MyGenericServer.net/hab
I can access the OpenHAB site on the LAN, with the Android App, at http://LANOpenHAB:8080
I CANNOT access the OpenHAB site remotely, with the Android App, at https://MyGenericServer.net/hab

**Comment by mueller-ma** [comment]
Can you access "mygenericserver.net" from inside your lan?

**Comment by maniac103** [comment]
I thought the root cause was already pinpointed in https://github.com/openhab/openhab-android/issues/250#issuecomment-281649942 ?
In any case, the web server access log would be interesting.

**Comment by mueller-ma** [comment]
My guess: the rest api contains full urls and that wont be rewritten by the proxy. The smartphone outside the lan then tries fetch the sitemaps via the internal urls.

**Comment by begleysm** [comment]
Why would the API use absolute URLs?  That seems totally inflexible and without advantage.

**Comment by begleysm** [comment]
i was able to solve my problem by following this tutorial (https://community.openhab.org/t/apache2-reverse-proxy-with-ldap-authentication-https-and-url-path-prefix/25867/8).

Basically he had all the rewrite/substitution rules necessary and I was/am too much of a newb to figure that stuff out on my own at this stage.

**Comment by mueller-ma** [comment]
@kaikreuzer Should the absolute urls in the rest api be changed to relative ones to avoid such rewrite rules in the proxy and make it easier to setup a proxy?
