### ISSUE TITLE
Add support for HTML notification styling (or other markup language) notification styling

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-android#2513]
Would it be possible to add HTML styling for notifications? I can think of other markup languages too.

I like to add some colors or font modifications to my messages sent to my Android device. Due to limitations with notifications on mobile platforms, a restricted set of supported styling elements would be sufficient. e.g.

- `<b>word</b>` - display **word** in bold
- `<i>word</i>` - display _word_ in italics
- `<font color="#0000ff">word</font>` - display <font color="#0000ff">word</font> in blue text
- `<a href="https://example.com/">word</a>` - display [word](https://example.com/)  as a tappable link to `https://example.com/`

**Comment by mueller-ma** [comment]
I think this should be discussed at the openhab-cloud repo first. Can you create an issue there and poke the android-maintainers and ios-maintainers groups?

> display word as a tappable link 

I haven't seen a tappable link in the text of a notification so far. IMO this should be implemented as notification action on Android: https://developer.android.com/guide/topics/ui/notifiers/notifications#Actions
