### ISSUE TITLE
Notifications are unavailable: Remote server isn't an openHAB cloud instance

### ISSUE THREAD

**Issue by niwla23** [openhab/openhab-android#2522]
### Actual behaviour
In the settings I see this error:
Notifications are unavailable: Remote server isn\'t an openHAB cloud instance
Notifications are really not working. I use the public openhab cloud instance and it works for remote access.

### Expected behaviour
There should be no error and I should receive notifications

 
### Steps to reproduce
1. Add a Server with remote openhab

### Can you reproduce the issue in demo mode?
no

#### Client
* Android version: 11
* Device model: OnePlus Nord
* App version : 2.16.0
* Build flavor : Full
* Device language: de

#### Server
* Server version: 3.0.1
* Reverse Proxy: none
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: 
* openHAB Cloud version : 
* Authentication method :  user and password

#### App log
https://hatebin.com/sjqqzlckwz

**Comment by mueller-ma** [comment]
It seems that the app may not log on your device. There are only logs of the OS regarding openHAB, that don't display enough information.
Can you capture a log via ADB?

**Comment by niwla23** [comment]
Can you give me a filter for logcat? I am not into adb that much but I know it produces many bullshit messages....

**Comment by niwla23** [comment]
I just figured out that it works if you set openhab cloud to "Only Notifications". It only breaks if you set it to both.

![grafik](https://user-images.githubusercontent.com/46248939/115613047-3b8cd900-a2ec-11eb-9f64-df71bc228220.png)

**Comment by niwla23** [comment]
okay so this doesn't actually work, but gives no error most of the time. However after a few minutes the error is there again and push notitifacions are working at no point of time.

**Comment by mueller-ma** [comment]
> Can you give me a filter for logcat? I am not into adb that much but I know it produces many bullshit messages....

This seems to be a good answer: https://stackoverflow.com/a/9869609
Package name is `org.openhab.habdroid` (for stable) and `org.openhab.habdroid.beta` (for beta).

**Comment by mueller-ma** [comment]
What exactly did you enter as remote host?

**Comment by mueller-ma** [comment]
Please reopen if you have set the remote url to `myopenhab.org`, not `home.myopenhab.org`. The latest beta shows a warning in this case.
