### ISSUE TITLE
Consistent item heights - Screenshot included

### ISSUE THREAD

**Issue by anonymous-one** [openhab/openhab-android#2529]
Before I begin just want to say thank you for everyone involved in bringing this app to life. I have been using it for years, and thanks to all those involved it just keeps getting better.

This is a small cosmetic change. Perhaps this is somehow related to my setup, although I doubt it.

I have noticed that switch items have a different height than text or other items.

I have included a screenshot that shows what I am talking about quite clearly.

Any way we could get all items to have a consistent height, would look a little bit better :)

Final note : Although probably unrelated, I am running OpenHAB 1.8.3... I know I know... But it works great for me, and I have hundreds of rules that I have been adding over the years and hundreds of items...

Thanks!
![Screenshot_20210420-113610_openHAB](https://user-images.githubusercontent.com/4963653/115374577-46048100-a1cd-11eb-90ed-ad9b7a81ba29.jpg)

**Comment by mueller-ma** [comment]
Thanks for the report, I can reproduce it with openHAB 3.
