### ISSUE TITLE
Import SSL-Certificate doesn't work

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-android#2545]
### Actual behaviour
I just came across the server settings in the OH Beta App and clicked on "SSL-Client-Zertifikat" which translates to "SSL-Client Certificate" and saw that the import doesn't work. See this screen recording:
https://user-images.githubusercontent.com/45742226/116274992-762ac180-a783-11eb-9b5c-6759da55975e.mp4

The same thing happens on my OnePlus 7T Pro:

https://user-images.githubusercontent.com/45742226/116275062-8a6ebe80-a783-11eb-8182-3b0c88954ffd.mp4

### Expected behaviour
Open the file explorer

#### Client
* Android version: 11
* Device model: Samsung S21 Ultra and OnePlus 7T pro (happens on both devices)
* App version : 2.16.18
* Build flavor : Full
* Device language: German

#### App log
[log.txt](https://github.com/openhab/openhab-android/files/6386020/log.txt)

**Comment by Trysupe** [comment]
Does happen in the non beta version (2.16.0) as well

**Comment by mueller-ma** [comment]
I can reproduce this on an emulator: If no key is present, the dialog is shown, but instantly closed. It logs `KeyChain: No keys to choose from`. Unfortunately this log line cannot be seen in the in-app log viewer, but over ADB with no filter at all.
I haven't found a way to ask `KeyChain` if there are any keys.

Can you make sure a client certificate is installed?

**Comment by Trysupe** [comment]
> Can you make sure a client certificate is installed?

Sadly not since I don't have one and always failed in the past when trying to create one. Unless you can provide one for me since I guess it doesn't have to be a valid one for my server

**Comment by mueller-ma** [comment]
Maybe this is helpful for you: https://community.openhab.org/t/using-nginx-reverse-proxy-for-client-certificate-authentication-start-discussion/43064

> I don't use the SSL-Certificates currently. I just noticed the feature not working while playing around with the app

In this case, I'm going to close this issue. Thanks for reporting it anyway.
