### ISSUE TITLE
[Samung] App doesn't receive sendBroadcastNotification

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-android#2547]
### Actual behaviour
The Android Beta App doesn't receive notifications from the server sent with `sendBroadcastNotification`. While the App on my OnePlus 7T Pro receives them just fine.

----

This is the code on the server:
```
rule "Testrule"
when
    Item Test_Trigger_For_Testrules received command
then
    logInfo("testrule", "testrule")
    sendBroadcastNotification("test")
end
```

While the App on the OnePlus phone receives the notification as expected my Samsung S21 Ultra stays quiet and does not receive it. 

----

At first sight I thought that the Samsung OS just puts the App to sleep however even if I am in the app as the notification should arrive nothing happens.

-----

Settings:
I compared the settings between the two phones and they are identical:

### Expected behaviour
Receive notifications

#### Client
* Android version: 11
* Device model: Samsung Galaxy S21 Ultra
* App version : 2.16.18
* Build flavor : Full
* Device language: German

#### Server
* Server version: 2.5.12
* Reverse Proxy: no
* Authentication method : None

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab.org
* openHAB Cloud version : 
* Authentication method : user and pw

#### App log
Here is the Log from my Samsung device. I can't find anything about notifications
[log-notifications.txt](https://github.com/openhab/openhab-android/files/6386084/log-notifications.txt)

Here is the Log from my OnePlus device (where the notifications work as expected)
[---------------.txt](https://github.com/openhab/openhab-android/files/6386098/---------------.txt)

where there are entries about getting the notification
`04-27 18:24:13.156 16196 11525 I okhttp.OkHttpClient: --> GET https://<openhab-remote-address-openHAB>/api/v1/settings/notifications`

**Comment by Trysupe** [comment]
Does happen in the non beta version (2.16.0) as well

**Comment by mueller-ma** [comment]
Can you check https://www.openhab.org/docs/apps/android.html#i-don-t-receive-any-notifications and https://www.openhab.org/docs/apps/android.html#my-notifications-are-delayed?

**Comment by Trysupe** [comment]
> https://www.openhab.org/docs/apps/android.html#i-don-t-receive-any-notifications

I was not able to find the "push notification status" or anything similar even after changing my phone language to english:
![Screenshot_20210427-212004_openHAB Beta](https://user-images.githubusercontent.com/45742226/116299959-99af3580-a79e-11eb-9420-d1c984f30151.jpg)

------

> https://www.openhab.org/docs/apps/android.html#my-notifications-are-delayed

I tried anything to make exceptions for the app but no luck. I added the app to the list of "not optimized apps". And even while I am in the app there are no notifications so I don't think it's an android app battery _saving_ feature which is causing this. 

May I help by giving you any further information? I am more than willing to try an apk specifically made for this with more verbose logging or anything needed =)

**Comment by mueller-ma** [comment]
The notification status is on the settings page, I'll change that: #2549

**Comment by Trysupe** [comment]
Thanks for pointing that out. It said that there was an error: I had the url for the remote access set to `https://home.myopenhab.org` instead of `https://myopenhab.org`. Changing this made it work. 
Interestingly enough showing the sitemaps and everything else in the app working with the remote access url set to `...home...`

**Comment by Lzsolo1** [comment]
sendBroadcastNotification

**Comment by mueller-ma** [comment]
home.myopenhab.org directly proxies every request to the local openHAB server and therefore the notification api isn't present at all.

**Comment by mueller-ma** [comment]
There will be a hint for this case:  #2565
