### ISSUE TITLE
[Samsung] Sending alarms to server only works partially

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-android#2548]
### Actual behaviour
Sending alarms to the server only works sometimes. Let me give you some examples. Right now it's 18:45 on 27.04.:

|Set in clock app| what the server receives human readable|state|
| ---- | ----|----| 
|Alarm today at 19:00|Alarm today at 17:00 (19:00 when correctly formatted to my timezone)|2021-04-27T17:00:00.000+0000
|Removing the alarm, next alarm on 28.04. at 07:30|Alarm today at 00:00 (in the past)|2021-04-27T22:00:00.000+0000|
|Removing the alarm on 07:30, next alarm on 29.04. 07:30|Alarm today at 00:00 (in the past)|2021-04-27T22:00:00.000+0000|
|Removing all alarms|server receives nothing|-|
|Setting an alarm for 28.04. 07:30|Alarm today at 00:00 (in the past)|2021-04-27T22:00:00.000+0000|

.... and more weird stuff.
The only thing working as expected (from my testing) is setting an alarm for today in the hours of the day that are left.

The item the information is sent to is defined as follows:
```
DateTime    Wecker_Android
```

### Expected behaviour
Send alarms correctly to the server. I never had this issue with my OnePlus 7T Pro. Sending the alarms worked flawlessly.

 
#### Client
* Android version: 11
* Device model: Samsung Galaxy S21 Ultra
* App version : 2.16.18
* Build flavor : Full
* Device language: German

#### Server
* Server version: 2.15.12
* Reverse Proxy: no
* Authentication method : None

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab
* openHAB Cloud version : 
* Authentication method : user and pw

#### App log
[android.txt](https://github.com/openhab/openhab-android/files/6386269/---------------.txt)
#### Server log
[server.txt](https://github.com/openhab/openhab-android/files/6386281/server.txt)

**Comment by Trysupe** [comment]
Does happen in the non beta version (2.16.0) as well

**Comment by Trysupe** [comment]
> The only thing working as expected (from my testing) is setting an alarm for today in the hours of the day that are left.

I did some more testing. This is what I found out
- setting an alarm in the next 16 hours and some minutes (sometimes it's 58, sometimes 56, ...(...what? why? ^^) )works and updates the item accordingly
- any other alarm further in the future sets the item to `UNDEF` and therefore no alarm

**Comment by mueller-ma** [comment]
Whenever an alarm time is sent there should be a log line `Alarm sent by ....`. Can you check that?
It's possible to exclude apps that send false alarms.

**Comment by Trysupe** [comment]
> Can you check that?

Yes. There are two apps sending alarms sending different values:
```
04-27 18:45:09.074  7552  7552 D BackgroundTasksManager: Alarm sent by com.sec.android.app.clockpackage
...
04-27 18:45:09.292  7552 11470 D ItemUpdateWorker: Item 'Wecker_Android' successfully updated to value 2021-04-27T17:00:00+0000

```
and
```
04-27 18:46:47.914  7552  7552 D BackgroundTasksManager: Alarm sent by com.samsung.android.calendar
...
04-27 18:46:48.091  7552  8186 D ItemUpdateWorker: Trying to update Item 'Wecker_Android' to value 2021-04-27T22:00:00+0000, was 1619560800000
```

My first assumption is that the calendar sends wrong states. A friend of mine had this issue as well: she hat to take a pill (medicine) daily and the app would show its next due time as an alarm as well.
It's probably a good idea to exclude the calendar from sending alarms however I will investigate this further in the next few days before coming to a conclusion.

-----

Would you mind setting me as the assignee for this issue to add it to my list on github. This feature isn't unlocked for me

**Comment by Trysupe** [comment]
I just created a new openHAB App log and there the package `com.android.providers.calendar` ( != `com.samsung.android.calendar`) was creating false alarms

**Comment by mueller-ma** [comment]
I think it's a good idea to ignore `com.samsung.android.calendar` anyway. `com.android.providers.calendar` is already ignored by the app. Therefore it sends `UNDEF` instead of any alarm time.

**Comment by Trysupe** [comment]
>  `com.android.providers.calendar` is already ignored by the app. Therefore it sends `UNDEF` instead of any alarm time.

But this doesn't solve the issue...? Sending UNDEF to the Server let it think there is no alarm set in the device. Imo this is just as bad as sending a wrong alarm. 

By ignoring I thought you meant there would be no value sent to the server

**Comment by mueller-ma** [comment]
The app should send the correct alarm time if it's the next event scheduled in alarm manager. Can you check that?

> By ignoring I thought you meant there would be no value sent to the server

In this case the app might not send `UNDEF` if the alarm has been canceled by the user, which is also bad.

**Comment by Trysupe** [comment]
> The app should send the correct alarm time if it's the next event scheduled in alarm manager. Can you check that?

You mean by checking using the new version `2.17.1`? Then no, since the new version doesn't install on my device. Since switching from my OnePlua 7TPro to the new Samsung Galaxy S21 Ultra I noticed I am not able to side load apks from not the Google play store...

------

> In this case the app might not send `UNDEF` if the alarm has been canceled by the user, which is also bad.

Why? Imo the calendar app should not be able to send any commands no matter whether the command is `UNDEF` or a time. The clock app should be able to send *all* commands (including `UNDEF` to cancel an alarm)

**Comment by Trysupe** [comment]
> INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package org.openhab.habdroid.beta signatures do not match previously installed version; ignoring!

Can you fix this? If not I will uninstall the existing app and reinstall the `apk`

**Comment by mueller-ma** [comment]
> Why? Imo the calendar app should not be able to send any commands no matter whether the command is UNDEF or a time. The clock app should be able to send all commands (including UNDEF to cancel an alarm)

I fully agree, however the API used here is quite limited. All we get is "The next alarm time has been set by package `foo` and is at `some unix timestamp`". From my understanding all I can do here is to ignore packages that are known to set alarm times that aren't "real" alarm times.

https://developer.android.com/reference/android/app/AlarmManager#getNextAlarmClock()


> INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package org.openhab.habdroid.beta signatures do not match previously installed version; ignoring!

It should be possible to install the APK from GitHub over the Play Store version. I'll upload the latest beta to Play later, so you can get it from there.

**Comment by Trysupe** [comment]
I am a bit confused by your two entries:
> I fully agree, however the API used here is quite limited. All we get is "The next alarm time has been set by package `foo` and is at `some unix timestamp`". From my understanding all I can do here is to ignore packages that are known to set alarm times that aren't "real" alarm times.


and 

> `com.android.providers.calendar` is already ignored by the app. Therefore it sends `UNDEF` instead of any alarm time.

Does an ignored app send an `UNDEF` or does it send nothing instead of an alarm time? Since `com.samsung.android.calendar` already [was ignored](https://github.com/mueller-ma/openhab.android/commit/1ab2186739e846d9d4f3cbf6c33761f5f8be03cd) and it still sends `UNDEF` commands as seen in [this post](https://github.com/openhab/openhab-android/issues/2548#issuecomment-842467773) I assume it ignored apps are able to send commands, right?

**Comment by mueller-ma** [comment]
> Does an ignored app send an `UNDEF`

This

When an app, that we ignore, sets the next alarm time, we cannot make any assumption about the real next alarm time and therefore the app send `UNDEF(ined)`.

**Comment by Trysupe** [comment]
okay, but why does it send anything? I think no command should be sent to the server. As seen in my example letting the calendar send an `UNDEF` to the server lets the server this there is no alarm set even though the alarm app sent its alarm which only was to be overwritten by the `UNDEF` of the calendar.

Or in other words:

> Why? Imo the calendar app should **not** be able to send **any** commands no matter whether the command is `UNDEF` or a time. The clock app should be able to send **all** commands (including `UNDEF` to cancel an alarm)
