### ISSUE TITLE
Honor refresh for fullscreen images

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#2571]
I consider this a follow-up on PR #2411 

### Is your feature request related to a problem? Please describe.
I really like the feature to display images in fullscreen in the app.
I use it to show images of the ip cams and zoom in to interesting regions when needed.
However, zooming disables the refresh which is bad for ip cams.

### Describe the solution you'd like
1. Use an widget like ```Image url="http://10.0.0.xxx/webcapture.jpg?command=snap&channel=0" refresh=1000```
2. Enjoy the every-second refreshed image stream
3. Click on the widget to get to fullscreen view
4. The app should honor the refresh interval even in fullscreen and should allow to zoom to regions of interest and still refresh the image

### Describe alternatives you've considered
Using the video widget does not (yet, #320 ) allow for fullscreen, so this is no successful route.

### Additional context
Should be clear enough already ;-)

Thank you very much for your great efforts!!! :)

**Comment by mueller-ma** [comment]
When I implemented #2411 I was afraid that the auto refresh may reset the zoom, which is probably unwanted, but I actually never tested it. I'll give it a try.

**Comment by Lzsolo1** [comment]
ខ្ញុំគិតអី្វលែងឃើញហើយ.
