### ISSUE TITLE
new fullscreen image function disables filial content

### ISSUE THREAD

**Issue by cwihne** [openhab/openhab-android#2573]
### Is your feature request related to a problem? Please describe.
When tapping an image, it is now shown fullscreen. Great feature, especially for highres images, but this prohibits access to filial page
```
Image url="..." {
Frame {
Text item=xyz
}
}
```
I my case, a single webcam image accesses a page with multiple webcams.
Such content is accessible on browser access, but not through App any more.

### Describe the solution you'd like
The tap on image conflicts on fullscreen ./. tree access. Any non-image entry with filial structure asks for tapping, so it might be consistent to allow tap for lower page, but e.g. long-press/swipe/(other event) for fullscreen.

### Describe alternatives you've considered
- Vice versa (fullscreen = tap + filial content = long-press, which seems inconsistent with non-image entries
- access filial content only from fullscreen

**Comment by mueller-ma** [comment]
The same issue should apply to charts as well, but I haven't seen a report so far. I guess that not many people use images and charts as element with children.

Maybe bind long press on images and charts to fullscreen and a short press to the subpage if present and fullscreen otherwise. For most users having to long press to access fullscreen might seem illogically, because their images don't have subpages.

**Comment by cwihne** [comment]
Although inconsistent with the web access to mainUI, I admit I appreciate the fullscreen view of both images and charts. That's why I placed this as a feature discussion. Why not investigating if more users run into this after publishing updated behaviour to release?

**Comment by mueller-ma** [comment]
Yes, that's a good point. Let's see how much feedback we get when this changes goes live: https://github.com/openhab/openhab-android/issues/549#issuecomment-835889081

**Comment by maniac103** [comment]
> Maybe bind long press on images and charts to fullscreen and a short press to the subpage if present and fullscreen otherwise.

That sounds like a decent compromise. The only alternative I can think of would be showing the right arrow when there's a subpage, and letting the arrow navigate to the subpage.

**Comment by mueller-ma** [comment]
> Why not investigating if more users run into this after publishing updated behaviour to release?

I haven't seen a single other user mentioning this issue, so IMO this issue could be closed as "won't fix".
