### ISSUE TITLE
Widgets lose titles so unable to tell them apart

### ISSUE THREAD

**Issue by watou** [openhab/openhab-android#2603]
Latest app update on 22-May-2021 identifying itself as 2.17.0 has changed widget drawing so the text they use to identify themselves has disappeared, making it impossible to distinguish one from the other.  See partial screen capture:

![Screenshot_20210523-112111](https://user-images.githubusercontent.com/3008217/119256662-b120e900-bbb9-11eb-8239-74a88d2a0c10.png)

Previous app version would overlay widget with label so user knew which was which.

On Pixel 2 running latest Android 11.

**Comment by mueller-ma** [comment]
Thanks for your report.
As a workaround you can add labels by pressing on the gear icon.
