### ISSUE TITLE
Basic UI > Custom Start-Sub-Page for faster access

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-android#2607]
### Is your feature request related to a problem? Please describe.
I feel, that accessing my customized openHAB 3 UI pages is not fast enough for everyday-use:
1. Start the App
2. Wait to connect (in my case openHAB 3 UI is configured as starting-page)
3. Push the burger menu
4. Choose my custom page (Tabbed page)
5. Start to make the settings i want to
--> High effort to just turn on the TV for example

### Describe the solution you'd like
Configure one of the "sub-pages" in openHAB 3 UI as sub-start-page
--> This way i can directly open the app and start from exactly the configured page to perfectly fit my system
--> In my opinion i could access everything much better from a page, containing tabs i configured myself (and not the default ones with location etc.)

### Describe alternatives you've considered
For sure the more clean solution could be, to already configure this sub-page in openHAB 3 UI itsself as start-page. (See linked issue below)
A configuration possibility in the android app however could have the advantage of user-individual start pages.

### Additional context
Issue, regarding more configurable start-behaviour of overview-page in WebUI
https://github.com/openhab/openhab-webui/issues/866#issue-797440213

Others also would like such a feature, see this discussion
https://community.openhab.org/t/oh-3-ui-custom-tabbed-page-on-overview/117541?u=shured

**Comment by mueller-ma** [comment]
A button for creating Android home screen shortcuts has to be added to the main UI subpages: https://github.com/openhab/openhab-android/issues/2506#issuecomment-811467659
