### ISSUE TITLE
Image elements from sitemaps not rendered if no Content-Type header

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#263]
It looks like sitemap elements of type image are ignored by HABdroid.

**Comment by watou** [comment]
HABdroid 1.8.0.5 shows images for me no problem against latest unstable and now testing 2.0 RC1 server versions.  Anything in your server logs?

**Comment by lolodomo** [comment]
I am running the last version (1.8.0.5) too.

I am testing that with my enhancement of the Sonos binding.
Here is how is defined my item:
```
Image SonosChambreAlbumArt "Album cover art" (GMusiqueChambre) {channel="sonos:PLAY5:chambre:currentalbumart"}
String SonosChambreAlbumArtUrl "Album cover art URL [%s]" (GMusiqueChambre) {channel="sonos:PLAY5:chambre:currentalbumarturl"}
```
and one part of my sitemap:
```
		Text label="Musique chambre" icon="none" {
			Image url="http://ausdroid.net/wp-content/uploads/2014/12/Sonos-Logo-640x324.jpg" item=SonosChambreAlbumArtUrl
			Text item=SonosChambreArtist visibility=[SonosChambreArtist!=""]
			Text item=SonosChambreTitle visibility=[SonosChambreTitle!=""]
			Text item=SonosChambreAlbum visibility=[SonosChambreAlbum!=""]
			Text item=SonosChambreDetails visibility=[SonosChambreDetails!=""]
			Default item=SonosChambreControl
		}
```

**Comment by lolodomo** [comment]
Nothing wrong in my server logs.

**Comment by lolodomo** [comment]
On the same Android device, album art is showing in Chrome browser using Basic UI or Classic UI.

**Comment by lolodomo** [comment]
Sonos is not providing the Content-Type header in its HTTP response and this makes HABdroid not displaying the picture.
Would it be possible to correct HABdroid to have a display of picture even when there is no Content-Type header ?

**Comment by lolodomo** [comment]
@watou : for your information, the new proxy servlet implementation has not resolved this problem.

Depending on the music service played by Sonos, HABdroid is able or not to display the image. It does not work with a tunein radio or Amazon music while it works with my local music library or Spotify.

PS: of course, it works in all cases with Basic UI and Classic UI.

**Comment by watou** [comment]
Just to confirm, your debug log says "Starting up 'Proxy (async)' servlet  at /proxy"?

Also to confirm, you observe that the only difference between images appearing in HABdroid vs. not appearing in HABdroid is whether or not the source of the image gave a `Content-Type` header?

**Comment by lolodomo** [comment]
What package should I set to DEBUG ?

I have not checked again the content-type header but did it in the past.

**Comment by watou** [comment]
The logger `org.eclipse.smarthome.ui` should do.

**Comment by lolodomo** [comment]
I confirm I got this debug log.

**Comment by SciLor** [comment]
I can confirm this.

I have a cgi-script which sends 
  printf("Content-Type:Image/jpeg\r\n\r\n");
and then the image content.

On the basic ui it works fine, in the app it does not.

**Comment by lolodomo** [comment]
For information, testing again the Sonos binding with tune-in, Spotify, Amazon music and my personal library, I was not able to reproduce the problem in the openHAB app.
Sonos has probably fixed something (HTTP headers).
Using the channels providing image as URL is a good workaround to the lack of support of image item in openHAB app.

**Comment by mueller-ma** [comment]
@lolodomo @SciLor Can you still reproduce this issue?

**Comment by SciLor** [comment]
I will come back to you in 2 weeks.
