### ISSUE TITLE
Images in subfolder of html not loaded (only in app)

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-android#2631]
### Actual behaviour
I wanted to sort all used images in my static (html) folder by putting them into sub-folders like:
- html/images

I mentioned, that this is working if i use a browser to show openHAB 3 UI, but it is not working through Android app

Maybe this is wanted for some reason, but in case its not, i wanted to highlight this behaviour by issue

### Expected behaviour
When i use static/images as path to images for widgets, the image gets loaded

 
### Steps to reproduce
1. Open a site and images can not be loaded

#### Client
* Android version: 12 beta 2
* Device model: Google Pixel 3a
* App version : 2.17.8-beta
* Build flavor : Foss
* Device language: German

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab.org

If anything more is needed, ill spend time to provide the information

**Comment by mueller-ma** [comment]
Are you using http or https for local connections? If latter, do you have a self signed or a trusted certificate?

**Comment by SHU-red** [comment]
Hi,
im using local:
- server url: http://[IP]:8080/
- username: no
- password: no

**Comment by Mark-VG** [comment]
I also seem to have this issue. My image is located as follows:
http://10.163.199.252:8080/static/FloorPlan3Dsmall.jpg
When using a browser the floor plan displays correctly. However with the Android App (2.18.3-beta)
Using https for local access

**Comment by mueller-ma** [comment]
> http://10.163.199.252:8080/static/FloorPlan3Dsmall.jpg
> Using https for local access

I'd say this is blocked because it's mixed content: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

Maybe the browser rewrites all URLs to https, but the app doesn't.

**Comment by maniac103** [comment]
Maybe setting compat mixed content mode via [this API](https://developer.android.com/reference/android/webkit/WebSettings.html#setMixedContentMode(int)) would be worth a try.

**Comment by Mark-VG** [comment]
Thank you. I also submitted a document change to rather use relative URL:

https://github.com/openhab/openhab-docs/pull/1637

**Comment by mueller-ma** [comment]
https://github.com/openhab/openhab-android/releases/tag/2.18.5-beta contains the fix.

**Comment by Mark-VG** [comment]
Thank you. That seems to have fixed the issue I was seeing. Though using a relative URL also works.
Thanks so much for looking so quickly.

**Comment by SHU-red** [comment]
Could not test it by now but thanks a lot for your effort 🤟🤟🤟
