### ISSUE TITLE
If opening text item which contains also webview(s), then webviews are opened in new browser window

### ISSUE THREAD

**Issue by mbolsteins** [openhab/openhab-android#2633]
### Actual behaviour
I have a sitemap with expandable Text items.
These text items contains sub-items and one or more webviews.
When I open that text item, new browser window is opened

### Expected behaviour
When opening (expanding) text item, sub-items should be displayed and in-line webview along with them, not in new browser window.

 
### Steps to reproduce
Part of sitemap -
````
	Frame label="label of frame" {
		Text item=Pagrabs_Summary icon="supermarket" {
			Default item=Pagrabs_temperature label="Temperature"
			Default item=Pagrabs_humidity label="Humidity"
			Default item=Pagrabs_lastUpdate
			Webview url="http://192.168.xx.xxx:3000/dashboard-solo/db/saimnieciba?orgId=1&panelId=4&theme=light" height=8 icon=none
			Webview url="http://192.168.xx.xxx:3000/dashboard-solo/db/saimnieciba?orgId=1&panelId=5&theme=light" height=8 icon=none
		}		
		
		Text item=Workshop_temperature {
			Default item=Workshop_lastUpdate
			Webview url="http://192.168.xx.xxx:3000/dashboard-solo/db/saimnieciba?orgId=1&panelId=3&theme=light" height=8 icon=none
		}
	}
````

When clicking on text item "Workshop_temperature" or "Pagrabs_summary", new browser window will open.

#### Client
* Android version: 10 and 9
* Device model: Huawei P30 Pro and Samsung Galaxy Tab A
* App version: 2.17.4
* Build flavor: Full
* Device language: lv, en-us
On both devices Google Chrome is set as default browser.

#### Server
* Server version: 
* Reverse Proxy: No
* Authentication method: None

**Comment by mueller-ma** [comment]
Can you post the log of the app, especially the lines with `ConnectionWebViewClient`?
