### ISSUE TITLE
App should not connect to HTTP port if HTTPS was given in server URL

### ISSUE THREAD

**Issue by obones** [openhab/openhab-android#2651]
I have setup a reverse proxy for my openHAB installation so that it is only reachable via this entry point and not opened to the whole Internet. The setup is done like this:

http://openhab.mydomain.com:80 --> redirect to https://openhab.mydomain.com:443
https://openhab.mydomain.com:443 --> Basic Auth then proxy to http://machinerunningopenhab:8080

Inside the App, I have thus given `https://openhab.mydomain.com` as the remote server URL, using the `https` prefix to indicate usage of SSL security.

As changing slider values worked when connected to the local URL but not when using the remote URL, I went looking at the reverse proxy logs and found this:

```
37.171.7.140 - - [08/Jul/2021:23:25:27 +0200] "POST /rest/items/RollerShutter_Position HTTP/1.1" 301 265
37.171.7.140 - openhab [08/Jul/2021:23:25:27 +0200] "GET //rest/items/RollerShutter_Position HTTP/1.1" 200 247
```

So, here, we have a first request to `POST` the position that gets a `301 redirect` reply because it has connected to the non SSL port.
This is downgraded to a `GET` request on the SSL port which explains why it does not work. Changing the redirect to a `308` code prevents the downgrade which in turn fixes the issue with positions not being set.

However I believe the whole redirection should not have happened at all because the URL given to the app has the `https://` prefix, conveying the idea that it should connect to the default port for HTTPs, that is the 443 one. 
And if that was the case, there would be no redirection at all.

So right now, every call is doubled because the app always connects to the non SSL port first, then follows the redirection.

I would thus suggest that the App follows the scheme convention and directly tries to connect to port 443 if `https` was given.

**Comment by maniac103** [comment]
The app connects to the URLs returned by the respective API endpoint. If those URLs are HTTP ones, the app will connect via HTTP.
Solution: configure your reverse proxy to rewrite not only the hostname and port in the URLs returned by the internal openHAB server, but also the URL scheme.

**Comment by obones** [comment]
Ah, thanks, that makes sense. 
Well, the API could return relative URLs instead of absolute, but that's a whole other story.

For those looking for a solution, this is the line that is required in the reverse proxy configuration for apache

     RequestHeader set X-Forwarded-Proto "https"

Thanks for the help
