### ISSUE TITLE
Support of command options

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#2655]
Items with command options are currently rendered as a simple switch (commands are so ignored).

These items, when associated to a Switch widget, should be rendered similar as items with state options, that is with one button for each command/state.

PS: I was planning to replace few switch channels in bindings by string channels with command options, but until it is supported by the Android app, it is not worth it.

**Comment by mueller-ma** [comment]
Is there a difference between "command options" and "item options" (as in #912)?

**Comment by lolodomo** [comment]
No real difference in UI perspective.
But for command options, you will not receive state updates.

**Comment by mueller-ma** [comment]
Can you post a rest api response of an item with command options?

**Comment by lolodomo** [comment]
Thank you
