### ISSUE TITLE
Notifications broken 

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-android#2662]
Using 2.18.0 against OH3.1, notifications haven't been working for me in quite a long time.
In Settings screen it says
```
Benachrichtigungen nicht verfügbar:
Fehler beim Verbinden mit dem Server für den Fernzugriff: Unbekannter Fehler: Value <!doctype of type java.lang.String cannot be converted to JSONObject
```

That message also keeps popping up as an error.

**Comment by mueller-ma** [comment]
Are you using myopenhab.org?

**Comment by mstormi** [comment]
no, actually

**Comment by maniac103** [comment]
> no, actually

So you're using an own openhab-cloud deployment? If so, in what version?

The error message sounds like the response from the notifications endpoint fetched [here](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/core/connection/CloudConnection.kt#L34) is not JSON, but something else? Can you try accessing that endpoint manually (browser, curl or whatever) and share the result?

**Comment by mueller-ma** [comment]
Can you add `-v` to this curl command and run it again?

**Comment by maniac103** [comment]
> No cloud, actually.

What can be said for certain is: no cloud, no notifications. The openhab-cloud instance (be it a self-hosted one or myopenhab) is what's providing the API for fetching notifications, and what's processing the notifications.

What @mueller-ma wants to find out is probably why you're not getting a 404 error in this HTTP call, which is what we're using to distinguish 'no cloud instance' from 'broken cloud instance'.

**Comment by mueller-ma** [comment]
I've seen this issue in the forum a few weeks ago: https://community.openhab.org/t/openhab-android-app-no-openhab-3-ui-and-no-notification/124136
It was 'fixed' by moving from public IP and reverse proxy to myopenhab. I thought that this was caused by a wrong reverse proxy setup, but maybe there's an issue with openHAB itself.

**Comment by mstormi** [comment]
I have it on have with both setups, through reverse proxy and with direct access

**Comment by mueller-ma** [comment]
Same for me (direct connection to openHAB server):

````
$ curl http://openhabian:8080/api/v1/settings/notifications -v
[...]
< HTTP/1.1 200 OK
< ETag: "1624816166000"
< Content-Type: text/html
< Content-Length: 1215
< Server: Jetty(9.4.40.v20210413)
[...]
````

The server shouldn't respond with 200 if this is an invalid path. I'll open an issue at server.
