### ISSUE TITLE
Switch item in 2 lines not updating accurately

### ISSUE THREAD

**Issue by cwihne** [openhab/openhab-android#2673]
### Actual behaviour
Item split over 2 lines for readability in sitemap not in sync with value:
```
sitemap test label="Test" {
	Switch item=knxRoomlightScene	label="living room [%d]"	mappings=[ 0.0="Off", 1.0="5%", 2.0="10%", 3.0="25%", 4.0="30%" ]
	Switch item=knxRoomlightScene	label="living room 2 [%d]"	mappings=[ 5.0="50%", 10.0="100%" ]
}
```
.item:
`Number knxRoomlightScene`

![grafik](https://user-images.githubusercontent.com/64205667/128617872-511b5c89-5380-4cb2-90bc-fc564d19a362.png)
This stays even when changing view to other tree sections and coming back.

### Expected behaviour
Only selected switch option is highlighted, no highlight in case of no match
 
### Steps to reproduce
1. have single item used in 2 sitemap lines, with individual options
2. select value 1 in line 1
3. select value 2 in line 2
4. see: now both values are highlighted, although correct singular value "10.0" is shown in both lines according to label definition. Yet, per line only single option is highlighted.

#### Client
* Android version: 11
* Device model: Samsung Galaxy S21
* App version : 2.18.2-beta
* Build flavor : Play Store 
* Device language: DE

#### Server
* Server version: OH3.2.M1, identical in OH3.1 release and Milestones
* Reverse Proxy: myopenhab
* Authentication method : user/pass

</details>

**Comment by mueller-ma** [comment]
What happens after you pull down to refresh?

**Comment by cwihne** [comment]
No change to above described behaviour.
