### ISSUE TITLE
Send device information to openhab

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#269]
I would like to have a simple way to send information about my device (e.g. gps location, battery status) to openhab. This way it would be easy to have a very good present recognition or to control a charger.

Of course this would need more permissions. See: #244

**Comment by Adminius** [comment]
another use case:
if near home then open garage door

**Comment by tsheldon** [comment]
This is actually already available when using the OwnTracks (aka MQTTitude) binding for OpenHAB.  http://docs.openhab.org/addons/bindings/mqttitude1/readme.html

It provides location updates that can trigger rules natively in OpenHAB without the actual app being updated to require more permissions.

Location messages also include the device's battery state, so while not immediately passed through or available in the binding, it shouldn't be too hard to extend that binding to handle it.

**Comment by cribskip** [comment]
Should be fairly simple when #472 is implemented.

**Comment by maniac103** [comment]
I would not recommend starting a foreground service for this. I'd rather suggest doing a battery state string item ('OK', 'LOW', 'CHARGING') using the broadcasts in https://developer.android.com/training/monitoring-device-state/battery-monitoring
The periodical update may also be OK, as long ad we provide rather loose timing constraints for the worker. 
As long as we have a small number of options I personally wouldn't do the subscreen. For the delay of 3. we can subclass ItemUpdatingPreference and add that delay to the dialog.

**Comment by mueller-ma** [comment]
> I'd rather suggest doing a battery state string item ('OK', 'LOW', 'CHARGING') using the broadcasts in https://developer.android.com/training/monitoring-device-state/battery-monitoring

These broadcasts are not the following list: https://developer.android.com/guide/components/broadcast-exceptions

**Comment by mueller-ma** [comment]
> Conversely, a worker that returned Result.failure() is considered to be FAILED. This is also a terminal State; only OneTimeWorkRequests may enter this State. All dependent work will also be marked as FAILED and will not run.

https://developer.android.com/topic/libraries/architecture/workmanager/how-to/states-and-observation

This is an issue for `PeriodicWorkRequest`s that I want to use for things like battery.
