### ISSUE TITLE
Very slow local access if Internet is down

### ISSUE THREAD

**Issue by andredts** [openhab/openhab-android#271]
Interface takes over 10 seconds to respond every time the local network is OK but there is no internet connection. Using the web interface in the same wifi does not seems to be slower, only the app.

**Comment by mueller-ma** [comment]
Do you use openhab cloud?

**Comment by maniac103** [comment]
@andredts Is this still an issue?

**Comment by mueller-ma** [comment]
This should have been fixed by recent connection improvements.
