### ISSUE TITLE
Incorrerct rendering of Sitemap Image

### ISSUE THREAD

**Issue by fmalfatto** [openhab/openhab-android#2749]
I have  this Image in my sitemap:
                Image url="https://www.yr.no/en/content/2-6535684/meteogram.svg" label="Meteo" refresh=3600000

### Actual behaviour
The image shows correctly in web page but is missing parts in android app.

### Expected behaviour
I expect to see the same image.

#### Client
* Android version:  11
* Device model: Samsung S20 FE
* App version 2.19.0
* Build flavor FULL 
* Device language: Italian

#### Server
* Server version:  3.2.0~S2446-1 Raspbery PI 4
* Reverse Proxy: none
* Authentication method  none (local)

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab.org
* openHAB Cloud version 
* Authentication method : user and password,
* 
![Cattura](https://user-images.githubusercontent.com/7314962/140381111-1f38ac72-84b0-4a86-bd3a-acda500cb565.JPG)

![Screenshot_20211103-092758_openHAB Beta](https://user-images.githubusercontent.com/7314962/140381130-11dfdec7-e01d-4d20-9ce3-637d36909254.jpg)

**Comment by mueller-ma** [comment]
I guess the missing icons are imported in a way the SVG library doesn't support, but I haven't checked yet.

**Comment by mueller-ma** [comment]
I opened an issue at the SVG lib: https://github.com/BigBadaboom/androidsvg/issues/240

I can reproduce this issue, but I don't see any log lines of androidsvg.

**Comment by mueller-ma** [comment]
@fmalfatto The issue has been fixed in the SVG lib, but a new version with the fix hasn't been released yet.
