### ISSUE TITLE
Only try to update mobile app info on certain SSID

### ISSUE THREAD

**Issue by PMunch** [openhab/openhab-android#2790]
### Is your feature request related to a problem? Please describe.
I have my OpenHAB set up to only be accessible on my local network. This means that when my phone is not connected to my WiFi it won't be able to update the status of the phone. However when I'm elsewhere I get notifications from OpenHAB saying it can't update, which is a bit annoying.

### Describe the solution you'd like
It would be nice to have a whitelist of SSIDs or saved WiFi networks to make sure it only tries to update when the OpenHAB server is actually available.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by mueller-ma** [comment]
Currently you can add Wi-Fi SSIDs to automatically switch server when switching Wi-Fi. We could add a switch there to only connect to a server if the SSIDs match the currently connected one.

**Comment by mueller-ma** [comment]
You can now restrict the connections to specific wifis: https://github.com/openhab/openhab-android/commit/9952762d9f18db5e1a7878e32c295572b560dbef
In your case this will only change the error message to "Got no connection" :/

However with https://github.com/openhab/openhab-android/commit/bba892146de262e4d356f688947ef9bb9eb13fd7 there shouldn't be any updates when the last successful update had the same value.
Does this improve the situation for you?
