### ISSUE TITLE
Children link http to https rewrite

### ISSUE THREAD

**Issue by dakhnod** [openhab/openhab-android#2800]
I am using the following setup:

Mobile Client <---https---> Apache2 reverse proxy <---http---> Openhab2 API

My Apache2 has three tasks:
- redirect HTTP requests to HTTPS
- authenticate https requests
- forward authenticated https requests to Openhab2

Here's the issue:
Openhab thinks it's being talked to over http by the reverse proxy, which is true in a sense.
As such, openhab inserts links in json with the "http://" scheme.
The app on android then tries to follow these línks, but fails, since the reverse proxy returns a redirect response, not the actual content.

Here are my proposed solutions:
- make the connection between apache and openhab https, which I would like to avoid due to the unnecessary SSL overhead
- make the Openhab app follow redirects when trying to retrieve child elements via link, which would still produce some overhead
- make the Openhab app rewrite all the "http://" links to "https://", when talking to the server over https

Here are my questions:
- Is there anything wrong with my setup?
- Is there a way to make Openhab REST return the links with "https", although it's being talked to over http?
- Which of the solutions would make the most sense? I would love to implement the last one, although it seems a bit unconventional...

**Comment by maniac103** [comment]
> Which of the solutions would make the most sense? I would love to implement the last one, although it seems a bit unconventional...

'Unconventional' seems like an euphemism for 'gross hack' ;-) It probably would work, but has the potential for subtle breakage, e.g. when some links point outside of the server.
I see two possible options:
- let the app follow redirects (seems like a safe choice?)
- let the server provide rest API links as relative instead of absolute URLs

**Comment by dakhnod** [comment]
The issue I see with relative links is that I probably wouldn't work per sé, since the client probably doesn't support that out of the box.

We would need to rewrite the app append the scheme and host in case of relative links, right?

**Comment by maniac103** [comment]
The app already correctly handles relative URLs.

**Comment by mueller-ma** [comment]
Can you post the config of your Apache?

**Comment by mueller-ma** [comment]
My guess is that Apache doesn't tell openHAB that it's behind an TLS reverse proxy. You can do that by setting the `X-Forwarded-Proto` header: https://webmasters.stackexchange.com/questions/97005/setting-x-forwarded-proto-under-apache-2-4

**Comment by dakhnod** [comment]
You are right, Setting that header fixed my issue. Thanks a lot.
