### ISSUE TITLE
Add more locale/tasker intigration, being able to open page on locale

### ISSUE THREAD

**Issue by TheGreyDiamond** [openhab/openhab-android#2805]
### Is your feature request related to a problem? Please describe.
It would be usefull to be able to open a main UI page on tasker command

### Describe the solution you'd like
A way to send a tasker command to openhab, which will open the specified page

**Comment by mueller-ma** [comment]
This was implemented in #2498, but then closed due to no demand anymore. I can reopen this PR.

**Comment by TheGreyDiamond** [comment]
Reading throught it I did not see a way to specify which page to open tho, but it looks good

**Comment by mueller-ma** [comment]
I'm not aware of an API that returns the available pages in main UI. Would it be useful for you to open the start page of main UI via Tasker and not any subpage?

**Comment by TheGreyDiamond** [comment]
I think it would be more useful to be able to do that via intents. I hoped there was a way to open a specific page via intents or locale/tasker
