### ISSUE TITLE
Feature Request: Open app and jump to openHAB UI pages via link

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-android#2817]
### Is your feature request related to a problem? Please describe.
Im generating different notifications for different events.
I want to give the possibility to provide a link within a notification to directly jump to the functions related to the notifications.

For example:
- 3 Days left --> Notification to vaccum the apartement
- In the notifcication there is a link to
- a) directly jump to the custom created "vacuum-page" of openHAB UI
- b) directly trigger the command to vacuum the apartement

Basically i think it would be like some kind of openHAB ui Action, triggered from the Notification via URL???

### Describe the solution you'd like
Links can be created, which open the android app and open directly a specific page from openHAB Ui.
This shall also work when im not in my local network.

### Describe alternatives you've considered
At the moment im using the notifications of the openHAB App itsself.
But it would be no problem for me, to use e.g. pushbullet notifications if this is the only way to provide links within notifications.
(Im not sure but i think for the openHAB app at the moment ins only possible to provide notifications with text)

Im not an expert in this but i could not find anything like this during my research.
Sorry if this has already been mentioned somewhere else ...

**Comment by mueller-ma** [comment]
I'm not sure where this feature request should be opened. There were similar requests in the past, but both got closed:

- https://github.com/openhab/openhab-cloud/issues/160 (closed because other parts of this issue got implemented)
- https://github.com/openhab/openhab-addons/issues/3296 (closed due to inactivity)

@openhab/openhab-cloud-maintainers Can you move this request to either openhab-cloud or openhab-addons?

**Comment by SHU-red** [comment]
Im NOT into this, but just do roll another dice i want to mention that "Deep Linking" could also be a thing?
https://developer.android.com/training/app-links

**Comment by mueller-ma** [comment]
AFAIK these links have to be added to the manifest and therefore cannot be changed during runtime. This means that the app cannot register as handler for the URL of the user's server.

**Comment by SHU-red** [comment]
One last comment/suggestion:
Maybe it would be enough if openHAB notifications could support URLs (wich i THINK they dont do ...)

This would at least give the opportunity to access the openHAB UI via browser, directly by klicking at the notification and going to a sub-page, related to the topic

Just a suggestion
I may also be thinking about realizing this via Pushbullet
