### ISSUE TITLE
Garbled Openhab 3 UI - Android 12 Incompatibility?

### ISSUE THREAD

**Issue by stage-rl** [openhab/openhab-android#2818]
### Actual behaviour
After opening Openhab 3 UI always the attached screen is shown

### Expected behaviour
Normal Openhab 3 UI should appear. This works on the same server installation with other phone on Android 11 (LineageOS 18.1)

 
### Steps to reproduce
Start Android App with Start page set to "openHAB 3 UI"

#### Client
* Android version: 12
* Device model: Pixel 6
* App version: 2.19.11-beta
* Build flavor Play store
* Device language: English

#### Server
* Server version: 3.2.0
* Reverse Proxy: N/A - using myopenhab.org
* Authentication method user and password

#### openHAB Cloud
myopenhab.org
Authentication method: user and password
![openhab_issue](https://user-images.githubusercontent.com/10260098/151661781-673c50ed-aafe-45e0-895d-d2ea7a0d22ce.jpeg)

**Comment by mueller-ma** [comment]
On an emulator with Android 12 the UI is shown correctly. Do you have the lastest WebView installed?

https://play.google.com/store/apps/details?id=com.google.android.webview
