### ISSUE TITLE
Add "Hide notification" action to event listener notification

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2851]
### Is your feature request related to a problem? Please describe.
The persistent notification for the event listener can be hidden by disabling the notification channel. This doesn't impact the functionality.

### Describe the solution you'd like
Add "Hide notification" action to this persistent notification. It should open the notification settings of openHAB and show a toast that this channel can be hidden.

**Comment by maniac103** [comment]
This seems somewhat redundant, as it effectively duplicates the notification settings button accessible via 'half swipe'.

**Comment by mueller-ma** [comment]
That's true, but users might think that this notification has to be shown.

**Comment by maniac103** [comment]
They might, but doesn't that argument apply to any persistent notification from any app?

**Comment by mueller-ma** [comment]
That's true. What about adding "You can safely hide this category" to the notification text then (Android 8+ only)?

**Comment by mueller-ma** [comment]
Let's keep it as is.
