### ISSUE TITLE
[enhancement] Route voice command to openHAB server based on WiFi name

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-android#2856]
I have two openHAB instances defined in the app.

I have the widget with the over-under configuration (microphone icon on top / openHAB icon on bottom) on my home screen.

It appears that using the microphone from the widget to speak commands doesn't use the currently active openHAB instance. No matter which openHAB instance I select to be active, it always seems to use the first openHAB instance that was active.

This can be very confusing because when you're on the sitemap of the currently active openHAB instance, voice commands (correctly) go to that instance.

**Comment by maniac103** [comment]
Voice commands from widgets are sent to the primary server, as mentioned in [the docs](https://www.openhab.org/docs/apps/android.html#multi-server-support). The primary server can be chosen in the server settings in the app.
The point of that distinction (primary vs. active) is that
- one should not need to remember which server was active at the time one last used the app and
- the idea of multi server support was that there's a primary / most important server (your home), and other ones are auxiliary ones (servers of other people or of auxiliary buildings)

**Comment by mhilbush** [comment]
Oh, sorry, I completely missed that in the docs. Thanks for the explanation.

The problem I'm trying to solve... I have 2 locations whose networks are interconnected (in this case by an IPSEC tunnel). So, both openHAB instances are accessible from either location. Using the voice widget to enter a voice command can cause unwanted/unexpected results when I forget to change the primary server. For example, opening the garage door in the other location.

So if I'm on the WiFi at location 1, I'd like location 1 to be the primary server. And if I'm on the WiFi at location 2, I'd like location 2 to be the primary server. That way, I don't need to change the primary server every time I change locations.

I see you can associate the WiFi name(s) with a server, but that doesn't seem to have any effect on selection of the primary server. It would be nice if the WiFi name(s) associated with the servers could be used to automatically select the primary. Or, simply to direct the voice command to the server associated with that WiFi location.

If that's not possible, or if there are unwanted side-effects of doing it, it would be nice to see the Primary Server name on the Google voice prompt.

I've changed the title to reflect that this is a new feature request. Since I don't have permissions on this repo, can you please change the label from Bug to Enhancement?

**Comment by mueller-ma** [comment]
> I see you can associate the WiFi name(s) with a server, but that doesn't seem to have any effect on selection of the primary server.

This is the current intended behavior and I wouldn't change it.

However you can long press the app icon and use the voice recognition shortcut there. It'll open the app and start the in-app voice recognition. So it'll use the active server. You can use the Wi-Fi names to change the active server.
