### ISSUE TITLE
Write NFC tag throwing "Tag write error"

### ISSUE THREAD

**Issue by nose-gnome** [openhab/openhab-android#2858]
### Actual behaviour
Describe us what happens
The phone displays "Tag write error" and fails to write to NFC tag

### Expected behaviour
Describe us what should happen

The phone should successfully write to the NFC tag, allowing it to complete the desired task when pressed against the phone.
 
### Steps to reproduce
1. Open OpenHab
2. Hold finger on one of the options until a select menu appears
3. Select "Write Sitemap NFC tag"
4. Press NFC tag to the back of phone

### Can you reproduce the issue in demo mode?

I can reproduce this in demo mode

#### Client
* Android version: 12
* Device model: Samsung Galaxy S20 
* App version : 2.20.0
* Build flavor :  Full (Play Store)
* Device language: English (United Kingdom)

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: 
* openHAB Cloud version : 
* Authentication method : 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```
-----------------------
Device information
Model: SM-G981B
Manufacturer: samsung
Brand: samsung
Device: x1s
Product: x1sxeea
OS: 12
Display: 720x1452, 2.0 density
Data usage policy: DataUsagePolicy(canDoLargeTransfers=true, loadIconsWithState=true, autoPlayVideos=false, canDoRefreshes=false), data saver: 1, battery saver: true
-----------------------

--------- beginning of main
03-22 23:02:19.359 23422 23422 I ViewRootImpl@471a337[LogActivity]: ViewPostIme key 0
03-22 23:02:19.548 23422 23422 I ViewRootImpl@471a337[LogActivity]: ViewPostIme key 1
--------- beginning of events
03-22 23:02:25.895 23422 23422 D WidgetAdapter: onGlobalLayout()
03-22 23:02:25.928 23422 23422 I ViewRootImpl@a88255c[PopupWindow:f8502a9]: Relayout returned: old=(275,957,720,1277) new=(275,957,720,1277) req=(445,320)0 dur=13 res=0x1 s={true 525282246624} ch=false fn=18
03-22 23:02:27.775 23422 23422 I ViewRootImpl@a88255c[PopupWindow:f8502a9]: ViewPostIme pointer 0
03-22 23:02:27.855 23422 23422 I ViewRootImpl@a88255c[PopupWindow:f8502a9]: ViewPostIme pointer 1
03-22 23:02:27.855 23422 23422 D AbsListView: onTouchUp() mTouchMode : 0
03-22 23:02:27.922 23422 23422 I menu_item_selected: [1,Write Sitemap NFC tag]
03-22 23:02:27.943 23422 23422 I ViewRootImpl@a88255c[PopupWindow:f8502a9]: Relayout returned: old=(275,957,720,1277) new=(275,957,720,1277) req=(445,320)0 dur=7 res=0x1 s={true 525282246624} ch=false fn=23
03-22 23:02:27.944 23422 23422 I wm_on_top_resumed_lost_called: [38624000,org.openhab.habdroid.ui.MainActivity,topStateChangedWhenResumed]
03-22 23:02:27.945 23422 23422 D MainActivity: onPause()
03-22 23:02:27.945 23422 23422 D WidgetListFragment: onPause() https://<openhab-local-address-openHAB>:8443/rest/sitemaps/default/default
03-22 23:02:27.947 23422 23422 I wm_on_paused_called: [38624000,org.openhab.habdroid.ui.MainActivity,performPause]
03-22 23:02:27.960 23422 23422 I DecorView: [INFO] isPopOver=false, config=true
03-22 23:02:27.960 23422 23422 I DecorView: updateCaptionType >> DecorView@2001c9f[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
03-22 23:02:27.960 23422 23422 D DecorView: setCaptionType = 0, this = DecorView@2001c9f[]
03-22 23:02:27.960 23422 23422 I DecorView: getCurrentDensityDpi: from real metrics. densityDpi=320 msg=resources_loaded
03-22 23:02:27.963 23422 23422 D WriteTagActivity: Got URL openhab:///default/0203 (short URI null)
03-22 23:02:27.963 23422 23422 I wm_on_create_called: [34379049,org.openhab.habdroid.ui.WriteTagActivity,performCreate]
03-22 23:02:27.978 23422 23422 I wm_on_start_called: [34379049,org.openhab.habdroid.ui.WriteTagActivity,handleStartActivity]
03-22 23:02:27.979 23422 23422 D WriteTagActivity: onResume()
03-22 23:02:27.984 23422 23422 I wm_on_resume_called: [34379049,org.openhab.habdroid.ui.WriteTagActivity,RESUME_ACTIVITY]
03-22 23:02:27.987 23422 23422 I MSHandlerLifeCycle: isMultiSplitHandlerRequested: ignored. pkg=org.openhab.habdroid parent=null callers=com.android.internal.policy.DecorView.setVisibility:4224 android.app.ActivityThread.handleResumeActivity:5294 android.app.servertransaction.ResumeActivityItem.execute:54 android.app.servertransaction.ActivityTransactionItem.execute:45 android.app.servertransaction.TransactionExecutor.executeLifecycleState:176 
03-22 23:02:27.987 23422 23422 I MSHandlerLifeCycle: removeMultiSplitHandler: no exist. decor=DecorView@2001c9f[]
03-22 23:02:27.991 23422 23422 I ViewRootImpl@8785120[WriteTagActivity]: setView = com.android.internal.policy.DecorView@2001c9f TM=true
03-22 23:02:27.991 23422 23422 I MSHandlerLifeCycle: isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@2001c9f[WriteTagActivity]
03-22 23:02:27.991 23422 23422 I MSHandlerLifeCycle: removeMultiSplitHandler: no exist. decor=DecorView@2001c9f[WriteTagActivity]
03-22 23:02:27.991 23422 23422 I wm_on_top_resumed_gained_called: [34379049,org.openhab.habdroid.ui.WriteTagActivity,topStateChangedWhenResumed]
03-22 23:02:28.003 23422 23422 I ViewRootImpl@8785120[WriteTagActivity]: Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)0 dur=8 res=0x7 s={true 525282272784} ch=true fn=-1
03-22 23:02:28.003 23422 23472 D OpenGLRenderer: eglCreateWindowSurface
03-22 23:02:28.004 23422 23422 I ViewRootImpl@8785120[WriteTagActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11264 android.view.ViewRootImpl.performTraversals:4089 android.view.ViewRootImpl.doTraversal:2833 
03-22 23:02:28.004 23422 23422 D ViewRootImpl@8785120[WriteTagActivity]: Creating frameCompleteCallback mNextDrawUseBlastSync=false mReportNextDraw=true commitCallbacks size=0
03-22 23:02:28.009 23422 23472 D ViewRootImpl@8785120[WriteTagActivity]: Received frameCompleteCallback frameNum=1
03-22 23:02:28.010 23422 23422 I ViewRootImpl@8785120[WriteTagActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$createFrameCompleteCallback$3$ViewRootImpl:4847 android.view.ViewRootImpl$$ExternalSyntheticLambda15.run:6 android.os.Handler.handleCallback:938 
03-22 23:02:28.010 23422 23422 I ViewRootImpl@8785120[WriteTagActivity]: [DP] rdf()
03-22 23:02:28.010 23422 23422 D ViewRootImpl@8785120[WriteTagActivity]: reportDrawFinished (fn: -1) 
03-22 23:02:28.010 23422 23422 I ViewRootImpl@a88255c[PopupWindow:f8502a9]: MSG_WINDOW_FOCUS_CHANGED 0 1
03-22 23:02:28.011 23422 23422 I ViewRootImpl@e068410[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
03-22 23:02:28.013 23422 23422 I ViewRootImpl@e068410[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
03-22 23:02:28.030 23422 23422 I ViewRootImpl@8785120[WriteTagActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
03-22 23:02:28.031 23422 23422 D InputMethodManager: startInputInner - Id : 0
03-22 23:02:28.031 23422 23422 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
03-22 23:02:28.047 23422 23422 I wm_on_idle_called: {org.openhab.habdroid/org.openhab.habdroid.ui.WriteTagActivity}
03-22 23:02:28.259 23422 23472 D OpenGLRenderer: setSurface called with nullptr
03-22 23:02:28.259 23422 23472 D OpenGLRenderer: setSurface() destroyed EGLSurface
03-22 23:02:28.259 23422 23472 D OpenGLRenderer: destroyEglSurface
03-22 23:02:28.259 23422 23422 I ViewRootImpl@a88255c[PopupWindow:f8502a9]: dispatchDetachedFromWindow
03-22 23:02:28.262 23422 23422 D InputTransport: Input channel destroyed: '38badf7', fd=133
03-22 23:02:28.427 23422 23422 I ViewRootImpl@a88255c[PopupWindow:f8502a9]: handleAppVisibility mAppVisible=true visible=false
03-22 23:02:28.443 23422 23422 I ViewRootImpl@e068410[MainActivity]: handleAppVisibility mAppVisible=true visible=false
03-22 23:02:28.443 23422 23422 I ViewRootImpl@e068410[MainActivity]: stopped(true) old=false
03-22 23:02:28.447 23422 23422 D MainActivity: onStop()
03-22 23:02:28.447 23422 23422 D PageConnectionHolderFragment: onStop()
03-22 23:02:28.447 23422 23422 D PageConnectionHolderFragment: Canceling connection for URL https://<openhab-local-address-openHAB>:8443/rest/sitemaps/default/default
03-22 23:02:28.450 23422 23422 I wm_on_stop_called: [38624000,org.openhab.habdroid.ui.MainActivity,STOP_ACTIVITY_ITEM]
03-22 23:02:28.450 23422 23422 D MainActivity: onSaveInstanceState()
03-22 23:02:28.450 23422 23422 D ContentController: onSaveInstanceState()
</details>

**Comment by mueller-ma** [comment]
Can you please test the following apk?

- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk

[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/8335375/mobile-foss-beta-debug.zip)

**Comment by nose-gnome** [comment]
> Can you please test the following apk?
> 
>     * Rename it to .apk
> 
>     * Uninstall openHAB Beta if installed
> 
>     * Install my apk
> 
> 
> [mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/8335375/mobile-foss-beta-debug.zip)

Thank you, this works beautifully now.

**Comment by maniac103** [comment]
> Can you please test the following apk?

Let me guess ... Immutable -> Mutable for the pending intent in `WriteTagActivity`? If so, I came to the same conclusion ;-)

**Comment by mueller-ma** [comment]
Exactly. I propose a PR later today.
