### ISSUE TITLE
Remote Access does not work without https

### ISSUE THREAD

**Issue by niwla23** [openhab/openhab-android#2864]
### Actual behaviour
I tried setting the remote url to a VPN address with http but it tells me the format is invalid.

### Expected behaviour
Allow use of http like for local network. Maybe put a warning there that you should only do this over a VPN connection
 
### Steps to reproduce
1. go to server settings
2. try setting the remote url

### Can you reproduce the issue in demo mode?
doesn't apply

#### Client
* Android version: 11
* Device model:  OnePlus Nord 
* App version :  2.20.5-beta
* Build flavor : Full
* Device language: German

#### Server
* Server version: 3.2.0
* Reverse Proxy: nope
* Authentication method : none

**Comment by niwla23** [comment]
![Screenshot_20220401-195740.jpg](https://user-images.githubusercontent.com/46248939/161317196-e6fca782-2e6b-452e-9291-f46cfe2b0b04.jpg)

**Comment by maniac103** [comment]
If it's a VPN, I assume the same address is also reachable in your local network? If so, why don't you assign it to the local connection?

**Comment by niwla23** [comment]
> If it's a VPN, I assume the same address is also reachable in your local network? If so, why don't you assign it to the local connection?

1. It needs to be routed over internet uplink > slow
2. If internet or vpn goes down, I can't access openHAB

fixed it for now by putting a proxy with self signed certificates in front of it, but I think it would still be nice if https was optional.

**Comment by zynexiz** [comment]
It don't alow unsecure connections for a reason, as how it should be. Using unencrypted connections open up your entire home for hackers, as your password is sent in plain text. Give me one minute and I have access to everything in your home, not very good right?
