### ISSUE TITLE
Frame item='…' does not show the state of the item

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#2868]
My sitemap contains: `Frame item=iii1 label="yyy"`.  The web-interface (basicui/app?sitemap=uicomponents_page_442558d5fe) does show after the frame the state of the iii1 item.

OpenHAB/Android 2.20.5-beta does not use the item state in Frames.

Extend OpenHAB/Android to display the state of the referenced item.

**Comment by mueller-ma** [comment]
Can you change the label to `label="yyy[%s]"`?

**Comment by dilyanpalauzov** [comment]
I change it, but the change makes no difference.

**Comment by mueller-ma** [comment]
What's the type of item `iii1`?

**Comment by mueller-ma** [comment]
Nevermind, the app doesn't support item states in Frames:

- https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt#L482
- https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/model/Widget.kt#L61-L62

**Comment by dilyanpalauzov** [comment]
For the record, when I replace `Frame item=iii1 label="yyy"` with `Frame item=iii1 label="yyy"` the state of the item iii1 is shown as state of the Group.
