### ISSUE TITLE
▼ of `Selection` not aligned to the right

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#2875]
![Screenshot_20220411-105602_openHAB](https://user-images.githubusercontent.com/4992947/162690956-be1906c2-3e81-4d7b-9703-ce55f3eba764.png)

At the bottom of the screenshot there are two `Selection` elements, indicated by ▼.  The label of the second Selection is not displayed, because the Item’s value is too long.

The problem is that the two ▼ are not equally aligned to the right.  All ▼ should have equal distance to the left and right borders of the viewport.

I use OpenHAB 2.20.0 gplay.

**Comment by mueller-ma** [comment]
Interesting. The arrow should be on the right and has a fixed margin: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/res/layout/widgetlist_selectionitem.xml#L16-L20

**Comment by dilyanpalauzov** [comment]
Why was a help wanted tag added? I cannot help.  But I can amend, that Android has an option ”Font size”.

If I decrease the font size, then more information fits in the line and both ▼ are equally aligned.

If I increase the font size, above what I have by default, the lower ▼disappears completely.  Its line ends then with exactly two dots. The upper selection line start literally with two and a half dots, and has ▼at the end.

**Comment by mueller-ma** [comment]
> Why was a help wanted tag added? 

I added the tag so new contributors know that they can help here.

**Comment by mueller-ma** [comment]
This should be fixed with https://github.com/openhab/openhab-android/releases/tag/2.23.5-beta.
