### ISSUE TITLE
Frame is not closed

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#2876]
When a Frame within Sitemap is shown, the Android-OpenHAB 2.20.0 application shows a horizontal line at the begin of the Frame.  It does not show a horizontal line at the end of the Frame, thus in the UI it is unclear when the Frame ends.

Cf. to the Web UI (whatever it is called - /basicui/app?sitemap=uicomponents_page_442558d5fe ) where Frames are put in rectangles in different color and it is clear where a Frame ends.

**Comment by mueller-ma** [comment]
That's the intended behavior. When a frame ends there's either the start of a new frame (and with that a new horizontal line) or the end of the current page (and therefore it's clear that the frame ends here).

**Comment by dilyanpalauzov** [comment]
Objects this intended behaviour.  While it does work properly, when I put all frames at the end of the sitemap, I wanted to put frames in the middle of the sitemap, and afterwards insert some Items (outside of frames).  I see no reason, while it shall not be reasonable to insert items after a frame is closed, and visually the UI shows, that an UI is outside/after a frame.

**Comment by mueller-ma** [comment]
While https://www.openhab.org/docs/ui/sitemaps.html doesn't mention that Frames are mandatory, all examples on that page and all other examples I have seen in the docs use frames for all items. I recommend to do that in this case as well.

**Comment by dilyanpalauzov** [comment]
I personally have usedItems for a while, because this is what I got working.  At some time I discovered Frames, so I wanted to group some of the existing Itemms in a Frame.  Tgis does not work as expected.
