### ISSUE TITLE
Option to hide the microphone icon

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#2887]
I do not use voice control, since for my language no voice recognition software exists.  I want to hide the microphone icon from the top right corner of openhab-android.

![Screenshot_20220424-105204_openHAB](https://user-images.githubusercontent.com/4992947/164966218-946c9b81-8539-456b-a263-378ce1af3fc8.png)

The screenshot shows at the top a group name, followed by a group value (a value of a real Item), and finally a microphone icon.  The microphone icon prevents that the Group value it fully shown.

* add an option to hide the microphone, or detect automatically that the OpenHAB instance does not utilize voice recognition, and hide the microphone automatically.

**Comment by maniac103** [comment]
The voice recognition does not depend on the OH instance, but runs on the phone. But you're right, the app should check whether voice recognition is available on the phone for displaying the icon.

**Comment by mueller-ma** [comment]
What happens when you press the microphone icon?

**Comment by dilyanpalauzov** [comment]
It shows the message “No voice recognition app found.  INSTALL”.
