### ISSUE TITLE
Send connected Bluetooth device in device information

### ISSUE THREAD

**Issue by sjonez** [openhab/openhab-android#2895]
Are there any plans to include the connected bluetooth device name as a device information item like we do with the WiFi SSID? I currently do this with the IFTTT app to know when I've entered my car (specifically so I can inform the Tesla binding to immediately start polling for status when it thinks the car is asleep) but I'm sure there are lots of other use cases.

It'd be great if I could do this natively with the OpenHAB app and remove my dependency on IFTTT.

**Comment by mueller-ma** [comment]
This seems quite easy to implement:

* Get connected devices: https://developer.android.com/reference/kotlin/android/bluetooth/BluetoothManager?hl=en#getconnecteddevices
* Broadcast receiver when new device is connected: https://developer.android.com/reference/android/bluetooth/BluetoothDevice#ACTION_ACL_CONNECTED

**Comment by maniac103** [comment]
> Get connected devices

This seems to return BLE devices only though, judging from the description of the `profile` parameter.

Also, if multiple devices are connected, what's the desired/expected item state format? Semicolon separated list of device MAC addresses or something?

**Comment by mueller-ma** [comment]
> Also, if multiple devices are connected, what's the desired/expected item state format? Semicolon separated list of device MAC addresses or something?

I'd send a list of the bluetooth device aliases, maybe separated by `|` or `;`.

**Comment by mueller-ma** [comment]
With https://github.com/openhab/openhab-android/pull/2897 I was able to send the bluetooth mac address of my bluetooth speakers

**Comment by sjonez** [comment]
I just noticed this is now in the beta and works great, so thanks for the very quick turnaround! 👍 

@mueller-ma one minor observation, in settings it has been placed under the "Schedule based" section, but it seems to be very much event based from my testing? (I don't have the event monitor enabled and the updates _appear_ to be instant). Should it live in the top section along with call state and alarms?

**Comment by mueller-ma** [comment]
I didn't see that bluetooth broadcasts are sent to apps that are running in background: https://developer.android.com/guide/components/broadcast-exceptions.html

https://github.com/openhab/openhab-android/pull/2918 moves the entry to the event based ones.
