### ISSUE TITLE
Frame labels have an trailing null

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-android#2896]
### Actual behaviour
In the Beta version of the App all labels of frames have a trailing `null`. In the `non-beta` version of the app (from the playstore) this doen't happen

### Beta Version
Version: `2.20.6`
![Screenshot_20220501-011938_openHAB Beta](https://user-images.githubusercontent.com/45742226/166423333-78b58c43-8aa0-472e-83b1-f19549756fe6.jpg)
![Screenshot_20220501-011945_openHAB Beta](https://user-images.githubusercontent.com/45742226/166423338-d0fd962f-b35c-4957-ae47-534b54114168.jpg)

### Stable (From Playstore)
Version: `2.20.0`
![Screenshot_20220501-011953_openHAB](https://user-images.githubusercontent.com/45742226/166423341-09a3495b-0d2e-47b1-8370-543ab1528428.jpg)
![Screenshot_20220501-011957_openHAB](https://user-images.githubusercontent.com/45742226/166423343-e6d77de7-dcec-4221-891f-7bedcc44ccc0.jpg)

 
### Steps to reproduce
Sitemap code:
```
sitemap smartphone label="Felix"
{
    Frame label="Licht"
    {
        ...
    }

    Frame label="Steckdosen" visibility=[Netzwerk_BrennstuhlBridge_Online==ON]
    {
        ...
    }

    ...
}
```

#### Client
* Android version: 12
* Device model: Samsung Galaxy S22 Ultra
* App version : See above
* Build flavor : `Full`
* Device language: German

#### Server
* Server version: `2.5.12`

#### App log
[Log from Beta](https://github.com/openhab/openhab-android/files/8609225/framelabels.txt)
[Log from Stable](https://github.com/openhab/openhab-android/files/8609314/stable.1.txt)

**Comment by mueller-ma** [comment]
Duplicate of #2889?

**Comment by Trysupe** [comment]
Yes, sorry
