### ISSUE TITLE
Move Group labels from sitemaps to the left in the titlebar

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#2898]
The title of a Group is not wide enogh to accommodate the Group label and value.  The space on the top left after the arrow is likely reserved for an icon, but the Group in the example has no icon.

I propose moving the Group name (label+value) to the left, closer to the arrow, when the titlebar is not wide enough and the group has no icon.

For the record, the screenshots at https://play.google.com/store/apps/details?id=org.openhab.habdroid suggest that the space between the arrow and the start of the label is not used for icons.

![Screenshot_20220504-074924_openHAB](https://user-images.githubusercontent.com/4992947/166624563-febd9f13-f778-4d18-9035-26a4f09b1f9b.png)

**Comment by mueller-ma** [comment]
We use the default app bar here with the default spacing. When looking at https://material.io/components/app-bars-top#anatomy you can see that it's not recommended to put much text into a regular app bar.

You could add the group value as text item as first item and shorten the group label.

**Comment by dilyanpalauzov** [comment]
I put in a group a device and spread the properties of a device as group members.  The most important property of the device is put as the Group/Item’s value.  This way I can see the property’s value, when the group is collapsed.  For this reason I do not want to move the Group’s value into a separate element.

In the case where Group label+value is longer than the available space, my impression is that for collapsed groups, preference is given to the value (so the label is shortened), while for expanded groups (showing all items) the full label is shown and the value is cut.  I would prefer if in both cases the value is always displayed and the label is shortened.

**Comment by maniac103** [comment]
The problem with that is us not having any control over the title bar's text shortening behavior. This is different from the widget list, where label and value are separate text elements which we have control over.

**Comment by dilyanpalauzov** [comment]
The lack on any control is very pity, but presenting the text as right-to-left (or the opposite direction to the current one) will show the Group value and hide the Group item, if there is no place for both of them.

This ticket is about reducing the empty space in the titlebar between the arrow and the start of the text.

**Comment by mueller-ma** [comment]
I haven't found a way to control the title shortening behavior in the action bar.

**Comment by mueller-ma** [comment]
> I haven't found a way to control the title shortening behavior in the action bar.

I'm closing the issue because of this.
