### ISSUE TITLE
[Feature request] Show channel status in widget (Android)

### ISSUE THREAD

**Issue by Hoerli1337** [openhab/openhab-android#2902]
Currently you can create widgets on the Android home screen to control channels.
Unfortunately it is not possible to show the status of channels.
I would like to show the temperature of sensors on my home screen, or if the washing machine is still running or already finished.
Unfortunately, this is not possible (yet) ... or I am too stupid to set it up.

To not drain the battery quickly, it would be good if you could set a refresh rate.
E.g. poll every 5 minutes, or every 15 minutes, .... :)

**Comment by mueller-ma** [comment]
I commented in https://github.com/openhab/openhab-android/issues/6#issuecomment-462417659 on that topic. Things like this would require server side changes.

> if the washing machine is still running or already finished

You can use notifications for that.

**Comment by maniac103** [comment]
@mueller-ma Implementing this using a polling mechanism should be possible though. It's obviously not ideal, but it's how virtually all status widgets by other apps work as well.

**Comment by Hoerli1337** [comment]
I think it is completely wrong to abuse notifications for these things.
I don't want to get an info that it's 22°C now, but I just want to see it on my homescreen when I need it.
Why this should be dependent on Google - as in your comment - I can't explain.
The app would only have to actively load the data from the server.
Roughly speaking, load the sitemap, search for the item and display the value.
I'm not a programmer, but I don't think it's particularly difficult (except for the usual code blah blah).

**Comment by mueller-ma** [comment]
The current periodic workers (Send device info and FOSS notifications) could be used to fetch the item state.
