### ISSUE TITLE
Android Device Controls: subtitle

### ISSUE THREAD

**Issue by KingTomaHawk** [openhab/openhab-android#2904]
### Is your feature request related to a problem? Please describe.
Android Device Controls, subtitles missing. Opportunity to display useful Information like "item.name" missed.

### Describe the solution you'd like
Use` .setSubtitle() `to add additional Information like location or name of parent item. 

I added: 
`.setSubtitle(item.name)`
under line 319 and under line 326 in the file `ItemsControlsProviderService.kt` (path: \openhab-android-main\mobile\src\main\java\org\openhab\habdroid\background)

The results can be seen in the screenshots below.

### Describe alternatives you've considered
Showing the item location, instead of item name, would also be a good alternative.

### Additional context
**Current state (used paint to remove subtitles, as I use the app with my the implemented code now):**

<img src='https://user-images.githubusercontent.com/36895999/167680478-2dd204b7-4146-4614-85da-7dd7091a9bf6.png' width='300'>

**With implemented Code:**

<img src='https://user-images.githubusercontent.com/36895999/167680548-882d5bd0-a9b6-4b1d-b468-ca10ff9690b0.png' width='300'>

**Comment by mueller-ma** [comment]
There aren't many properties that are connected to Items: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/model/Item.kt#L30-L43

IMO the item name is too technical to be displayed here.

Maybe display the item state, e.g. for temperature?

**Comment by maniac103** [comment]
> IMO the item name is too technical to be displayed here.

Not sure. Think e.g. having 5 switches of some outlet relay plugs, which each have the default name of 'State' (or likewise 'Level' for roller shutters)... in that case, seeing the item name would be really helpful.
After all, we show the item name in the item picker as well...

**Comment by mueller-ma** [comment]
>  After all, we show the item name in the item picker as well...

True, but the item picker isn't made for being used every day.

But I also see that it helps, so no veto from my side. @KingTomaHawk Do you want to open a PR?

**Comment by KingTomaHawk** [comment]
@mueller-ma never done a PR till today, so please check if everything is done right :)
 
**achievement unlocked: create first PR**

**Comment by mueller-ma** [comment]
TBH I'm not really happy with that change. The UI looked much cleaner before and for some users, e.g. for me, the item name doesn't add any information as the item label is already unique.

In the [documentation ](https://developer.android.com/guide/topics/ui/device-control#user-interface)the subtitle is the location of the item. We could do that, but I'm not sure how to get the location. For things I can set a location, but not for items....

The location could be set as [zone](https://developer.android.com/reference/android/service/controls/Control.StatefulBuilder#setZone(java.lang.CharSequence)). This makes it easier to find item when searching in the long list of items.

Maybe add a preference subscreen with a setting for the subtitle: Item name, location or nothing?
In this screen there could be an setting for https://developer.android.com/reference/android/service/controls/Control.StatefulBuilder#setAuthRequired(boolean)

**Comment by KingTomaHawk** [comment]
Hmm.. I understand that. You said that it looked cleaner before, but I don't understand what exactly the problem is. Is the problem that some text doesn't fit (which I fully understand, that bothers me too) or that there is text at all?

But It seems like Android 13 Beta 2 broke something with Device Controls so I can't experiment with it for a while.

**Comment by mueller-ma** [comment]
The "problem" for me is that the item name as subtitle adds redundant and technical information.

**Comment by mueller-ma** [comment]
@KingTomaHawk Can you check the PR https://github.com/openhab/openhab-android/pull/2925?

**Comment by KingTomaHawk** [comment]
Sadly I can't currently check it, as Android 13 beta 2 broke something with Openhab and Device Controls. 
At the moment I'm not sure if it's a bug which will be fixed by Google or they changed something that will effect the current implementation, but I have to wait for Beta 3 to check.  Sorry.

**Comment by maniac103** [comment]
I'll give it a try.
