### ISSUE TITLE
Resolving translation conflicts

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#2913]
I have changed the translations of `error_unable_to_resolve_hostname` and `error_connection_failed` in mobile/src/main/res/values-bg/strings.xml in Crowdin approximately a month ago.  Or rather, I proposed a new wording, as I cannot change the existing text, which new wording is not yet at https://github.com/openhab/openhab-android/pull/2906 nor in the codebase itself.

Please clarify, what is the procedure to change existing translations.

**Comment by mueller-ma** [comment]
I granted you proofreader rights, so you can press the check mark next to your translation now. Then it'll show up in the Pull Request.
