### ISSUE TITLE
Troubles with two networks

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#2936]
I run OpenHAB on Raspberry Pi.  It has a private IP address (192.168.0.x).  The router has static IP address (say 2.3.4.5) and port forwarding is installed to the OpenHAB.  The OpenHAB Android app is configured using two IP addresses:
- local 192.168.0.x and
- remote (2.3.4.5)

This works fine.  Now my house is disconnected from internet and the OpenHAB is accessible only over 192.168.0.x.  I tell my Android device to connect both to the local netwoork (over WiFi) and to the internet (over LTE).

As long as the Android device is connected to both networks, it does not connect to the OpenHAB instance.

**Comment by mueller-ma** [comment]
Sorry for the late reply. Can you capture the app log via ADB while opening the app when the device is connected to both networks?

**Comment by dilyanpalauzov** [comment]
No, as I have not worked with ADB and it will take very long to get it running, and because I will not be in the described environment in the near future.
