### ISSUE TITLE
valuecolor not applied to the buttons in Sitemap-Switch

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#2950]
I have in a sitemap:

>  Switch item=rm label="Switch [MAP(switcha.map):%s]"  mappings=[ON="AAA", OFF="BBB"] valuecolor=[ON="green", OFF="red", "blue"] labelcolor=[ON="green", OFF="red", "blue"]

This shows two choices on Android: AAA or BBB.  The AAA and BBB choice are not colored with `labelcolor`.  Instead labelcolor is used to present the value on the left of the choices (the `[MAP(switcha.map):%s]` content).

labelcolor shall change the color of the buttons/ON/OFF toggle.

**Comment by mueller-ma** [comment]
Can you post a screenshot of Basic UI with this setup?

**Comment by dilyanpalauzov** [comment]
![basicuilabelcolor](https://user-images.githubusercontent.com/4992947/174553247-c9d28ae3-fddc-4bf1-8934-74a441835a32.png)

**Comment by dilyanpalauzov** [comment]
![Screenshot_20220620-105313_openHAB_Beta](https://user-images.githubusercontent.com/4992947/174553399-55c0c30a-c2e9-4259-9911-97033ddf4654.png)

**Comment by maniac103** [comment]
What makes you think `labelcolor` and `valuecolor` should be applied to the switches? From their naming, `labelcolor` should apply to the label (`Switch` in your example), and `valuecolor` applies to the label (the cyrillic text in your example). I do not see any evidence in [the docs](https://www.openhab.org/docs/ui/sitemaps.html#label-and-value-colors) that either color should apply to switches, and your BasicUI screenshot shows that (at least) BasicUI developers agree with that interpretation.

**Comment by dilyanpalauzov** [comment]
For `Switch mappings=[]`, having extra text `label="in brackets after label [MAP(...):%s]"` has no use, as the active value is evident from the selected button.  Since having an extra rendered value makes no sense here, the valuecolor shall be applied on the buttons.

**Comment by dilyanpalauzov** [comment]
>  … should make the valuecolor apply elsewhere.

It is not about applying it elsewhere.  The buttons/choices are part of the value of the property, so valuecolor shall apply to them, too.  In other words, the above `Switch` has its value rendered twice: once as string and once as buttons.

**Comment by mueller-ma** [comment]
I fully agree with @maniac103. The buttons aren't part of the value and thus shouldn't be colored.

The fact that Basic UI works in the same way is an indicator that both UIs work as intended.
