### ISSUE TITLE
Dynamic icons do not work for `Switch`

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#2958]
I have openHAB-Android 2.20.13-beta and in a sitemap `Switch item=r label="R" icon="x.svg"`.

In /etc/openhab/icons/classics I have the files `x.svg` - ![x.svg](https://user-images.githubusercontent.com/4992947/175828105-07dcf7bd-da70-4c10-8691-8d0539d50053.svg), `x-off.svg` - ![x-off.svg](https://user-images.githubusercontent.com/4992947/175828115-013d8bcf-6b27-41f5-9a6a-f5c2d624955d.svg), and `x-on.svg` - ![x-on.svg](https://user-images.githubusercontent.com/4992947/175828133-5389f303-9bcf-436f-9431-376970f8eb56.svg).

The basicui displays the icons correctly, it shows either x-on.svg or x-off.svg, depending on the state of the toggle.

OpenHAB-Android displays only x.svg.

**Comment by maniac103** [comment]
On the demo server (Widget Overview -> Toggle Switch) it seems to work fine for me ... how about you, is that one working for you?

**Comment by dilyanpalauzov** [comment]
I cannot say for the demo server, since I cannot upload icons there.

The basicui requests `http://.../icon/x.svg?state=OFF&format=svg&anyFormat=true` and does get the right image.

In OpenHAB Android I have stopped the application, deleted the cache, started logging all requests on the server and started openhab-android.  This is the access log:
```
2.1.1.1 - user [26/Jun/2022:21:48:03 +0300] "GET /api/v1/settings/notifications HTTP/2.0" 200 563 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:03 +0300] "GET /rest/ HTTP/2.0" 200 1980 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:04 +0300] "GET /rest/sitemaps HTTP/2.0" 200 192 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:04 +0300] "GET /rest/sitemaps/ab/ab?includeHidden=true HTTP/2.0" 200 18055 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:04 +0300] "POST /rest/sitemaps/events/subscribe HTTP/2.0" 200 353 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:05 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 499 0 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/text?format=SVG&anyFormat=true HTTP/2.0" 200 942 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:07 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:07 +0300] "GET /rest/sitemaps/ab/29?includeHidden=true HTTP/2.0" 200 3288 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:07 +0300] "POST /rest/sitemaps/events/subscribe HTTP/2.0" 200 353 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:07 +0300] "GET /icon/number?format=SVG&anyFormat=true HTTP/2.0" 404 325 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:07 +0300] "GET /icon/energy?format=SVG&anyFormat=true HTTP/2.0" 200 773 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:07 +0300] "GET /icon/number?format=SVG&anyFormat=true HTTP/2.0" 404 325 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:07 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:07 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:48:07 +0300] "GET /icon/temperature?format=SVG&anyFormat=true HTTP/2.0" 200 635 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:50:31 +0300] "GET /rest/sitemaps/events/929e2188-ff6c-43ad-9db3-4c8f564f11f1?sitemap=ab&pageid=29 HTTP/2.0" 200 1225 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
2.1.1.1 - user [26/Jun/2022:21:50:31 +0300] "GET /rest/sitemaps/events/8d3aa57c-cdfc-40d8-b8cb-150d00e43f13?sitemap=ab&pageid=ab HTTP/2.0" 200 63243 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
```

I do not see anywhere icon names requested, but `x.svg` is transferred.  Perhaps this is done over websockets, sends payload to GET, or by other means, which are not logged.

In any case, the line

> 2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true HTTP/2.0" 404 321 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"

appears too many times.  The user agent shall request the file once and remember the 404-results.

The file `http://192.168.0.176:8080/rest/sitemaps/ab/ab?includeHidden=true` does not include `x` as icon.

Item definition from JSONDB:
```json
  "r": {
    "class": "org.openhab.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [],
      "itemType": "Switch",
      "tags": [
        "Switch"
      ],
      "label": "R",
      "category": ""
    }
  },

```

**Comment by dilyanpalauzov** [comment]
> On the demo server (Widget Overview -> Toggle Switch) it seems to work fine for me ... how about you, is that one working for you?

Visiting https://demo.openhab.org/basicui/app?w=0202&sitemap=demo with Firefox and clicking on “Toggle Switch” does change the state, but not the icon.  Clicking on “Button Switch” does not change anything.

**Comment by mueller-ma** [comment]
Can you post the "device information" part of the log of the app? It's shown in the Settings => Show log

**Comment by dilyanpalauzov** [comment]
Now I deleted the image cache within OpenHAB-Android.  On the previous cache-deletion, I told the operating system Android to delete cache.  These are apparently different things.  Now the access.log contains:

> 2.1.1.1 - user [26/Jun/2022:22:23:12 +0300] "GET /icon/x.svg?format=SVG&anyFormat=true HTTP/2.0" 200 1683 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"

So OpenHAB-Android is not transmitting the state to the web server.  Is this enough? I prefer not to send the Log, since I have first to remove the private information from it (all items).  The log file contains about x.svg four entries:
```
06-26 22:23:12.561 29078 29078 D PageConnectionHolderFragment: Widget 1: Widget(id=2900, parentId=null, rawLabel=R [OFF], icon=IconResource(icon=x.svg, isOh2=true, customState=OFF), state=ParsedState(asString=OFF, asBoolean=false, asNumber=0.0, asHsv=null, asBrightness=null, asLocation=null), type=Switch, url=null, item=Item(name=r, label=R, category=, type=Switch, groupType=None, link=https://<openhab-remote-address-openHAB>:717/rest/items/r, readOnly=false, members=[], options=[], state=ParsedState(asString=OFF, asBoolean=false, asNumber=0.0, asHsv=null, asBrightness=null, asLocation=null), tags=[Point], groupNames=[], minimum=null, maximum=null, step=null), linkedPage=null, mappings=[], encoding=null, iconColor=null, labelColor=null, valueColor=null, refresh=0, minValue=0.0, maxValue=100.0, step=1.0, period=D, service=, legend=null, forceAsItem=false, switchSupport=false, height=0, visibility=true)

06-26 22:23:12.613 29078 29078 I WidgetImageView: Refreshing image at https://<openhab-remote-address-openHAB>:717/icon/x.svg?format=SVG&anyFormat=true, avoidCache false

06-26 22:23:12.615 29078 32140 I okhttp.OkHttpClient: --> GET https://<openhab-remote-address-openHAB>:717/icon/x.svg?format=SVG&anyFormat=true
06-26 22:23:12.615 29078 32140 I okhttp.OkHttpClient: User-Agent: Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19
06-26 22:23:12.615 29078 32140 I okhttp.OkHttpClient: Cache-Control: max-stale=2147483647
06-26 22:23:12.615 29078 32140 I okhttp.OkHttpClient: --> END GET

06-26 22:23:12.893 29078 32140 I okhttp.OkHttpClient: <-- 200 https://<openhab-remote-address-openHAB>:717/icon/x.svg?format=SVG&anyFormat=true (278ms)
06-26 22:23:12.893 29078 32140 I okhttp.OkHttpClient: server: nginx/1.18.0
06-26 22:23:12.893 29078 32140 I okhttp.OkHttpClient: date: Sun, 26 Jun 2022 19:23:12 GMT
06-26 22:23:12.893 29078 32140 I okhttp.OkHttpClient: content-type: image/svg+xml
06-26 22:23:12.893 29078 32140 I okhttp.OkHttpClient: last-modified: Sun, 26 Jun 2022 19:23:12 GMT
06-26 22:23:12.893 29078 32140 I okhttp.OkHttpClient: set-cookie: ██
06-26 22:23:12.893 29078 32140 I okhttp.OkHttpClient: <-- END HTTP
```

**Comment by maniac103** [comment]
> In any case, the line
> 
> 2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true
> appears too many times. The user agent shall request the file once and remember the 404-results.

I do not agree to the 'shall remember 404 statement' (where does that requirement come from?), but the actual problem is that no icon is actually requested (there should be the icon name in the path). The root cause likely is

> The file http://192.168.0.176:8080/rest/sitemaps/ab/ab?includeHidden=true does not include x as icon.

This. Please share the output of that call.

**Comment by maniac103** [comment]
Nevermind my last request, our responses overlapped. Do you by any chance have data saver enabled in Android?

**Comment by dilyanpalauzov** [comment]
Yes, I do have.  When I disable it, the icons are displayed correctly.

I thought the flag does not apply to Wi-Fi, but apparently it applies.  However it seems, that even if I disable metering for a concrete Wifi-network, the dynamic icons still do not work (assuming I disable the metering correctly for a wifi network)

> I do not agree to the 'shall remember 404 statement'

There is zero chance, that requesting an icon within few milliseconds in a row several times, will return useful results, if the first call returned 404.  Skipping the subsequent requests (or caching the 404 request for 15 seconds) will reduce network traffic, server load and speed up the client.

**Comment by maniac103** [comment]
> I thought the flag does not apply to Wi-Fi, but apparently it applies. However it seems, that even if I disable metering for a concrete Wifi-network, the dynamic icons still do not work (assuming I disable the metering correctly for a wifi network)

A network being metered and data saver are orthogonal concepts. We currently key on the latter, but it may be worth a thought to apply the loading restrictions only to metered networks in the 'app data saver not explicitly enabled' case. @mueller-ma WDYT?

> There is zero chance, that requesting an icon within few milliseconds in a row several times, will return useful results, if the first call returned 404. 

We rely on OkHttp to do the caching. Apparently they disagree on that 'zero chance sentiment as well, as otherwise they would cache the 404...

**Comment by dilyanpalauzov** [comment]
> We rely on OkHttp to do the caching. Apparently they disagree on that 'zero chance sentiment as well, as otherwise they would cache the 404...

How about utilizing HTTP Negative Caching?  Once Jetty returns 404 for an icon, it tells the caller to cache the results for 3 seconds?

**Comment by mueller-ma** [comment]
> it may be worth a thought to apply the loading restrictions only to metered networks in the 'app data saver not explicitly enabled' case. @mueller-ma WDYT?

Makes sense. This is already tracked in #1934.

**Comment by dilyanpalauzov** [comment]
Is the request
> 2.1.1.1 - user [26/Jun/2022:21:48:06 +0300] "GET /icon/?format=SVG&anyFormat=true
appears too many times. The user agent shall request the file once and remember the 404-results.

for sitemap elements without `icon=""`?

**Comment by maniac103** [comment]
> Is the request ... for sitemap elements without icon=""?

No, those will yield an empty image without HTTP request. See [here](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt#L1544-L1547) ... constructing the URL you're seeing happens right below that part. So the options are
- omit `icon` completely -> no HTTP request
- `icon="x"` -> GET request for `/icon/x.svg?format=...` (may also be .png, depending on settings)
- `icon=""` -> the GET request you're seeing

We may want to fix the latter case and treat an empty string the same way as if `icon` was omitted.

**Comment by dilyanpalauzov** [comment]
I have no `icon=""` in the sitemap file.

**Comment by mueller-ma** [comment]
You could use `icon="none"` for no icon.

> We may want to fix the latter case and treat an empty string the same way as if icon was omitted.

👍

**Comment by dilyanpalauzov** [comment]
Since dynamic icons caus a l lot of HTTP traffic, there shall be options to turn them off, when:
* power saving is enabled
* network is metered, or
* data saving is enabled

`icon=""` is supposed not to cause network traffic, as opposed to `icon="none"`, therefore the former is better.

**Comment by maniac103** [comment]
> Since dynamic icons caus a l lot of HTTP traffic

Citation needed. We're talking about a few kB per image, which are additionally cached on multiple levels (short term as bitmaps in memory, and longer term on disk by OkHttp).

> icon="" is supposed not to cause network traffic, as opposed to icon="none", therefore the former is better.

Neither of both should cause network traffic. The latter isn't causing traffic as of now, and we'll fix the former as well.

**Comment by dilyanpalauzov** [comment]
I visit `/basicui/app` and observe the traffic.  Any time an icon is requested, the state is passed in the URL.  When the item is for Watts, it can have virtually 50 000 states (any number between 0 and 5000, like 2323.2 W and 2323.3 W are two distinct states, so once the consumption changes from 2323.2 W to 2323.3 W a new HTTP request is made for the icon).  Even with caching, for a single item with that many states, there are many HTTP request.  Plus, a lot of memory to store the results.

When an icon is delivered, it has “Last-Modified” header.  However the request does not contain the If-Modified-Since header, it contains instead `Cache-control: no-cache`.  (This is what Basic UI does.  I assume OpenHAB-Andoid does the same).  That said, whenever a state changes, there is a HTTP request.

As far as I can see, in Basic UI, this request is made for "dynamic icons" and "static icons” on each state change.  On my system, states can change every 10 seconds, so there are really a lot of requests for updated icons (even for items without `icon=`).

**Comment by maniac103** [comment]
> and we'll fix the former as well.

See #2961 

> This is what Basic UI does. I assume OpenHAB-Andoid does the same

That assumption is wrong. As mentioned before, we *do* use OkHttp's caching logic, and set 'Cache-control: no-cache' only in very specific cases, such as refreshing images that have the `refresh=...` widget parameter set.

**Comment by mueller-ma** [comment]
IMO this issue can be closed now. With #2961 no request is made for `icon=""` and the data saver on unmetered networks is tracked in #1934.
