### ISSUE TITLE
Improve "Device control subtitle" string

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2970]
As I also noted on Crowdin, I don't think this string describes the setting very well:
https://github.com/openhab/openhab-android/blob/ab128c13d8227bd24c33a71ec58b70d753dc7391/mobile/src/main/res/values/strings.xml#L141

This option is found under the "main settings" in the app, and there's not much context there that give it more meaning. `Device control subtitle` leaves a lot open for interpretation, and my first understanding was that it was about "Device controlled subtitles/caption" when playing video media. The German translation is `Beschreibung für Android-Gerätesteuerung`, which means something very different as I understand it, something like "Description for Android device-control". It's better, but still not very clear IMO.

I've tried to study the source code, and it seems to me like this is about a "tile feature" introduced in recent versions of Android. It's still unclear to me if this only applies to watches/wearables, or if it can also be useful on mobile devices. Regardless, I think it should include "tile" in some form or shape to make the connection clear.

Since I'm still not familiar with the "tile concept", I'm not sure, but I'm thinking that `Item tile subtitle` or maybe `Item tile description` would be a better fit..?

_Originally posted by @Nadahar in https://github.com/openhab/openhab-android/issues/2925#issuecomment-1177781298_

**Comment by Nadahar** [comment]
As I've never seen these tiles and don't really know what they do, it's hard for me to judge what would be the best. But I was also thinking that a sub-menu could be a solution, to give some "context". Maybe all the tile settings could be gathered there for example?

**Comment by mueller-ma** [comment]
The info "setting" can also contain a link to the docs: https://next.openhab.org/docs/apps/android.html#quick-access-device-controls
