### ISSUE TITLE
Only one sitemap available

### ISSUE THREAD

**Issue by Talw3g** [openhab/openhab-android#2998]
### Actual behaviour
No matter how many sitemaps I create in /conf/sitemaps, I only see the one already used by OH-android. If I delete it, then the app asks me to choose one from the list of all the sitemaps in /conf/sitemaps : once chosen, I cannot change it.

### Expected behaviour
All sitemaps should appear in the left drawer, and be freely switched between.
 
### Steps to reproduce
1. Connect the app to the OH server ; the default sitemap should appear
2. Add a new sitemap in /conf/sitemaps
3. Try to switch between sitemaps in the app

### Can you reproduce the issue in demo mode?
Don't know: I only see one sitemap in demo mode...

#### Client
* Android version: 12
* Device model: Fairphone 3+
* App version: 2.21.1-beta
* Build flavor: Foss
* Device language: English 

#### Server
* Server version: 3.3.0 Build 2961 (docker image)
* Reverse Proxy: Traefik
* Authentication method: user and password

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method: user and password

#### App log
Too long to paste here, see attached log file: [OH-android_log.txt](https://github.com/openhab/openhab-android/files/9255262/OH-android_log.txt)
</details>

Thanks,
Talw3g

**Comment by mueller-ma** [comment]
That's the default behavior, but it can be changed in the settings: Side menu entries => Show all Sitemaps in side menu.
