### ISSUE TITLE
Theme issues

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#300]
- Selection items are in bright themes black and in dark themes white and do not look like normal buttons that are mostly grey. See #537
- Version entry in settings is greyed out. (Saw this on a Oreo AVD, but not on a real 7 device) Edit: The version field in the settings has been removed.
- Menu isn't themed (Fix in #361)

![screenshot_2017-05-20-11-52-43](https://cloud.githubusercontent.com/assets/22525368/26275123/cf0d436a-3d59-11e7-92ce-b5fe9fd7e2b6.png)

**Comment by mueller-ma** [comment]
@digitaldan Can you explain how the themes work here? Android Studio says the theme HabDroid.black isn't used anywhere and in the preview the menu is themed

**Comment by digitaldan** [comment]
Sorry I missed this.  I have no idea, have not done any development around themes.

**Comment by mueller-ma** [comment]
Selection items are in bright themes black and in dark themes white and do not look like normal buttons that are mostly grey

**Comment by lolodomo** [comment]
@mueller-ma : isn't it fixed now ? I see now the right menu dark when the theme is dark.

**Comment by mueller-ma** [comment]
The first point isnt fixed.
