### ISSUE TITLE
Beta version has been removed by Google from Play Store

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3012]
Mail from Google:

![grafik](https://user-images.githubusercontent.com/22525368/187280071-0244487f-8d28-45e6-8864-ce273e7f7c0a.png)

I submitted a appeal as Google publishes beta versions as an own app as well: https://play.google.com/store/apps/details?id=com.chrome.beta

**Comment by rkoshak** [comment]
With the release of 2.22 I assume that now the main app is now ahead of any beta version app we've installed from the play store previously, correct?

It's totally bogus that they removed it. *Lots* of apps have a beta version on the store). I anxiously await their resolution.

**Comment by mueller-ma** [comment]
In the appeal I submitted I mentioned the Google Chrome Beta, but it seems that the Play Store rules don't count for them....

The beta version could also be published in the beta channel of the app. This means that you cannot install beta alongside the stable version. For this the `.beta` suffix of the package id has to be removed for fullBeta, but kept for fossBeta (because the beta version is still on F-Droid and F-Droid doesn't support channels).

> With the release of 2.22 I assume that now the main app is now ahead of any beta version app we've installed from the play store previously, correct?

Correct. You could download the beta version from https://github.com/openhab/openhab-android/releases, which can be installed alongside the stable version.

**Comment by mueller-ma** [comment]
I will submit future stable version in the open test track before deploying it as production.

You can join at https://play.google.com/apps/testing/org.openhab.habdroid
