### ISSUE TITLE
Time Display is not shown corectly in Charts 

### ISSUE THREAD

**Issue by learnlinuxnow** [openhab/openhab-android#3050]
### Actual behaviour
Wenn Displaying Charts included in sitemap time US shown in UTC. 

### Expected behaviour
Time which is shown shall be the settedlocal timezone of openhab. 

#### Client
* Android version: 12
* Device model: pixel3a
* App version 2.22.0
* Build flavor  Play Store
* Device language: German

#### Server
* Server version: openhab3.3 stabile build
* Reverse Proxy: nginx 
* Authentication method api

#### openHAB Cloud
* myopenhab.org:

**Comment by mueller-ma** [comment]
How does Basic UI handle this?

**Comment by mueller-ma** [comment]
The app requests the chart as image on the server, so the time zone is controlled by the server. There are some regional settings on https://<openhab_server>/settings/services/org.openhab.i18n

I can confirm that my openHAB 3 server returns charts with my time zone.
