### ISSUE TITLE
Webview and target="_blank"

### ISSUE THREAD

**Issue by marcoNieddu** [openhab/openhab-android#3072]
### Actual behaviour
Describe us what happens
An hiperlink with target="_blank" into sitemap.webview is not open in external web browser

### Expected behaviour
Describe us what should happen
Open url into the web browser
 
### Steps to reproduce
1. Describe us how to reproduce the issue
2. Use a list for it

#### Client
* Android version: 
* Device model: 
* App version : 
* Build flavor : 
* Device language: 

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: 
* openHAB Cloud version : 
* Authentication method : 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by mueller-ma** [comment]
The webview widget opens the website in an external browser, if the host of the new site doesn't match the current one: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/ConnectionWebViewClient.kt#L61-L74

AFAIK there's no way to read the `target` value of a link in this function.
