### ISSUE TITLE
send items information to tablet or smartphone

### ISSUE THREAD

**Issue by mclassen2** [openhab/openhab-android#3075]
i am disappointing development of HABPanelViewer app I grues they lost interested of programming laugauge
HABPanelViewer not comparability with android 12 or newer there of feature have is sent iteam sever to tablet or smartphone
for example motion detection from openhab sever sent to tablet to turn screen on can you willing port from HABPanelViewer to openhab android app?
it called device control
link address: https://github.com/vbier/habpanelviewer

I would want take over the HABPanelViewer app if I know lot about  programming laugauge but I know only basic HTML

**Comment by mueller-ma** [comment]
A new preference category could be added to "Send device info to server" containing Items that can only be updated when the app is running.

**Comment by mueller-ma** [comment]
I misunderstood your feature request. Turning the screen of the tablet on when the server requests it has been requested in #150 already.
