### ISSUE TITLE
Black text on dark backgroud is hard to read

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3077]
This is how in dark mode OpenHAB-Android 2.23.2-beta shows error messages from the server:
![Screenshot_20221106_161140_org openhab habdroid beta](https://user-images.githubusercontent.com/4992947/200175854-fc87e3ed-3a6f-44bd-8953-0c4ec4f982ec.jpg)

**Comment by mueller-ma** [comment]
Do you know if that's a regression of the Material 3 update?

**Comment by dilyanpalauzov** [comment]
No, but I have not seen this screen before, or at least not in this contrast.  It appears while openHAB is booting and there are no other errors (like 404, or the answer was 0 bytes long).

**Comment by mueller-ma** [comment]
Which UI did you want to open? openHAB 3 main UI?

**Comment by dilyanpalauzov** [comment]
This error happens extremely seldom.  As far as I remember it appeared while raspberry Pi (openHAB-host) was booting, and openhab-Android requested the sitemap file.  But I am not 100% sure.

**Comment by mueller-ma** [comment]
In case of an error of the main page (not for subresources like CSS or pictures) the webview should be replaced by a custom view with high contrast text: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt#L341-L347

For some reason this didn't happen here.

**Comment by dilyanpalauzov** [comment]
> Which UI did you want to open? openHAB 3 main UI?

Yes, this happens with the openHAB 3 main UI and does not happen with Sitemaps.
