### ISSUE TITLE
F-Droid screenshots are not in Material 3 design

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3078]
openHAB-Android 2.32.2-beta moved to Material 3 design.  The screenshots in F-Droid for openHAB-beta are now outdated.

**Comment by mueller-ma** [comment]
I want to gather some more feedback before I create new screenshots.

**Comment by hmerk** [comment]
This is definitely not a bug, as it has no impact on functionality.
@dilyanpalauzov Please remove bug label.

**Comment by dilyanpalauzov** [comment]
I do not know how to remove the bug label.
