### ISSUE TITLE
Outdated screenshots on google play

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#309]
It shows an openhab 1 installation. I can do some screenshots and upload them here, but I dont have nfc, voice crontroll or myopenhab set up

**Comment by mueller-ma** [comment]
@digitaldan Picture number 19 is still old. Can you remove it?

**Comment by mueller-ma** [comment]
I created some new screenshots and would like to add an title to them (e.g. like this https://medyo.github.io/assets/images/playstore-generator-demo.png).

Welcome to openHAB - empowering the smart home:
![1](https://user-images.githubusercontent.com/22525368/56366565-bbf73b80-61f3-11e9-87b5-75ca56e07120.png)

"Turn on the lights in the living room": 
![2](https://user-images.githubusercontent.com/22525368/56366568-bbf73b80-61f3-11e9-91a6-d06aca01a6d1.png)

(No title):
![3](https://user-images.githubusercontent.com/22525368/56366569-bbf73b80-61f3-11e9-891c-01175d3dd5c2.png)

Item control can be bound to NFC tags:
![4](https://user-images.githubusercontent.com/22525368/56366571-bbf73b80-61f3-11e9-98c2-7412ec5681f4.png)

Keep track of you devices:
![5](https://user-images.githubusercontent.com/22525368/56366572-bbf73b80-61f3-11e9-8c7f-a01c3cafa6e7.png)

Access HABPanel:
![6](https://user-images.githubusercontent.com/22525368/56366573-bc8fd200-61f3-11e9-88ef-163400cf1177.png)


Maybe adding a screenshot of "Group demo" with the title "Never forget open windows when leaving your home" or similar.

**Comment by mueller-ma** [comment]
Here's a preview of phone screenshots:
![image](https://user-images.githubusercontent.com/22525368/56422098-194bc500-62a6-11e9-9be9-98b43e9b755a.png)

**Comment by mueller-ma** [comment]
![image](https://user-images.githubusercontent.com/22525368/56472159-6a50ea00-645b-11e9-9d32-820b637234cb.png)

We need to find a good title for the "Widget overview" screenshot.

**Comment by maniac103** [comment]
> Suggestion: "Choose from a variety of UI elements"

As this is about the Android app, wouldn't something like `Full support for all openHAB widgets` be more appropriate?
(Same for the Astro binding screenshot, as you can't install addons in the Android app)

**Comment by mueller-ma** [comment]
IMO the target group should be every (tech-savvy) play store user and not only openHAB users. I mean "Full support for all openHAB widgets" will help us to win the competition against other apps for openHAB on Android, but not against other smart home solutions.

**Comment by mueller-ma** [comment]
I don't have unlimited exports on the website where I build the screenshots, so I want to wait until #1346 is fixed and #1358 is merged.

**Comment by mueller-ma** [comment]
The website I used for the screenshots above doesn't allow free exports without watermarks anymore.
