### ISSUE TITLE
Add pinch zoom

### ISSUE THREAD

**Issue by s0170071** [openhab/openhab-android#3139]
### Is your feature request related to a problem? Please describe.
Sometimes I cannot read the font on e.g. the axis of graphs.

### Describe the solution you'd like
Pinch zoom throughout the app.

### Describe alternatives you've considered
Make a screenshot and zoom it. No kidding, this is what I do now.

**Comment by mueller-ma** [comment]
You can configure the scalling of charts in the settings. For regular images you can tap on them to see them fullscreen and pinch zoom then.

> Pinch zoom throughout the app.

Where exactly do you want to have it added?

**Comment by rkoshak** [comment]
> Where exactly do you want to have it added?

The whole screen, similar to how it works in the browser. If I don't have my reading glasses I often cannot read the text as it's displayed in a sitemap or MainUI. In the browser I can pinch to zoom in on a row or widget to make it temporarily big enough to read. 

For sitemaps I could see maybe something like a long press or the like to temporarily blow up a single row or some other similar implementation but I'd also like to have this for MainUI for which I can't think of any other intuitive approach beyond pinch to zoom.

In fact, currently, while I have the android app installed to get notifications and send info to Items like the alarm clock, to interact with it I use the browser because of the support for pinch to zoom.

**Comment by maniac103** [comment]
Supporting that throughout the app unfortunately isn't possible. It's simply not supported by the UI framework. There's a 'display size' (not font size) setting in Android settings which can be used to scale up all UI elements. I'm not aware of any other option for native UI control scaling (besides duplicating each and every layout file, which isn't feasible from a maintainability point of view).

**Comment by maniac103** [comment]
Yes, that's exactly what I was referring to. Changing 'display size' works pretty well for mebut YMMV, obviously. In any case, the thing is: if you have issues to read small text, those issues won't apply to the OH app only.

**Comment by mueller-ma** [comment]
> Sometimes I cannot read the font on e.g. the axis of graphs.

@s0170071 In this case you can change the graph scaling in the app settings.

@maniac103 Do you think it makes sense to provide a setting that informs the user about the system-wide text scaling and redirect to it?

**Comment by maniac103** [comment]
> Do you think it makes sense to provide a setting that informs the user about the system-wide text scaling and redirect to it?

Not sure. I've never seen such a hint in any other app I've used so far. I'm also not aware of an intent action for the display/for size screen.

**Comment by s0170071** [comment]
Using differnt font sizes creates other problems, like e.g. the labels on other widgets do not fit any more. Then you can only read the first characters which sometimes is not enough.  I thought it to be most intuitive if one could just do a pinch zoom, anywhere in the app. On charts and on the sitemap main page as well. 

Sometimes I make a screenshot and zoom that. Soounds stupid, I know, but it actually does the trick. I do that not because of labels but also for details of the charts. 

I think pinch zoom is just nicely intutive. What would also be nice is if one could scroll to the past on graphs. 
Yeah I know, this is  probably not feasible but yet it would be brilliantly intuitive. And useful. Kind of mitigates that zoom issue.

What if the graph would actually be some sort of a html iframe whith an oversized png fitted into the available space. Wouldn't that make it zoomable ?

**Comment by mueller-ma** [comment]
> What if the graph would actually be some sort of a html iframe whith an oversized png fitted into the available space. Wouldn't that make it zoomable ?

Instead of doing this I'd rather fetch the persistent values from the API and render the chart on the client. I assume that there are libraries for this that implement zooming and other gestures.
