### ISSUE TITLE
Ignoring the ssl certificate should give a warning

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab-android#314]
At the moment, if the user checks the checkbox to ignore all ssl certificates (better: trust all certificates), it is applied without any warning. This setting is more or less a security problem when used in the wrong way and we should warn the user, that he should use this option only, if he knows what he's doing and probably say, that he should do it only, if he wants to connect to his newly installed local Openhab (which comes with a self-signed certificate).

**Comment by mueller-ma** [comment]
Many apps use following concept: They show a warning when connecting to a host with an invalid ssl cert. Than you can trust it once, always or cancel.
This way the app would only trust a specific "untrusted" cert and not all.

**Comment by mueller-ma** [comment]
I just saw that the behavior I descriped was implemented before #275
