### ISSUE TITLE
Allow for more customization for device controls entries

### ISSUE THREAD

**Issue by depau** [openhab/openhab-android#3140]
### Is your feature request related to a problem? Please describe.

I find the device controls quite inflexible and inconvenient for most use cases.

- A custom name can't be applied; my items are configured in groups such as:
  >	- Air purifier [Group]
  >	   - Power [Switch]
  >	   - Speed [Dimmer]
  >  - Desk light [Group]
  >	   - Power [Switch]
  >	   - Brightness [Dimmer]
  >	   - ColorTemperature [Dimmer]
  
  So I can't simply add the "Power" item cause I'd have no idea of what's being toggled
- Things can't be grouped; I'd like the control for lights to be swipable (to control the brightness) and tappable (to toggle it); at the current stage I can only add two controls, and tapping the brightness one would turn it off by setting it to zero (losing memory of the previous brightness setting)   

### Describe the solution you'd like

I think it'd be really useful to have a new metadata type similar to that for Google Assistant that allows to:

- Override names and other settings
- Group multiple items together to create controls with complex traits

I'm okay with having creating a few proxy items if necessary to match the controls behavior, and/or with adding additional groups to match the semantics of the controls.

### Describe alternatives you've considered

The alternative I considered is going through Google Home, and that's what I'm currently doing, though that's not ideal since I'd rather talk to openHAB directly, for performance and privacy reasons.

**Comment by mueller-ma** [comment]
> The alternative I considered is going through Google Home, and that's what I'm currently doing, though that's not ideal since I'd rather talk to openHAB directly, for performance and privacy reasons.

Can you post a screenshot of that?

**Comment by depau** [comment]
Sure, sorry for having you wait.

The former is my Google Home device controls dashboard; the latter is the "add controls" screen for openHAB **beta** (from F-Droid).

<a href="https://user-images.githubusercontent.com/1151321/213277511-e54d5f37-2588-4a85-8f65-3cf9106b9ef6.jpg"><img src="https://user-images.githubusercontent.com/1151321/213277511-e54d5f37-2588-4a85-8f65-3cf9106b9ef6.jpg" width=300></a> <a href="https://user-images.githubusercontent.com/1151321/213277516-d86778b2-3179-411a-a7df-577f16f94c34.jpg"><img src="https://user-images.githubusercontent.com/1151321/213277516-d86778b2-3179-411a-a7df-577f16f94c34.jpg" width=300></a>

I must say that the Google-based solution is still far from what I'd consider to be ideal, but it's fully functional.

I can swipe on any dimmable device to change the brightness/volume/speed, tap to toggle the power, long press to open a view with more controls for that device.

The openHAB controls are all over the place, the items with an okay name you see are groups with a type. But for instance if I add the light to the controls I can only toggle it, not change the brightness.

I would at the very least like to be able to pair a Switch and a Dimmer into a single tile, then ideally also a sitemap that is displayed on long press.

**Comment by depau** [comment]
Maybe my model isn't configured properly though, here's a screenshot to give you an idea how I structured it:

![image](https://user-images.githubusercontent.com/1151321/213281337-93a5554e-d80e-4045-8a63-083200ec4c22.png)

I then have some additional non-semantic items for things that need extra hacks, such as this one that bundles the air purifier switch and fan speed dimmer into a single item that accepts on/off/speed setting.

![image](https://user-images.githubusercontent.com/1151321/213281824-6b49e441-d08a-40d5-a6ac-00b2fe55db0c.png)

**Comment by mueller-ma** [comment]
> But for instance if I add the light to the controls I can only toggle it, not change the brightness.
> I would at the very least like to be able to pair a Switch and a Dimmer into a single tile,

That does work currently. Which item type has the item you add as tile?

> then ideally also a sitemap that is displayed on long press.

It has to be discussed how the sitemap should be linked to that widget.

> Maybe my model isn't configured properly though

Can you click on "Scooter smart plug" and make a screenshot of the right side of the screen?

**Comment by depau** [comment]
> > But for instance if I add the light to the controls I can only toggle it, not change the brightness.
> > I would at the very least like to be able to pair a Switch and a Dimmer into a single tile,
> 
> That does work currently. Which item type has the item you add as tile?

I'm currently using the setup required for SpecialColorLight for Google Assistant, therefore

- Light group `ga:SpecialColorLight` (no group type) ← added as a tile
  - Switch (power) `ga:lightPower`
  - Dimmer (brightness) `ga:lightBrightness`
  - Dimmer (color temperature) `ga:lightColorTemperature`

I could change it to a different setup if needed, the current one is as it is because of the GA binding requirements, but it would be nice to have common conventions whenever possible.
 
> > then ideally also a sitemap that is displayed on long press.
> 
> It has to be discussed how the sitemap should be linked to that widget.
> 
> > Maybe my model isn't configured properly though
> 
> Can you click on "Scooter smart plug" and make a screenshot of the right side of the screen?

Here you go. No group type is set.

![image](https://user-images.githubusercontent.com/1151321/214388628-133931f1-33bb-438e-b90b-0ea4844c90d8.png)

**Comment by mueller-ma** [comment]
Ok, now I got your feature request. This seems like a bigger task as it requires some kind of Sitemap rendering based on Items in a group (compared to Widgets like in normal Sitemaps).
