### ISSUE TITLE
Limited number of selectable items on Sitemap 

### ISSUE THREAD

**Issue by vayavalla** [openhab/openhab-android#3161]
### Actual behaviour
Describe us what happens
I had a Sitemap with an item with selection and 18 posible options. Before, all were shown. Now only the first 16 are shown.

### Expected behaviour
Describe us what should happen
Unlimited posible selections
 
### Steps to reproduce
1. Describe us how to reproduce the issue
2. Use a list for it

Create a sitemap wit this entry:
Selection item=EmisoraDeRadioTodaLaCasa mappings=[
                    1="hr1", //
                    2="SER Valladolid", //2
                    3="COPE Valladolid", //3
                    4="1 Live", //4
                    5="Europa FM Huelva", //5
                    6="Europa FM Valladolid", //6
                    7="Kiss FM", //7
                    8="Los 40 Principales", //8
                    9="Onda Cero Valladolid", //9
                    10="Nadie Sabe Nada", //10
                    11="Informativo Ángel Martín", //11
                    12="Cuerpos Especiales", //12
                    13="Misterios Cotidianos", //13
                    14="El Partidazo de la Cope", //14
                    15="El larguero", //15
                    16="Buenos días Javi y Mar", //16
                    17="ZDF Nachrichten", //17
                    18="ARD Tageschau" ] //18

#### Client
* Android version: 13
* Device model: Xiaomi Mi 11 Lite 5G
* App version :  3.0.1
* Build flavor : Full
* Device language: Spanish

#### Server
* Server version:  3.4.1.
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: 
* openHAB Cloud version : 
* Authentication method : 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by xaziwb** [comment]
I have the same issue. 16 options from 25 are shown in portait mode. And only 6 in lansdcape mode.
