### ISSUE TITLE
Blank popup after a new OH version installation (probable theme issue)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#3163]
After installing a new OH version, the first time I run the Android app, I have 2 popups to validate, the second is about using an IP IIRC but the first one is always blank. This is certainly a problem of theme. My setup theme is "Sombre". The second popup has a grey/black background with white text, while the first has a white background with probably white text.

I open an issue only now but this is like that already since a long time. But it worked in the past.

**Comment by lolodomo** [comment]
In case you need to know what is exactly in that popup, I will change my theme to a white theme and I can see its content the next time I install a new OH version.
But I am almost sure this popup is about SSL certificate. I setup an HTTPS server using an IP.

**Comment by mueller-ma** [comment]
Should be fixed by #3232.
