### ISSUE TITLE
Selection bottom sheet not expanded in landscape mode

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3168]
### Actual behaviour
When my phone is in landscape mode and I press on a selection widget, the bottom sheet is opened, but only the title is visible. I have to swipe up to see the possible values.

### Expected behaviour
The sheet is expanded by default.

**Comment by mkrathome** [comment]
Hi, 

also the stepper-widget with the opening slider is affected. 

![Screenshot_2023-02-03-18-01-29-288-edit_com adobe reader](https://user-images.githubusercontent.com/123715591/216663128-03a5a5b7-e420-4834-a873-177c8333a09a.jpg)

All the Best 🖖🏻

**Comment by maniac103** [comment]
All bottom sheets are affected by this (color too). Potential solution: https://stackoverflow.com/a/54643203
