### ISSUE TITLE
Adjustable accent color for the new v3.x app?

### ISSUE THREAD

**Issue by tobiasisenberg** [openhab/openhab-android#3176]
### Is your feature request related to a problem? Please describe.
In the old v2.x app version, it was possible to change the accent color that was used for the menu backgrounds. In the new version, this color cannot be adjusted anymore. And not everybody may be happy with the salmonish color currently used in the new app version. ;-)

### Describe the solution you'd like
If possible, it would be great if something like the old setting of the accent color could be reinstated and that color would be used for the menu/frame title backgrounds.

### Describe alternatives you've considered
I thorougly searched but did not find a way to adjust the color.

### Additional context
Screenshot of the old menu with the accent color:
![Screenshot of the old menu with the accent color](https://user-images.githubusercontent.com/32764273/216010843-42c31b73-3177-4ddb-929c-4424935ef07b.jpg)

**Comment by maniac103** [comment]
That control was removed, but we introduced adoption of the color palette to the wallpaper color - see #3166.

**Comment by tobiasisenberg** [comment]
I did check out the setting of the wallpaper colors, and the color palette was set to blue-gray-black (apparently from my dark blue wallpaper), yet the accent color in the (beta) app was still salmon. I changed the wallpaper color palette by enabling the color palette setting and then picking one from the wallpaper color options that did not include the samlon color, yet still no change in the app. Even after restarting the app. Any suggestions on how to then affect the color in the app, maybe I am looking at the wrong location? Another question, what about Android version before 12 that do not have the wallpaper color options? Thanks a lot in advance!

**Comment by maniac103** [comment]
You need to enable this in the app: Settings -> Dynamic colors

> Another question, what about Android version before 12 that do not have the wallpaper color options?

For those devices currently no theme setting is available. Doesn't apply to you though, right? ;-) (Looks like LineageOS on OnePlus 6T, so you should be able to get Android 13)

As for why theme setup was removed, I'll defer to @mueller-ma (it was removed in #3061)

**Comment by tobiasisenberg** [comment]
Thanks a lot for the reply. But it does not help me:
1) I do not have the setting "Settings -> Dynamic colors" in the app (app version: 3.0.5-beta, tested on a tablet with Android 13)
2) It does apply to me: the OnePlus 6T is not on Lineage and will not be for a while, because Lineage (and similar alternatives) prevents me from using apps that check for the state of the bootloader (banking etc.). So I am stuck with Android 11, at least for now. Second, I and my family have more than one device, with various versions of Android.

**Comment by maniac103** [comment]
> app version: 3.0.5-beta

You need 3.0.6. Not sure whether it's in Play Store yet, but it's certainly available from the releases in this repo.

> OnePlus 6T is not on Lineage and will not be for a while, because Lineage (and similar alternatives) prevents me from using apps that check for the state of the bootloader (banking etc.).

ih8sn or Magisk are your friend ;-) (Writing this from a OnePlus 6 on Lineage 20)

**Comment by tobiasisenberg** [comment]
Thanks a lot, will check both things out!

**Comment by maniac103** [comment]
For the latter, [this config](https://github.com/maniac103/android_vendor_extra/blob/lineage-19.1/ih8sn/ih8sn.conf.enchilada) is sufficient for me to make banking apps work. Never used Magisk myself, since I build my LineageOS builds myself.

**Comment by mueller-ma** [comment]
> Another question, what about Android version before 12 that do not have the wallpaper color options? 

They won't have theming anymore. I removed this in order to make the migration to Material Design 3 easier and the app better maintainable. The new theming requires only a few lines of code and no duplication of resources.
