### ISSUE TITLE
Activate "Dynamic colors" by default

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-android#3185]
Version 3 changes the typical orange color of openHAB in the headers to a slightly weird brownish tone, which does not really seem to match the taste of many users and which also has no association to openHAB itself.

I noticed the setting "Dynamic colors", which in my case immediately improved my impression of the new design, as it chose the colors that I have anyhow selected for my OS. If a user does not like those colors, it is then clearly their own fault. 😎 

I'd therefore like to propose to enable that setting by default instead of having users to find it first. Wdyt?

**Comment by maniac103** [comment]
I don't have a strong opinion on this either way, I just have two remarks:
- Please be aware that after #3178 the frame color will change again to another color from the palette ('secondary container' -> 'primary container') to make the Basic UI theme work again. The new color is the one e.g. used as selection highlight in Gmail's navigation drawer.
- the 'slightly weird brownish tone' is just a lighter version of the OH orange ;-) The OH orange was used as primary (and secondary) color when building the palette. Or are you talking about dark more? I think the palette builder simply makes the colors darker in dark mode. You can try for yourself [here](https://m3.material.io/theme-builder#/custom)

**Comment by kaikreuzer** [comment]
> another color from the palette ('secondary container' -> 'primary container')

I don't think that will look any better when the OH orange is chosen as a primary color. So I would stick to the idea of this issue.

> the 'slightly weird brownish tone' is just a lighter version of the OH orange

Well, I think it is a color that Google thinks fits well to the OH orange. It might, but as the OH orange does not really turn up anywhere anymore in the UI, the different browns become the dominant color of the interface. With the old design, we had the OH orange in the title, the toggles and the subtitles, so it was really "primary" and actively used.

> Or are you talking about dark more? 

I indeed tested it in dark mode, but in light mode it imho doesn't look any better.

**Comment by maniac103** [comment]
> on't think that will look any better when the OH orange is chosen as a primary color. So I would stick to the idea of this issue.

What I was heading at was the dynamic theme looking different after that change, not the default one.

> Well, I think it is a color that Google thinks fits well to the OH orange.

It's a color an algorithm (developed by Google) thinks fit well to the OH orange. It's the same algorithm that extracts the colors from your wallpaper, just fed with a predefined color. [This section](https://m3.material.io/styles/color/the-color-system/color-roles#55d2b7d2-0202-4616-887e-f575a7946aac) talks about that algorithm a bit. It also shows how dark mode colors are not the same as light mode ones.

**Comment by mueller-ma** [comment]
Since the Basic UI theme (only the colors, not the exact look of the controls) is back again, I'd keep the themes for current installations as-is.
For new installations on Android 12 the dynamic colors could be enabled IMO.

**Comment by maniac103** [comment]
>  For new installations on Android 12 the dynamic colors could be enabled IMO.

On Android 12 the availability of dynamic colors is determined by [checking manufacturer and/or brand](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/color/DynamicColors.java#L368-L373). This is hard to replicate in (preference) XML. What about enabling it by default on Android 13+? That one is easy to do (have a string resource with the default value, overlay it in `values-v33`).

**Comment by mueller-ma** [comment]
It could be done in code here: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/IntroActivity.kt#L127

Doing it on Android 13+ is also fine, I guess.
