### ISSUE TITLE
When entering a subpage and turning the tablet in landscape, no entry is marked

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#319]
First: I selected "First Floor"
![screenshot_2017-06-19-20-21-56](https://user-images.githubusercontent.com/22525368/27299547-fa270b54-552c-11e7-9315-d2f50a225e4e.png)
Second: Turn tablet into landscape. How it looks:
![screenshot_2017-06-19-20-22-00](https://user-images.githubusercontent.com/22525368/27299548-fa2902e2-552c-11e7-9131-089e71d14561.png)
And how it should look:
![screenshot_2017-06-19-20-22-05](https://user-images.githubusercontent.com/22525368/27299549-fa293ca8-552c-11e7-9e91-ea775f49f18b.png)

**Comment by lolodomo** [comment]
In fact, it looks like when you remains in landscapoe mode and select in the left column, the selection appears a short time and then disappears when the right column is updated.
So there is something wrong even when remaining in landscape mode.

**Comment by mueller-ma** [comment]
The blue selection is now completly broken.
