### ISSUE TITLE
Slider max value more than 100%

### ISSUE THREAD

**Issue by dkneisz** [openhab/openhab-android#3194]
I have a "Dimmer" item for brightness that uses an mqtt Thing as a channel. The Thing has a min value of 0 and a max value of 254.
```
Type dimmer : brightness "Helligkeit" [
	stateTopic="zigbee2mqtt/LampLiving/brightness",
	commandTopic="zigbee2mqtt/LampLiving/set/brightness",
	min=0, max=254
]
```
In my sitemap I use a slider to display it:
```
Slider item=LampLivingBrightness label="Helligkeit [%d %%]"
```

In BasicUI (on my PC and on my Android phone) this shows up as a slider with the values from 0% to 100% selectable:
![image](https://user-images.githubusercontent.com/43378003/216943375-75563a11-c4fe-4569-9ac9-f5488911f339.png)

In the recent App 3.1.0 I can select more than 100%:
![image](https://user-images.githubusercontent.com/43378003/216943684-16da5721-14a4-4f2c-b6cb-c8547dad55ef.png)

I have the same behavior with other slider, and all of them use an mqtt-channel with min and max values. Sliders, that don't have a min or max value set, seem to work fine. 

#### Client
* Android version: 13
* Device model: Oneplus 9 Pro
* App version 3.1.0
* Build flavor: "Full"
* Device language: DE

#### Server
* Server version: openHAB 2.5.12
* Reverse Proxy: NginX

**Comment by rkoshak** [comment]
> I have a "Dimmer" item for brightness that uses an mqtt Thing as a channel. The Thing has a min value of 0 and a max value of 254.

This is your first problem. A Dimmer can only store a `PercentType` which can only store integers between 0 and 100. 

I believe when you configure an MQTT Channel like that, the binding will convert between 0-255 to 0-100 and back. So all that OH ever sees is 0-100. So already you can't get there from here unless you change to using a Number Channel as opposed to a Dimmer Channel.

> In BasicUI (on my PC and on my Android phone) this shows up as a slider with the values from 0% to 100% selectable:

So this will actually work as expected. And in many ways this is more intuitive to your end users anyway. 100% makes intuitive sense. 255, not so much. If you set the slider to 50%, either 127.5 will be published or 128 will be published (I don't remember if it rounds or not). 

But, if you *really* want to see a slider that goes from 0-255 instead, as mentioned above, you'll need to use a Number Channel and Item instead. Then you can configure the `Slider` element on the sitemap widget with a min, max, and step properties to set the beginning, ending, and how far each tick of the slider moves. Similar properties are available on the oh-slider-card on MainUI but I believe setting a semantic tag to "Setpoint" and setting the min and max in the Item's State Description metadata will generate a slider with the proper min and max range without setting a custom default widget.

**Comment by dkneisz** [comment]
@rkoshak you got that totally wrong. I don't want a slider that goes from 0 to 254. I want that, what BasicUI does, translate from 0-254 to 0-100. The issue here is, that in the app the slider is going from 0-254, when it actually should go from 0-100.

**Comment by rkoshak** [comment]
> The issue here is, that in the app the slider is going from 0-254, when it actually should go from 0-100.

OK, I had it backwards. So the problem is that in the most recent version of the Android app, the slider isn't just from 0-100 like it should be.

So the question would be, if you set the min and max properties on the Slider widget in the sitemap, what happens?

**Comment by dkneisz** [comment]
> > The issue here is, that in the app the slider is going from 0-254, when it actually should go from 0-100.
> 
> OK, I had it backwards. So the problem is that in the most recent version of the Android app, the slider isn't just from 0-100 like it should be.
> 
> So the question would be, if you set the min and max properties on the Slider widget in the sitemap, what happens?

When I change the slider to:
```
Slider item=LampLivingBrightness label="Helligkeit [%d %%]" minValue=0 maxValue=100
```
it is working in the app as it should. While this is a workaround, it should still work without it (I believe it has worked before the update to app version 3.x). If this bug only applies to openHAB 2.5 I could understand it, if this will not be fixed, but if it applies to openHAB 3.x also, this should be fixed. Since there is a workaround it's not super urgent, but you know how people get if they have to change their sitemap because of a bug (or inconvenience) in the app ;)

**Comment by dkneisz** [comment]
@rkoshak the part with "fixing the bug" was not directed at you, just a general comment from my side (or my point of view). Sorry if that did come over wrong.

**Comment by maniac103** [comment]
I don't quite get the expected behavior at. What the app is doing is 'if widget specifies a max value, use that, else if item specifies max value, use that, else use 100'. The fallback to the item values was added in #3102. Maybe that was a wrong idea? @mueller-ma What was the actual problem this PR intended to fix?

**Comment by dkneisz** [comment]
The expected behavior is, that the slider goes from 0 to 100 (if nothing else is set in sitemap). This is not the case here, since the slider goes from 0 to 254. That's the value that the MQTT binding uses for "translation". I don't have this case with another binding, since the MQTT binding is the only one I use that has this option.

**Comment by mueller-ma** [comment]
> What was the actual problem this PR intended to fix?

I added the following `stateDescription` to my radiator items:

![grafik](https://user-images.githubusercontent.com/22525368/217089712-b19f6b51-57b6-4478-aa4f-70bcca5ff043.png)

I would expect that the Setpoints in my Sitemap honor these values (temperature in Celsius), but they didn't. It felt strange to me that I have to configure these values twice. So I made #3102 to reuse the existing values, if they aren't overridden in the Sitemap.

In this case there's an Item that says: I can have values from 0 to 254. And then the Slider in the Sitemap should go from 0 to 100? How should the UI know that?
A possible solution would be: If no widget max value is defined and the label contains `%`, use 100 as fallback. Else use the item max value as fallback.

**Comment by dkneisz** [comment]
@mueller-ma no, the item itself stores values from 0 to 100. The MQTT binding just allows you to set additional max and min values, that are used to "communicate" (sending and receiving) with mqtt. In the docs it says (https://next.openhab.org/addons/bindings/mqtt.generic/#channel-type-dimmer):

>The value is internally stored as a percentage for a value between min and max.
>The channel will publish a value between min and max.

Also in BasicUI everything is working as expected. Just the app (I think since version 3.x) is somehow using the min and max values set in the MQTT thing as min and max values for the slider. The value of the item itself is between 0 and 100. You can see that in the screenshot of the app it says "100%" next to the slider. I have other sliders, that use the WLED binding, where I don't have this issue. There however you don't have this "translation" as with the MQTT binding. I also have another case (also with the MQTT binding) where min is set to 153 and max to 370, so I cannot even change the value in the app (because min > 100). Keep in mind, that these are only settings in the MQTT Thing, that do not represent the internal value of the item (according to the docs).

**Comment by maniac103** [comment]
I think the issue can be fixed simply by an item type check: the `min` and `max` values from the item's state description do not apply to `Dimmer` items, because those items are fed with `PercentageType`, which in turn has an implicit range of 0..100. For `Number` items, the current behavior is correct, I think.
I'll submit a PR.
