### ISSUE TITLE
Change color of "colorless" SVG icons dependent on design

### ISSUE THREAD

**Issue by moltke69** [openhab/openhab-android#3204]
If you use own SVG icons without any "color information" (like fill, stroke, ...) the used color is always "black" independent to the the design you use (light or dark). For light design this maybe ok, but for dark design, you cannot see the icon anymore.

![Screenshot_20230207-182555](https://user-images.githubusercontent.com/96469391/217319805-19aa3750-ae5c-40aa-adba-825dfbe005e1.png)  ![Screenshot_20230207-182635](https://user-images.githubusercontent.com/96469391/217319810-0c5b6c87-3d6a-4dc9-a633-814259f0b927.png)

Of course, it is possible to add colors in the SVG files, but if you want to be flexible (one user at home is using the light design, the other the dark design), you cannot use the same icons.

It would be great, if you can choose the default color (for colorless SVG icons) on the basis of the design or perhaps on the "dynamic colors based on the wallpaper".

Thank you.

_[This is my first feature request based on the app comparison with other smarthome apps for other smarthome-systems]._

**Comment by maniac103** [comment]
The request makes a lot of sense, but from a quick glance over the code of [the SVG library we're using](https://bigbadaboom.github.io/androidsvg/), it looks like it does not support setting such a 'default color'. I'll create a feature request in their repo.

**Comment by mueller-ma** [comment]
I opened a FR: https://github.com/BigBadaboom/androidsvg/issues/264

**Comment by mueller-ma** [comment]
@moltke69 You can use the keyword `currentColor` as color in the SVG icons. With #3282 it will be replaced by a suitable color.
