### ISSUE TITLE
Cannot use SIP client, as there is no way to grant microphone access to OpenHAB-Android

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3207]
I create a SIP-client card in Main UI 3.4. With OpenHAB-Android 3.0.5-beta I load the main page.  OpenHAB-Android shows:

> openHAB
> To use the SIP widget you must allow microphone/camera access in your browser and reload this page.

I do not know how to allow microphone/camera access to OpenHAB.

In F-Droid the application does not show that it requires Camera/Microphone access.

**Comment by dilyanpalauzov** [comment]
I can provide a SIP account for tests.

**Comment by maniac103** [comment]
Looks like we need to implement at least [this](https://developer.android.com/reference/kotlin/android/webkit/WebChromeClient?hl=en#onpermissionrequest). The flow probably is
- get onPermissionRequest callback
- check respective app permission
- if already granted -> call grant callback
- if not granted, forward request to app permission request and call grant/deny callback when receiving response for that
