### ISSUE TITLE
UI broken on Android API 22

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3219]
https://github.com/openhab/openhab-android/commit/d7db481e40f9f622612316bf2cbf93969c94d516 introduced a sever bug on API 22. UI elements won't vanish anymore when they should.

Directly after start: Progress indicator still shown
![Screenshot_2023-02-09-16-36-29](https://user-images.githubusercontent.com/22525368/217860090-0b2694dc-c254-44bf-8b9d-3171038d4f7f.png)

When scrolling the Sitemap:
![Screenshot_2023-02-09-16-36-33](https://user-images.githubusercontent.com/22525368/217860077-18e97e33-d25a-406e-89a5-e06a4ae0560f.png)

**Comment by maniac103** [comment]
I can not reproduce this on API 21 or 22 emulator. Can you?

**Comment by mueller-ma** [comment]
These screenshot are from my Amazon Tablet with FireOS (Android fork). I thought this issue applies to all devices with API 22.

I'll check it. Maybe it's an issue with a color resource in the Android namespace, e.g. `<item name="android:windowBackground">?android:colorBackground</item>`

**Comment by maniac103** [comment]
Never mind. I should have updated my local branch to latest `main` :man_facepalming: I'll check it.

**Comment by maniac103** [comment]
Found it: `android:colorBackground` must be a reference to a color resource on lower API levels.

**Comment by maniac103** [comment]
Change on the Android side probably happened [in 2018](https://android.googlesource.com/platform/frameworks/base/+/56c68bc296933fb5efbdce95499ecdef6fecafb6), so 'older API level' probably means '<= 28'.
