### ISSUE TITLE
Do not Disturb does not work and will be ignored

### ISSUE THREAD

**Issue by cinemarene** [openhab/openhab-android#3228]
I have now tested the whole thing on three devices (Oneplus Nord Android 12, Oneplus 7T Android 11, Google Pixel 7 Pro Android 13). On all devices it is the case that notifications from OpenHAB trigger vibration and/or ring tones if the respective device has activated "Do not disturb". The normal settings for ringtone/vibration and silent work. But if the device is set to vibration and ringtone, for example, but at the same time is set to "Do not disturb", then it still rings and/or vibrates.

**Comment by mueller-ma** [comment]
That's strange. I thought that the DND mode is enforced by the OS. Do other apps behave the same?

I'm quite sure that there isn't custom code in any other app that checks for DND.

**Comment by cinemarene** [comment]
I was thinking the same thing. But all other apps work normally, as they should. I also completely reinstalled the app once and checked the notification settings.

**Comment by mueller-ma** [comment]
Does this happen for notifications you send in rules only, or also for other notifications, e.g. these "failed to update item" notifications (they occur if you use home screen widgets or send device information like alarm clock).

**Comment by cinemarene** [comment]
I have just tested this and it is only if it is a notification from the rules.

**Comment by mueller-ma** [comment]
Maybe this happens because these notifications are declared as events: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt#L244

Did you configure an exception in DND for events?

**Comment by mueller-ma** [comment]
https://developer.android.com/reference/kotlin/androidx/core/app/NotificationCompat?hl=en#CATEGORY_EVENT()

> Notification category: calendar event.

That seems to be the wrong category.

**Comment by cinemarene** [comment]
> Did you configure an exception in DND for events?

No, I have not. I first became aware of severity through another thread (OH 4.0 notifications), which is what brought me to the problem I have just started here to discuss.

**Comment by cinemarene** [comment]
> > Notification category: calendar event.
> 
> That seems to be the wrong category.

Yes, I have set calendar appointments to bypass my "do not disturb".

**Comment by mueller-ma** [comment]
I remove the category for this notification at all. CATEGORY_MESSAGE is for incoming direct messages.
