### ISSUE TITLE
SectionSwitchViewHolder: MaterialButton.isCheckable not always set when view is recycled.

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3238]
`MaterialButton.isCheckable` is set for the overflow button, but not for regular ones. This can cause issues when the view is recycled.

https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt#L771-L786

**Comment by maniac103** [comment]
I'll take care of that; I want to refactor the overflow button handling anyway so the overflow button doesn't get layout weight anymore. In that refactoring this issue will be solved as a side effect.

**Comment by mueller-ma** [comment]
Maybe a more dynamic solution would be better: Display as many buttons as possible and add an overflow button only, if there's not enough space for all buttons. The button width should be based on the text width inside the buttons.

**Comment by maniac103** [comment]
That's also a *vastly* more complicated solution though ;-)
