### ISSUE TITLE
Setpoint (Slider) could generate unpredictable intermediate value changes events

### ISSUE THREAD

**Issue by dwrobel** [openhab/openhab-android#3241]
### Actual behaviour
Describe us what happens

I have the `Setpoint` configured as follows _(excerpt from the configuration)_:
- Item:
```Number:Temperature  R01_target_temperature  "Target temp. [%.1f %unit%]"  {channel="mqtt:topic:mosquitto:test_topic:R01_target_temperature", autoupdate="false"}```
- Thing:
```Type number : R01_target_temperature  [ stateTopic="test_topic/status/R01_target_temperature", commandTopic="test_topic/command/R01_target_temperature" ]```
- Sitemap:
```Setpoint item=R01_target_temperature step=0.1```

![image](https://user-images.githubusercontent.com/228873/218988188-37e2bdb1-4394-4a3f-a568-8e044a9228bd.png)

This is the example when I wanted to change _(slide)_ the value from 41 to 42 _(log at the MQTT level)_:
```
test_topic/status/R01_target_temperature 41.0
test_topic/status/R01_target_temperature 41.0
test_topic/status/R01_target_temperature 41.0
test_topic/command/R01_target_temperature 42.5
test_topic/command/R01_target_temperature 43.4
test_topic/command/R01_target_temperature 42
test_topic/command/R01_target_temperature 41.9
test_topic/command/R01_target_temperature 42
test_topic/status/R01_target_temperature 41.0
test_topic/status/R01_target_temperature 42.5
test_topic/status/R01_target_temperature 43.4
test_topic/status/R01_target_temperature 42.0
test_topic/status/R01_target_temperature 41.9
test_topic/status/R01_target_temperature 42.0
```
There are couple of issues:

 - there is more then one `command` being generated so it's difficult, later on, to analyze the history of the changes,
 - long time _(25 secs)_ before the final value stabilizes _(note that each `command` event takes ~5 seconds to be handled by the Modbus device which is connected through the mqtt2modbus proxy)_,
 - the intermediate values e.g. `43.4` destabilizes the controlled device _(in terms of power consumption, PID controller, etc.)_.

This is especially manifested on a phone in a vertical position where sliding a little bit changes the value more then you wanted _(imagine how unergonomic is to change the value from e.g. 41.0 to 41.4 in one shot - being sure that you don't slide below 41.0 and above 41.4)_.

### Expected behaviour
Describe us what should happen

On the old `Beta` version `2.20.16-beta` _(which I'm still using as a workaround)_ the same `Setpoint` allows to precisely set the value prior to generating the `command` event:
![image](https://user-images.githubusercontent.com/228873/218985988-e29e24c9-127a-4105-a216-c0aa36ba969a.png)
This was very elegant solution as it avoids all of the aforementioned issues. Please consider to restore the old behaviour or provide equivalent functionality.
 
#### Client
* Android version: 11
* Device model: 
* App version : 3.2.0
* Build flavor : Play Store
* Device language: English

#### Server
* Server version: 3.4.1
* Reverse Proxy: Apache
* Authentication method: password

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: self hosted
* openHAB Cloud version : 
* Authentication method :

**Comment by mueller-ma** [comment]
I see these possible solutions here, which could be combined as well:

1. Add a global toggle to control this behavior.
2. Increase the current timeout of 200ms. Could be set to a value that is (indirectly) controllable by the user, e.g. the time until a click counts as long click.
3. Make this timeout configurable by a new field in the sitemap.
4. Use server-side mitigation for this, e.g. https://community.openhab.org/t/debounce-4-0-0/143786

Please note that Basic UI does only allow to change this Item in 0.1 steps, so solution 4 is required anyway if you want to use Basic UI.

**Comment by maniac103** [comment]
#3244 tries to implement an option 5: dynamically determine whether to do updates during movement or not. It should cover this case (by not doing it for setpoints at all) and [this case from forums](https://community.openhab.org/t/sliders-not-working-on-android-update/143843/15) (by not doing it for rollershutters either).

**Comment by dwrobel** [comment]
>I see these possible solutions here, which could be combined as well:

IMHO 1..4 looks like an over-engineered solution compared to adding/restoring fully deterministic `Cancel/Set` approach.

>Please note that Basic UI does only allow to change this Item in 0.1 steps, so solution 4 is required anyway if you want to use Basic UI.

I'm aware of it, but it would be nice to have it fixed in `Basic UI`, to be in pair with `openhab-android`, rather then introducing server-side workaround.

**Comment by maniac103** [comment]
> I'm aware of it, but it would be nice to have it fixed in Basic UI, to be in pair with openhab-android, rather then introducing server-side workaround.

The cancel/set approach is the outlier, though: no widget (switch, section switch, slider, etc.) uses that approach, so the setpoint was adjusted to match. As mentioned above, #3244 will change the setpoint slider to only apply when you stop dragging the slider, which should be sufficient here.

**Comment by maniac103** [comment]
> This is especially manifested on a phone in a vertical position where sliding a little bit changes the value more then you wanted (imagine how unergonomic is to change the value from e.g. 41.0 to 41.4 in one shot - being sure that you don't slide below 41.0 and above 41.4).

Something I'm curious about: what kind of temperature are you setting there which *requires* setting a 0..100°C temperature in 0.1°C steps?

**Comment by mueller-ma** [comment]
With #3244 it might be unclear to the user how/when sliders send updates. 

> IMHO 1..4 looks like an over-engineered solution compared to adding/restoring fully deterministic Cancel/Set approach.

With solution 1 you could completely disable the current behavior and have "send when I release my finger". Maybe make a list preference: 
* All items
* Only numbers
* No items

**Comment by maniac103** [comment]
> With https://github.com/openhab/openhab-android/pull/3244 it might be unclear to the user how/when sliders send updates.

Yes, but generally one expects the UI to do The Right Thing™. For dimmer and rollershutter items the choice seems somewhat clear, it's just numbers that are a bit of grey area, because there could be both e.g. a dimmer (think some light attached via MQTT) or a setpoint behind it.

The only proper solution without magic would be
- specifying the behavior of `Slider` widgets
- allow overriding that behavior via sitemap option (similar to `switchSupport`)

I'm not sure something like that is going to happen, though.

**Comment by dwrobel** [comment]
>The only proper solution without magic would be
>   specifying the behavior of Slider widgets

I'm not sure I got the idea, please bear in mind that I'm not using [Slider](https://www.openhab.org/docs/ui/sitemaps.html#element-type-slider) but [Setpoint](https://www.openhab.org/docs/ui/sitemaps.html#element-type-setpoint) and while I could understand this kind of behaviour for [Slider](https://www.openhab.org/docs/ui/sitemaps.html#element-type-slider) _(btw. there is a possibility to specify updating frequency using: `sendFrequency=` parameter for it, please consult with the documentation)_, then I presume no one would expect this unpredictable behaviour for [Setpoint](https://www.openhab.org/docs/ui/sitemaps.html#element-type-setpoint) for which it doesn't make sense to send any intermediate values as there is no `sendFrequency=` parameter for it.

**Comment by maniac103** [comment]
> please bear in mind that I'm not using [Slider](https://www.openhab.org/docs/ui/sitemaps.html#element-type-slider) but [Setpoint](https://www.openhab.org/docs/ui/sitemaps.html#element-type-setpoint)

I got that part, and #3244 unconditionally disables that behavior for setpoints.

> in the 3.xx version the Setpoint element is implemented by the Slider widget?

No, it's not. The new setpoint bottom sheet just happens to use a slider, but it's completely unrelated to the `Slider` sitemap widget.

> possibility to specify updating frequency using: sendFrequency= parameter for it, please consult with the documentation

I indeed didn't know about that one, but `sendFrequency is used to distinguish between long and short button presses in the classic (web) frontend. This parameter defines the interval in milliseconds for sending increase/decrease requests.` [1] doesn't sound like it really matches our use case, which isn't about increase/decrease requests, but about the amount of time until the slider movement is considered stable enough to be sent out (in the form of the actual value, not `INCREASE` or `DECREASE`).

[1] I'm not sure whether you're aware of how Sliders looked in Classic UI. If you aren't, please see a screenshot [here](https://v2.openhab.org/docs/configuration/ui/classic/)

**Comment by mueller-ma** [comment]
I suggest to open an issue at openhab-core and discuss the behavior of sliders there. I just found out, that sliders Main UI behave the same way as the Android app, at least the one on the Item config page (https://openhab/settings/items/some_item)

Sitemap development isn't that dead as we always think. Two new settings have been added in 2022 and one is even undocumented and unsupported by this app: https://github.com/openhab/openhab-core/commits/main/bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext

**Comment by mueller-ma** [comment]
I created a topic to discuss this issue: https://community.openhab.org/t/define-slider-behavior/144714

**Comment by mueller-ma** [comment]
@dwrobel Please test version 3.4.2-beta.

**Comment by dwrobel** [comment]
Thank you for the info, I'll give it a try...

**Comment by maniac103** [comment]
> However, It still possible that you set the desired value and while releasing the finger it gets moved slightly changing the final value.

This brings me back to my question above:

> Something I'm curious about: what kind of temperature are you setting there which requires setting a 0..100°C temperature in 0.1°C steps?

If there's no necessity for that, setting proper min, max and/or step values seems like the most meaningful approach to that problem.

**Comment by maniac103** [comment]
> All of the temperature related settings in my heatpump can be adjusted with 0.1°C steps.

*Can be adjusted* != *need to be user adjusted in that granularity*

> But if that's not a valid use case then please simply imagine that the unit is [V] instead of [°C].

> Something I'm curious about: what kind of voltage are you setting there which requires setting a 0..100V range in 0.1V steps?

Seriously: 

> the UI is not limiting some of the applications

The new UI is somewhat harder to use in (at least as far as we know) niche or made up use cases to improve usability in its main use case, which is temperature sliders in the 15..30°C range - or more generally - values with a limited amount of possible values. As mentioned, the old UI was clunky to use in that case, and the controls used by it do not exist in the currently used control library. When designing UI, it's always a trade-off between use cases, there's no UI that perfectly fits all imaginable use cases. 
When there is a specific real world example where the new UI works poorly (which you didn't present yet) we can think about a possible solution, but I don't think it makes sense to do that for use cases that exist only in theory.

**Comment by dwrobel** [comment]
>setting a 0..100V range in 0.1V 

Controlling a power supply `0-30V`, `0-5A` with `0.01V` resolution is something absolutely minimum for every `5V` `±5%` compatible device. It's not too difficult to image, how danger this UI could be when your finger will 'slightly move' above `>5.25V`.

> != need to be user adjusted in that granularity

This approach perfectly breaks the "Rule of Diversity" [1].

[1] https://www.linuxtopia.org/online_books/programming_books/art_of_unix_programming/ch01s06_15.html

**Comment by maniac103** [comment]
> Controlling a power supply 0-30V, 0-5A with 0.01V resolution is something absolutely minimum for every 5V ±5% compatible device. 

And yet, every cheap bench supply only has 0.1V resolution, which reduces your example from 3000 to 300 steps, where a deviation of 2 steps is fine. I'm pretty sure this can be fulfilled by the current slider solution. For precise number input, there [also will be a solution](https://github.com/openhab/openhab-android/pull/3337).

**Comment by mueller-ma** [comment]
I wasn't a fan of this new slider in the beginning, but after using it for only a few days I realized how much faster you can set values.
For small value changed (e.g. `20.0 V` -> `20.02 V`) you can still use the up and down arrow buttons.

**Comment by mueller-ma** [comment]
The original request (sending updates while sliding) has been fixed for some Items (and maybe we have more control over this in the future: https://github.com/openhab/openhab-core/issues/3430).

As @maniac103 pointed out the now merged Input widget allows a precise input, when it's required. You need openHAB server 4, though.
