### ISSUE TITLE
Support parameter "yAxisDecimalPattern" of Chart widgets

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3246]
Added to the server in https://github.com/openhab/openhab-core/pull/2937

**Comment by maniac103** [comment]
What's great is that the number format specifier from state description JSON is *not* compatible with that parameter, so we'd have to massage [the former format](https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html) into [the latter format](https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html)
