### ISSUE TITLE
Popup slider also for Rollershutter-Switch

### ISSUE THREAD

**Issue by alltime84** [openhab/openhab-android#3247]
For Rollershutter-Switches it would be nice to also have the Popup-Slider beside the up, stop and down buttons just like the Setpoint-Widget.
I know I could use the Setpoint-Widget. But for Rollershutter-Items it is better to have up, stop and down than step-up and step-down.
**Would it be possible to also add the Popup-Slider to Rollershutter-Switches when you click on the line?**
Then it would support up, stop, down and position in one Widget.

Furthermore the up-arrow is currently triggering the down-command for Rollershutters. Any chance to revert it for Rollershutters?

![image](https://user-images.githubusercontent.com/15026656/219071675-3609aa48-2350-467c-9604-59e581a7d520.png)

**Comment by maniac103** [comment]
> Furthermore the up-arrow is currently triggering the down-command for Rollershutters

I can not reproduce that (using `main` branch): the left button triggers an `UP` command, the right one a `DOWN` command. Can you double check the app log for that?

> Would it be possible to also add the Popup-Slider to Rollershutter-Switches when you click on the line?

I think so, yes. I'll have a look into it, it seems like a good idea to me.

**Comment by alltime84** [comment]
> > Furthermore the up-arrow is currently triggering the down-command for Rollershutters
> 
> I can not reproduce that (using `main` branch): the left button triggers an `UP` command, the right one a `DOWN` command. Can you double check the app log for that? Edit: or are you talking about the case of (ab)using the Setpoint control for rollershutters? That one should only send item values though, not UP/DOWN...

Yes, I was talking about (ab)using the Setpoint. For some Rollershutters it is nice to move it in steps using the buttons.
For Switches it is working correctly.
But never mind. I think when there is a slider also for the switch, I will only use the switch.
