### ISSUE TITLE
Use theme colors for label- or valuecolor

### ISSUE THREAD

**Issue by alltime84** [openhab/openhab-android#3248]
I am using one of the dynamic theme colors of the app to have the values in a slightly different color than the labels to improve the visibility of the data:
![image](https://user-images.githubusercontent.com/15026656/219076765-ad453fbb-0a15-4cfe-afef-29509866fbff.png)

But I have to "hard code" the valuecolor. So If I change the Android-Theme-Color it might not fit anymore.

Would it be possible to select the theme-colors like:
valuecolor=["themecolor1"]

**Comment by maniac103** [comment]
You mean adding something like `primary` and `secondary` to [the list of known colors](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/res/values/arrays.xml#L93-L113)? That should not be much of a problem, albeit it'll obviously only work in the Android app, not in Basic UI or iOS.

**Comment by mueller-ma** [comment]
@alltime84 Can you open this feature requests in the repos for iOS and webui as well and link to this issue?

In a few weeks I'll add these two special colors to the docs and mention the supported UIs there.

**Comment by maniac103** [comment]
> Can you open this feature requests in the repos for iOS and webui as well and link to this issue?

Opening for web UI makes sense (primary/secondary are blue/pink there), but does the iOS app style even have the concept of primary and/or secondary theme colors?

**Comment by mueller-ma** [comment]
The iOS maintainers should at least know about it. Even a fallback to black is probably better than an undefinied behavior ("primary" is no valid html color) which might lead to crashes or invisible text.

**Comment by alltime84** [comment]
> `primary` and `secondary`

Thanks a lot for enabling this request!

I create a feature request for iOS:
https://github.com/openhab/openhab-ios/discussions/711

and for webUI:
https://github.com/openhab/openhab-webui/issues/1716
