### ISSUE TITLE
Allow different port than the default 9001 for Frontail

### ISSUE THREAD

**Issue by felixschndr** [openhab/openhab-android#3260]
I'd love to see a setting where the user can change the port of frontail. I am running frontail in a docker container with its internal port `9001` not exposed to the external port `9001` but to a different port to have port ranges per service (e.g. everything related to openhab gets ports between `5000` and `5999`)

Currently the port is [hardcoded](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/activity/FrontailWebViewFragment.kt#L34). I suggest to add a setting in the [server configuration](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/res/xml/preferences_server.xml). Maybe under `Advanced`

**Comment by mueller-ma** [comment]
> I suggest to add a setting in the [server configuration](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/res/xml/preferences_server.xml). Maybe under Advanced

Under Advanced it should be fine 👍
