### ISSUE TITLE
No Norwegian language option in "app language"

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3264]
From https://crowdin.com/project/openhab-android/discussions/19:

In the current (3.2.0) Android app, I can't set the language to Norwegian. Also, by default, it shows up in English although other apps are often in Norwegian (depending on if they offer it I suppose).

The question is thus if there is something that needs enabling that hasn't been enabled to make Norwegian available in the app.

It there's nothing obvious, there might potentially be an issue with the special Norwegian stupidity of having two "languages" that both claim to be "Norwegian". It's all stupidity, because it's not two languages, it's only slightly different ways to spell most words (with a few that are unique to each "variant"). There is a relatively small group in Norway that see this as somehow important for their "cultural identity" which has caused all the rest of us to live with this mess (all public texts must exist in both versions etc).

Regardless of the internal craziness of this, it has also "infected" the world of computers. There thus does exist 3 different ISO 639-1 codes for Norwegian: "no", "nn" and "nb" (corresponding ISO 639-2 codes are "nor", "nno" and "nob"). "no"/"nor" can mean either variant, but usually means the same as "nb" (Norwegian Book-language) that most of us use. But, as the most difficult people can claim that it could also mean "nn" (New Norwegian), it is somewhat controversial in some circles. I don't know how Android handles this, and if you must use one of "nb" and "nn", not "no". It's just speculation on my part, but it's a potential pitfall. If this is the case, I'd like to note that the translations I've been making here is in "standard Norwegian" aka "nb".

**Comment by mueller-ma** [comment]
@Nadahar Can you post the link to source code of an app that is in Norwegian on your device? Did you set your device language to `Norsk bokmal` or `Norsk nynorsk`?

**Comment by Nadahar** [comment]
@mueller-ma I'm sorry but I don't make Android software, so I don't have any example of an open source "app". The device language is set to `Norsk bokmål`.

**Comment by mueller-ma** [comment]
I was able to set the app language to Norwegian, when using the language code `nb` instead of `no`. It seems that Android doesn't handle `no` at all.
I replaced [Norwegian](https://crowdin.com/project/openhab-android/no) by [Norwegian Bokmal](https://crowdin.com/project/openhab-android/nb) in Crowdin. I was able to move 94% of the translations by export and import.

**Comment by Nadahar** [comment]
@mueller-ma What happened to the remaining 6%? It should be possible to export/import all..? I hope you approved them on import to.

**Comment by Nadahar** [comment]
@mueller-ma Please don't delete `no` from Crowdin until everything has been "transferred".

**Comment by Nadahar** [comment]
@mueller-ma If you give me "offline translation" privileges for `no` and `nb`, I can try to do the export/import myself and see if I can get them all. I'm the owner of one and the manager of another Crowdin project, so I know how to do it - and I've been able to export/import everything before.

**Comment by mueller-ma** [comment]
It seems that the import has issues when 
1. the translations is equal to the source string (e.g. "Video")
2. the source is XML

Crowdin is at least smart enough to share the TM between no and nb, so I was able to restore the translations.

I disable no now and here's a backup: [openhab-android (no).zip](https://github.com/openhab/openhab-android/files/10821539/openhab-android.no.zip)
