### ISSUE TITLE
`Disable screen timeout` has no effect

### ISSUE THREAD

**Issue by SteWers** [openhab/openhab-android#3273]
### Actual behaviour
When set `Disable screen timeout`, the display turns off after the time which configured in the device.

### Expected behaviour
Display stays on.
 
### Steps to reproduce
1. Set `Disable screen timeout`
2. Wait and see if display stays on

### Can you reproduce the issue in demo mode?
Yes

#### Client 1
* Android version: 13
* Device model: Samsung Galaxy XCover Pro
* App version: 3.2.0
* Build flavor: Full 
* Device language: DE

#### Client 2
* Android version: 9
* Device model: Huawei P10
* App version: 3.2.4-beta
* Build flavor: Full 
* Device language: DE

**Comment by maniac103** [comment]
Does it never work for you, or does it start working if you restart the app (as in: swipe it out of recents and start it again) after enabling the 'disable screen timeout' option?

**Comment by SteWers** [comment]
That does the trick. :-)
Thanks!

**Comment by mueller-ma** [comment]
It shouldn't need this workaround, so I reopen this issue.
