### ISSUE TITLE
Backend for kernel module in WireGuard breakes communication

### ISSUE THREAD

**Issue by zynexiz** [openhab/openhab-android#3276]
I just found a problem when I tried connect to my local OpenHAB instance thru WireGuard VPN. I knew it worked before, but now it didn't connect to the server. I did however work if I opened the URL in Firefox, so the problem had something to do with the application itself (or so I though, still might be the case?).

I did some tinkering inside OPNsense firewall, so first I though it had to do with that one. But the firewall didn't indicate that where any traffic at all from the phone to OpenHAB. As it turned out, I had activated something called "Backend for kernel module" inside the WireGuard application. When I disabled it, everything worked again.

All other applications I use works without issue when this module is activated, so I guessing it does something that OpenHAB do not like? I tried multiple versions of the app, all had the same issue. Nothing huge, but good to know if others run into same issue. Spent many hours before I found what caused the problem :)

![Screenshot_20230226-202744](https://user-images.githubusercontent.com/22789493/221432599-07e843d0-eb53-4ab1-9205-a33556338751.png)

**Comment by maniac103** [comment]
My guess is that it's detected as non-local network type. The template asks for the app log for a reason ;-)

**Comment by zynexiz** [comment]
> My guess is that it's detected as non-local network type. The template asks for the app log for a reason ;-)

Sorry for that, but you where correct. The logs indicate that it's on mobile network and not WiFi. Guess the kernel module makes the VPN work transparently in the background, thus not indicating that your not on cellular network. Found this in the logs;

```
02-26 21:03:04.445 18247 18247 D MainActivity: onActiveConnectionChanged()
02-26 21:03:04.446 18247 18247 D ContentController: Indicate no network (message Nätverk inte tillgängligt)
02-26 21:03:04.446 18247 18247 D PageConnectionHolderFragment: updateActiveConnections: URL list [], connection null
02-26 21:03:04.446 18247 18247 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=uicomponents_page_008bacda42, label=Hemma), wifiSsids=[], restrictToWifiSsids=false)
02-26 21:03:04.447 18247 18247 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=uicomponents_page_008bacda42, label=Hemma), wifiSsids=[], restrictToWifiSsids=false)
02-26 21:03:04.447 18247 18247 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=uicomponents_page_008bacda42, label=Hemma), wifiSsids=[], restrictToWifiSsids=false)
02-26 21:03:04.447 18247 18247 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=uicomponents_page_008bacda42, label=Hemma), wifiSsids=[], restrictToWifiSsids=false)
02-26 21:03:04.449 18247 18247 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=uicomponents_page_008bacda42, label=Hemma), wifiSsids=[], restrictToWifiSsids=false)
02-26 21:03:04.449 18247 18247 D MainActivity: Cannot auto select server: No server with configured wifi
02-26 21:03:04.449 18247 18247 I wm_on_start_called: [10444487,org.<openhab-local-address-openHAB>.habdroid.ui.MainActivity,handleStartActivity]
02-26 21:03:04.449 18247 18247 D MainActivity: onPostCreate()
02-26 21:03:04.450 18247 18247 D MainActivity: onResume()
02-26 21:03:04.455 18247 18247 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=http://<openhab-local-address-openHAB>:8080/, userName=<none>, password=<none>), remotePath=null, sslClientCert=null, defaultSitemap=DefaultSitemap(name=uicomponents_page_008bacda42, label=Hemma), wifiSsids=[], restrictToWifiSsids=false)
02-26 21:03:04.456 18247 18247 I wm_on_resume_called: [10444487,org.<openhab-local-address-openHAB>.habdroid.ui.MainActivity,RESUME_ACTIVITY]
02-26 21:03:04.459 18247 18247 I wm_on_top_resumed_gained_called: [10444487,org.<openhab-local-address-openHAB>.habdroid.ui.MainActivity,topStateChangedWhenResumed]
02-26 21:03:04.459 18247 18247 D EventListenerService: onStartCommand()
02-26 21:03:04.460 18247 18247 D MainActivity: onActiveCloudConnectionChanged()
02-26 21:03:04.461 18247 18247 D MainActivity: onPrimaryCloudConnectionChanged()
02-26 21:03:04.461 18247 18305 D ConnectionFactory: checkAvailableConnection: found types [ConnectionType(type = Mobile, network=100)]
02-26 21:03:04.462 18247 18247 D MainActivity: onActiveConnectionChanged()
02-26 21:03:04.464 18247 18247 D ContentController: Indicate missing configuration (resolveAttempted false)
```

**Comment by maniac103** [comment]
> Guess the kernel module makes the VPN work transparently in the background (think the option is only available with rooted devices), thus not indicating that your not on cellular network.

Yes, my suspicion is exactly that as well. In some cases this might be desired behavior, but our app uses the network type to select between local and remote connections, and mobile network always is considered a remote network.

**Comment by zynexiz** [comment]
> Yes, my suspicion is exactly that as well. In some cases this might be desired behavior, but our app uses the network type to select between local and remote connections, and mobile network always is considered a remote network.

Sounds logical now afterwards, didn't even realise the module did that until now. You always learn new stuff :) If anyone else run into same issue, they can find it here even if I would say it's a special scenario.
