### ISSUE TITLE
Support Sitemap widget Input

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3285]
~~I just discovered the Sitemap widget "List". What does it do and should it be supported?~~

A new sitemap widget `Input` was introduced: https://github.com/openhab/openhab-core/pull/3398
We need to add support for it.
NB: Also take care of https://github.com/openhab/openhab-core/pull/3418 in case it's merged.

**Comment by mueller-ma** [comment]
And there's also a new widget called Input: https://github.com/openhab/openhab-core/commits/main/bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext

We definitely need a place where all maintainers of Sitemap UIs come together, so new features aren't discovered "by accident".

**Comment by mherwege** [comment]
@mueller-ma @maniac103
Sorry if I took you by surprise on this. It has been on my wish list for a while, so I implemented the Input element myself in core and BasicUI.
I absolutely want to see have it in the Android App as well. I never looked at the Android app code and never touched Kotlin, but I am still willing to have a go at it. It will take time though, so don’t expect it soon from my side. And I wouldn’t mind if someone else takes it on. There is enough I can still contribute to.

**Comment by maniac103** [comment]
>  It is probably implemented in BasicUI but I have to confirm it and test it.

It is (I at least found it in the code). I wonder, though, whether the better option is 
- documenting it or
- removing the code for it

All it does is splitting up the (`String`, I suppose) item state at some separator defined in the widget, and then displaying the lines resulting from that beneath each other, so it's (AFAICT) essentially a multi-line text widget. Is this really that useful?

**Comment by lolodomo** [comment]
I tested the List widget in Basic UI and I should admit it does not work well ! No dynamic update of the value and more important it breaks the layout !
I was very annoyed with the idea to remove it (breaking existing setups) but if it was really used, we will have issue opened to fix it.

That being said, I believe we got a 4.0 wish to add such widget in 4.0. To be verified. If there is a real need, I can also try to fix it in Basic UI.

**Comment by maniac103** [comment]
> (breaking existing setups)

Given it was never documented, was it ever officially supported? Neither Android nor iOS apps do support it.

> I believe we got a 4.0 wish to add such widget in 4.0. To be verified.

If you find it, please also link it here :-)

**Comment by maniac103** [comment]
Support for List was removed from core: https://github.com/openhab/openhab-core/pull/3423
Changing scope of the issue to only cover the input widget.
