### ISSUE TITLE
Different corner radius on section switches

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3286]
### Actual behaviour

![Screenshot_20230301-170304_openHAB Beta](https://user-images.githubusercontent.com/22525368/222195267-78d98344-d787-44f3-b090-bac9dcf80d5e.png)

### Expected behaviour
The corner radius on the left side should be equal to the one on the right side.

**Comment by maniac103** [comment]
Probably just need to increase horizontal padding [here](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/res/layout/widgetlist_sectionswitchitem_overflow_button.xml#L10) a bit. My intention was to keep the overflow button as small as possible.
