### ISSUE TITLE
Navigation bar overlaps sitemap

### ISSUE THREAD

**Issue by SteWers** [openhab/openhab-android#3287]
**The navigation bar overlaps the sitemap at the bottom in version 3.3.2-beta.**
The problem doesn't exist in the release version 3.3.1. I believe it has to do with the PR https://github.com/openhab/openhab-android/pull/3277. 

### Actual behaviour
![NOK](https://user-images.githubusercontent.com/42718143/222232879-98a7f7fe-a7b2-4fe4-be7c-298635526c47.png)

### Expected behaviour
![OK](https://user-images.githubusercontent.com/42718143/222232954-8ebeee24-e591-47f4-9a0d-ae19767d76ce.png)
 
### Steps to reproduce
1. Install version 3.3.2-beta
2. Do not use full screen mode

### Can you reproduce the issue in demo mode?
Yes

#### Client
* Android version: 9
* Device model: P10
* App version: 3.3.2-beta
* Build flavor: full
* Device language: DE

**Comment by maniac103** [comment]
This is a mess *sigh* What about the status bar when e.g. showing Main UI?

**Comment by maniac103** [comment]
I'll see whether it's reproducible on an Android 9 emulator. Hopefully it's not a Huawei specific thing.

**Comment by SteWers** [comment]
The Main UI seems to be very close to the status bar, but no overlapping. The other pages are looking normal.
I just tested on an old Telekom tablet with Android 7.1.2. There is the same behavior as on the P10.

**Comment by SteWers** [comment]
This afternoon I saw, that the status bar is overlapped by the Main UI when you scroll a little bit down. It is transparent and there is no impact with the operation of the app. Just for info to you and sorry than I didn't recognized it yesterday.

![OH](https://user-images.githubusercontent.com/42718143/222496476-39376ee1-6f16-461a-8ae0-13289eaa2d48.png)

**Comment by SteWers** [comment]
As you're waiting for the next issue after merging #3293, I'll report the results of my quick tests:
The problems with overlapping are solved in Android 9 and Android 7. Thanks for that!

One thing I saw, is this:
![image](https://user-images.githubusercontent.com/42718143/223360770-7a7aace4-9f49-49c5-9ed9-76c4e8fe1376.png)
The weekday and date is cut in the Main UI.
It is related to: 
- Android 7 with app-version 3.3.5-beta and the release-version 3.3.1
- Android 13 with the release-version 3.3.1 (beta not tested here)

In Android 9 it is OK with beta and release version. 🤪

**Comment by maniac103** [comment]
>  The weekday and date is cut in the Main UI.

Looks like a WebView issue to me, since both the hamburger menu and the text below are part of the web page. I just tried it using an API 33 emulator (Android 13) with the demo server and it worked fine (no cut date). An API 24 emulator (Android 7) gives me just a white page and complains:
```
I/chromium: [INFO:CONSOLE(35)] "Uncaught SyntaxError: Unexpected token ...", source: https://demo.openhab.org/js/app.b85df14c3a7ad94c41f1.js (35)
```
:man_shrugging:
