### ISSUE TITLE
Beta does not show a sitemap-Group, while Stable and WebUI show it

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3307]
I have OpenHAB 3..4.2 and OpenHAB-Android 3.3.2-beta.  My sitemap contains several Groups of the form:
```
    Group item=rd_power label="ABC" visibility=[rd_online==OPEN] valuecolor=[rd_color=="green"="green", rd_color=="lime"="lime", rd_color=="red"="red", rd_color=="maroon"="maroon"] {
        Switch item=rd visibility=[rd_manual==ON]
        Text   item=rd visibility=[rd_manual==OFF] valuecolor=[ON="green", OFF="red"]
        Switch item=rd_manual mappings=[ON="Ръчно", OFF="Автоматично"] labelcolor=[OFF="green", ON="red"] visibility=[rd_manual!=NULL]
        Text item=rd_voltage
        Text item=rd_current
        Text item=rd_temperature
        Text item=rd_energy
        Setpoint item=rd_on_watts minValue=400 maxValue=3500 step=100
        Setpoint item=rd_on minValue=49.5 maxValue=55 step=0.1
        Setpoint item=rd_off_watts minValue=-100 maxValue=3500 step=100
        Setpoint item=rd_off minValue=48.5 maxValue=52 step=0.1
    }
```
where just `rd` is replaced with other prefix in the other groups.  This work usually reliably.  But I see right now that this particular group (rd-prefix) is displayed on the WebUI- (/basicui/app) , but not in openHAB-Android.  The value of `rd_online` is OPEN, so openHAB-Android shall display it.

When I use openHAB-Android 3.3.1 STABLE, that item is displayed.  So this appears to me to be a regression in openHAB current beta.

I have to say, that I use OpenHAB - Website and OpenHAB-Android for several months and this is the first time I observe this inconsistency.  As I said, I have other identical groups, and they are displayed correctly.

**Comment by mueller-ma** [comment]
Is this group the last one on the Sitemap? If so this might be a bug that has been fixed in a later beta version. Is it visible when you enable full screen mode?

**Comment by dilyanpalauzov** [comment]
This group is the last visible one in the sitemap.  If I move it to the top, then the last visible one is not shown.  The item is visible when I change to full screen mode.

**Comment by dilyanpalauzov** [comment]
>  If I move it to the top, then the last visible one is not shown. 
If I move it to the top, this particular group is then shown.  But the one which is at the bottom, is still not shown.

**Comment by maniac103** [comment]
Please try with 3.3.6-beta.

**Comment by dilyanpalauzov** [comment]
It is not in F-Droid yet.

**Comment by mueller-ma** [comment]
F-Droid has quite large delays (~1 week) currently.

**Comment by dilyanpalauzov** [comment]
This is off-topic here, but can you tell me why there are large delays with F-Droid and what is the plan to reduce these delays.

**Comment by maniac103** [comment]
It should be updated automatically, and the respective YAML file is at 3.3.6 already. I guess they have build server capacity issues; i do t think we can do anything about it.

**Comment by mueller-ma** [comment]
F-Droid stores the signing keys on an air gaped machine, so there's a manual step required as well. Maybe someone is on vacation, who knows.
I guess it's getting better in a few days.

**Comment by mueller-ma** [comment]
The update is now live on F-Droid.
