### ISSUE TITLE
Top bar hides date from Overview page

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3308]
This screenshot is from OpenHAB-Android 3.3.1 stable and 3.3.2 beta.  It displays the Overview page.

As can be seen the date and weekday, at the very top, are partially hidden by the top horizonal bar.

![Screenshot_20230311_191750_org openhab habdroid](https://user-images.githubusercontent.com/4992947/224505158-4b253240-4c17-464d-b1f2-f9cb7f8f0d4c.jpg)

**Comment by maniac103** [comment]
I can't reproduce this (on Android 13). What's your Android version? (The template exists for a reason ;-) )
Since both the top line (menu button etc.) and the date are both part of the web page, I suspect a main UI and/or system web view issue.

**Comment by dilyanpalauzov** [comment]
I use “EMUI 12”, so I assume this is Android 12.

**Comment by mueller-ma** [comment]
In the app log there should be a line "OS: XX" at the top. You can view the log in the settings (last entry). What number is XX in your case?

**Comment by maniac103** [comment]
EMUI 12 should be Android 11.

**Comment by dilyanpalauzov** [comment]
It is:

> OS: 10
