### ISSUE TITLE
device Information (Battery Level Update) don't work in a network without internet access

### ISSUE THREAD

**Issue by adnandela** [openhab/openhab-android#3313]
### Actual behaviour
Describe us what happens
i am using this app on a tablet that is connected to a wlan without internet access . 
Openhab is also in this network.So everything works fine.
Only this App don't update my Battery Level ITEM on openhab server . 
-->APP Notification : Wait for Network to update ITEM

### Expected behaviour
It should update the item when openhab server is reachable , independent of internet access of the wifi network

 
### Steps to reproduce
1.Use a WIFI Network without internet access , and try to update battery level of the android device

#### Client
* Android version: 
* Device model: 
* App version : 
* Build flavor : 
* Device language: 

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: 
* openHAB Cloud version : 
* Authentication method : 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by maniac103** [comment]
Please provide the app log.

**Comment by mueller-ma** [comment]
I guess the issue is the `NetworkType.CONNECTED` constraint on the workers: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt#L501

**Comment by adnandela** [comment]
![screenshot](https://user-images.githubusercontent.com/18698954/225237462-e13018de-57d5-4b69-b20e-8efd929e9530.png)

**Comment by adnandela** [comment]
[openhab-log.txt](https://github.com/openhab/openhab-android/files/10977063/openhab-log.txt)

**Comment by mueller-ma** [comment]
The mentioned constrained could be removed from the worker, but then WorkManager will try to update items even if no network is present. This will cause error messages for users when their phone is in airplane mode.

**Comment by mueller-ma** [comment]
Changing the behavior will make it worse for most people, so I'd keep it as is.
