### ISSUE TITLE
Used Libraries repeats ACRA three times

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3318]
When I select About -> Used Libraries ACRA appears three times in an identical manner.  ACRA shall be listed only once.

**Comment by felixschndr** [comment]
I cannot see ACRA at all and thus not reproduce this. I am using v. 3.4.0
![Screenshot_20230329_174146_openHAB](https://user-images.githubusercontent.com/45742226/228593249-2087d016-570f-4291-a1b9-29d0a86d8973.jpg)

**Comment by mueller-ma** [comment]
@felixschndr I guess you're using the version from GitHub or Play Store that uses Firebase for crash reports, not ACRA.
