### ISSUE TITLE
Key authentication how-to is empty

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#333]
https://github.com/openhab/openhab.android/blob/master/KeyAuth.md

**Comment by digitaldan** [comment]
@slawekjaranowski can you fill in the details the README please?

**Comment by slawekjaranowski** [comment]
Ok, I will try prepare something.

**Comment by slawekjaranowski** [comment]
Maybe better place for manual is documentations site:
http://docs.openhab.org/installation/security.html

Most of documentations about seccurity and remote connection are allready writen.

**Comment by mueller-ma** [comment]
I agree. It's better to have the tutorial for client ssl cert there

**Comment by digitaldan** [comment]
Yes, this would be a good solution.

**Comment by mueller-ma** [comment]
@slawekjaranowski Any updates on that?

**Comment by slawekjaranowski** [comment]
Hi,
I started some discussion on https://community.openhab.org/t/using-nginx-reverse-proxy-for-client-certificate-authentication-start-discussion/43064

**Comment by maniac103** [comment]
@mueller-ma Can close this one?
