### ISSUE TITLE
Support material and iconify as new icon sources

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#3339]
The icon at item level or sitemap widget level can now reference new icon sources (material, framework7, iconify).
As I am almost certain that the Android app is already using mainly the material font, it would be nice if the app could also consider "material" as new icon source.
I will not be surprised that it is only few lines of code to add.

**Comment by maniac103** [comment]
> As I am almost certain that the Android app is already using mainly the material font

It isn't. All used icons are manually imported vector drawables.

**Comment by lolodomo** [comment]
Bad luck.

**Comment by mueller-ma** [comment]
The iconify API can be used to fetch iconify and material icons:

- https://api.iconify.design/mdi/bulb.svg
- https://docs.iconify.design/api/queries.html

It requires some rework in the app to avoid sending the openHAB credentials to iconify.
