### ISSUE TITLE
Feature Request: Favorite items

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#334]
I have thought a long time how to access openhab faster than opening the app and I think I found a good solution: long press an item to select it as favorite.
Those items (maximum ~5, probably no slider or colorpicker) are used at three different places. Each of these places can be turn on seperatly and you have an option to only show them when on a specific wifi:

1. [App Shortcuts](https://developer.android.com/guide/topics/ui/shortcuts.html) (API 25+)
2. Android Wear watchface: Rise our arm and tab on a switch or see some text items. I dont really know how good it is to have a switch on the clock. And I dont know if an app can change the watch face, if not we can display a nice simple analog or digital clock, when we have to "deactivate" the watch face. (#73)
3. Persistent push notification: Very fast accessable, even from lockscreen.

Let me know what you think about this idea.

**Comment by digitaldan** [comment]
>App Shortcuts (API 25+)

I think that would be a great feature, we could also do this on IOS,  so our apps have parity with each other.  Would you retrieve all items from /rest/items and let the user pick from that, or are they items that are only contained in a sitemap? 

>Android Wear watchface:

I could not comment as I don't use an android watch

>Persistent push notification: Very fast accessable, even from lockscreen.

I'm not sure I understand how that would work?

**Comment by mueller-ma** [comment]
> I think that would be a great feature, we could also do this on IOS, so our apps have parity with each other. Would you retrieve all items from /rest/items and let the user pick from that, or are they items that are only contained in a sitemap?

Three options:

1. Let the user pick from those which are in the sitemap
2. Use all from a sitemap called "android-favorite" or similar. This way you could sync the items between all devices without any modifications needed in the oh server
3. Add some kind of attribute (maybe homkit tags) to mark a favorite. Idk if we can retrieve those tags through the rest api. Example: Mark your favorite light as favorite_person1 and configure the app to handle those as favorites.

> I'm not sure I understand how that would work?
Like a music player notification that you cannot swipe away

**Comment by digitaldan** [comment]
>Let the user pick from those which are in the sitemap

That sounds reasonable

>Use all from a sitemap called "android-favorite" or similar.

I would avoid specially named sitemaps

>Add some kind of attribute (maybe homkit tags) to mark a favorite.

This sounds reasonable as well, I would want to run it by kai if we did this as there is a discussion about how far we use tags in applications like this, but I like the concept.

**Comment by digitaldan** [comment]
>Like a music player notification that you cannot swipe away

So this would be in addition to the shortcuts? So if i had three shortcuts, I would have three persistent lock notifications?  What would happen if I clicked one?  Does it open the app or does it toggle the item? 

This leads me to another question, can the shortcuts and notifications contain complex widgets (slider, multi button, color wheel) or do they need to be simple buttons?

**Comment by mueller-ma** [comment]
> So this would be in addition to the shortcuts? So if i had three shortcuts, I would have three persistent lock notifications? What would happen if I clicked one? Does it open the app or does it toggle the item?

You would have one notification for all items. Imagine you are in a different app and want to toggle an item quickly. Going to home screen and using the shortcuts is not very fast. If you dont want to have the notification you can disable it. There are also many users without Android 7.1 which is needed for shortcuts.

> This leads me to another question, can the shortcuts and notifications contain complex widgets (slider, multi button, color wheel) or do they need to be simple buttons?

Shortcuts: Display text item or press them to toggle item state or set slider to predefiend value.
Notification: Display text item or click on a button inside the notification. The app will not be opened when doing this.

**Comment by mueller-ma** [comment]
1. App shortcuts are used to access HABPanel, notifications and voice recognition.
2. Wear support is tracked in #73
3. I don't think that's a good idea anymore.
