### ISSUE TITLE
Severity for notifications and notification actions

### ISSUE THREAD

**Issue by redeye86** [openhab/openhab-android#335]
I think it would be good to different levels of importance for the notifications. 

For instance, if i am on the go it is not that important to know that the washer has finished and i don't want to be disturbed because of that. But in case a burglar is triggering the alarm, water is leaking somewhere in the house or it's burning, i always want to notified of course.

As far as i could see there is already a severity parameter in the sendBroadcastNotification call. I guess it is just unused on the android side and has to be implemented. By the way, the upcoming android O release will support so called notification channels, which would fit together very well:
https://developer.android.com/preview/features/notification-channels.html#Importance

Additionally it would be great to have support for notification actions to be able to react to the events instantly. Example: Switch of the siren in case of false alarm. I am not sure how to handle that technically. Maybe you would pass an array of items with label, item and value from from within the rule.

**Comment by mueller-ma** [comment]
How should openhab distinguish between important and unimportant events?

**Comment by redeye86** [comment]
You have to specify the severity in the rules. It can be defined in the sendNotification call already:

https://github.com/openhab/openhab2-addons/blob/master/addons/io/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/NotificationAction.java

I would suggest to use the 5 levels of severity introduced with android o. The user can define which priorities will be shown. For backwards compatibility it would be good to have a configuration dialog in the app which allows to assign ringtones, vibration patterns, etc for each severity class.

**Comment by digitaldan** [comment]
Right now openHAB cloud is not sending the severity string to the GCM provider ( or ios for that matter), but it does receive and persist it from OH.   This is not hard to do however, we would just need a plan of how this would look in terms of the message format and how clients react to that.
