### ISSUE TITLE
Show NULL value of Switch toggles

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3358]
As described at https://github.com/openhab/openhab-webui/issues/1555 openHAB-Android shall highlight somehow Switch items, if they have NULL or UNDEFINED value.  That is: neither ON nor OFF.

I mean here sitemaps.

**Comment by dilyanpalauzov** [comment]
> how should a regular switch look like?

E.g. the toggling point can be in the middle (neither left/right =off/on).

**Comment by mueller-ma** [comment]
AFAIK that's not possible with the switch from the material package.

An icon could be displayed on the switch thumb: https://m3.material.io/components/switch/guidelines#7e33ceea-6cdf-4542-8d50-4b75ca23d887 Maybe a question mark?

**Comment by dilyanpalauzov** [comment]
There must exist somewhere in Internet a switch which can show three states.

Other possibilities:
- provide implicit `mappings=[ON="ON",OFF="OFF"] ` when there is no mapping and the value is NULL or UNDEFINED.
- render the value by spelling NULL or UNDEFINED (I think this currently displays `-`, even when the configuraion has suppressed showing the item-value.
- use an icon for the switch, one for NULL, one for UNDEFINED and document the meaning of the used icons.

**Comment by maniac103** [comment]
> There must exist somewhere in Internet a switch which can show three states.

I doubt there's a switch which *shows* 3 states, but allows *controlling* only 2 states.

**Comment by lolodomo** [comment]
> * provide implicit `mappings=[ON="ON",OFF="OFF"] ` when there is no mapping and the value is NULL or UNDEFINED.

The rendering with buttons or a small slider should be triggered by the presence of "mappings" in definition, and not depend on the item value. The user must keep the control of what rendering he decides.

> * render the value by spelling NULL or UNDEFINED (I think this currently displays -, even when the configuration has suppressed showing the item-value.

MAP can be used to display the value you like when state is NULL/UNDEF. But yes, it supposes you have requested to hide the item value.

By the way, a solution to show NULL/UNDEF values in a different way should not be thought only for a unique kind of widget (switch) but more generally to any kind of existing widget.

**Comment by dilyanpalauzov** [comment]
> The user must keep the control of what rendering he decides.

The user cannot decide to render NULL and UNDEFINED in some way, which is invisible, when the values are ON or OFF.

**Comment by dilyanpalauzov** [comment]
Will be there the same icon for NULL and UNDEFINED?

**Comment by mueller-ma** [comment]
It uses the same icon. Internally the app handles NULL and UNDEF equally. TBH I don't even know the difference between these two states.
