### ISSUE TITLE
CanvasText-color in SVGs on sitemaps does not change depending on the app light/dark mode

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3364]
I create the file office_phone.svg with this content:
```svg
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
<svg height="800px" width="800px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
	 viewBox="0 0 17.026 17.026" xml:space="preserve" style="color-scheme: light dark">
<g>
	<g>
		<path style="fill:CurrentColor" d="M6.719,0h-1.05C5.114,0,4.664,0.45,4.664,1.005v12.622c0,0.548,0.439,0.993,0.985,1.004
			c-0.172,0.875-0.945,1.538-1.869,1.538c-1.051,0-1.907-0.857-1.907-1.907V9.45c0-0.238-0.192-0.43-0.429-0.43
			s-0.43,0.191-0.43,0.43v4.812c0,1.524,1.241,2.764,2.766,2.764c1.397,0,2.554-1.044,2.737-2.393H6.72
			c0.555,0,1.006-0.451,1.006-1.006V1.006C7.725,0.451,7.274,0,6.719,0z"/>
		<path style="fill:CanvasText" d="M15.159,1.595h-7.01V13.89h7.01c0.472,0,0.853-0.381,0.853-0.852V2.447
			C16.012,1.976,15.631,1.595,15.159,1.595z M10.812,12.631h-1.49v-1.489h1.49V12.631z M10.812,10.556h-1.49v-1.49h1.49V10.556z
			 M10.823,8.495h-1.49v-1.49h1.49V8.495z M12.942,12.631h-1.491v-1.489h1.491V12.631z M12.942,10.556h-1.491v-1.49h1.491V10.556z
			 M12.952,8.495h-1.491v-1.49h1.491V8.495z M15.071,12.631h-1.49v-1.489h1.49V12.631z M15.071,10.556h-1.49v-1.49h1.49V10.556z
			 M15.082,8.495h-1.491v-1.49h1.491V8.495z M15.088,4.085H9.073V2.328h6.015V4.085z"/>
		<path style="fill:CanvasText" d="M3.696,13.89h0.521V1.595H3.696c-0.47,0-0.852,0.382-0.852,0.852v10.592
			C2.844,13.509,3.226,13.89,3.696,13.89z"/>
	</g>
</g>
</svg>
```
and a file a.html:
```html
<!DOCTYPE html>
<html style="color-scheme: light dark">
  <body>
    <img src="office_phone.svg">
  </body>
</html>
```
When I change the browser preference to dark or light mode, the image is accordingly with white background white image, or vice versa.

I create an Item in a sitemap file, which has the very same phone_office.svg file.

I expect that openHAB-Android 3.4.5-beta does change the colors in the SVG file, depending on whether the application is using dark or light mode.  But it does not: the `CanvasText` and `CurrentColor` are always shown in black.

* When rendering SVG icons, openHAB-Android shall adjust the so called System colors (Canvas, CanvasText, CurrentColor) depending on the light/dark app-mode.

**Comment by mueller-ma** [comment]
The library we use for rendering SVGs has two limitations:
1. `CanvasText` doesn't seem to be supported at all.
2. `CurrentColor` is only supported when written `currentColor`: https://github.com/BigBadaboom/androidsvg/blob/master/androidsvg/src/main/java/com/caverock/androidsvg/utils/SVGParserImpl.java#L3029-L3030

Would you like to open an issue at https://github.com/BigBadaboom/androidsvg/issues to improve the situation? openHAB uses CSS to pass a color: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt#L267

**Comment by dilyanpalauzov** [comment]
I filled https://github.com/BigBadaboom/androidsvg/issues/269 and https://github.com/BigBadaboom/androidsvg/issues/268.
