### ISSUE TITLE
SIP does not unregister when Main UI is left

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3380]
I have a SIP widget.  When I change from the Main UI to sitemaps I the SIP client does not unregister: send REGISTER with Expires: 0.  I think these shall be sent, so that the server frees resources.

openHAB 3.4.2, openhab-android 3.4.6

**Comment by dilyanpalauzov** [comment]
I filled https://github.com/openhab/openhab-webui/issues/1872 .  I suspect that the browser does not tell the webpage that it is unloaded, and therefore the wrbpage cannot handle events when left.  But I am not sure.  In such case, when the webpage is managed by openHAB-Android there shall be a reliable way to tell Main UI that it is unloaded.

**Comment by maniac103** [comment]
That could be double checked by opening Main UI in the browser (ideally on the phone).
