### ISSUE TITLE
Tooltip about icons in data saver mode appears, disappears then appears again for very short time and then disappears

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3393]
In openHAB-Android 3.5.2-beta I change under Settings Data saver to ON.  It shows the text “Sitemap elements that may require larger data transfers aren’t loaded”.  Then I go back to a sitemap. At the bottom is shown a tooltip “Icons aren't based on Item states, because data saver is turned on [Got it!]”.  This hint disappears by itself, possibly before it was read.  Then it appears again for a second and disappears again.

The problem report is in first place, that the tooltip appears for a second and then disappears.  This behaviour serves no purpose.

**Comment by mueller-ma** [comment]
There are three different duration for snackbars: short, long and indefinite. The data saver hint is already shown long and as there could be more snackbars in the queue, I want to avoid indefinite here.

> Then it appears again for a second and disappears again.

I can reproduce this issue with other snackbars as well, e.g. "connected to local".
