### ISSUE TITLE
HABDroid can't load charts

### ISSUE THREAD

**Issue by adarazs** [openhab/openhab-android#34]
Hi,

I have a relatively simple sitemap where I generate 3 charts of different time period and the HABDroid app can't display them. Sometimes it loads one of the 3 images but most of the time it's nothing.

items (relevant part):

```
Group gPhones
Switch phone_xxx "Phone 1 [MAP(phone.map):%s]" <network> (gPhones)
Switch phone_yyy "Phone 2 [MAP(phone.map):%s]" <network> (gPhones)
```

sitemap:

```
Chart item=gPhones period=4h refresh=300
Chart item=gPhones period=D refresh=3600
Chart item=gPhones period=W refresh=86400
```

In the server's event logs I only see that the HABDroid client re-requests the chart images over and over.

```
192.168.1.42 -  -  [27/Nov/2014:22:16:56 +0000] "GET /chart?groups=gPhones&period=4h&random=814808101&w=1080&h=540 HTTP/1.1" 200 10667
192.168.1.42 -  -  [27/Nov/2014:22:17:00 +0000] "GET /chart?groups=gPhones&period=4h&random=814808101&w=1080&h=540 HTTP/1.1" 200 10682
192.168.1.42 -  -  [27/Nov/2014:22:16:59 +0000] "GET /chart?groups=gPhones&period=D&random=-2123270323&w=1080&h=540 HTTP/1.1" 200 16096
192.168.1.42 -  -  [27/Nov/2014:22:17:03 +0000] "GET /chart?groups=gPhones&period=4h&random=833497091&w=1080&h=540 HTTP/1.1" 200 10589
192.168.1.42 -  -  [27/Nov/2014:22:17:05 +0000] "GET /chart?groups=gPhones&period=D&random=-1042861998&w=1080&h=540 HTTP/1.1" 200 16084
192.168.1.42 -  -  [27/Nov/2014:22:17:10 +0000] "GET /chart?groups=gPhones&period=4h&random=833497091&w=1080&h=540 HTTP/1.1" 200 10520
192.168.1.42 -  -  [27/Nov/2014:22:17:13 +0000] "GET /chart?groups=gPhones&period=4h&random=833497091&w=1080&h=540 HTTP/1.1" 200 10533
192.168.1.42 -  -  [27/Nov/2014:22:17:13 +0000] "GET /chart?groups=gPhones&period=4h&random=833497091&w=1080&h=540 HTTP/1.1" 200 10533
```

If I try to enter this URL in my browser it works. The images also load well in the classic UI.

I installed the Android Studio and set it up, tried to run the app in an emulator and I got "java.net.SocketTimeoutException". When I had security ON, then I got "java.io.FileNotFoundException: http://192.168.1.2:8080/chart?groups=gPhones&period=4h&random=660312469&w=1080&h=540" on the client side and I saw that OpenHAB gave 401 Unauthorized to the client. 

Log with security OFF: http://fpaste.org/154767/71279731/
Log with security ON: http://fpaste.org/154768/12805214/

I don't program in Java, so I'm quite clueless what happens but hopefully this will be helpful enough to solve it. Please let me know if you need more information.

HABDroid version: 1.5.1.1
OpenHAB version: 1.5.1 on Raspbian

Attila

**Comment by cingolanifede** [comment]
Hi, they work perfect! thanks.
