### ISSUE TITLE
Send device inforamation→Call state alternates colour of help link (question mark)

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3402]
In 3.6.1-beta under Settings → Send information about this device → Call state there is a question mark in the right top edge of the dialogue.  The colour of the question mark changes, depending on whether the toggle is on or off.

Since the availability of help information does not depend on whether this is enabled or disabled, the color of the circled question mark shall not change.

**Comment by mueller-ma** [comment]
Currently this is done on purpose. The help is still available when grayed out, so I see your point here.
