### ISSUE TITLE
Map shows location only after a refresh

### ISSUE THREAD

**Issue by felixschndr** [openhab/openhab-android#3412]
### Actual behaviour
The app shows the location of a `Location` item only after a refresh:
1. Open the app
2. Access a site with a `Location` item
3. --> Shows a map of the whole earth
4. Refresh (Slide down or go back and then back into the site)
5. Correct location is shown

### Expected behaviour
Show the location on first sight

 
### Steps to reproduce
See above
See [this](https://drive.google.com/file/d/1eRivv0viszKc7WwwmGNl-5n_fJOelvi4/view) screenshare to further demonstrate the issue

#### Client
* Android version: 3.4.0
* Device model: Samsung Galaxy S22 Ultra
* App version : 3.4.0
* Build flavor : Full
* Device language: DE

#### Server
* Server version: 3.4.3

#### App log
<details>
  <summary>Click to expand</summary>

[Log.txt](https://github.com/openhab/openhab-android/files/11593437/Log.txt)

</details>

**Comment by lolodomo** [comment]
I can confirm this issue.
I hope it can be reproduced by everyone. @maniac103 @mueller-ma : can you reproduce it ?

**Comment by maniac103** [comment]
Yes. I'll check it, it's likely related to async map loading.
