### ISSUE TITLE
Grafana Diagram not displayed

### ISSUE THREAD

**Issue by steand** [openhab/openhab-android#3413]
### Actual behaviour
The Grafana diagram not displayed. Only the frame and the time buttons are shown.
If I use the browser (Chrome on Android or Firefox on PC) the diagrams works already

### Expected behaviour
%

 
### Steps to reproduce
Config action "popup" -- Grafana chart with timeranges -- 

### Can you reproduce the issue in demo mode?
no Grafana

#### Client
* Android version: 13
* Device model: Samsung A54
* App version : 3.6.0
* Build flavor : 
* Device language: German

#### Server
* Server version: 3.4.1
* Reverse Proxy: 
* Authentication method :  User/Password

#### openHAB Cloud
* Self hosted cloud or myopenhab.org:  rPI (on Docker)
* openHAB Cloud version : 
* Authentication method : 

#### App log

*** Too long ***

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by mueller-ma** [comment]
Do you have Grafana in your Sitemap inside a WebView? Can you post a screenshot of it?

**Comment by steand** [comment]
I use the WebUI:
YAML:

> component: oh-label-item
config:
  action: popup
  actionAnalyzerItems:
    - Wetterstation_WindSpeed
  actionModal: widget:Grafana chart with timeranges
  actionModalConfig:
    URL: http://openhab:3000/d-solo/PVH-ratVk/myopenhab?orgId=1&refresh=1m&theme=light&{period}&panelId=6
    timerange: from=now-12h&to=now&var-zeit=15m;12h,from=now-24h&to=now&var-zeit=1h;24h,from=now-1w&to=now&var-zeit=1d;Woche,from=now-4w&to=now&var-zeit=1d;Monat,from=now-90d&to=now&var-zeit=1w;Quatal,from=now-1y&to=now&var-zeit=1mo;Jahr
    title: Windgeschwindigkeit
  icon: oh:Wind
  item: Wetterstation_WindSpeed
  title: Wind
slots: null

[http://bilder.myandres.de/share/Screenshot_20230604_064413_openHAB.jpg](url)
[http://bilder.myandres.de/share/Screenshot_20230604_064436_openHAB.jpg](url)

**Comment by mueller-ma** [comment]
> URL: http://openhab....

This could be a mixed content issue. Do you load the Main UI via https? Can you try to change the Grafana URL to https?

**Comment by steand** [comment]
I use Grafana and OpenHAB on the same RPi (local) without https. If I call the Grafana link direct the graphic is displayed.
Also, if I use the Chrome browser the link (action) to Grafana works.
[Screenshot](http://bilder.myandres.de/share/OH_App_Log-2023-06-13.txt)
Logfile from OH App (maybe it helps): [Logfile](http://bilder.myandres.de/share/Screenshot_20230613_072930_openHAB.jpg)

**Comment by steand** [comment]
Not closed

**Comment by steand** [comment]
I use Grafana and OpenHAB on the same RPi (local) without https. If I call the Grafana link direct the graphic is displayed.
Also, if I use the Chrome browser the link (action) to Grafana works.
[Screenshot](http://bilder.myandres.de/share/OH_App_Log-2023-06-13.txt)
Logfile from OH App (maybe it helps): [Logfile](http://bilder.myandres.de/share/Screenshot_20230613_072930_openHAB.jpg)

**Comment by steand** [comment]
OK it works.
