### ISSUE TITLE
Use weblate for translations

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#342]
Weblate offers free hosting for oss, has login via github and makes translations a lot easier.
https://weblate.org/en/hosting/

**Comment by mueller-ma** [comment]
@digitaldan If I get a "yes" I can start working on this. It would make translations much easier.

**Comment by jmvaz** [comment]
I can contribute with PT-PT language.

**Comment by mueller-ma** [comment]
You can fork the repository, copy the file mobile/src/main/res/values/strings.xml to mobile/src/main/res/values-pt/strings.xml, remove all lines with "translatable=false" and translate the other lines. Than open a PR.

**Comment by mueller-ma** [comment]
@ThomDietrich mentioned crowdin [here](https://github.com/openhab/openhab.android/pull/437#discussion_r148939226), however its not free.

**Comment by ThomDietrich** [comment]
https://github.com/marketplace/category/localization
https://github.com/marketplace/crowdin

Crowdin is completely free for open source projects and has a strong integration with GitHub.

**Comment by mueller-ma** [comment]
Ok, I didnt find that on their website. Is crowdin under a free license?

**Comment by ThomDietrich** [comment]
Found it here: https://crowdin.com/page/open-source-project-setup-request
Not sure what you mean by "under a free license". They are a company looking for paying customers offering an free open source plan to lure in the potential customers of tomorrow. Very much the same strategy as of GitHub, Slack, Trello and co ;)

**Comment by mueller-ma** [comment]
I mean with "under a free license": The weblate source code is under GPL: https://github.com/WeblateOrg/weblate

**Comment by ThomDietrich** [comment]
Ah I see. Well no it is not. For me the offered functionality is a strong argument: https://support.crowdin.com

**Comment by mueller-ma** [comment]
We can give it a try. I think @digitaldan must do the setup or can you do it?

**Comment by ThomDietrich** [comment]
Let's give @digitaldan the honor of final decision 😃 I technically could but this is clearly not my call to make.

**Comment by ThomDietrich** [comment]
@digitaldan if okay with you i can set up crowdin tomorrow. We are already using it in other repositories and it's quite nice. It would also be a good thing to have all openHAB projects translated there to attract more contributors.

@mueller-ma this will then also make your request for updated strings easier ;)

**Comment by ThomDietrich** [comment]
@digitaldan are there any concerns you want to discuss? The lack of a response tells me that there are unspoken issues!? I already created dummy projects. I'll trigger them once to create a PR so you can have a look at potential results.

Everyone interested, please have a look at: https://crowdin.com/project/openhab-android

**Comment by mueller-ma** [comment]
@kaikreuzer @ThomDietrich I miss https://github.com/openhab/openhab.android/tree/master/mobile/src/main/res/values-lt in crowdin.
I have a few questions about crowdin:

1. What happens, when the original (English) string changes?
2. Will new english string automatically be uploaded?
3. Does crowding automatically open a PR?
4. What happens, when I merge a translation via a PR? Will it be uploaded or overwritten?
5. Why is English at 0%?
6. Can anyone start translation, without any review in crowdin?
7. Can anyone open a new language?

**Comment by maniac103** [comment]
From my LineageOS experience I can say that the answer to 4 is 'it gets overwritten' ... in LOS, we thus have a policy of not touching translations in PRs (which IMHO is a good idea). For 6, I think there's a setting that only translations approved by proofreaders get exported.

**Comment by ThomDietrich** [comment]
@mueller-ma just a heads up: I'll answer some time tomorrow ;)

**Comment by mueller-ma** [comment]
@ThomDietrich Can you add some lines about crowdin to the readme?

**Comment by ThomDietrich** [comment]
Hey guys! 

I've added values-lt to the list.

1. Crowdin syncs regularly, will see the new/changed string and show this new string as untranslated. As Translator/Proofreader you should receive regular email notifications for such cases.
2. What's the difference to 1? Yes :)
3. Yes it does. At a later point it will no be as annoying as it is right now.
4. As we've just learned, turns out it will create a conflict. We should remember that.
5. Silly mistake. Because english is the base language and there is no values-en folder. I am not sure when/who would need this combination. I've removed english just now.
6. Yes, no. I guess you know that by now.
7. (Sadly) no. They would need to contact us first. That is why Kai selected many languages.

@maniac103 See: https://github.com/openhab/openhab-android/pull/589 😖

**Comment by maniac103** [comment]
@ThomDietrich I guess you now know why the mentioned policy was put in place ;-)

**Comment by mueller-ma** [comment]
> That is why Kai selected many languages.

He definitly missed klingon 😆 
Just kidding, but it exists in crowdin

**Comment by mueller-ma** [comment]
Crowdin is now in production, so I'm going to close this issue.

@jmvaz Feel free to submit PT translation.

**Comment by comradekingu** [comment]
@ThomDietrich Crowdin isn't gratis for libre software, it is only gratis for libre software that has no source of income. To me the point of using libre software automation software, is escaping tracking. Crowdin employs both tracking and profiling, and sells it to advertisers and data collection agencies. As per their terms and conditions.
Weblate is far superior as a tool and in terms of freedom. It has more and better translators, and produces greater translations and upstream fixes as a result.
