### ISSUE TITLE
Changing device orientation shall have no impact on data saving questions

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3420]
In data saver mode I tell openHAB-Android to load a chart.  The chart is loaded.  I rotate my device to 90 degrees (change its orientation).

OpenHAB hides the chart and ask again if it shall load it.

**Comment by mueller-ma** [comment]
After rotation the chart has a different resolution, so it needs to be downloaded again. So the current behavior isn't that wrong.

**Comment by dilyanpalauzov** [comment]
Agreed

**Comment by maniac103** [comment]
It should be. The client side chart data is not reloaded on rotation if it's still reasonably recent.
