### ISSUE TITLE
After `GenericItem.setCategory(…)` icons are not updated until manual reload

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3427]
A have a device with many measurements and I have an item for each of them: Number i1, Switch i2, Number i3, Number i4.  In a sitemap I want to have a Text item=i1 {Text item=i2, Text item=i3, Switch=i4} element.  The top-most Text shall present the state of the whole device.  When unfolded the many individual measurements shall also be displayed.

To see the state of the whole device on the Text item=i1 line, I use valuecolor depending on i2 and labelcolor depending on i3.  I want to change the icon of i1 depending on the state of i4.  I have this rule:
```
import org.openhab.core.model.script.ScriptServiceUtil

val ir = ScriptServiceUtil.getItemRegistry

rule "E1, E2, E3 on/off change"
when
  Item e1 changed or
  Item e2 changed or
  Item e3 changed
then
  (ir.getItem(triggeringItemName + "_power") as NumberItem).category = ir.getItem(triggeringItemName).state.toString().toLowerCase()
end
```
which does change the icon.

The problem is that in openhab-Android 3.6.2 the icon is not updated, until I manually trigger refresh of the content (pull down the data presented in the sitemap)

**Comment by lolodomo** [comment]
@mueller-ma and @maniac103 : please look at my comment in the Basic UI issue. Are you ok with me ?

**Comment by dilyanpalauzov** [comment]
I filled the same for Basic UI at https://github.com/openhab/openhab-webui/issues/1938.

**Comment by mueller-ma** [comment]
From my point of view this is a server-side issue, see my comment in https://github.com/openhab/openhab-webui/issues/1938#issuecomment-1609071710
