### ISSUE TITLE
In charts add an option “before”, while keeping the selected resolution

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3431]
For Charts, once loaded, in openHAB-Android I can change the duration of the displayed data: 1h, 4h, 8h, half-, one-, two days.

Some significant details are visible only when a small period of time is selected - 1h.  But once I select 1h as rendered duration, I cannot see that details for longer time ago.

Please add a function to go back in time:  When the chart shows in total 1h of data, that new functionality shall permit showing the second-last hour, the third last hour of data, and so on.

**Comment by maniac103** [comment]
That's a request for OH core. The API currently doesn't allow for that. See [here](https://github.com/openhab/openhab1-addons/wiki/Charts) for the docs on what's supported.

**Comment by mueller-ma** [comment]
I'd rather focus on charts that are rendered on the client, so you can swipe left/right and zoom in:  #3209
