### ISSUE TITLE
FR: Api 26 and adaptive icons

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#345]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

I will fix this soon (TM). I need the oh icon in

1. Both layers must be sized at 108 x 108 dp.
2. The inner 72 x 72 dp of the icon appears within the masked viewport.

**Comment by mueller-ma** [comment]
@kabili207 Do you have an Android 8 device?

**Comment by kabili207** [comment]
Yes, I do.

**Comment by mueller-ma** [comment]
Can you try [mobile-debug.zip](https://github.com/openhab/openhab.android/files/1401684/mobile-debug.zip)?
Adaptive icons doesn't seem to work in the emulator and I dont have a physical device.

**Comment by mueller-ma** [comment]
This one is complied with api 26: [mobile-debug.zip](https://github.com/openhab/openhab.android/files/1401692/mobile-debug.zip)

**Comment by kabili207** [comment]
Works nicely, although I can see black corners when using a square mask.
If you're having issues with the emular, try using the adaptive icon playground app. https://github.com/nickbutcher/AdaptiveIconPlayground

Surprisingly, the fist apk worked just fine as well, even though it was targeted for API 25.

![screenshot_20171020-071430](https://user-images.githubusercontent.com/1270500/31818625-eeb8925c-b566-11e7-8fce-18246f9d9d22.png)

**Comment by mueller-ma** [comment]
The foreground icon is way to large. @kaikreuzer can you upload the icon as svg?

**Comment by kabili207** [comment]
Ah, that would make sense. I forgot the was a ring around it.

**Comment by mueller-ma** [comment]
I have created the adaptive icons with the generator in Android Studio. Please test this apk (Complie and target api are 25):
[mobile-debug.zip](https://github.com/openhab/openhab.android/files/1424053/mobile-debug.zip)

**Comment by kabili207** [comment]
I'm not seeing the openhab logo with this build. It's just the default bugdroid head.

**Comment by mueller-ma** [comment]
Compiled with 26, but targets 25:
[mobile-debug.zip](https://github.com/openhab/openhab.android/files/1424262/mobile-debug.zip)

**Comment by kabili207** [comment]
It appears to be showing the icon correctly now, and behaves as it should.

![screenshot_20171028-092748](https://user-images.githubusercontent.com/1270500/32134774-507f00fa-bbc2-11e7-9c5c-e562b5af9f85.png)

**Comment by mueller-ma** [comment]
Great. Do you have openHAB cloud and can test if notifications still work?

**Comment by kabili207** [comment]
I do have openHAB cloud, but I never set up any notifications since I haven't had any need for them. If you give me a while, though, I can set up some to test with.

**Comment by mueller-ma** [comment]
Here is the source code of the apk: https://github.com/mueller-ma/openhab.android/tree/410-icon3

**Comment by mueller-ma** [comment]
@kabili207 Any updates on this? You can send a test notification from oh cloud. When that one shows up, I can open a PR for this change.

**Comment by kabili207** [comment]
I've confirmed the test notifications still work.

**Comment by mueller-ma** [comment]
My bad, #477 did add the adaptive icon, but there is still some work that need to be done for target api 26.
https://www.youtube.com/watch?v=7kD0ZYzJbYo
https://www.youtube.com/watch?v=Pumf_4yjTMc
