### ISSUE TITLE
App stops regularly

### ISSUE THREAD

**Issue by Mark-VG** [openhab/openhab-android#3473]
### Actual behavior
I run the Android APP on an tablet and have noticed recently that the APP keep stopping. If I get it in time I see a message asking about submitting logs, but this message is not always seen.

I have set app to send Crash Reports

I see there is an option to view logs, however these are cleared when the app starts - so not available for a crash?

### Expected behavior
The app to run mostly with no crashes/restarts

 
### Steps to reproduce
Not sure how to reproduce - looking for ideas to access to logs to see if I can find anything.

#### Client
* Android version: Andoid Version 7
* Device model: MW16Q9_3G
* App version : 3.7.4 beta (Same on 3.7.0) 
* Build flavor: Play Store
* Device language:  English

#### Server
* Server version: 4.1.0.M1
* Reverse Proxy: None (Local Lan
* Authentication method : user and password

#### App log
Lost on restart

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

**Comment by maniac103** [comment]
@mueller-ma Any crashes in Play console for that time?

**Comment by mueller-ma** [comment]
No, I don't see any crashes with the combination 3.7.0 and Android 7 for that device.

**Comment by Mark-VG** [comment]
I am now running a beta version. All I get in teh logs is:
```
-----------------------
Device information
Model: MW16Q9_3G
Manufacturer: Mecer
Brand: Mecer
Device: MW16Q9_3G
Product: MW16Q9_3G
OS: 7.0
Display: 1280x752, 1.0 density
Data usage policy: DataUsagePolicy(canDoLargeTransfers=true, loadIconsWithState=true, autoPlayVideos=true, canDoRefreshes=true), data saver: 1, battery saver: false
-----------------------

```
There does not seem to be any more logging happening.

**Comment by Mark-VG** [comment]
I do not have a Play Console account.

**Comment by Mark-VG** [comment]
I reverted to the release version which offers' an option to send logs etc:

![image](https://github.com/openhab/openhab-android/assets/84638697/ca3587df-5b0c-453e-9a7f-81dd3ddd94bd)

Which I have just done. Sadly it appears one if not able to download the details etc, only preview?

Please see if you receive this?

**Comment by mueller-ma** [comment]
> I do not have a Play Console account.

You don't need one. The crash report is uploaded automatically. The account is only required to view the crashes.
However I don't see any crash for that device.

You could try to get the log via adb: https://developer.android.com/tools/logcat

**Comment by Mark-VG** [comment]
> You could try to get the log via adb: https://developer.android.com/tools/logcat

Thanks. I tried and will keep trying. Was not able to access the app log. Probably as I have no idea what I am doing.

Can you check if you got the crash report I manually submitted as per my previous post?

Any other guidance woukd be appreciated

**Comment by maniac103** [comment]
> Can you check if you got the crash report I manually submitted as per my previous post?

If it wasn't (correctly) sent, another option would be a screenshot of the crash data preview (middle button in the pictured dialog). It should contain a Java stack trace that should help in finding the issue.

**Comment by Mark-VG** [comment]
I managed to get some logs by going back to the release version. I also think I changed something in dev options to get logging working again!

[logs.txt](https://github.com/openhab/openhab-android/files/12709307/logs.txt)

Hope this helps?

**Comment by maniac103** [comment]
Looks like either the WebView (Chrome) process and/or the graphics driver crashed. It doesn't look like the crash happens in our code.

**Comment by Mark-VG** [comment]
Thank you for the feedback. I have tried updating, factory reset. Remove chrome etc.
Do you have any other suggestions I could try? This is a wall mount tablet just runs openHAB.

**Comment by Mark-VG** [comment]
Hi
I have actually managed to narrow this issue down to a specific widget on my Overview page, details provided in teh following thread:

https://community.openhab.org/t/oh4-overview-page-with-widgets-causing-android-app-to-crash-suspected/149907/3

Not sure of this is only an issue with the Android App, as I do not see the same issue when running the same page on my browser on my desktop all day.

**Comment by maniac103** [comment]
> Not sure of this is only an issue with the Android App, as I do not see the same issue when running the same page on my  browser on my desktop all day.

As mentioned: it's an issue of Webview and/or graphics drivers on your device, see your log:
```
09-24 18:50:06.870 17051 17051 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (17183) crash detected (code 5).
09-24 18:50:06.956 17051 17051 F chromium: [FATAL:crashpad_client_linux.cc(732)] Render process (17183)'s crash wasn't handled by all associated  webviews, triggering application crash.
--------- beginning of crash
09-24 18:50:06.957 17051 17051 F libc    : Fatal signal 5 (SIGTRAP), code 4 in tid 17051 (penhab.habdroid)
```

This excerpt says the chromium process died, and killed off the app process as a consequence. Since Webview is also API level specific, it might also be related to your tablet running Android 7. The reason for my suspicion of the graphics stack is various graphics related in the logs before that point, but that's just a guess.

What definitely *can* be said, though: There's absolutely no code of us involved in this crash, so I don't think there's anything we can do to fix this. (At least) newer Android versions have a toggle for the WebView to be used in developer options, where one can choose between Chrome and the WebView shipped with the system. I'm not sure whether that toggle existed in Android 7 already, but it'd be worth a try to check.
Other than that, I don't have any other ideas really, besides looking for a custom ROM for that device or replacing it. :-(

**Comment by Mark-VG** [comment]
I guess it could be an issue between Webview and how openHAB renders the components when using the ```=Math.random() + items.UI_Refresh_Timer.state``` workaround to get a chart to refresh.

I have not been able to confirm the same issue when using a browser on my PC (Chrome).

As I mentioned, removing the workaround does resolve the issue and the App no longer crashes. So happy with that.

Hoping that someone on the OH Community has a clever idea, otherwise I will just go forward without the refresh.

Appreciate you taking the time to look though.

**Comment by mueller-ma** [comment]
It's most likely a bug in the Webview that causes this crash. I might be fixed by updating the Webview, but it seems your vendor doesn't offer updates anymore.
