### ISSUE TITLE
icon color lost

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3481]
### Actual behaviour
When I press a button on a widget and this button press does not cause a new state, the `iconcolor=....` is discarded and the icon is un-tint.
Such a button press could be the arrow down button on a color picker when the light is already off.

### Expected behaviour
The iconcolor should be kept.

 
#### Client
* App version : Latest main

**Comment by mueller-ma** [comment]
@lolodomo The server sets `iconcolor` in every SSE update event if the iconcolor is set to a fixed value, e.g. `red`. When using `itemValue` it is only included when the item actually changes. IMO this is a bug as the client doesn't know if the iconcolor was dropped on purpose or not.

**Comment by lolodomo** [comment]
The SSE event is built by this code:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/PageChangeListener.java#L224
For me, the code is correct. 
If you got null, that would mean your item state is not of type HSBType. 
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java#L622
Is the item you are using a Color item?

**Comment by lolodomo** [comment]
And the behavior should be the same for labelcolor and valuecolor.

**Comment by mueller-ma** [comment]
It's a color item linked to a tradfri color bulb. I'll check if I can reproduce this with a color item without a linked thing.

**Comment by lolodomo** [comment]
And then provide the definition of your item and sitemap element.

**Comment by mueller-ma** [comment]
It's an issue with the Tradfri binding. The state of the color item is set to `OFF` when pressing the arrow down button. 
Logs: 
````
[openhab.event.ItemCommandEvent       ] - Item '<item>' received command OFF
[openhab.event.ItemStatePredictedEvent] - Item '<item>' predicted to become OFF
````

However in the console the state is still returned as color:
````
openhab> openhab:status <item>
0,0,0
````

Maybe the rest api could also try to convert the current state to a color with `OFF => 0,0,0`?

**Comment by lolodomo** [comment]
> However in the console the state is still returned as color:
> 
> ```
> openhab> openhab:status <item>
> 0,0,0
> ```

Or maybe the binding is just properly handling the OFF command and set the item state to 0,0,0.
In the SSE event, what state value to you have in event.item ? And is event.state null ?

**Comment by mueller-ma** [comment]
I opened an issue at the addon repo: https://github.com/openhab/openhab-addons/issues/15825
