### ISSUE TITLE
on/off is used for roller shutter icon state

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3482]
I have a group of roller shutters:
![grafik](https://github.com/openhab/openhab-android/assets/22525368/5cd2bf48-87fc-48af-9e29-05336200c2a9)

In Main UI I can see that the icon state is currently `0` as all roller shutters in this group are up. I expect that the icon `rollershutter` with state `0` is fetched. However it's fetched with state `OFF`. A corresponding icon doesn't exist in the classic iconset, so the stateless icon is shown.

Sitemap: `Switch item=<item name>`

### Can you reproduce the issue in demo mode?

No, it's working in demo mode: Widget Overview => Demo Roller Shutter

So there's something I could change in the server config, but maybe we should add a special handling for roller shutter switches, so it works out of the box.

#### Client
* App version : Latest main

**Comment by lolodomo** [comment]
A group item has no state except if you define an aggregation function. 
So I don't understand your use case.

**Comment by mueller-ma** [comment]
The use case is that I can controll two blinds with one widget.
I see that I didn't set an aggregation function. This could fix the issue, but I switched the icon set and the new set doesn't support states in the blinds widget.
