### ISSUE TITLE
remove missing permissions popup or move to settings 

### ISSUE THREAD

**Issue by osztrovszky** [openhab/openhab-android#3548]
![Screenshot_20231226-141446~2](https://github.com/openhab/openhab-android/assets/13378055/23e9a7f2-c908-4a2c-954a-cdb1a0fa280f)

If no permission granted, the popup stays on forever, covering the lower part.

App works fine without permissions.
Is it possible, to make the popup disappear after a few seconds or move it to the settings menu?

**Comment by mueller-ma** [comment]
Can you go to Settings => Send device information to server and check if something is enabled there?

**Comment by osztrovszky** [comment]
Nothing enabled there.
![Uploading Screenshot_20231226-162204.png…]()

**Comment by mueller-ma** [comment]
Which Android version do you have and did you allow notifications (Settings => Ringtone & Vibration)?

**Comment by osztrovszkyzs-ahrt** [comment]
Android 14.
I did not allow notifications.

**Comment by osztrovszky** [comment]
Android 14.
I did not allow notifications.

**Comment by mueller-ma** [comment]
The app cannot notify you about issues in background tasks, so this snackbar is shown. You don't send device information, but e.g. the voice widget also counts as background task.
We could try to detect if any notifications might be shown and only display this snackbar then. However there are quite some cases that can cause notifications and I'm not sure if it's worth to implement.

**Comment by osztrovszky** [comment]
Thanks, it fixed it.
Although the app should ask for notification permission if that is so vital for it. I did not set up any notification on server.

**Comment by mueller-ma** [comment]
It depends. If not using the widgets or notifications from the server, it's not vital to the app.
