### ISSUE TITLE
`icon="none"` could be a dynamic icon

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3566]
According to https://github.com/openhab/openhab-android/issues/2958#issuecomment-1168657809 in OpenHAB-Android `icon=""` and `icon="none"` shall not request icons from the server, or generate traffic to the server, and implicitly, `icon="none"` is assumed to be a static icon (`staticIcon="none"`).

But https://github.com/openhab/openhab-core/issues/3977#issuecomment-1875721505 presents a different view: there could be a dynamic icon `none.svg` and thus `icon="none"` should generate traffic to the server on each state change (fetching none-5.svg, none-20.svg, …).

Please agree on https://github.com/openhab/openhab-android/issues/2958#issuecomment-1168657809 whether `icon="none"` implies dynamic icon or no icon fetching from the server and implement consistent behaviour in OpenHAB-WebUI and OpenHAB-Android

**Comment by mueller-ma** [comment]
This issue can be re-opened when https://github.com/openhab/openhab-core/issues/3977#issuecomment-1892548744 is resolved.
IMO having `icon=none` => No icon is fine and didn't make issues in many years.
