### ISSUE TITLE
Disable NFC completely as an option

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-android#357]
A users reports that the NFC functionality is  falsely getting triggered every time they use their phone to read a critical medical device which also used NFC.  They would like to continue using our app, but this is difficult if it interferes with a more critical medical function.   The request would be to disable NFC in our app as an option.

**Comment by mueller-ma** [comment]
The app is only triggered by tags starting with `openhab://`. Without more information it's not possible to debug this issue.
