### ISSUE TITLE
Only 12 hour selection for time input

### ISSUE THREAD

**Issue by Bloodboy1986** [openhab/openhab-android#3581]
Hello everyone,

I have a problem with the new date/time input.
I use a German cell phone in German language, but I only get a 12 hour selection for the time:

![Screenshot_20240125_141156_openHAB](https://github.com/openhab/openhab-android/assets/42858373/cdb3fed9-e3af-4f0b-af38-5279c7f99bbd)

Is this a bug or am I making something wrong?
I have not found any settings to controle the behavior...
Release and beta is the same behavior, also for local or cloud controle!

openHAB 4.0.4

Samsung S20 FE (Android 13)
App v3.9.0
App beta v3.8.6

### Expected behaviour
Get a 24 Hour input.

**Comment by mherwege** [comment]
Can't you use the AM/PM switch? The input representation will depend on your device locale, not on OH.

**Comment by maniac103** [comment]
> The input representation will depend on your device locale,

He said his phone is set to German (hence 24h), though. I think the issue simply is that we don't call `setTimeFormat` when building the `MaterialTimePicker` and thus are relying on the default value, which is 12h.

**Comment by Bloodboy1986** [comment]
You are the best 🤩
