### ISSUE TITLE
Other sitemaps not shown in side menu

### ISSUE THREAD

**Issue by s0170071** [openhab/openhab-android#3604]
### Actual behaviour
When trying to select another site map, there  is only the default sitemap

### Expected behaviour
When I swipe from left to right, all sitemaps that are available should be visible here.  Thats how I used to switched sitemaps in the past.  I can still pick a *default* sitemap and choose from all that are available. 

Note: I am not sure since when this error occurs. I used the beta version for the past yeary but when I switched my device to a brand new Samsung S24, that version did not run at all. I then installed the normal version and found I could not switch sitemaps any more. 

Also, I jsut noticed that the log viewer is not selectable from the side bar. I can set it as a start pagee. It shows up but is still not readable (some formatting issue). 
 
### Steps to reproduce
1. Get yourself a new phone, 
2. Install the app. 
3. try to switch site maps :-)

### Can you reproduce the issue in demo mode?
not possible.

#### Client
* Android version: 14
* Device model: Galaxy S24
* App version: 4.9 
* Build flavor : Play store 
* Device language: german

#### Server
* Server version: OH latest (4.1.1)
* Reverse Proxy: none
* Authentication method : none
#### openHAB Cloud
* Self hosted 
*

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by mueller-ma** [comment]
Did you set the setting "Side menu entries"?
The beta version has been blocked by Google, but you can join the open test track to get the stable updates ass one of the first.

**Comment by Flowdalic** [comment]
> Did you set the setting "Side menu entries"?

FWIW, I also missed this setting and was surprised that the App did no show all sitemaps per default. Not saying that this should be changed, there are probably good reasons to not show all sitemaps per default, but maybe the user could be made more aware of it (otoh, it is not unlikely that this is already the case and that I just missed it).

**Comment by mueller-ma** [comment]
The current behavior is intended, so it won't change. One reason I like this is that I can "hide" sitemaps from users when I configure the app for them.

**Comment by s0170071** [comment]
That was the solution indeed. Thank you.  I  have to admit I am a little 
afraid I would fall for this again when I switch ma device in five years 
from now.
May I suggest to allow multiple site maps as default setting?


Am 26. Februar 2024 17:26:37 schrieb mueller-ma ***@***.***>:

**Comment by mueller-ma** [comment]
When you switch your device you can use the Android backup and restore to recover all settings. 

> May I suggest to allow multiple site maps as default setting?

We want to keep it similar to Basic UI where switching Sitemaps isn't easily possible as well.
