### ISSUE TITLE
metadata/android/en-US/full_description.txt: fullstop at end of sentences

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3631]
I think sentences from fastlane/metadata/android/en-US/full_description.txt ending with URL, should have also a terminating fullstop:

> Discover all available add-ons and supported devices and/or functions at: https://www.openhab.org/addons/
> Join the openHAB community forum over at https://community.openhab.org
> When you find an issue please report it in the forum or at https://github.com/openhab/openhab-android/issues
> If you want to translate the app into your language join us at https://crowdin.com/project/openhab-android
> Learn about the mission and the services of the foundation under https://www.openhabfoundation.org

Otherwise they look ugly.

Translations with fullstop are suspicious for Crowdin, it suggests “autofixing” the translations by removing the fullstop.

But: I do not know how F-Droid handles text with URLs without markup, with fullstop immediately after the URL. Like

> `brumbrum https://gg.dd/ee. tt`

That is, I do not know if the URL recognized by F-droid ends with `ee` or with `ee.`. Even in the latter case there should exist some markup, I am not aware of, as a workaround.

**Comment by mueller-ma** [comment]
Let's see how F-Droid handles the URL handling when there's a fullstop at the end. I added one to the German translation: https://github.com/openhab/openhab-android/pull/3630/commits/7b6990ae6119e6730cb8f45750f06057abaf68b6
