### ISSUE TITLE
Material icons containing "_" not rendered

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#3674]
There is no icon rendered when the name of the material icon contains a "_".

Item:
```
String TestTrend "Trend"
```

Sitemap:
```
Default item=TestTrend icon="material:trending_up"
Default item=TestTrend icon="material:favorite"
```

No icon on the first widget while icon is OK on the second widget.

**Comment by lolodomo** [comment]
#3603 makes the job for framework7, I assume the same has to be done for material.

**Comment by lolodomo** [comment]
@jimtng : I see you already provided the fix for framework7. Maybe you could do the same for material icons ?

**Comment by jimtng** [comment]
I'll take a look later today
