### ISSUE TITLE
Add a default path option for Main UI

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-android#3683]
### Is your feature request related to a problem? Please describe.
My home dashboard in Main UI is not located on the Main UI root, but rather on a tabbed page located at the path `/page/myHome`.
When opening the Android app, I always have to manually navigate to that page.

### Describe the solution you'd like
It would be great to have the option to specify a default path for Main UI, which is automatically opened when Main UI is opened inside the app. This functionality is already provided by the iOS app and is really great - I don't have to click me to my dashboard anymore.

### Describe alternatives you've considered
Probably modifying Main UI to allow setting custom pages as the Main UI root, but that is a different topic and even though I don't know the Android app codebase and have never developed for Android before, seems like more effort than my suggestion above.

**Comment by florian-h05** [comment]
@mueller-ma WDYT about my proposal?

**Comment by mueller-ma** [comment]
Can you post some screenshots on how it's done in the iOS app? Is it just a simple text field setting?

**Comment by florian-h05** [comment]
Yes, it’s just a simple text field with a button to store the last used path into it:

![IMG_3714](https://github.com/openhab/openhab-android/assets/73423173/3ac792fa-86b3-4058-8b46-1bcbf93e5d48)
![IMG_3715](https://github.com/openhab/openhab-android/assets/73423173/d43270c1-4875-48b9-a13b-ee1f913c99ac)
