### ISSUE TITLE
Separate settings lock from screen lock

### ISSUE THREAD

**Issue by joshuakoh7** [openhab/openhab-android#3687]
### Is your feature request related to a problem?
Having the settings lock tied to screen lock means that a standalone tablet will be locked after X mins and require the same password to unlock as the settings tab

### Describe the solution you'd like
Separate lock password/pin for settings tab

**Comment by mueller-ma** [comment]
AFAIK it's not possible to have custom lock patterns when using this library. Implementing it on our own is too much work, so I'd close this issue as "not planned".

**Comment by joshuakoh7** [comment]
> AFAIK it's not possible to have custom lock patterns when using this library. Implementing it on our own is too much work, so I'd close this issue as "not planned".

The current feature is has no actual use case though as explained in the original post. Everyone will need to know the screen lock details to unlock the tablet when it eventually locks itself and sharing that with the settings tab means that everyone will know the password to unlock that too. 

There's no need for complex lock patterns, just a simple numeric/alphanumeric code for unlocking it would be sufficient. Just an additional page with an input box and an additional setting in the settings tab would be sufficient to make this feature useful.

**Comment by jimtng** [comment]
a "lock pattern/pin -> page / sitemap" mapping might also be useful, so different people with different lock pattern/pin gets presented with unique sitemap for that pattern.

**Comment by mueller-ma** [comment]
>  Everyone will need to know the screen lock details to unlock the tablet when it eventually locks itself and sharing that with the settings tab means that everyone will know the password to unlock that too.

Does your tablet have some components for biometric authentication like fingerprint? I could add a new setting to require biometric auth when unlocking settings. Then you can share the pin to everyone, but add only your finger.
