### ISSUE TITLE
Support for LED strips

### ISSUE THREAD

**Issue by Wjxfi** [openhab/openhab-android#3712]
Configuration of running colors and other

all types

**Comment by mueller-ma** [comment]
Can you give some more context on this? Sitemaps already have a Color widget.

**Comment by mueller-ma** [comment]
I won't install apps with trackers as well :) Please share some screenshots and explain which features are missing.

**Comment by mueller-ma** [comment]
Please open an issue at https://github.com/openhab/openhab-core/issues/new/choose if you want to request a new Sitemap widget.
