### ISSUE TITLE
App 3.14 crashes on notification receipt

### ISSUE THREAD

**Issue by MarcR2000** [openhab/openhab-android#3729]
App 3.14 crashes every time a notification is received. Happens on all testet Android devices. Problem occurs since this morning.

### Expected behaviour
App should keep running and notification should be displayed.

 ### Steps to reproduce
On every notification sent, e.g. through myopenhab.org the same problem occurs

* Android version: 14
* Device model: Samsung S23 (e.g.)
* App version 3.14
* Build flavor FULL
* Device language: German

#### Server
* Server version: 4.1.2
user and password or SSL Client certificate)

#### openHAB Cloud
myopenhab.org: 
user and password or SSL Client certificate

#### App log
-----------------------
Device information
Model: SM-S911B
Manufacturer: samsung
Brand: samsung
Device: dm1q
Product: dm1qxeea
OS: 14
Display: 1080x2214, 3.0 density
Data usage policy: DataUsagePolicy(canDoLargeTransfers=true, loadIconsWithState=true, autoPlayVideos=true, canDoRefreshes=true), data saver: 1, battery saver: false
-----------------------

--------- beginning of main
07-01 14:16:46.949 19553 19553 I ViewRootImpl@5827884[LogActivity]: ViewPostIme pointer 0
07-01 14:16:47.013 19553 19553 I ViewRootImpl@5827884[LogActivity]: ViewPostIme pointer 1
07-01 14:16:47.027 19553 19553 D LogActivity: onOptionsItemSelected()
--------- beginning of events
07-01 14:16:47.036 19553 19553 I wm_on_top_resumed_lost_called: [176894794,org.openhab.habdroid.ui.LogActivity,topStateChangedWhenResumed]
07-01 14:16:47.037 19553 19553 I wm_on_paused_called: [176894794,org.openhab.habdroid.ui.LogActivity,performPause,1]
07-01 14:16:47.037 19553 19582 D SessionLifecycleClient: Sending lifecycle 2 to service
07-01 14:16:47.037 19553 19613 D SessionLifecycleService: Activity backgrounding at 86463566
07-01 14:16:47.043 19553 19553 I ViewRootImpl@e5c7aae[PreferencesActivity]: handleAppVisibility mAppVisible = false visible = true
07-01 14:16:47.043 19553 19553 I ViewRootImpl@e5c7aae[PreferencesActivity]: stopped(false) old = true
07-01 14:16:47.043 19553 19553 D ViewRootImpl@e5c7aae[PreferencesActivity]: WindowStopped on org.openhab.habdroid/org.openhab.habdroid.ui.preference.PreferencesActivity set to false
07-01 14:16:47.043 19553 19553 I wm_on_restart_called: [137049731,org.openhab.habdroid.ui.preference.PreferencesActivity,performRestart,0]
07-01 14:16:47.045 19553 19553 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=https://<openhab-local-address-openHAB>:8443/, userName=<none>, password=<none>), remotePath=ServerPath(url=https://myopenhab.org/, userName=<redacted>, password=<redacted>), sslClientCert=null, defaultSitemap=null, wifiSsids=[], restrictToWifiSsids=false, frontailUrl=null, mainUiStartPage=null)
07-01 14:16:47.046 19553 19553 I wm_on_start_called: [137049731,org.openhab.habdroid.ui.preference.PreferencesActivity,handleStartActivity,3]
07-01 14:16:47.047 19553 19553 I wm_on_resume_called: [137049731,org.openhab.habdroid.ui.preference.PreferencesActivity,RESUME_ACTIVITY,0]
07-01 14:16:47.047 19553 19593 D SessionLifecycleClient: Sending lifecycle 1 to service
07-01 14:16:47.047 19553 19553 I wm_on_top_resumed_gained_called: [137049731,org.openhab.habdroid.ui.preference.PreferencesActivity,topWhenResuming]
07-01 14:16:47.047 19553 19613 D SessionLifecycleService: Activity foregrounding at 86463575.
07-01 14:16:47.047 19553 19623 I okhttp.OkHttpClient: --> GET https://myopenhab.org//api/v1/settings/notifications
07-01 14:16:47.047 19553 19623 I okhttp.OkHttpClient: User-Agent: Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19
07-01 14:16:47.048 19553 19623 I okhttp.OkHttpClient: Cache-Control: no-cache
07-01 14:16:47.048 19553 19623 I okhttp.OkHttpClient: --> END GET
07-01 14:16:47.048 19553 19590 D ConnectionFactory: checkAvailableConnection: found types [ConnectionType(type = Wifi, network=122)]
07-01 14:16:47.048 19553 19590 D ServerConfiguration: load: ServerConfiguration(id=1, name=openHAB, localPath=ServerPath(url=https://<openhab-local-address-openHAB>:8443/, userName=<none>, password=<none>), remotePath=ServerPath(url=https://myopenhab.org/, userName=<redacted>, password=<redacted>), sslClientCert=null, defaultSitemap=null, wifiSsids=[], restrictToWifiSsids=false, frontailUrl=null, mainUiStartPage=null)
07-01 14:16:47.048 19553 19590 D ConnectionFactory: Server openHAB isn't restricted to Wi-Fis
07-01 14:16:47.048 19553 19590 D AbstractConnection: Checking reachability of https://<openhab-local-address-openHAB>:8443/ (via 122)
07-01 14:16:47.049 19553 19590 D TrafficStats: tagSocket(6) with statsTag=0xffffffff, statsUid=-1
07-01 14:16:47.056 19553 19553 I BufferQueueProducer: [](id:4c6100000003,api:0,p:-1,c:19553) setDequeueTimeout:2077252342
07-01 14:16:47.056 19553 19553 I BLASTBufferQueue_Java: new BLASTBufferQueue, mName= ViewRootImpl@e5c7aae[PreferencesActivity] mNativeObject= 0xb40000776cba6e00 sc.mNativeObject= 0xb40000774b5577c0 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3028 android.view.ViewRootImpl.relayoutWindow:10131 android.view.ViewRootImpl.performTraversals:4110 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698 android.view.Choreographer.doCallbacks:1153 android.view.Choreographer.doFrame:1079 android.view.Choreographer$FrameDisplayEventReceiver.run:1646
07-01 14:16:47.057 19553 19553 I BLASTBufferQueue_Java: update, w= 1080 h= 2340 mName = ViewRootImpl@e5c7aae[PreferencesActivity] mNativeObject= 0xb40000776cba6e00 sc.mNativeObject= 0xb40000774b5577c0 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:89 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3028 android.view.ViewRootImpl.relayoutWindow:10131 android.view.ViewRootImpl.performTraversals:4110 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344
07-01 14:16:47.057 19553 19553 I ViewRootImpl@e5c7aae[PreferencesActivity]: Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) relayoutAsync=false req=(1080,2340)0 dur=5 res=0x403 s={true 0xb4000077747fc800} ch=true seqId=0
07-01 14:16:47.057 19553 19553 D ViewRootImpl@e5c7aae[PreferencesActivity]: mThreadedRenderer.initialize() mSurface={isValid=true 0xb4000077747fc800} hwInitialized=true
07-01 14:16:47.057 19553 19553 D ViewRootImpl@e5c7aae[PreferencesActivity]: reportNextDraw android.view.ViewRootImpl.performTraversals:4718 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698
07-01 14:16:47.057 19553 19553 I ViewRootImpl@e5c7aae[PreferencesActivity]: Setup new sync=wmsSync-ViewRootImpl@e5c7aae[PreferencesActivity]#6
07-01 14:16:47.058 19553 19553 I ViewRootImpl@e5c7aae[PreferencesActivity]: Creating new active sync group ViewRootImpl@e5c7aae[PreferencesActivity]#7
07-01 14:16:47.058 19553 19553 I ViewRootImpl@e5c7aae[PreferencesActivity]: registerCallbacksForSync syncBuffer=false
07-01 14:16:47.059 19553 19618 I ViewRootImpl@e5c7aae[PreferencesActivity]: Received frameDrawingCallback syncResult=0 frameNum=1.
07-01 14:16:47.059 19553 19618 I ViewRootImpl@e5c7aae[PreferencesActivity]: mWNT: t=0xb40000776519e480 mBlastBufferQueue=0xb40000776cba6e00 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:13841 android.view.ThreadedRenderer$1.onFrameDraw:792 <bottom of call stack>
07-01 14:16:47.059 19553 19618 I ViewRootImpl@e5c7aae[PreferencesActivity]: Setting up sync and frameCommitCallback
07-01 14:16:47.061 19553 19607 I BLASTBufferQueue: [ViewRootImpl@e5c7aae[PreferencesActivity]#3](f:0,a:0,s:0) onFrameAvailable the first frame is available
07-01 14:16:47.061 19553 19607 I ViewRootImpl@e5c7aae[PreferencesActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
07-01 14:16:47.061 19553 19553 I ViewRootImpl@e5c7aae[PreferencesActivity]: reportDrawFinished seqId=0
07-01 14:16:47.065 19553 19553 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=navigationBars, host=org.openhab.habdroid/org.openhab.habdroid.ui.preference.PreferencesActivity
07-01 14:16:47.065 19553 19553 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=statusBars, host=org.openhab.habdroid/org.openhab.habdroid.ui.preference.PreferencesActivity
07-01 14:16:47.065 19553 19553 I ViewRootImpl@5827884[LogActivity]: handleWindowFocusChanged: 0 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
07-01 14:16:47.066 19553 19553 I ImeFocusController: onPreWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
07-01 14:16:47.066 19553 19553 I ImeFocusController: onPostWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
07-01 14:16:47.066 19553 19590 D AbstractConnection: Socket connected (attempt  0)
07-01 14:16:47.066 19553 19590 D ConnectionFactory: Connecting to local URL via ConnectionType(type = Wifi, network=122)
07-01 14:16:47.077 19553 19553 I wm_on_idle_called: {org.openhab.habdroid/org.openhab.habdroid.ui.preference.PreferencesActivity}
07-01 14:16:47.088 19553 19623 I okhttp.OkHttpClient: <-- 200 OK https://myopenhab.org/api/v1/settings/notifications (40ms)
07-01 14:16:47.089 19553 19553 I ViewRootImpl@e5c7aae[PreferencesActivity]: handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
07-01 14:16:47.089 19553 19623 I okhttp.OkHttpClient: Server: nginx/1.18.0 (Ubuntu)
07-01 14:16:47.089 19553 19623 I okhttp.OkHttpClient: Date: Mon, 01 Jul 2024 12:16:47 GMT
07-01 14:16:47.089 19553 19623 I okhttp.OkHttpClient: Content-Type: application/json; charset=utf-8
07-01 14:16:47.089 19553 19623 I okhttp.OkHttpClient: Content-Length: 35
07-01 14:16:47.089 19553 19623 I okhttp.OkHttpClient: Connection: keep-alive
07-01 14:16:47.089 19553 19623 I okhttp.OkHttpClient: X-Powered-By: Express
07-01 14:16:47.089 19553 19623 I okhttp.OkHttpClient: ETag: W/"23-fmFNFNMjs09m01kwm7gJsWohDT4"
07-01 14:16:47.089 19553 19553 D ViewRootImpl@e5c7aae[PreferencesActivity]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000077747fc800}
07-01 14:16:47.089 19553 19623 I okhttp.OkHttpClient: <-- END HTTP
07-01 14:16:47.089 19553 19553 D InputMethodManagerUtils: startInputInner - Id : 0
07-01 14:16:47.089 19553 19553 I InputMethodManager: startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
07-01 14:16:47.096 19553 19553 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=false, type=ime, host=org.openhab.habdroid/org.openhab.habdroid.ui.preference.PreferencesActivity
07-01 14:16:47.098 19553 19567 I ViewRootImpl@e5c7aae[PreferencesActivity]: Resizing android.view.ViewRootImpl@52a3bed: frame = [0,0][1080,2340] reportDraw = false forceLayout = false syncSeqId = -1
07-01 14:16:47.098 19553 19553 I ViewRootImpl@e5c7aae[PreferencesActivity]: handleResized, msg = 4 frames=ClientWindowFrames{frame=[0,0][1080,2340] display=[0,0][1080,2340] parentFrame=[0,0][0,0]} forceNextWindowRelayout=false displayId=0 dragResizing=false compatScale=1.0 frameChanged=false attachedFrameChanged=false configChanged=false displayChanged=false compatScaleChanged=false
07-01 14:16:47.107 19553 19595 D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4402)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4966)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4933)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4907)] [androidx.work.impl.utils.NetworkApi24$$ExternalSyntheticApiModelOutline0.m(SourceFile:0)] [androidx.work.impl.utils.NetworkApi24.registerDefaultNetworkCallbackCompat(Unknown Source:10)] [androidx.work.impl.constraints.trackers.NetworkStateTracker24.startTracking(Unknown Source:19)] [androidx.work.impl.constraints.trackers.ConstraintTracker.addListener(Unknown Source:72)] [androidx.work.impl.constraints.controllers.ConstraintController$track$1.invokeSuspend(Unknown Source:43)] [androidx.work.impl.constraints.controllers.ConstraintController$track$1.invoke(SourceFile:0)] [androidx.work.impl.constraints.controllers.ConstraintController$track$1.invoke(SourceFile:0)] [kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Unknown Source:2)] [kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Unknown Source:0)] [kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Unknown Source:60)] [kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(Unknown Source:34)] [kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)] [kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)] [androidx.work.impl.utils.SerialExecutorImpl$Task.run(Unknown Source:2)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)] [java.lang.Thread.run(Thread.java:1012)]
07-01 14:16:47.110 19553 19590 D FcmRegistrationWorker: Run with action org.openhab.habdroid.action.REGISTER_GCM
07-01 14:16:47.111 19553 19553 D FcmRegistrationWorker: Register device at openHAB cloud with URL: addAndroidRegistration<redacted>

**Comment by krpearce** [comment]
Also having this problem.
Exception seen after receiving notification.

--------- beginning of main
07-01 15:17:46.732 19122 19122 D FcmMessageListenerService: onCreate()
07-01 15:17:46.739 19122 20245 D FcmMessageListenerService: onMessageReceived with data {persistedId=6682ba8b66ae6fc354e2c86f, icon=, type=notification, timestamp=Mon Jul 01 2024 16:17:47 GMT+0200 (Central European Summer Time), notificationId=180692317, severity=}
--------- beginning of crash
07-01 15:17:46.756 19122 20245 E AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
07-01 15:17:46.756 19122 20245 E AndroidRuntime: Process: org.openhab.habdroid, PID: 19122
07-01 15:17:46.756 19122 20245 E AndroidRuntime: java.lang.NumberFormatException: For input string: "Mon Jul 01 2024 16:17:47 GMT+0200 (Central European Summer Time)"
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at java.lang.Long.parseLong(Long.java:594)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at java.lang.Long.parseLong(Long.java:636)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at org.openhab.habdroid.core.FcmMessageListenerService.onMessageReceived(Unknown Source:94)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(Unknown Source:66)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(Unknown Source:119)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(Unknown Source:12)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:66)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0(Unknown Source:1)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at com.google.firebase.messaging.EnhancedIntentService.$r8$lambda$9b4qTh6k1amVzUe1kAE6oojA2-8(SourceFile:0)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at com.google.firebase.messaging.EnhancedIntentService$$ExternalSyntheticLambda1.run(SourceFile:0)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
07-01 15:17:46.756 19122 20245 E AndroidRuntime: at java.lang.Thread.run(Thread.java:923)

**Comment by MarcR2000** [comment]
It's now working again. Maybe it was a server side problem?

**Comment by jimtng** [comment]
https://community.openhab.org/t/android-app-crashes-when-a-push-notification-arrives/156954/7
