### ISSUE TITLE
Skeleton view breaks server discovery layout

### ISSUE THREAD

**Issue by maniac103** [openhab/openhab-android#3736]
### Actual behaviour
See screenshot:
![Screenshot_20240710_173230](https://github.com/openhab/openhab-android/assets/781373/1052ce2c-2ac8-428e-bdc9-9b5781c0f24b)

### Expected behaviour
Skeleton view not visible in that case, icon and text should be centered vertically

 
### Steps to reproduce
1. Clear app data
2. Restart app, ideally without server available in network

**Comment by mueller-ma** [comment]
I'll revert this layout while keeping skeleton for other loading screens. And probably make it a bit darker in dark mode as it's quite bright there.
