### ISSUE TITLE
Sitemaps Input widget strips off `[]` characters

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-android#3756]
### Actual behaviour

Item:
```
String TestString1
```

Sitemap:
```
sitemap test {
  Input item=TestString1
}
```

- Open that sitemap on android 3.15.0
- Enter `abcdefgh[]` into the text field, and click the checkmark (enter) on the Android's virtual keyboard
- The app will send a command `abcdefgh[]` to the item but then changed the text inside the input field to `abcdefgh` stripping away the `[]`
- The same thing would happen if `[]` is entered in the middle of the string, e.g. `abcdefg[]h` - > it strips off everything after `[]` so the text became `abcdefg` (note the `h` is also gone)
- But this "bug" doesn't happen, if `[]` is at the very beginning of the string, e.g. `[]abcdefgh` - the `[]` don't get stripped off, and neither do they get stripped off when I entered `[]abcdefgh[]`.

### Expected behaviour

It shouldn't strip off any text inputs

 
### Steps to reproduce
Described above

#### Client
* Android version: Android 14
* App version 3.15.0
* Build flavor Play Store
* Device language: English

#### Server
* Server version: 4.3.0-SNAPSHOT

**Comment by mueller-ma** [comment]
In your title you wrote "BasicUI", but I guess you mean Sitemaps? Can you check the behavior in Basic UI (Sitemaps in browser)?

**Comment by jimtng** [comment]
Yes I meant Sitemap, sorry. 
BasicUI (sitemaps in browser) has its own, different bug related to this: https://github.com/openhab/openhab-webui/issues/2675
