### ISSUE TITLE
'Switch with mappings' icon misplaced

### ISSUE THREAD

**Issue by maniac103** [openhab/openhab-android#3773]
See screenshot from demo server:
![Screenshot_20240719-191043](https://github.com/user-attachments/assets/63978016-5b81-47ea-9bc8-5091379d901f)

**Comment by mueller-ma** [comment]
I cannot reproduce this issue. Which Android version and which device do you have?

**Comment by maniac103** [comment]
Pixel 8 / Android 14. I just tried it again, it's  still the same (with 3.15.4 that is). I can also have a look into it myself when I get some time allocated.

**Comment by lehanspb** [comment]
Same issue
app version 3.15.5
Samsung Galaxy S22
Android 14
