### ISSUE TITLE
Strange issue with switch mapping text

### ISSUE THREAD

**Issue by lehanspb** [openhab/openhab-android#3781]
Samsung Galaxy S22
Android 14
app version 3.15.5 (from Play Store)

From sitemap:

```
			Frame
			{
				Switch	item=ValveSelector mappings=[153="First1111", 154="Second", 155="Third"] icon="" label=""
				Switch	item=ValveSelector mappings=[153="First1111", 154="Second", 155="Third"] icon="" label=""
				Switch	item=ValveSelector mappings=[153="First1111", 154="Second", 155="Third"] icon="" label=""
				Switch	item=ValveSelector mappings=[153="First1111", 154="Second", 155="Third"] icon="" label=""
			}

```

![image](https://github.com/user-attachments/assets/76eb32a8-e6df-49ab-84bb-82d6edd55acc)
 
In older app versions there was full text in switch mappings

**Comment by maniac103** [comment]
Works for me in 3.16.2:

![grafik](https://github.com/user-attachments/assets/0d0a1f9f-2c3d-4609-b4f1-e9f81c4b83e9)

Is this issue happening permanently or only sometimes for you? Only with specific app versions or all of them?

**Comment by lehanspb** [comment]
> Works for me in 3.16.2:
> 
> 
> Is this issue happening permanently or only sometimes for you? Only with specific app versions or all of them?

Confirm. Everything is perfect on version 3.16.2. Thanks.
