### ISSUE TITLE
Enhanced Actions onClickAction ui :Main UI Popup" not working

### ISSUE THREAD

**Issue by Mark-VG** [openhab/openhab-android#3793]
Hi

This has been reported as follows:

https://community.openhab.org/t/oh4-2-0-notifications-with-android-app-actions/157204/24

### Actual behavior
I have been using the new Blockly Blocks to setup notifications.

I have however not been able to get the Main UI Popup option to work. When trying the Popup option the App opens the default Sitemap and not a popup.

Using Main UI Path doe however work

Using:

```
actions.notificationBuilder('Gate has Closed! ').withTitle('Gate Closed').withIcon('presence').withTag('warn').withOnClickAction('ui:popup:' + '/page/OverviewOLD').addActionButton('Toggle Garage Door', 'command:ShellyGarageDoorshelly1a4cf12f486ac10163199232_Power:' + 'ON').send()
```
Results in the APP opening and the old default site map being displayed.

Using:

```
actions.notificationBuilder('Gate has Closed! ').withTitle('Gate Closed').withIcon('presence').withTag('warn').withOnClickAction('ui:popup:' + 'widget:Harmony_V1').addActionButton('Toggle Garage Door', 'command:ShellyGarageDoorshelly1a4cf12f486ac10163199232_Power:' + 'ON').send()
```
Results in the APP opening and the old default site map being displayed.

### Expected behavior
The click on actions to produce the correct popup

#### Client
Android version: 14 UI Version 6.1
Device model: Galaxy S21 5G
App version: 3.15.5
Build flavor: Play Store
Device language: English
#### Server
Server version: 4.3.0 Build 4201
Reverse Proxy: openHAB Clound Connector

**Comment by Mark-VG** [comment]
Maybe a duplicate of https://github.com/openhab/openhab-android/issues/3762 ?

**Comment by mueller-ma** [comment]
Indeed :)
