### ISSUE TITLE
Crashes when a video element is accessed

### ISSUE THREAD

**Issue by DiKaY1969** [openhab/openhab-android#3802]
### Actual behaviour
Crashes when a video element is accessed
`
Video label="Hauseingang Livestream:" staticIcon="camera" url="http://1.2.3.4:8080/ipcamera/4eeab5ab03/ipcamera.mjpeg" encoding="mjpeg"
`

### Expected behaviour
The video is supposed to be displayed but the app crashes
 
### Steps to reproduce
Simply configure and access a video element in the sitemap

### Can you reproduce the issue in demo mode?
No, I didn't find any video elements in demo mode

#### Client
Android 11
Xiaomi Redmin Note 8 Pro
3.15.8 Beta - 3.16.0 Release
German

#### Server
Openhab 4.2.1

#### openHAB Cloud
myopenhab.org

#### App log
`-----------------------
Device information
Model: Redmi Note 8 Pro
Manufacturer: Xiaomi
Brand: Redmi
Device: begonia
Product: begonia_eea
OS: 11
Display: 1080x2134, 2.75 density
Data usage policy: DataUsagePolicy(canDoLargeTransfers=true, loadIconsWithState=true, autoPlayVideos=true, canDoRefreshes=true), data saver: 1, battery saver: false
-----------------------

--------- beginning of events
08-16 07:22:23.602  6601  6601 I auditd  : type=1400 audit(0.0:441186): avc: denied { read } for comm="penhab.habdroid" name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=16114 scontext=u:r:untrusted_app:s0:c14,c258,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=org.openhab.habdroid
08-16 10:42:03.438  4406  4406 I menu_item_selected: [0,Nur Fehler anzeigen]
08-16 10:42:05.922  4406  4406 I menu_item_selected: [0,Protokoll löschen]
08-16 10:42:06.860  4406  4406 I wm_on_top_resumed_lost_called: [141088523,org.openhab.habdroid.ui.LogActivity,topStateChangedWhenResumed]
08-16 10:42:06.861  4406  4406 I wm_on_paused_called: [0,org.openhab.habdroid.ui.LogActivity,performPause,0]
08-16 10:42:06.867  4406  4406 I wm_on_restart_called: [0,org.openhab.habdroid.ui.preference.PreferencesActivity,performRestartActivity,0]
08-16 10:42:06.870  4406  4406 I wm_on_start_called: [0,org.openhab.habdroid.ui.preference.PreferencesActivity,handleStartActivity,3]
08-16 10:42:06.870  4406  4406 I wm_on_resume_called: [0,org.openhab.habdroid.ui.preference.PreferencesActivity,RESUME_ACTIVITY,0]
08-16 10:42:06.871  4406  4406 I wm_on_top_resumed_gained_called: [246404971,org.openhab.habdroid.ui.preference.PreferencesActivity,topWhenResuming]
08-16 10:42:07.429  4406  4406 I wm_on_stop_called: [0,org.openhab.habdroid.ui.LogActivity,LIFECYCLER_STOP_ACTIVITY,0]
08-16 10:42:07.430  4406  4406 I wm_on_destroy_called: [0,org.openhab.habdroid.ui.LogActivity,performDestroy,0]
08-16 10:42:08.895  4406  4406 I wm_on_top_resumed_lost_called: [246404971,org.openhab.habdroid.ui.preference.PreferencesActivity,topStateChangedWhenResumed]
08-16 10:42:08.897  4406  4406 I wm_on_paused_called: [0,org.openhab.habdroid.ui.preference.PreferencesActivity,performPause,1]
08-16 10:42:08.903  4406  4406 I wm_on_activity_result_called: [0,org.openhab.habdroid.ui.MainActivity,ACTIVITY_RESULT,1]
08-16 10:42:08.903  4406  4406 I wm_on_restart_called: [0,org.openhab.habdroid.ui.MainActivity,performRestartActivity,0]
08-16 10:42:08.914  4406  4406 I wm_on_start_called: [0,org.openhab.habdroid.ui.MainActivity,handleStartActivity,11]
08-16 10:42:08.918  4406  4406 I wm_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY,3]
08-16 10:42:08.919  4406  4406 I wm_on_top_resumed_gained_called: [142194181,org.openhab.habdroid.ui.MainActivity,topWhenResuming]
08-16 10:42:09.480  4406  4406 I wm_on_stop_called: [0,org.openhab.habdroid.ui.preference.PreferencesActivity,LIFECYCLER_STOP_ACTIVITY,0]
08-16 10:42:09.482  4406  4406 I wm_on_destroy_called: [0,org.openhab.habdroid.ui.preference.PreferencesActivity,performDestroy,2]
--------- beginning of crash
08-16 10:42:11.819  4406  4406 E AndroidRuntime: FATAL EXCEPTION: main
08-16 10:42:11.819  4406  4406 E AndroidRuntime: Process: org.openhab.habdroid, PID: 4406
08-16 10:42:11.819  4406  4406 E AndroidRuntime: java.lang.ClassCastException: org.openhab.habdroid.ui.widget.WidgetImageView cannot be cast to android.widget.ImageView
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at org.openhab.habdroid.ui.WidgetAdapter$MjpegVideoViewHolder.<init>(Unknown Source:25)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at org.openhab.habdroid.ui.WidgetAdapter.onCreateViewHolder(SourceFile:0)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at org.openhab.habdroid.ui.WidgetAdapter.onCreateViewHolder(SourceFile:0)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(Unknown Source:5)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(Unknown Source:238)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:0)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:0)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(Unknown Source:11)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:0)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(Unknown Source:38)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:357)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:66)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:71)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(Unknown Source:135)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(Unknown Source:0)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(Unknown Source:0)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source:42)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source:56)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.View.layout(View.java:23266)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6532)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3708)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3166)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2135)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8624)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:799)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:734)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8057)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
08-16 10:42:11.819  4406  4406 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
08-16 10:42:22.748 12742 12742 I auditd  : type=1400 audit(0.0:460243): avc: denied { read } for comm="penhab.habdroid" name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=16114 scontext=u:r:untrusted_app:s0:c14,c258,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=org.openhab.habdroid
08-16 10:42:22.807 12742 12742 I wm_on_create_called: [0,org.openhab.habdroid.ui.MainActivity,performCreate,42]
08-16 10:42:22.835 12742 12742 I wm_on_start_called: [0,org.openhab.habdroid.ui.MainActivity,handleStartActivity,27]
08-16 10:42:22.854 12742 12742 I wm_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY,19]
08-16 10:42:22.869 12742 12742 I wm_on_top_resumed_gained_called: [209311072,org.openhab.habdroid.ui.MainActivity,topStateChangedWhenResumed]
--------- beginning of system
08-16 10:42:22.869 12742 12742 W Looper  : PerfMonitor looperActivity : package=org.openhab.habdroid/.ui.MainActivity time=0ms latency=390ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=2 (msgIndex=1 wall=273ms seq=2 running=181ms runnable=12ms io=26ms late=20ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=118ms seq=3 running=91ms runnable=3ms late=273ms h=android.app.ActivityThread$H w=159)
08-16 10:42:22.944 12742 12742 W Looper  : PerfMonitor doFrame : time=71ms vsyncFrame=0 latency=301ms procState=2 historyMsgCount=7 (msgIndex=1 wall=273ms seq=2 running=181ms runnable=12ms io=26ms late=20ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=118ms seq=3 running=91ms runnable=3ms late=273ms h=android.app.ActivityThread$H w=159)
--------- beginning of main
08-16 10:42:23.504 12742 12768 D AbstractConnection: Socket connected (attempt  0)
08-16 10:42:23.505 12742 12768 D ConnectionFactory: Connecting to local URL via ConnectionType(type = Wifi, network=112)
08-16 10:42:23.546 12742 12828 I okhttp.OkHttpClient: <-- 200 OK https://<openhab-local-address-openHAB>:8443/icon/toilet?format=SVG&anyFormat=true&iconset=classic (47ms)
08-16 10:42:23.546 12742 12828 I okhttp.OkHttpClient: Content-Type: image/svg+xml
08-16 10:42:23.546 12742 12828 I okhttp.OkHttpClient: Last-Modified: Fri, 16 Aug 2024 08:42:24 GMT
08-16 10:42:23.546 12742 12828 I okhttp.OkHttpClient: Transfer-Encoding: chunked
08-16 10:42:23.546 12742 12828 I okhttp.OkHttpClient: Server: Jetty(9.4.54.v20240208)
08-16 10:42:23.546 12742 12828 I okhttp.OkHttpClient: <-- END HTTP
08-16 10:42:23.548 12742 12825 I okhttp.OkHttpClient: <-- 200 OK https://<openhab-local-address-openHAB>:8443/icon/alarm?format=SVG&anyFormat=true&iconset=classic (49ms)
08-16 10:42:23.548 12742 12825 I okhttp.OkHttpClient: Content-Type: image/svg+xml
08-16 10:42:23.548 12742 12825 I okhttp.OkHttpClient: Last-Modified: Fri, 16 Aug 2024 08:42:24 GMT
08-16 10:42:23.548 12742 12825 I okhttp.OkHttpClient: Transfer-Encoding: chunked
08-16 10:42:23.548 12742 12825 I okhttp.OkHttpClient: Server: Jetty(9.4.54.v20240208)
08-16 10:42:23.548 12742 12825 I okhttp.OkHttpClient: <-- END HTTP
08-16 10:42:23.559 12742 12830 I okhttp.OkHttpClient: <-- 200 OK https://<openhab-local-address-openHAB>:8443/icon/lightbulb?format=SVG&anyFormat=true&iconset=classic (60ms)
08-16 10:42:23.559 12742 12830 I okhttp.OkHttpClient: Content-Type: image/svg+xml
08-16 10:42:23.560 12742 12830 I okhttp.OkHttpClient: Last-Modified: Fri, 16 Aug 2024 08:42:24 GMT
08-16 10:42:23.560 12742 12830 I okhttp.OkHttpClient: Transfer-Encoding: chunked
08-16 10:42:23.560 12742 12830 I okhttp.OkHttpClient: Server: Jetty(9.4.54.v20240208)
08-16 10:42:23.560 12742 12830 I okhttp.OkHttpClient: <-- END HTTP
08-16 10:42:23.565 12742 12829 I okhttp.OkHttpClient: <-- 200 OK https://<openhab-local-address-openHAB>:8443/icon/battery?format=SVG&anyFormat=true&iconset=classic (66ms)
08-16 10:42:23.565 12742 12829 I okhttp.OkHttpClient: Content-Type: image/svg+xml
08-16 10:42:23.565 12742 12829 I okhttp.OkHttpClient: Last-Modified: Fri, 16 Aug 2024 08:42:24 GMT
08-16 10:42:23.565 12742 12829 I okhttp.OkHttpClient: Transfer-Encoding: chunked
08-16 10:42:23.565 12742 12829 I okhttp.OkHttpClient: Server: Jetty(9.4.54.v20240208)
08-16 10:42:23.565 12742 12829 I okhttp.OkHttpClient: <-- END HTTP
08-16 10:42:23.567 12742 12827 I okhttp.OkHttpClient: <-- 200 OK https://<openhab-local-address-openHAB>:8443/icon/network?format=SVG&anyFormat=true&iconset=classic (67ms)
08-16 10:42:23.567 12742 12827 I okhttp.OkHttpClient: Content-Type: image/svg+xml
08-16 10:42:23.567 12742 12827 I okhttp.OkHttpClient: Last-Modified: Fri, 16 Aug 2024 08:42:24 GMT
08-16 10:42:23.567 12742 12827 I okhttp.OkHttpClient: Transfer-Encoding: chunked
08-16 10:42:23.567 12742 12827 I okhttp.OkHttpClient: Server: Jetty(9.4.54.v20240208)
08-16 10:42:23.567 12742 12827 I okhttp.OkHttpClient: <-- END HTTP
08-16 10:42:23.577 12742 12833 I okhttp.OkHttpClient: <-- 200 OK https://<openhab-local-address-openHAB>:8443/icon/garagedoor?format=SVG&anyFormat=true&iconset=classic (76ms)
08-16 10:42:23.577 12742 12833 I okhttp.OkHttpClient: Content-Type: image/svg+xml
08-16 10:42:23.577 12742 12833 I okhttp.OkHttpClient: Last-Modified: Fri, 16 Aug 2024 08:42:24 GMT
08-16 10:42:23.578 12742 12833 I okhttp.OkHttpClient: Transfer-Encoding: chunked
08-16 10:42:23.578 12742 12833 I okhttp.OkHttpClient: Server: Jetty(9.4.54.v20240208)
08-16 10:42:23.578 12742 12832 I okhttp.OkHttpClient: <-- 200 OK https://<openhab-local-address-openHAB>:8443/icon/line?format=SVG&anyFormat=true&iconset=classic (77ms)
08-16 10:42:23.578 12742 12833 I okhttp.OkHttpClient: <-- END HTTP
08-16 10:42:23.578 12742 12832 I okhttp.OkHttpClient: Content-Type: image/svg+xml
08-16 10:42:23.578 12742 12832 I okhttp.OkHttpClient: Last-Modified: Fri, 16 Aug 2024 08:42:24 GMT
08-16 10:42:23.578 12742 12832 I okhttp.OkHttpClient: Transfer-Encoding: chunked
08-16 10:42:23.578 12742 12832 I okhttp.OkHttpClient: Server: Jetty(9.4.54.v20240208)
08-16 10:42:23.578 12742 12832 I okhttp.OkHttpClient: <-- END HTTP
08-16 10:42:23.584 12742 12831 I okhttp.OkHttpClient: <-- 200 OK https://<openhab-local-address-openHAB>:8443/icon/pump?format=SVG&anyFormat=true&iconset=classic (84ms)
08-16 10:42:23.584 12742 12831 I okhttp.OkHttpClient: Content-Type: image/svg+xml
08-16 10:42:23.584 12742 12831 I okhttp.OkHttpClient: Last-Modified: Fri, 16 Aug 2024 08:42:24 GMT
08-16 10:42:23.584 12742 12831 I okhttp.OkHttpClient: Transfer-Encoding: chunked
08-16 10:42:23.584 12742 12831 I okhttp.OkHttpClient: Server: Jetty(9.4.54.v20240208)
08-16 10:42:23.584 12742 12831 I okhttp.OkHttpClient: <-- END HTTP
08-16 10:42:23.602 12742 12826 I okhttp.OkHttpClient: <-- 200 OK https://myopenhab.org/api/v1/settings/notifications (108ms)
08-16 10:42:23.603 12742 12826 I okhttp.OkHttpClient: Server: nginx/1.18.0 (Ubuntu)
08-16 10:42:23.603 12742 12826 I okhttp.OkHttpClient: Date: Fri, 16 Aug 2024 08:42:24 GMT
08-16 10:42:23.603 12742 12826 I okhttp.OkHttpClient: Content-Type: application/json; charset=utf-8
08-16 10:42:23.603 12742 12826 I okhttp.OkHttpClient: Content-Length: 35
08-16 10:42:23.603 12742 12826 I okhttp.OkHttpClient: Connection: keep-alive
08-16 10:42:23.603 12742 12826 I okhttp.OkHttpClient: X-Powered-By: Express
08-16 10:42:23.603 12742 12826 I okhttp.OkHttpClient: ETag: W/"23-fmFNFNMjs09m01kwm7gJsWohDT4"
08-16 10:42:23.603 12742 12826 I okhttp.OkHttpClient: <-- END HTTP
08-16 10:42:23.604 12742 12742 D MainActivity: onActiveCloudConnectionChanged()
08-16 10:42:23.605 12742 12742 D MainActivity: onPrimaryCloudConnectionChanged()
08-16 10:42:23.606 12742 12742 D AbstractBaseActivity: Show snackbar with tag connectionEstablished
08-16 10:42:23.624 12742 12769 D FcmRegistrationWorker: Run with action org.openhab.habdroid.action.REGISTER_GCM
08-16 10:42:23.625 12742 12742 D FcmRegistrationWorker: Register device at openHAB cloud with URL: addAndroidRegistration<redacted>`

**Comment by DivineJimmi** [comment]
I have the exact same issue since updating to 3.16

**Comment by lenschith** [comment]
The same issue here after Update to 3.16.0.
If i set the encoding to mjpeg
