### ISSUE TITLE
Fatal error upon opening app

### ISSUE THREAD

**Issue by bestego** [openhab/openhab-android#3807]
### Actual behaviour
Since version 3.16.1 (or maybe already since 3.16.0?) A fatal error is reported on the opening screen. This suddenly happened on 3 different andoid devices running Android version 10(samsung) 12(moto G41) and 14(moto G54).  On one of the devices I have removed the replaced the 3.16.1 by the 3.15.5 version which works perfectly again.

### Expected behaviour
App should open normally and display what is configured in the selected sitemap

 
### Steps to reproduce
Automatically reproduces on all 3 of my Android devices (since automatic update to version 3.16.[01]

#### Client
* Android version: 10/12/14
* Device model: Moto G41 and G54 and Samsun SM-T590
* App version 3.16.1
* Build flavor : 
* Device language: NL

#### Server
* Server version: 1.8.3

* Reverse Proxy: 
* Authentic
ation method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: 
* openHAB Cloud version : 
* Authentication method : 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>
![Screenshot_20240824-212134](https://github.com/user-attachments/assets/d89c69b4-fffa-41c3-b62b-97d92c84b3b3)
![general.sitemap.txt](https://github.com/user-attachments/files/16737828/general.sitemap.txt)
![Screenshot_20240824-212134](https://github.com/user-attachments/assets/93952389-58c8-4771-b3df-7d11aa95f85d)

**Comment by bestego** [comment]
The error message in the opening screen says:
An unknown error has occurred: Value <?xml of type java.lang.String cannot be converted to JSONObject
Only 1 "try again"button is displayed below this message

**Comment by mueller-ma** [comment]
This was the last version with support for the ancient server version 1: https://github.com/openhab/openhab-android/releases/tag/3.15.2-release

**Comment by maniac103** [comment]
See #3725.
@mueller-ma Maybe we should reconsider? Maintenance effort of OH1 support code wasn't that high, after all.

**Comment by spiral27** [comment]
Hello, I am very happy user of openHAB since ~2014. I am still on version 1 because it has always been very reliable to me. I'd like to keep it that way if possible but I am facing the exact same problem as @bestego since my client updated to 3.16.  The error is also "_an unknown error occurred. Value <?xml of type java.lang.String cannot be converted to JSONObject_".

As a workaround, I installed the 3.15.5-release apk

**Comment by mueller-ma** [comment]
There seem to be more openHAB 1 installations than I thought, so let's revert it. #3809

**Comment by mueller-ma** [comment]
I restored support for openHAB 1 in app version 3.16.2, which I will release today.

**Comment by spiral27** [comment]
> I restored support for openHAB 1 in app version 3.16.2, which I will release today.

Wonderful! Thank you so much

**Comment by 8lazo8** [comment]
> I restored support for openHAB 1 in app version 3.16.2, which I will release today.

Thanks for restoring the support! I am still using V1.8, had not time to move to a new version and modify my complicated setup for it :)
