### ISSUE TITLE
openhab android 3.16.2 with android table version 14, no device data are sendig to openhan

### ISSUE THREAD

**Issue by baluderba** [openhab/openhab-android#3829]
Hallo and good morning team

I am using openhab 4.2.2 (currently the latest version) with the android app 3.16.2

tablet software.:
-----------------
android version 14
kernel version 5.4.249
knox version 3.10
knox api level 37
android sicherheitspatch ebene  1.10.2024

this (openhab app) is installed on 6 devices. mobile phone / tablet.
on 5 devices this version works absolutely correctly, without problems.
now I have treated myself to a new tablet. installed this app and cannot send any data to openhab.

this is internal no firewall, etc is using.

device identification => SamsungTablet_CarstenA9Tablet

I can recreate this with all values.
for testing here:
- BatteryLevel
- ChargingState
- WifiName
- BluetoothDevices

excample.:
==========
11-17 01:04:54.719 23356 23912 I okhttp.OkHttpClient: --> GET http://4.2.2>:8080/rest/items/SamsungTablet_CarstenA9TabletChargingState
11-17 01:04:54.719 23356 23912 I okhttp.OkHttpClient: User-Agent: Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19
11-17 01:04:54.719 23356 23912 I okhttp.OkHttpClient: Cache-Control: no-cache
11-17 01:04:54.719 23356 23912 I okhttp.OkHttpClient: --> END GET
11-17 01:04:54.719 23356 23911 D TrafficStats: tagSocket(166) with statsTag=0xffffffff, statsUid=-1
11-17 01:04:54.720 23356 23912 D TrafficStats: tagSocket(207) with statsTag=0xffffffff, statsUid=-1

......

11-17 01:04:54.735 23356 23912 I okhttp.OkHttpClient: <-- 404 Not Found http://4.2.2>:8080/rest/items/SamsungTablet_CarstenA9TabletChargingState (15ms)
11-17 01:04:54.735 23356 23912 I okhttp.OkHttpClient: Content-Type: application/json
11-17 01:04:54.735 23356 23912 I okhttp.OkHttpClient: Date: Sun, 17 Nov 2024 00:04:54 GMT
11-17 01:04:54.735 23356 23912 I okhttp.OkHttpClient: Transfer-Encoding: chunked
11-17 01:04:54.735 23356 23912 I okhttp.OkHttpClient: Server: Jetty(9.4.54.v20240208)
11-17 01:04:54.735 23356 23912 I okhttp.OkHttpClient: <-- END HTTP
11-17 01:04:54.737 23356 23423 E ItemUpdateWorker: Error updating item 'SamsungTablet_CarstenA9TabletChargingState' to 'ValueWithInfo(value=UNDEF, mappedValue=null, type=MapUndefToOffForSwitchItems, debugInfo=null)'. Got HTTP error 404
11-17 01:04:54.737 23356 23423 E ItemUpdateWorker: org.openhab.habdroid.util.HttpClient$HttpException: Not Found
11-17 01:04:54.737 23356 23423 E ItemUpdateWorker: at org.openhab.habdroid.util.HttpClient$method$2$2.onResponse(Unknown Source:45)
11-17 01:04:54.737 23356 23423 E ItemUpdateWorker: at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:51)
11-17 01:04:54.737 23356 23423 E ItemUpdateWorker: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-17 01:04:54.737 23356 23423 E ItemUpdateWorker: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-17 01:04:54.737 23356 23423 E ItemUpdateWorker: at java.lang.Thread.run(Thread.java:1012)

what has been done so far:
============================
update tablet last version
app deleted, memory cleaned with ccleaner and reinstalled
all values ​​saved by hand, turned off, rebooted the tablet and turned on again.
comparison between the tablets (values ​​and settings) everything is the same, except for the device name of course)
the result remains the same, no data is sent to openhab. (only from this tablet!!!)
that means the app works correctly as an app. only the device values ​​are not transferred.

openhab at home, view is OK and is displayed.
openhab logs (frontail) are also displayed correctly
openhab layout is also displayed correctly.

- BatteryLevel , no values
- ChargingState , no values
- WifiName , no values
- BluetoothDevices , no values

I assume there is a problem with the permissions, but I have no idea what could be wrong, ALL permissions in the openhab app are set to allowed.
possibly also a problem with Android version 14, since the function is available on all devices in version 13.

what I noticed are the java messages:
=====================================
11-17 01:05:07.648 23356 23421 E ItemUpdateWorker: Error updating item 'SamsungTablet_CarstenA9TabletChargingState' to 'ValueWithInfo(value=UNDEF, mappedValue=null, type=MapUndefToOffForSwitchItems, debugInfo=null)'. Got HTTP error 404
11-17 01:05:07.648 23356 23421 E ItemUpdateWorker: org.openhab.habdroid.util.HttpClient$HttpException: Not Found
11-17 01:05:07.648 23356 23421 E ItemUpdateWorker: at org.openhab.habdroid.util.HttpClient$method$2$2.onResponse(Unknown Source:45)
11-17 01:05:07.648 23356 23421 E ItemUpdateWorker: at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:51)
11-17 01:05:07.648 23356 23421 E ItemUpdateWorker: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-17 01:05:07.648 23356 23421 E ItemUpdateWorker: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-17 01:05:07.648 23356 23421 E ItemUpdateWorker: at java.lang.Thread.run(Thread.java:1012)
11-17 01:05:07.650 23356 23421 E ItemUpdateWorker: Error updating item 'SamsungTablet_CarstenA9TabletBluetoothDevices' to 'ValueWithInfo(value=UNDEF, mappedValue=null, type=Raw, debugInfo=null)'. Got HTTP error 404
11-17 01:05:07.650 23356 23421 E ItemUpdateWorker: org.openhab.habdroid.util.HttpClient$HttpException: Not Found
11-17 01:05:07.650 23356 23421 E ItemUpdateWorker: at org.openhab.habdroid.util.HttpClient$method$2$2.onResponse(Unknown Source:45)
11-17 01:05:07.650 23356 23421 E ItemUpdateWorker: at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:51)
11-17 01:05:07.650 23356 23421 E ItemUpdateWorker: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-17 01:05:07.650 23356 23421 E ItemUpdateWorker: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-17 01:05:07.650 23356 23421 E ItemUpdateWorker: at java.lang.Thread.run(Thread.java:1012)
11-17 01:05:07.650 23356 23401 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=58d5666e-c73f-43a7-9914-d9011ad3d14e, tags={ org.openhab.habdroid.background.ItemUpdateWorker, send_wifi_ssid, itemUploads, server-id-2 } ]
11-17 01:05:07.654 23356 23403 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=f6aed244-cb2e-4f3d-b597-29e78f7447c3, tags={ org.openhab.habdroid.background.ItemUpdateWorker, charging_state, itemUploads, server-id-2 } ]
11-17 01:05:07.658 23356 23403 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=90e3c0bc-c1b8-46d8-8a86-b1ee6b20b28e, tags={ org.openhab.habdroid.background.ItemUpdateWorker, send_bluetooth_devices, itemUploads, server-id-2 } ]

Does anyone have a good idea what I can do here?

Thanks to everyone and have a nice Sunday
The complete log is available, excerpts are posted here.

big thanks
balu
[fehler 6 .zip](https://github.com/user-attachments/files/17812591/fehler.6.zip)

**Comment by baluderba** [comment]
hey, zhanks for very quick anwser.

yes, that was also my first idea, but for me it cannot be, because good case on other devices shows at this point the same entry.

4.2.2 ist the servername " openhab 4.2.2 ", and that internal translated tho correct url.

and the other point is, that all the pages on my openhab are working /display correct ( hope i am right )

thanks
balu

**Comment by maniac103** [comment]
Okay, so that one is just the log filtering.

`11-17 01:04:54.735 23356 23912 I okhttp.OkHttpClient: <-- 404 Not Found [http://4.2.2>:8080/rest/items/SamsungTablet_CarstenA9TabletChargingState](http://4.2.2%3E:8080/rest/items/SamsungTablet_CarstenA9TabletChargingState) (15ms)` strongly points towards the item ` SamsungTablet_CarstenA9TabletChargingState` not being present on the server then. Did you double and triple check the item name?

**Comment by baluderba** [comment]
On server, no item with name in Front, this is the name of New tablet, old tablat hasafter "_" an other name. Only first Part is the same

**Comment by maniac103** [comment]
> new tablet did not send device infos from tablet to oüenhab ( as i wrote before )

That's not correct. The logs say it *does* send the device info (here: charging state), but your OH server rejects the update because the item doesn't exist. That's why I asked to check whether the item exists - if it doesn't it's hard for the app to update a non-existent item.

**Comment by baluderba** [comment]
hello maniac103

item are only for ping configured ( for both tablets => screenshot), same as all other android devices.
on page i go to items and select for "tab", and we see all entries for old tablet, one for ping device ( both tables ) => screenshot.
if i remember correct, i never define any other items for all android devices.

i startet app, define devicename, define url , servername, user and passwd, activat for excample "charging state" and got the name in my list.
but this was with version 3.2 ( hmmm ), i never had any problem on past with that till now.

i dont understand it, sorry

![Samsung_Tab_1](https://github.com/user-attachments/assets/3453bb58-5bec-4f6f-94bf-a0b5216535a7)
![Samsung_Tab_2](https://github.com/user-attachments/assets/92ae8778-23b8-4b03-a46c-6a07bc250d99)

**Comment by baluderba** [comment]
addon info.:

yes, you are correct, on opnehab i saw an auth error in case i set user and passwd. ( android version 14 )
on android version 13 user and passwd is also not set, and there are no problems.

logout on openhab , testlogon with user and passwd, everything is ok

now i create a new api key on openhab, insert this key on parameter user ( openhab android app ), and save this settings , reboot tablet, nothing changed.
i got no error messages on openhab/ event logs. and no parameter from new tablet are there.

**Comment by mueller-ma** [comment]
>  if i remember correct, i never define any other items for all android devices.

There's no automatic Item creation. You need to create the Items manually. If you do, the error will vanish.

**Comment by baluderba** [comment]
hey mueller-ma

you are total correct.
i found the problem. problem was that i did not see the item for this device. and that is correct. that item is in a "hidden" area ( model )
to activate / see that, i have to enable parameter "Show non-semantic". after enable , i can see all the devices and it is possible to add new parameter of new tablet.
every thing is now working correct.

so i must say sorry to all of you, and big thanks for your helping hand

balu
