### ISSUE TITLE
Dim Display if there is no touchscreen input

### ISSUE THREAD

**Issue by madon** [openhab/openhab-android#39]
It would be nice if there is an option to enable automatic display dimming if the display doesn't receive touch input for a configurable amount of time. If in dimmed state and the display is touched restore to the previous dimming value. This would be usefull if habdroid is used in conjunction with a wall mounted tablet and the 'disable display timer' option to reduce display wear and energy consumption. 
##

**Comment by belovictor** [comment]
Well, if you switch off 'disable display timer', it should behave exactly the way you described, but with the means of Android system itself. 'Disable display timer' option was created for stopping Android from going to standby and dimming the display. I don't think we really need such a function in the app.

**Comment by madon** [comment]
If I switch off the 'Disable display timer' option the system goes to standby and the display is switched off. But that's not what I want, because thn I have to press the power button to reenable the display and wake the system. In my setup the power switch of the tablet is not directly accessible cause it's wall mounted with a nice frame. So it would be nice if the display is just dimmed down to a certain level and on touch or if the state of a displayed item changes, the display goes back to full brightness. So if for example the door bell rings and the visibility of a frame in the sitemap which shows the live stream of the door cam is changed the display goes back to full brightness.

**Comment by digitaldan** [comment]
On my nexus tablets I have daydream mode enabled, I think this is what you are after.  After 30 seconds the screen dims to almost nothing, but its still on, so it responds to touches.  It dims  dark enough that I use it on the night stand as a clock.  This one is mounted in a frame, so I don't have easy access to a power button, but with this setup i have never needed it.

**Comment by madon** [comment]
Daydream may be an option. But it would be nice if habdroid can undim the diaplay if there are changes on the currently displayed items. So if for example the doorbell rings and a frame with the video stream of the door cam is displayed the display should get back to normal brightness. I think for such functionality the best place for the dimming is inside of habdroid.
