### ISSUE TITLE
Icon of beta version should contain a badge with "beta"

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#403]
The icon of the beta version should contain a badge with "beta".

----------
Previous post:
Hey,
it is possible and sometimes very usefull to distribute a beta version on play store, e.g. when a user, who reported a bug, should try a possible fix and doesn't have a building enviroment.

**Comment by FlorianSW** [comment]
+1 for that idea! Additionally to that I would even love to see a release in beta more often. There's probably also a way to automatically publish a new beta release from cloudbees, so that there could be a scheduled job for, say, each week to publish a new version?

**Comment by mueller-ma** [comment]
https://github.com/fastlane/fastlane might be worth a try.

Also https://gitlab.com/fdroid/repomaker is an application to built apps locally and publish them on e.g. github. I think I will setup a fdroid openhab repo for nightly builts and the official full built, which cannot make it to the official fdroid repo since it contains non-foss.

**Comment by mueller-ma** [comment]
@kaikreuzer @digitaldan Should I upload beta builds via the beta track or via a separate "app"? I preffer the latter, Google also does this: https://play.google.com/store/apps/details?id=com.chrome.beta

**Comment by kaikreuzer** [comment]
I cannot tell, what is the better way - up to you and @digitaldan to decide...

**Comment by mueller-ma** [comment]
Ok, I added it as separate app to the play store (https://play.google.com/store/apps/details?id=org.openhab.habdroid.beta), however it need to pass Google's review first.
A small todo list:

- [ ] Add note about the beta version to the description
- [ ] Add "Beta" to the app icon

**Comment by maniac103** [comment]
I'm not sure the transparency will work very well. I think it's better to make a 'cutout' in the logo to make room for the text.

**Comment by mueller-ma** [comment]
I prefer the version with a border:

![grafik](https://user-images.githubusercontent.com/22525368/204321345-2c4f991a-5b73-4a39-b172-33954c4b8f9b.png)

**Comment by maniac103** [comment]
In this size I agree, but in normal icon size?

**Comment by mueller-ma** [comment]
In icon size it looks indeed good, see #3107
