### ISSUE TITLE
Android 4.2.2: Ihr Gerät ist nicht mit dieser Version kompatibel

### ISSUE THREAD

**Issue by tonyathome2000** [openhab/openhab-android#41]
I just tried to install HABDroid from Google Play Store on my LIFETAB E10312 (Android-Version 4.2.2): Got the message: "Ihr Gerät ist nicht mit dieser Version kompatibel".
Even so the openHAB Wiki page on the Android client claims: "Android app is currently designed for mobile phones and tablets running Android 4.x."
##

**Comment by belovictor** [comment]
Can you please try to install developer snapshot from here, it should be fixed now:
https://openhab.ci.cloudbees.com/job/HABDroid/lastSuccessfulBuild/artifact/mobile/build/outputs/apk/mobile-debug.apk

**Comment by mueller-ma** [comment]
@tonyathome2000 Any updates on that? MinAPI is 14, 4.2.X is 17, so it should work.
