### ISSUE TITLE
FR: Display habpanel

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#426]
This app has some features for wallmounted tablets, e.g. wakelock and full screen. Do you think it might be good to have a webview, that displays habpanel and make profit of these features?

**Comment by kubawolanin** [comment]
There's a project of a community member called [HABPanelViewer](https://community.openhab.org/t/habpanelviewer/34112).
@vbier what are your thoughts on that? Maybe you'd like to jump on board and incorporate your code in existing official app?
Note that I have next to none experience with Android development so I have no idea how feasible it is at current state of both projects ;-)

Regardless of the implementation, it might be worth to display the HABPanel option only if http://demo.openhab.org:8080/rest/extensions
has `ui-habpanel` with `installed` parameter set to `true`.

Making @ghys aware too :-)

**Comment by vbier** [comment]
Everybody can take my code and incorporate it in the official android app, I have no problems with that. 

But I am not going to do it, as I think that both apps serve a different purpose/audience. People using habpanel most likely do not need the functionality in the official app (I do not know the official app very well, just judging from the screenshots). And most likely is it the same the other way round.

**Comment by mueller-ma** [comment]
@vbier Can you add a license to your habpanelviewer repo?
