### ISSUE TITLE
Image with or without upscaling

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#438]
I understand that the big images are downscaled to fit the layout. But systematic upscaling for small images could lead to a weird rendering.
Would it be possible to disable the upscaling ?
Could we have a display setting for users who prefer with or without upscaling ?

**Comment by lolodomo** [comment]
What do you think about the idea to avoid upscaling as soon as the source image width is for example a third or less of the drawable width ?
The general idea is to avoid a big upscale for very small images.

So if your phone is in portrait mode with screen width = 1080, all images with a width >= 360 will be upscaled to fill the 1080 but images with width < 360 will be displayed with their real width, without any updscale.

WDYT ?

**Comment by lolodomo** [comment]
Maybe we should consider the screen height too to avoid having an image with a bigger height than the phone screen ? I mean we should scale the image to be sure to have it rendered fully in the screen without the need of scrolling.
With my Android tablet in landscape mode, the Sonos album art is currently too big and I don't see fully the picture without scrolling. Maybe we should define that the image height should be at a maximum of 3/4 of the screen height for example.

**Comment by lolodomo** [comment]
A solution could be to limit the maximum upscaling ratio, maybe to 3 or 4.
WDYT ?

**Comment by mueller-ma** [comment]
> With my Android tablet in landscape mode, the Sonos album art is currently too big and I don't see fully the picture without scrolling.

This was fixed a long time ago, right?
