### ISSUE TITLE
Time to display a chart

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#440]
It takes around 7 seconds to render a chart. Why is it so long while it is fast in Basic UI ?

**Comment by mueller-ma** [comment]
On my devices basic ui is still faster, but it takes only about 0.5 seconds until the chart is loaded in app.

**Comment by lolodomo** [comment]
Strange. I should check my sitemap definition.

**Comment by lolodomo** [comment]
Here is one example that takes several seconds to display:
```
			Text label="Graphiques" icon="chart" {
				Switch item=HumChart1Periode icon="chart" mappings=[0="Jour", 1="Semaine"]
				Chart item=GHumiditeInt period=D refresh=60000 visibility=[HumChart1Periode==0]
				Chart item=GHumiditeInt period=W refresh=60000 visibility=[HumChart1Periode==1]
			}
```

**Comment by mueller-ma** [comment]
Try to reduce the refresh.

**Comment by lolodomo** [comment]
Still so slow even if I suppress the refresh tag.
I notice that it is even worst when using HTTPS rather than HTTP.
Using HTTPS leads to a slower app in general but that is relatively acceptable ... except for chart rendering.

PS: all this is on my local network.

**Comment by lolodomo** [comment]
Maybe the problem is the size of the image and/or rescaling.
What resolution of image is used for chart ?

**Comment by lolodomo** [comment]
As an example, my screen is 2560 x 1600 so screenWidth is 2560 and a chart is requested with height 1280 and width 2560. But finally the chart is displayed only in a portion of the screen width and so there is a rescaling required.
When the tablet is in a portrait mode, as the chart seems to be displayed on the full width, that should be ok.
Here is the generated URL: https://192.168.x.xxx:8443/chart?groups=GHumiditeInt&period=W&random=868643861&theme=black&dpi=320&w=2560&h=1280
We are manipulating a big bitmap image: around 200 KB.
The question is: would it help if we would request the real width/height of the final display, just to avoid any scaling ?

**Comment by lolodomo** [comment]
Of course, as my server is running on a RPI 2, it could be due to the server too.
What hardware for your server when you get your charts in 0,5 seconds ?

**Comment by lolodomo** [comment]
Adding traces in MyWebImage, I can say that what take time is the execution of the HTTPS request. onSuccess is called only 8 seconds after the call of `client.get(url, new MyHttpClient.ResponseHandler()`.
So what takes time is the download of the chart from the OH server.
Now why is it fast when I use Basic UI and slow when I use android app ?

**Comment by lolodomo** [comment]
In Basic UI, the URL is: https://192.168.x.xxx:8443/chart?groups=GHumiditeInt&period=W&theme=bright&t=1509713716123
So there is no dpi w an h parameters in the URL.
The image has only a size of 480x240 and a size of 5,5 kB.
**So the explanation is now clear, Basic UI is using a default low res image while the android app is using a hi-res and huge image.**

**Comment by lolodomo** [comment]
If a suppress dpi, h and w from the chart URL in the Android app, I immediately get better result, even if still longer than in Basic UI on the same device.

Additionnaly, with the current code, I can see that the resolution of the chart is not the same in landscape and portrait modes, probably for the reason I explained before.
If I suppress the dpi, h and w settings from the URL, the rendering is identical in landscape and portrait modes.

I am sure there was a reason to add these parameters in the chart URL but maybe we can make them optional ?

**Comment by lolodomo** [comment]
It is probably acceptable to let Java doing a little bitmap scaling.
So even if 480x240 is too small for a hi-res screen, we could find a compromise and avoid requesting the screen width as width for the chart. Maybe screen width / 3 could be acceptable ? 

What is the current highest screen resolution for Android tablet ?

**Comment by lolodomo** [comment]
After a quick search, it looks like 2560x1600 remains one of the highest resolution you can get with Android tablets.

**Comment by lolodomo** [comment]
200 KB in 8 seconds, it means 200 kbps, it seems to be very very low.
Maybe the server takes a lot of time to build the chart before sending it to the android app when hi-res is requested ?

**Comment by lolodomo** [comment]
```
             total       used       free     shared    buffers     cached
Mem:           973        939         33          6         33        121
-/+ buffers/cache:        784        188
Swap:           99          0         99
```
I can see that my RPI has only 33 MB of free memory ! Is it a problem ?
Using top, %MEM of my java process is 35,9%. Normal ?
PS: the hi-res chart requires around 3 MB on server side.

**Comment by mueller-ma** [comment]
```
                    chartLayoutParams.height = (int) (screenWidth / 2);
                    chartImage.setLayoutParams(chartLayoutParams);
                    chartUrl += "&w=" + String.valueOf(screenWidth);
                    chartUrl += "&h=" + String.valueOf(screenWidth / 2);
```



That means: query for a chart with width equals screen width and half hight. I think it is kinda bugged in landscape on tablets as it takes the whole screen width, scales it down.

> The question is: would it help if we would request the real width/height of the final display, just to avoid any scaling ?

I dont think we scale, just in tablet landscape.

> Why is it so long while it is fast in Basic UI ?

Basic ui doesn't add w and h attributes, maybe thats faster to render, because thats less pixel.

> Of course, as my server is running on a RPI 2, it could be due to the server too.

You could try a RPI 3 or overclock you Pi, run as less other software in background.

> What hardware for your server when you get your charts in 0,5 seconds ?

Ubuntu KVM on a Workstation with some Intel Xeon. I think e3.

> If I suppress the dpi, h and w settings from the URL, the rendering is identical in landscape and portrait modes.

Removing dpi shouldnt make a big difference, as it just scales the text. But we could read the dpi once and save it globally.

> Maybe screen width / 3 could be acceptable ?

That might be acceptable on most high res devices, but there are also some low res tablets, which really need as might width pixel as they can display.
Maybe we can depend on dpi or display resolution class (m,h,x,xx,xxx)

**Comment by mueller-ma** [comment]
For the ram "issue":
https://wiki.archlinux.org/index.php/Frequently_asked_questions#Why_is_Arch_using_all_my_RAM.3F

Newer version of `free` have `available`. If not:
`cat /proc/meminfo | grep '^MemAvailable:' | awk '{print $2/1024}'`

**Comment by lolodomo** [comment]
First I need to understand if there is a problem to handle such image size with slow hardware like RPI 2 or if the problem is only **MY** RPI 2. I need to check what takes time on server side but I imagine that it is the build of the chart itself.

If there is something to change, maybe that is better to do it on server side ?

What's a pity, we don't have any chart in the demo sitemap to esasily test. I would like to check how fast it is with a server running on my PC.

**Comment by lolodomo** [comment]
```
18:18:44.551 [INFO ] [rthome.ui.internal.chart.ChartServlet] - Received incoming chart request: Request(GET https://192.168.x.xxx:8443/chart?groups=GHumiditeInt&period=W&random=-456563398&theme=black&dpi=320&w=2560&h=1280)@161e4ed
18:18:44.609 [INFO ] [rthome.ui.internal.chart.ChartServlet] - start building the chart with width 2560 and height 1280
18:18:45.497 [INFO ] [rthome.ui.internal.chart.ChartServlet] - start writing the image data
18:18:51.452 [INFO ] [rthome.ui.internal.chart.ChartServlet] - end writing the image data
```
900 ms are needed by the server to build the chart (provider.createChart) and then 5 seconds are needed to write the PNG data with `ImageIO.write` at this line: https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java#L281
`ImageIO.write` is building a PNG file and it seems to be done very slowly on a RPI 2 if the data is big.
Can you confirm that it does not include the time to send the answer to the caller but only the preparation of this answer ?

**Comment by mueller-ma** [comment]
How can I see these log messages?

**Comment by lolodomo** [comment]
You can't, these logs have been added by myself.

**Comment by mueller-ma** [comment]
When we make an option called "high res charts" we could disable it by default and divide chart res by three.

**Comment by lolodomo** [comment]
I just see that we have a chart in the demo sitemap lol
It will help me.

**Comment by mueller-ma** [comment]
This is an example from my tablet. Original chart 1024 * 512, the other 512 * 256 (cleary too low):

![screenshot_2017-11-03-21-04-40](https://user-images.githubusercontent.com/22525368/32393643-a080ba40-c0da-11e7-859b-7bc2cadf1904.png)
![screenshot_2017-11-03-21-05-29](https://user-images.githubusercontent.com/22525368/32393645-a0a78d14-c0da-11e7-8e7f-688e4671b888.png)

**Comment by mueller-ma** [comment]
Also changing the dpi value makes it a little bit better:
![screenshot_2017-11-03-21-10-17](https://user-images.githubusercontent.com/22525368/32394393-44baa20e-c0dd-11e7-8f0d-5b0fc297d12c.png)

**Comment by lolodomo** [comment]
The problem was the time to compute the chart on the server side.

**Comment by mueller-ma** [comment]
Is this really closed? I think its more a client problem since the client request a too large chart.

**Comment by lolodomo** [comment]
The client has no knowledge of the server capabilities.
I have submitted a PR for an optional setting on the server side.
And I opened an issue here for the different rendering in landscape and portrait mode.

**Comment by lolodomo** [comment]
The result is ok with my tablet. I get reasonable delay if I force a maximum width to 960 and the chart looks ok in the android app.

**Comment by lolodomo** [comment]
And of course, on my PC, a chart with width 2560 is generated very fast, around 100 ms if I correctly remember.

**Comment by mueller-ma** [comment]
Many people in the play store complain about the long to time load a chart. They dont know about the server side fix. What can we do to change that?

**Comment by kaikreuzer** [comment]
Difficult. Some ideas:
- cache the last version and refresh it in the background. The user will at least immediately see something
- notice slow loading of charts (and thus identify a slow server) and dynamically reduce the requested resolution
- request the raw data from the server only and use a client side chart rendering. Would be cool to have something vector-based and interactive like in [HABPanel](https://github.com/openhab/org.openhab.ui.habpanel/blob/master/doc/images/habpanel_screenshot5.png) on the long run

**Comment by mueller-ma** [comment]
> cache the last version and refresh it in the background. The user will at least immediately see something

Thats what @lolodomo has done in #481, but there is still the problem with the initial load. I wouldn't show an outdated chart there.

**Comment by lolodomo** [comment]
@mueller-ma : don't forget that for charts you first erase the drawing so we will see nothing displayed during the loading of the chart.

**Comment by kaikreuzer** [comment]
> I wouldn't show an outdated chart there.

Maybe outdated and completely blurred to signal that it is loading? Or better have an animated GIF of Chuck Norris instead to keep the user calm? 🕺

**Comment by lolodomo** [comment]
Please note that my change was not introducing any cache, it was just avoiding concurrent requests to the same chart.

**Comment by mueller-ma** [comment]
> request the raw data from the server only and use a client side chart rendering. Would be cool to have something vector-based and interactive like in HABPanel on the long run

Indeed, that sounds like the best approach.
Do you think the old pngs based charts should still be available, e.g. switch between the old and new in the settings?

The current way to view a chart with multiple periods is:
````
Switch item=CHART_PERIOD label="Zeitspanne" mappings=[0="Stunde", 1="Tag", 2="Woche"]
Chart item=INET_PING period=h refresh=300000 visibility=[CHART_PERIOD==0, CHART_PERIOD=="Uninitialized"]
Chart item=INET_PING period=D refresh=1800000 visibility=[CHART_PERIOD==1]
Chart item=INET_PING period=W refresh=3600000 visibility=[CHART_PERIOD==2]
````
Do you think it should be possible to assign multiple periods and select one period client side? This way it enables using native controls, e.g. change period with two finger swiping. Should this rather be discussed in esh?

**Comment by mueller-ma** [comment]
@maniac103 WDYT about a slider like ChartScalingPreference in the settings to change between fast and high-res?

**Comment by maniac103** [comment]
@mueller-ma Sounds a bit overkill to me. How about a SwitchPreference with title 'Use reduced chart resolution' and summary along the lines of 'Generating charts can be taxing to the server. If you experience slow chart loading times and your server isn't powerful, enable this option to improve loading times' which cuts X and Y resolution in half?
