### ISSUE TITLE
Different chart resolution in landcape and portrait modes

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#445]
The chart resolution should be the same when the tablet/phone is in landscape or portrait mode.
The current implementation leads to lower texts in landscape mode than in portrait mode.
The reason is known: the chart is requested in the two cases with the full tablet width while finally only displayed (resized) in a part of the tablet width when in landscape mode.

**Comment by lolodomo** [comment]
@mueller-ma : have you an idea how this could be fixed ? Can we get the width of the final display ?

**Comment by lolodomo** [comment]
@mueller-ma : any idea how I can get the width of the right frame in case of a display in portrait mode on a tablet ?

**Comment by mueller-ma** [comment]
I have an idea, but need some help with the implementation. Code coming soon...

**Comment by mueller-ma** [comment]
https://github.com/mueller-ma/openhab.android/tree/445-size-chart
OpenHABFragmentPagerAdapter getPageWidth() seems to return wrong values. This only works for sub-sub-panes.

**Comment by lolodomo** [comment]
I got it, we can use `parent.getWidth()`. I will propose a fix.

**Comment by mueller-ma** [comment]
This bug was introduced, I think by #650

**Comment by maniac103** [comment]
@mueller-ma A bug from 2017 was introduced by my yesterday's pull request? I am confused.

**Comment by mueller-ma** [comment]
*reintroduced. I'm not sure if it was your PR, but it could be as you made a lot of changes to the internal layout.
