### ISSUE TITLE
Let Travis CI deploy CI-builds on Github

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#456]
Would be nice for interested users to download apks for easy installation right from github. Has been possible with Jenkins. 

For installation instructions, see: [http://szagurskii.com/blog/how-to-deploy-apk-to-github-releases-with-travis-ci/](http://szagurskii.com/blog/how-to-deploy-apk-to-github-releases-with-travis-ci/)

**Comment by digitaldan** [comment]
Hi, I agree and I'm already working on it now, hoping to have something by today.

**Comment by mueller-ma** [comment]
That will only work for git tags, but I think we should use tags anyway in the future since they trigger fdroid builds.
https://docs.travis-ci.com/user/deployment/releases/

**Comment by ThomDietrich** [comment]
Hey guys,
I lost track of all the activities over the last couple of days. (Kudos for that)
May I ask if by now there is any automated build system that I could get latest apks from?

**Comment by digitaldan** [comment]
So I have travis setup to create a signed APK release whenever a git tag is created, which is how travis ci recommends doing it.  So if you create a tag through the github web ui, or push a tag with git , a build will get triggered and when its complete it will create a github release based on that tag with the signed APK.

I would like to extend this to have every merge into master push a new signed APK into a "latest" release, I just have not had the time to do so yet.

**Comment by mueller-ma** [comment]
You could set up a small script, that creates a beta release every week.
Betas: 2.0.1
2.0.2
2.0.3
And so on..
The final release would be 2.1

**Comment by ThomDietrich** [comment]
https://semver.org/

There are many tools out there to ease the pain. Random example: https://github.com/alexfu/androidautoversion

**Comment by ThomDietrich** [comment]
@mueller-ma the script idea sounds good but it doesn't reflect how versions should be handled, ideally when a non-trivial change happened. As I said there are tools out there but it would actually be more important to have builds here and now. Could you as one of the currently most active developer create a tag as you suggested every now and then?

Long story short: I don't have a build environment but would like to try the latest build... 😃

**Comment by mueller-ma** [comment]
Beta versions are now regularly tagged be me and travis deploys the apks.
