### ISSUE TITLE
Widget broken - Wrong iconsize or microphone graphic is missing

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-android#531]
Hi,

After updating i recognized that the app widget is displayed wrong.

![image](https://user-images.githubusercontent.com/7161177/34114976-8492d522-e414-11e7-95df-0bb6fb5ed72b.png)
![image](https://user-images.githubusercontent.com/7161177/34114997-944ff044-e414-11e7-9a9c-11425138dea1.png)

Seems that something with the icons is wrong.
The voice button is usable if you have small fingers, but i don't think that this is the intended behavior.

BR 
Jerome

Edit:

Phone: Motorola Moto G Play
Android: 6.0.1

**Comment by mueller-ma** [comment]
![screenshot_20171218-172145](https://user-images.githubusercontent.com/22525368/34116223-36db40b8-e418-11e7-8526-f0d508e1aa9d.png)
I created a new widget (didnt had one before the update) and it looks like intended.

Android 7.1.2
LineageOS 14.1
Oneplus X

**Comment by mueller-ma** [comment]
Whats your grid size?

**Comment by Confectrician** [comment]
4x4

**Comment by mueller-ma** [comment]
I have 4x5 at 5 inch display. Did you try to remove and recreate the widget?

**Comment by Confectrician** [comment]
Did it right now, but that doesn't change anything.

**Comment by cribskip** [comment]
I'm having the same problem as @Confectrician.
I'll see if I can get my dev env ready today and take a look at this.

While at it, I'll make the widget resizable.

**Comment by cribskip** [comment]
Ok, finally got github to do what I wanted ;-) Please see #545

**Comment by robbyb67** [comment]
Same problem here - waiting for #545

**Comment by mueller-ma** [comment]
Fixed in #628
