### ISSUE TITLE
Issues with right to left languages

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#533]
This isnt an issue at all as long there is not translation in a rtl language.

Overlapping label and value:
![screenshot_ - - - - -](https://user-images.githubusercontent.com/22525368/34116748-c45f50f4-e419-11e7-913d-53724bd65fb2.png)
Text goes in wrong direction (should be on the left side of the icons)
![screenshot_ - - - - -](https://user-images.githubusercontent.com/22525368/34116749-c4e05320-e419-11e7-904d-0ba83f72762e.png)
Not sure if the swipe gesture is in the correct direction:
![screenshot_ - - - - -](https://user-images.githubusercontent.com/22525368/34116750-c590ce12-e419-11e7-98dc-5f8525fb5054.png)

**Comment by mueller-ma** [comment]
It seems to affect some users, I'll give it a try

**Comment by gargamelonly** [comment]
How can I help add translations?
Meanwhile, if no translation is available, why not display the default English text?

**Comment by mueller-ma** [comment]
The default english text is displayed, but the app is not optimized for right to left languages.
@ThomDietrich whats the current state of crowdin?

**Comment by mueller-ma** [comment]
We want to use a webbased translation platform, but until it is in use you can do the manual way. Here is a very good explanation how to do that: https://github.com/SimpleMobileTools/General-Discussion#how-do-i-add-a-new-file
The mentioned folder is https://github.com/openhab/openhab.android/tree/master/mobile/src/main/res in our repo.

**Comment by Aviramr** [comment]
Hi 
The same problem with my Galaxy S5 openhab app.
there is also some inconsistency of the icons, some of them from the left and some from the right of the switches and text.
I have just now finished to add new strings.xml file for Hebrew.
How can we proceed to fix the RTL issue ?
![1](https://user-images.githubusercontent.com/10687152/34341370-bfa6f83e-e99e-11e7-9d53-e99e0485122f.png)
![2](https://user-images.githubusercontent.com/10687152/34341371-bfc2cd52-e99e-11e7-8afc-4220a4f6320f.png)
![3](https://user-images.githubusercontent.com/10687152/34341372-bfe126f8-e99e-11e7-92f8-6f044971b176.png)
![4](https://user-images.githubusercontent.com/10687152/34341373-bffeff7a-e99e-11e7-8515-c00bb5c38dfa.png)
![5](https://user-images.githubusercontent.com/10687152/34341374-c01ae1e0-e99e-11e7-8736-5f72a51c5aff.png)
![6](https://user-images.githubusercontent.com/10687152/34341375-c036fe70-e99e-11e7-8a12-e6cbe86ec083.png)
![7](https://user-images.githubusercontent.com/10687152/34341376-c056abc6-e99e-11e7-8913-4f3695224b58.png)
![8](https://user-images.githubusercontent.com/10687152/34341377-c0717e38-e99e-11e7-95c2-db7fe2629c95.png)

**Comment by mueller-ma** [comment]
Are the frame texts in the right direction? I switched my tablet to the fake-rtl language (something with `(XB)`) and they where wrong, so I tried to fix that but I wasnt successfull. I can upload a apk and you can try it on your device. When everything works (or is at least better than before), @digitaldan can merge PR #547 and the next version in the play store will have this fix.

**Comment by gargamelonly** [comment]
Tested the apk.
Looks ok now.


בתאריך 25 בדצמ׳ 2017 07:59 PM,‏ "mueller-ma" <notifications@github.com> כתב:

**Comment by Aviramr** [comment]
I'll be happy to test the translation result , i'm usually doing this translation staff  in my work for the company i working for.
when the translation is RTL (All Hebrew) for most of the times it's easy, but when the text is "Heberw English Hebrew" or "Hebrew English" sometimes it's a mess. 
well i can fix it easily if something comes up . @mueller-ma
