### ISSUE TITLE
Selection Widget formatting incosistent

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-android#537]
The selection element presents the currently selected option to the right. Font, font size, color and positioning of the value are not in line with the rest of the Widgets. In addition it seems like the value does occupy more width than it needs to. me labels are cut off way before the value text.

**Comment by mueller-ma** [comment]
> In addition it seems like the value does occupy more width than it needs to. me labels are cut off way before the value text.

Can you select the longest value and check if it still occupies to much space?

> Font, font size, color and positioning of the value are not in line with the rest of the Widgets

We change all "active" elements to black (https://github.com/openhab/openhab-android/pull/736#pullrequestreview-101108788). The font and font size seems to be the same for selection and switches with mappings.

**Comment by mueller-ma** [comment]
> In addition it seems like the value does occupy more width than it needs to. me labels are cut off way before the value text.

It seems that there's always enough space reserved, so that the longest possible value can be displayed.
