### ISSUE TITLE
Refresh on pulldown

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-android#539]
When inside a sitemap view pulling down the view beyond the length of the sitemap should trigger a refresh action as known from many apps. Currently there is no easy way to trigger a refresh of the sitemap view.

Rationale: Even if that might technically not be needed, a user might want to do that and one of the google app design guidelines is that every user input should result in appropriate action...

**Comment by mueller-ma** [comment]
I dont think this is technically needed and I vote for not including a thing, that does nothing.

**Comment by ThomDietrich** [comment]
Why isn't it? At least in the past I had to refresh manually occasionally...

**Comment by mueller-ma** [comment]
AFAIK the app auto refreshes. See #504 for improvements.

**Comment by ThomDietrich** [comment]
Can't prove that it is not. I can tell you for a fact that I did see an outdated state of my sitemap in the past and had to refresh the view...
Please also reconsider my google design guideline argument from above.

The last decision is with you. Do what you want with the issue.

**Comment by mueller-ma** [comment]
@lolodomo had a deaper look in auto refresh. Is manual refresh needed?

**Comment by lolodomo** [comment]
Current implementation of auto refresh is not 100% reliable. I am working on a new solution based on SSE.

**Comment by beetle442002** [comment]
I can't even get the app to refresh and show a acurate state since the last update to the app without changing the state in the app first.

**Comment by ThomDietrich** [comment]
@beetle442002 are you sure your described behavior is a problem with the android app? sounds like an item initialization issue of your setup. Could you please verify with Basic UI?

**Comment by beetle442002** [comment]
@ThomDietrich you seem to be correct that it is not an app issue. The current status is not reflected in the PaperUI ether for me. Thank you for your response I will have to look into this farther.

**Comment by kaikreuzer** [comment]
> AFAIK the app auto refreshes.

Not necessarily. For Chart, Image and Video widgets, you can define a refresh interval and you might choose e.g. 1 minute here to avoid too regular automatic refreshes. I e.g. have images of IP cams in my sitemap, where it would be very useful to trigger a refresh "on-demand" by the pull down feature.
Also, Webview widgets are never automatically refreshed, so for those as well this feature makes sense.
