### ISSUE TITLE
Setpoint and Selection dialogs

### ISSUE THREAD

**Issue by CrazyIvan359** [openhab/openhab-android#550]
My app just updated and now the Selection and Setpoint Sitemap items both open a dialog, instead of their old behavior. This makes a bit more sense for the Selection item than it does for a Setpoint, but I don't like this new dialog instead of the nicely sized dropdown list that we had before. Setpoints are my big issue here, why have they been changed to a wheel dialog? This splits the user experience between android and the web. The web interface still uses the +/- buttons, as is indicated in all of the documentation.

**Comment by mueller-ma** [comment]
On a selection item with many entries, the old dropdown menu was a bit too small.
You have different input methods for basicui and the app (touch vs mouse/keyboard), so I think different dialogs are a good thing.

**Comment by cribskip** [comment]
I'm also missing the old style when controlling volume on my sound system. However, the UX of the new Dialog is better than the old style for things like thermostats.

What about adding +/- buttons to the new dialog right next to the value wheel?

**Comment by mueller-ma** [comment]
So like the color wheel? That seems to be a good idea.

**Comment by CrazyIvan359** [comment]
That sounds like a good mix of both options. The old up/down buttons on either side and the value between is actually a button that opens the wheel

**Comment by boc-tothefuture** [comment]
Would we still use the down triangle image?

**Comment by mueller-ma** [comment]
Thats a good question. If no, people might think we changed it back to the old layout. If yes, it might look odd.

**Comment by CrazyIvan359** [comment]
What about a small up/down arrow icon?
Something like this:
https://d30y9cdsu7xlg0.cloudfront.net/png/877877-200.png

**Comment by boc-tothefuture** [comment]
We could put +/- to left of the value?

**Comment by CrazyIvan359** [comment]
I think that might be confusing. I more meant something like this:
![setpoint](https://user-images.githubusercontent.com/6764025/34341078-dec5490a-e95d-11e7-893d-82711c4894b1.png)

And something else that came to mind, that would be useful in the basicui as well as the app, the up/down buttons could be disabled (greyed out) when the setpoint is at either limit

**Comment by mueller-ma** [comment]
In the android settings app switches are toggled by clicking somewhere in the row. When we add "short click actions" to this app, we could add:
1. Make switch touch targets full-screen #90
2. Send on/off in slider items #735
3. For selection items re-add the up and down buttons and open the dialog when clicking on the label, icon or the space between those and the switches

**Comment by maniac103** [comment]
BTW, something I also plan to do in the future is converting the dialogs into popups with instant apply behavior, that is, without OK/cancel buttons (apply on value change, close on touching elsewhere) ... might also help here a bit.

**Comment by gersilex** [comment]
I would also like to throw the idea of making the label a button between the two other buttons into the room. Re-introducting the up-down buttons and making the whole row clickable like in the Android settings app would fit better, though imho.

![34341078-dec5490a-e95d-11e7-893d-82711c4894b1](https://user-images.githubusercontent.com/2018039/38781861-e349436a-40eb-11e8-8788-914cae34462c.png)

**Comment by boc-tothefuture** [comment]
I like @gersilex mockup.

I will note that originally I had the whole row clickable to bring up the setpoint dialog.  I was told to remove that because it was inconsistent with the rest of the use cases.
