### ISSUE TITLE
Icons flash on normal sitemap page

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#552]
Situation:
Sitemap with multiple items, each with different icon.
One item is updated every 1,x seconds.

Problem:
All icons seem to be refreshed and flash as the updated item is refreshed.

Note aside:
Seems to be causing data traffic as it seems to be slower getting the images over mobile data.

This is not a duplicate of #541

**Comment by mueller-ma** [comment]
Icons are locally cached. They are only downloaded once, when a specific state of the item is set the first time. So when you have a simple switch, the icon is downloaded when the switch is the first time set to ON and OFF.

**Comment by cribskip** [comment]
Yes, that's what the cache used to be for.
I've tested reinstalling, clearing the cache (from app & system app settings). No change.

I'll try to post a YT video.

**Comment by cribskip** [comment]
https://www.youtube.com/watch?v=1DfoZ2-GuTY

**Comment by mueller-ma** [comment]
How do you know that this is no duplicate of #541
The longer flash on mobile can be explained that the rest json needs longer to be downloaded.

Can you capture a log when your on mobile?

**Comment by cribskip** [comment]
> How do you know that this is no duplicate of #541
I'm sorry, I caused a misunderstanding. I meant it's the same symptom but not in the drawer but on normal pages. I didn't mean to know the cause.

> Can you capture a log when your on mobile?
I'll try and post here. I may not be able to post while Xmas ;-)

**Comment by mueller-ma** [comment]
I changed #541 to `Navigate to any page in your sitemap and wait until some item changes. All icons in the sitemap flash.`. It is for the "normal" icons.

**Comment by lolodomo** [comment]
I am not sure if it is something new but yes the icons are "flashing" when something is changed in the page. Apparently, it happens as soon as the fragment is updated. Maybe we should check that the cache is still working well.

**Comment by lolodomo** [comment]
I agree that it is not very pleasant to see and it is surprising that it takes so long to reload an icon especially when there is a cache.

@mueller-ma : if I correctly remember, we are erasing the image before reloading it only for the charts but not for the icons or other images.

**Comment by mueller-ma** [comment]
We erase it for charts and not for image items. No idea how icons are handled.

The real issue here is, that the hole page is reloaded, when one item changes.

**Comment by lolodomo** [comment]
Yes but as I explained when discussing about SSE, I don't see how this could be easily changed. notifyDataSetChanged is called when there is a change in the page leading to a refresh of the full page through OpenHABWidgetAdapter.
I just checked the code and cache is apparently enabled for the icons.

**Comment by lolodomo** [comment]
Is there a way in an Android app to trigger the refresh of only one item in the data set ?

**Comment by mueller-ma** [comment]
@cribskip Can you try it with the latest beta version? https://github.com/openhab/openhab-android/releases
It seems to be fixed.

**Comment by cribskip** [comment]
Installed just yesterday. Working just fine now. Thank you all

**Comment by maniac103** [comment]
#669 is what fixed it.
