### ISSUE TITLE
Only visible pages should be refreshed

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#555]
As I am working on implementing refresh with SSE in the app, I am studying the current way the pages are displayed and refreshed. And I am surprised to discover that the app is not refreshing only the visible page but even not visible pages.
If you are displaying a page being at fourth in deepth in your sitemap, you have in fact 4 fragments handled by the app corresponding to each level leading to your current page, that is the home page, the page at second in deepth, the page at third in deepth and the current page (fourth in deepth). Even if only one page (or two in landscape mode) are visible, the 4 pages are opening a long polling HTTP request waiting for updates and so each one is refreshing.
Was there any reason to handle that such a way ?
I think only the visible page(s) should be refreshed by the app.

**Comment by maniac103** [comment]
Indeed, the polling should start in onStart of the fragment and stop in onStop.

**Comment by lolodomo** [comment]
In fact, the page is reloaded and the polling is started in onResume. onPuase/onResume are called even for not visible pages.

**Comment by maniac103** [comment]
That's worth looking into though, as onResume is only supposed to be called when the fragment is fully visible (onStart is called when the fragment is partially visible): https://developer.android.com/reference/android/app/Fragment.html#Lifecycle

**Comment by lolodomo** [comment]
How is determined if the fragement is visible ?
Would is it be by the call of `getPageWidth` ? Because `getPageWidth` is not returning 0 for not visible fragments...

**Comment by maniac103** [comment]
I haven't looked at how exactly sitemap fragments are added, but I'd assume some replacement fragment transaction happening that shows the new page. If that's the case, the old fragment should go to the onPause/onStop life cycle in that moment.

**Comment by maniac103** [comment]
Never mind, I see a ViewPager is used there ... for whatever reason? https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setOffscreenPageLimit(int) is the control one could play with there, but I guess understanding why exactly the ViewPager is there in the first place would be helpful before fiddling around...

**Comment by lolodomo** [comment]
Yes, maybe we should keep only necessary (visible) fragments.

**Comment by lolodomo** [comment]
I have not yet studied what is ViewPager ...

**Comment by lolodomo** [comment]
Having one fragment per page + a ViewPager makes easy the implementation of the back button.

I think the only change we should do is to not reload the page when resuming a hidden fragment. Maybe a new field on the fragment is required for that ?

**Comment by maniac103** [comment]
> Having one fragment per page + a ViewPager makes easy the implementation of the back button.

Err, why exactly? When using fragment transactions + back stack, there is exactly 0 special code needed for back button handling.

> I think the only change we should do is to not reload the page when resuming a hidden fragment. Maybe a new field on the fragment is required for that ?

I disagree (or we have a misunderstanding). As soon as we stop polling, we don't know the current state anymore and need to reload it when it becomes visible again.

**Comment by lolodomo** [comment]
Any fragment is systematically reloaded when onResume() is called.

**Comment by lolodomo** [comment]
I have to check what happens exactly when using the back button. The update is very fast in this case. The ViewPager is updated. Maybe no fragment are reloaded in this case ? I will check. That would explain why all parent fragments continue being updated even when not visible.

**Comment by lolodomo** [comment]
When the back button is pressed, we can see in OpenHABFragmentPagerAdapter.onPageSelected, when in 2 columns mode, that the last fragment is removed and `notifyDataSetChanged` is then called leading to a call to onResume() in all remaining fragments and so a full reload of all existing pages.

Maybe a solution would be to use `setUserVisibleHint` and in onResume() test if the fragment is visible or not before calling `showPage`.

**Comment by lolodomo** [comment]
Was it finally fixed ? If it is, I close the issue.

**Comment by maniac103** [comment]
Well, we (deliberately) still keep pages on the back stack updated (be it via long polling or SSE), so their content is up-to-date when returning back to them. I don't see any obvious problem with that though? (Even though my first impression in https://github.com/openhab/openhab-android/issues/555#issuecomment-353780574 was different)
Updates are canceled for a given page only if the page is closed or the app is sent to the background; in the latter case updates are resumed when it comes to the foreground again.

**Comment by lolodomo** [comment]
So if you think it is proper like that, I close the issue.
