### ISSUE TITLE
Inform user why GCM registration failed

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#560]
Currently it just shows that gcm registration failed, but not why. Possible reason:

1. No play services
2. Outdated play services
3. Foss build
4. No remote url configured

**Comment by maniac103** [comment]
FOSS build probably shouldn't show this line at all.

**Comment by mueller-ma** [comment]
We should definitly show it and that it is not available in the foss build.
"You're running the foss build, gcm is not available in this version. Click here to download the full version from play store" or similar.

**Comment by maniac103** [comment]
It's obviously not my call to make, but I disagree there. Play Store is the 'normal' way of getting the app, as in: used by the majority of people. If someone went to F-Droid to get the app, he already made an informed decision to not want non-OSS software. Google parts being missing is a natural consequence of that, and it's also the case among all other apps on F-Droid. Therefore IMHO there is no point directing those users to Play Store in the about dialog, as those users made an informed decision to not use Play Store when they installed the app.

**Comment by mueller-ma** [comment]
Ok, I agree to not display a link. But think of devs building accidentally the wrong flavor and trying to fix gcm for hours, until they realise that foss flavor is default.

**Comment by FlorianSW** [comment]
I think, that will be useful. After fixing #572 this would also look much snoozer I think :)
