### ISSUE TITLE
Notifications still have the old logo

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-android#563]
Push notifications displayed by the app still sport the old openHAB logo: I believe it is [ic_stat_openhab_bw.png](https://github.com/openhab/openhab.android/blob/master/mobile/src/main/res/drawable-xhdpi/ic_stat_openhab_bw.png) (available in different dpis, this is the xhdpi version).

**Comment by cribskip** [comment]
Hey, just tried with version out of the play store. For me, it's displaying the current (correct) logo in the notification area (pull down) and on the notification bar (top left). Xiaomi Redmi 4 Prime, Android 6.0.1

Can you clarify which icon you meant? Best would be to post a screenshot. Please list your phone specs (Make/Modell, Android version)

**Comment by mueller-ma** [comment]
I also looked at it. I searched for usages of the picture you mentioned, but Android Studio didnt find one.

**Comment by ghys** [comment]
This is what I get on my LG G4 (Android 6.0), with version 2.0.0:

![screenshot_2017-12-28-19-31-23](https://user-images.githubusercontent.com/2004147/34419797-3bd4b0f4-ec06-11e7-8608-5ba054cdda44.png)

**Comment by mueller-ma** [comment]
Can you try to clear the app cache? Settings => Apps => Openhab => Clear cache

**Comment by cribskip** [comment]
Tested the same way via myopenhab.org/Devices send notification. Right outcome/icon.
Please clear the cache, try to reinstall and/or reboot device. I also found no references to the icon. Maybe we should delete it and see what's your phone doing then ;-)

**Comment by ghys** [comment]
Tried clearing the cache, with no change, then completely uninstalled and reinstalled the app from the Play Store, cleared the cache again, and nope:
![screenshot_2017-12-28-20-30-06](https://user-images.githubusercontent.com/2004147/34421191-20926f36-ec0e-11e7-91ec-d7633f93ecd1.png)

Really don't know where this icon comes from 😮

**Comment by cribskip** [comment]
Ok, tomorrow I'll build a apk with this icon removed and send you a link. Let's see then. I'm guessing the LG specifics (theme?) trigger on the icon name.

**Comment by ghys** [comment]
That wouldn't be surprising...! The notifications drawer is significant from vanilla Android. What's more, the wrong icon is also the displayed in the notification area in the top-left, when the drawer is not pulled down.

**Comment by cribskip** [comment]
Well, turns out it's still used, see: https://github.com/openhab/openhab.android/blob/a3d428716e2ea593331ae04a498d8d8f38bd71e1/mobile/src/full/java/org/openhab/habdroid/core/GcmIntentService.java#L104

@mueller-ma and I perhaps did use "Find usages" function which really returns no references.

I've messed up with my fork... All I did was changing mobile\src\main\java\org\openhab\habdroid\core\GcmBroadcastReceiver.java:69 to .setSmallIcon(R.drawable.openhabicon) and deleted the old files (ic_stat...)

APK is attached. Please test and report back.
[mobile-full-debug.zip](https://github.com/openhab/openhab.android/files/1593144/mobile-full-debug.zip)

**Comment by ghys** [comment]
Thanks for looking into this 😇 
Now it's an opaque circle 🙄 

![screenshot_2017-12-29-14-37-53](https://user-images.githubusercontent.com/2004147/34438317-40074c68-eca6-11e7-826b-5baa936848c7.png)

**Comment by mueller-ma** [comment]
This notification has the new icon: https://github.com/openhab/openhab.android/pull/472/files#diff-22ef8d4658ad6e41ff9dc4b33418ed6aR48

**Comment by FlorianSW** [comment]
@cribskip What build variant do you use in Android Studio? The GcmIntentService is only included, if you use one of the full flavors, I think Android Studio preselects the foss flavor, were we do not include GCM, so the image isn't used in this case :) (I'd a similar expression when I deleted a method, which was marked as unused and later I recognized, that the method is used in the full flavor) :)

**Comment by FlorianSW** [comment]
#571 now looks like:
![screenshot_20171229-230736](https://user-images.githubusercontent.com/4892966/34448453-cc26376c-eced-11e7-9403-fd56f64438b6.png)
