### ISSUE TITLE
Custom log functions

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#565]
When we have our own log function, we can enhance the logging. They basicly pass the message to Android's `Log`, but have some more features, e.g.

- Only log debug and verbose, when running a debug build (like Android Studio suggests), but without needing to write the condition every time Log.d is used
- When an exception is caught, show stactraces in dialog, when debug mode is enabled. Most users are not able to capture a log, but they can easily take screenshots.
- Write a user accessable log file, when in debug mode

**Comment by maniac103** [comment]
> When an exception is caught, show stactraces in dialog, when debug mode is enabled. Most users are not able to capture a log, but they can easily take screenshots.

Maybe it's better to enable them to send a log? Running `logcat`, capturing its output and put it into a share intent isn't that hard to do.

**Comment by mueller-ma** [comment]
Signal has the ability to post the log at github as gist and shows the user the link to it. The nice thing about this is, that they made a library out of it: https://github.com/signalapp/libpastelog

**Comment by maniac103** [comment]
I don't see gist upload in that lib though, I only see upload to some AWS instance...
