### ISSUE TITLE
OpenHAB-Information tab in About activity looks weird

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab-android#572]
Compared with our About tab in the about activity, the information about the openHAB server the user is currently connected to looks weird, just some strings concatenated to something:
![screenshot_20171229-232200](https://user-images.githubusercontent.com/4892966/34448601-3e925974-ecef-11e7-8a6b-6ae6add18980.png)

I've nothing special in mind, just something that looks a bit better, probably have some sections (openHAB and openHAB-cloud or whatever) and some design where the user can differentiate between a heading and a value.

**Comment by mueller-ma** [comment]
Maybe something like the "About" section in the android settings with all the version information.

**Comment by FlorianSW** [comment]
My first try looked like:
![screenshot_20171230-001608](https://user-images.githubusercontent.com/4892966/34449245-b0efb492-ecf6-11e7-8d68-f6095ee0bd90.png)

With which I'm not happy at all, and I even can't say why, it just doesn't look that fancy and isn't a real improvement to the current state :(

**Comment by mueller-ma** [comment]
More whitespace above the dividers and the title should be black.

The about tab also needs to be improved. My pr for the about screen was merged while wip. Especially the one large multiline string is very hard to translate.

**Comment by FlorianSW** [comment]
Do you want to open a separate issue for the About screen? :)
