### ISSUE TITLE
NFC actions are not localized

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#576]
When long holding a switch without mappings, the actions are not localized. The translated strings exist, but are unused.

**Comment by FlorianSW** [comment]
I planned to fix that issue together with #538, which (what I've in mind) would remove this long press option all together and use translated strings for the actions in the new Activity. Not sure how fast we can achieve that, however, translating these strings should be pretty easy. There's already a context passed to the class handling these values.
