### ISSUE TITLE
Copyright in files is outdated

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#614]
or completely missing. See https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/model/OpenHABNFCActionList.java#L2

**Comment by FlorianSW** [comment]
The question is: Do we really need, or even want, to have such copyright line in the source code files? In my opinion, they're just pointless and requires work to update them, which could be invested into _real_ work :)

The license is already mentioned in the LICENSE file, and the contributors can easily retrieved with git-log, so no "openHAB.org and others" copyright needed. That the program is developed by openHAB.org is IMHO already visible, as it is under this org.

So, in my opinion, we should remove the copyright and license header from the files. Or, if we want to keep the license headers, I'll would still remove the copyright with dates and just keep the license header :)

**Comment by mueller-ma** [comment]
When we add license headers to all files, it's just a simple sed command to update them

**Comment by FlorianSW** [comment]
Where is the value :) We could even create a CI job to run each year to have the headers replaced, however, this does not bring us any more value than not having them :D

**Comment by mueller-ma** [comment]
@kaikreuzer @digitaldan WDYT?

**Comment by kaikreuzer** [comment]
I would prefer to follow the same principles (at least for Java code) throughout the different openHAB repos as much as possible. For all Maven-based repos, we are using a license plugin, see https://github.com/openhab/openhab-core/blob/master/poms/pom.xml#L112-L146. With this in place, all there is to do is to run `mvn license:format` and all headers are up to date.
Note sure if something similar is possible for Gradle?
In general, I think license headers are a best practice that we should not drop.
A related info: We might switch from EPLv1 to EPLv2 soon, which might also result in a change of the headers, see e.g. https://github.com/eclipse/smarthome/pull/4552.
