### ISSUE TITLE
Icons aren't updated with the state

### ISSUE THREAD

**Issue by jmvaz** [openhab/openhab-android#618]
With the latest update of openhab android, the status of the icons are not correctly setted.
I tried with png and svg icons, but dont solved the issue.

My Setup is Openhabian with stable OH 2.1.0.

In attachment I send 2 images from the same timestamp. In basic ui the icons are with correct state, and in android app the icons are incorrect.
![image](https://user-images.githubusercontent.com/19754068/34721468-c3654f14-f53a-11e7-9729-c7c1be07ed68.png)
![image](https://user-images.githubusercontent.com/19754068/34721519-f01a1558-f53a-11e7-8ec3-248d1be60ab0.png)

**Comment by mueller-ma** [comment]
I this is only the rollershutter icon, than its a duplicate of #543
