### ISSUE TITLE
Setpoint item displaying value from another one while others do not display any value

### ISSUE THREAD

**Issue by MaximeLussier** [openhab/openhab-android#621]
This is a weird one:

The 65% displayed in screenshot_1 is actually the volume from my receiver in screenshot_2. The other setpoint elements do not display a percentage (I believe they should).

screenshot_3 is from the basicUI showing what is expected: The percentage is correctly displayed and there is no link to the volume.

The issue is Android specific, the iOS application displays the percentages correctly. 

Furthermore, on an unrelated note, the setpoint elements are better on iOS IMO as they have +- buttons directly on the UI. The same was previously true on Android. Is there a way to return to the previous elements or combination of both (if you tab on the percentage)?

Thanks

Here is the sitemap:
sitemap home label="My Home"
{
    Frame label="Receiver" {
        Switch     item=Yamaha_Power_Zone   label="Power"
        Setpoint   item=Yamaha_Volume       label="Volume"
        Slider     item=Yamaha_Volume       label="Volume"
        Selection  item=Yamaha_Input mappings=[HDMI1="PC",HDMI2="HTPC",HDMI3="Bell Tv",HDMI4="BluRay","NET RADIO"="NetRadio",TUNER="Tuner"]
    }
    Frame label="Dimmers" {
        Setpoint     item=Dimmer1        label="Master Bedroom" icon="dimmablelight"
        Slider       item=Dimmer1        label="Master Bedroom" icon="dimmablelight"
        Setpoint     item=Dimmer2        label="Dining Room"    icon="dimmablelight"
        Slider       item=Dimmer2        label="Dining Room"    icon="dimmablelight"
        Setpoint     item=Dimmer4        label="Living Room"    icon="dimmablelight"
        Slider       item=Dimmer4        label="Living Room"    icon="dimmablelight"
        Setpoint     item=Dimmer3        label="Home Cinema"    icon="dimmablelight"
        Slider       item=Dimmer3        label="Home Cinema"    icon="dimmablelight"
        Setpoint     item=Dimmer5        label="Basement"       icon="dimmablelight"
        Slider       item=Dimmer5        label="Basement"       icon="dimmablelight"
    }
}

![screenshot_1](https://user-images.githubusercontent.com/944488/34751674-ffbc2de8-f57b-11e7-85d0-806bec03b92f.png)
![screenshot_2](https://user-images.githubusercontent.com/944488/34751679-040ae4b6-f57c-11e7-9363-773ecebc283f.png)
![screenshot_3](https://user-images.githubusercontent.com/944488/34751780-929f331c-f57c-11e7-8fe0-b7894970b580.png)

**Comment by MaximeLussier** [comment]
Please note that this is not a new bug.
Screenshots were made using v2.0.0 Dec 16.

In case this is related to the sitemap, here is my current complete sitemap:
sitemap home label="My Home"
{
    Frame label="Controls" {
        Switch     item=epsonPower          label="Power"
        Switch     item=epsonMute           label="Mute"
    }
    Frame label="Info" {
        Text  item=epsonPowerState
        Text  item=epsonAspectRatio
        Text  item=epsonSource
        Text  item=epsonColorMode
        Text  item=epsonColorTemperature
        Text  item=epsonLuminance
        Text  item=epsonLampTime
        Text  item=epsonErrCode
    }
    Frame label="Receiver" {
        Switch     item=Yamaha_Power_Zone   label="Power"
        Setpoint   item=Yamaha_Volume       label="Volume"
        Slider     item=Yamaha_Volume       label="Volume"
        Selection  item=Yamaha_Input mappings=[HDMI1="PC",HDMI2="HTPC",HDMI3="Bell Tv",HDMI4="BluRay","NET RADIO"="NetRadio",TUNER="Tuner"]
    }
    Frame label="Dimmers" {
        Setpoint     item=Dimmer1        label="Master Bedroom" icon="dimmablelight"
        Slider       item=Dimmer1        label="Master Bedroom" icon="dimmablelight"
        Setpoint     item=Dimmer2        label="Dining Room"    icon="dimmablelight"
        Slider       item=Dimmer2        label="Dining Room"    icon="dimmablelight"
        Setpoint     item=Dimmer4        label="Living Room"    icon="dimmablelight"
        Slider       item=Dimmer4        label="Living Room"    icon="dimmablelight"
        Setpoint     item=Dimmer3        label="Home Cinema"    icon="dimmablelight"
        Slider       item=Dimmer3        label="Home Cinema"    icon="dimmablelight"
        Setpoint     item=Dimmer5        label="Basement"       icon="dimmablelight"
        Slider       item=Dimmer5        label="Basement"       icon="dimmablelight"
    }
}

**Comment by mueller-ma** [comment]
I had a look at this one, but have no clue why this happens.

**Comment by maniac103** [comment]
@mueller-ma If I had to guess, I'd say views are recycled upon scrolling and the recycled view isn't initialized properly.

**Comment by MaximeLussier** [comment]
Using the following in OpenHABWidgetAdapter.java line ~692 fixes the issue of the duplicated percentage:
            case TYPE_SETPOINT:
                splitString = openHABWidget.getLabel().split("\\[|\\]");
                if (labelTextView != null && splitString.length > 0)
                    labelTextView.setText(splitString[0]);
                if (valueTextView != null) {
                    if (splitString.length > 1) {
                        // If value is not empty, show TextView
                        valueTextView.setVisibility(View.VISIBLE);
                        valueTextView.setText(splitString[1]);
                    }
+                  else {
+                       // If value is empty, hide TextView
+                       valueTextView.setVisibility(View.INVISIBLE);
+                       valueTextView.setText("");
+                    }
                    final Context context = getContext();

However, it does not explain why no value is displayed while in the webUI they are....

**Comment by MaximeLussier** [comment]
Actually, in the number picker it is correct. So if the split string is empty, it should get the value as is done when setting the index of the number picker "openHABWidget.getItem().getStateAsFloat()" or similar then converted to string. The same is true for the string selector (e.g The input for my Receiver)

**Comment by MaximeLussier** [comment]
Something along the lines of:
```
            case TYPE_SETPOINT:
                splitString = openHABWidget.getLabel().split("\\[|\\]");
                if (labelTextView != null && splitString.length > 0)
                    labelTextView.setText(splitString[0]);
                if (valueTextView != null) {
                    if (splitString.length > 1) {
                        // If value is not empty, show TextView
                        valueTextView.setVisibility(View.VISIBLE);
                        valueTextView.setText(splitString[1]);
                    }
+                   else {
+                       // If value is empty, use state in TextView
+                       valueTextView.setVisibility(View.VISIBLE);
+                       if (openHABWidget.getStep() % 1 == 0) {
+                           valueTextView.setText(Integer.toString(Math.round(openHABWidget.getItem().getStateAsFloat())));
+                       }
+                       else
+                       {
+                           valueTextView.setText(Float.toString(openHABWidget.getItem().getStateAsFloat()));
+                       }
+                   }
```

This way, there is no "%" displayed but at least a value is printed. I do not know the code enough to know if there is a way to get the required symbol (% in this case.)

**Comment by MaximeLussier** [comment]
For the TYPE_SELECTION line ~625, a textview named widgetvalue should be added to the view. Then if the value is between  "[ ]", You should use splitString[1] and match it with openHABWidget.mappings to display the currently selected value.
(or just not use split so the value will be printed in the labelTextView. Of course then no mapping would take place)

When the Spinner is started, you should also set the current value since it currently ends up being an empty last entry which is selected.

If you wish, I can open a separate issue (didn't do it yet since this is in the same neighbourhood)

**Comment by MaximeLussier** [comment]
Seems like I'm having a conversation by myself... It seems that the reason why my selector is not correct is that the item state does not match the mappings (e.g HDMI_2 vs HDMI2). This may be an issue with the addon for the Yamaha receiver.

**Comment by MaximeLussier** [comment]
If I use at line ~641:
```
                    if (openHABWidgetMapping.getCommand() != null && openHABWidget.getItem() != null) {
                        String strCommand = openHABWidgetMapping.getCommand().replaceAll("[^a-zA-Z0-9]+","");
                        String strState = openHABWidget.getItem().getState().replaceAll("[^a-zA-Z0-9]+","");

                        if (strCommand.equalsIgnoreCase(strState)) {
                            spinnerSelectedIndex = spinnerArray.size() - 1;
                        }
                    }
```
Instead of:
```
                    if (openHABWidgetMapping.getCommand() != null && openHABWidget.getItem() != null)
                        if (openHABWidgetMapping.getCommand().equals(openHABWidget.getItem().getState())) {
                            spinnerSelectedIndex = spinnerArray.size() - 1;
                        }
```
Then the "looser" matching (only alphanumerical characters) in a case insensitive manner, it works.
Of course this MAY be a workaroud due to the YamahaReceiver plugin. I will check the if the iOS app works properly.

**Comment by MaximeLussier** [comment]
@mueller-ma @maniac103 I did some investigating in the code, above are the results.

**Comment by maniac103** [comment]
@MaximeLussier I don't quite follow your various patch snippets, but in essence you've found my statement of views not being fully initialized after being recycled to be correct, right?

This whole adapter code needs a full rewrite, it's a complete mess right now.

**Comment by MaximeLussier** [comment]
@maniac103 Yes basically, the valueTextView is not set to invisible if the label does not contain the value between square brackets "[ ]". The first snippet was an else which did just that. That fixed the wrong value being displayed. The second snippet is using the state value to display the current value instead of nothing if the value is not present in the label. 

The third snippet is for the selection item to have "loose" matching so that it works properly for the input of my receiver. The mappings vs the states are "HDMI_X" vs "HDMIX". Keeping only alphanumerical characters and doing a caseless compare allows the match to be made. I will probably enter an issue for the addon to see if they can uniformize the  state and mappings.

It is up to you to see if the changes are acceptable enough to merge into the code.

**Comment by MaximeLussier** [comment]
@maniac103 While loose matching is still a good idea, the YamahaReceiver addon will fix the mismatch between state and mappings. Just FYI.

**Comment by maniac103** [comment]
@MaximeLussier I'm not quite sure loose matching really is a good idea in general. I think I prefer fixing the bindings instead ... and the Yamaha binding author seems to agree to that ;-)

Can you please give my PR #650 a try and see if it fixes the 'value is shown for wrong item' problem for you? (I expect it to fix it)

**Comment by MaximeLussier** [comment]
@maniac103 Yes, it does fix the issue
