### ISSUE TITLE
Include Play store description in this repo

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#627]
Currently there is https://github.com/openhab/openhab-android/blob/master/fastlane/metadata/android/en-US/full_description.txt. We should remove F-Droid related stuff, review the text, add links to crowdin and github and add a mail address for reporting issue for people who dont have Github.
Than we can add that file to crowdin and people can translate it.
@ThomDietrich

**Comment by ThomDietrich** [comment]
Sounds good. Additional thought: If you there is a way the text could consist of parts which can be translated individually. These would then be merged together through some templating language. This way you can predefine a certain style and e.g. make sure that all individual points are addressed by the translators.
