### ISSUE TITLE
Notifications only working with myopenhab/cloud connector

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#629]
Hi,

as we all know, push notifications are requireing the cloud connector to be set up.
When the internet link fails or some other problem exists (myopenhab down, connection pending...) there are no notifications pushed.

I'm thinking of implementing a multicast receiver being able to listen for local multicast notifications pushed by the local openhab instance. This way, no cloud would be required.

In the end, the infrastructure should be able to prevent duplicate messages. [Over at the eclipse smarthome forums](https://www.eclipse.org/forums/index.php/t/1070058/) there's a talk going on about a notification infrastructure. This resulted [in PR 459](https://github.com/eclipse/smarthome/pull/459).

What's your opinion on this?

Best,
Sascha

**Comment by FlorianSW** [comment]
So, in fact, the sending of notifications to the openHAB app should be pretty easy to be doable with any kind of backend, as long as it supports Google Cloud Messaging. The app "just" opens a specific api endpoint to get the GCM sender ID to register the device at GCM. It then registers itself within openHAB-cloud, so that it knows to which device ID it has to send a message. That's it. Once a message is provided to GCM with the correct device ID and the correct credentials (matching the sender ID with which the device registered earlier) it can receive push notifications.

This could also be done within a binding in openHAB, so tehnically, it's not necessary to have the openHAB-cloud, however, it's currently the only implementation. I'm not sure, what we can do here to fix that issue :/

**Comment by maniac103** [comment]
> I'm thinking of implementing a multicast receiver being able to listen for local multicast notifications pushed by the local openhab instance. This way, no cloud would be required.

I'm totally :+1: for the idea of receiving local OH notifications, but how is listening to multicast going to work when the app isn't running, which is a scenario that's not too unlikely? Or do you want to start a foreground listening service for that purpose?

**Comment by mueller-ma** [comment]
> supports Google Cloud Messaging

That would be a way, but openHAB leaks (through notifications) so much private information, that many people dont/might not want Google to be able to read them.


I dont know how GCM works, does some kind of message id exist?

**Comment by FlorianSW** [comment]
> I dont know how GCM works, does some kind of message id exist?

Yep, each message, which was accepted for deliver by GCM, does have a message ID, which is also send back in a result object to the calling application (openHAB-cloud, e.g.).

> That would be a way, but openHAB leaks (through notifications) so much private information, that many people dont/might not want Google to be able to read them.

That would require some service to be listening for messages on the device, I'm not sure, if there's anything we could use without needing to implement it from scratch.

**Comment by mueller-ma** [comment]
The messenger signal uses two ways for delivering messages:
1. If gcm is available on the device, the device receives the gcm wakeup and than downloads the message from the signal server. So the message itself is never seen by google.
2. If no gcm is available, the app starts a foreground service, that uses websockets to connect to the server and listen for messages.

**Comment by cribskip** [comment]
> The messenger signal uses two ways for delivering messages:
That seems like a resonable way. However, this requires also some extensive changes to the cloud connector/service.

In a first throw, I'd like to keep it simple and implement a service listening on the phone if it's in a local network (LAN, Wifi). Mitigating duplicate messages and such should be build afterwards.

I really like @FlorianSW proposal of a specific binding for using this service. This way, users may choose between 3 scenarios:

1. Only local notifications ("local" binding + service inside App)
2. Local & Remote thru GCM (myopenhab / cloud connector)
3. Local with "local" binding, remote with GCM

Refined with the signal-messenger idea, Google won't get any private data.

**Comment by FlyingEagle** [comment]
If I understood everything correctly, this thread should speak to me from the soul.
I can not understand why everything has to go to the cloud somehow.
The OH-App is already connected to my server (no matter if local or remote via port release) and * my * system. So why not alarm about it then?
The way GCM (only the message to the app "download new data") and then the app gets the data by itself via rest and Co. I find acceptable, but the OH-App is already connected to the event Bus, or am I wrong here? So why not pass on the notification via the event bus?
I do not want to use any other apps or services like Pushover, Pushbullet, Signal etc. I already have the OH-App from the OH universe.
Best regards

PS: If I'm past the topic, please delete the post.

**Comment by maniac103** [comment]
The app is only connected to your server as long as it's running in foreground (and the screen is on). As soon as that's no longer the case, the server connection is dropped. Keeping it running in the background would require keeping a foreground service running, which is entirely possible, but it's not how the app is working currently. Routing notifications via GCM has the advantage of being much more efficient in terms of data and battery usage.

**Comment by derSascha** [comment]
The _local_ broadcast idea seems to be very interesting. In some situations, it makes only sens to notify local devices (e.g. washing machine done). Has anyone experiences about udp broadcasts and android devices going into power save modes?

**Comment by BigRedBrent** [comment]
Seeing as how myopenhab.org is currently down, this post seems very relevant to me.

**Comment by cribskip** [comment]
I'm back on this and keep thinking of how to reliable transmit messages at home / locally. When User's phone switches from Wifi to Mobile, the device is not reachable. Maybe some type of queue on the server side could help - reconnect to Wifi: get "new" messages".

With GCM, there could be a "interrupt" which triggers the App to get the new messages.

Any ideas?

**Comment by mueller-ma** [comment]
I'm going to close this issue since it needs some server-side work before implemented in the client.
#1975 introduced notifications to the FCM-free client, but still requires openhab-cloud.

**Comment by FlyingEagle** [comment]
> but still requires openhab-cloud.

Then this Issue is not to close, the issue still exists ... or?

**Comment by TheTrueRandom** [comment]
@mueller-ma can we reopen the issue? There should be a solution to use notifications for openhab without using openhab cloud (e.g. by using VPN/proxy). 

A (temporary?) solution could be (at least until some server side changes are done) to copy the FCM token from the openhab android settings to the clipboard. With that at least notifications can be sent from rules/http-requests to the android app. 

A solution I would imagine is to enable FCM within some openhab config (maybe "addons.cfg") and providing the FCM token/password. 
If enabled, the app automatically sends the token to the openhab server. With that, broadcast notifications would work already, but additionally the device identifier could also be sent (as already configurable in the android app), which would enable device/user specific notifications.
