### ISSUE TITLE
Streaming usb web camera to habdroid

### ISSUE THREAD

**Issue by eluder87** [openhab/openhab-android#63]
Hi guys,
I am trying to stream my web camera to habdroid. I am using a usb web camera and using Yawcam to stream it live using mjpeg. Now i can view the webcamera in my internet browser with no issues at all but when i use habdroid to view the camera the camera comes up saying offline does anyone know what could be causing this issue?
here is my code.

Frame label="Multimedia Widgets" {
Webview url="http://192.168.1.121:8081/"  height=20
}

many thanks.
##

**Comment by belovictor** [comment]
What is that url? Is that a web page or a direct url of your mjpeg stream?

**Comment by belovictor** [comment]
@eluder87 , please respond, or I will have to close this issue.

**Comment by eluder87** [comment]
hi belovictor. Sorry about the slow reply i didn't see you respond the first time.
The URL  is the direct mjpeg stream.

**Comment by belovictor** [comment]
You should not use webview to watch it then. Instead you can use the Video widget in your sitemap pointing to this URL with MJPEG encoding configured as described in documentation:
https://github.com/openhab/openhab/wiki/Explanation-of-Sitemaps

**Comment by xsnrg** [comment]
As this is still open, and I am also having problems, will comment here.

I have two mjpeg camera streams at knowning working URLs.  Webview will display the stream, but Video will not.

non-working:
```
Video item=cam1 icon="video" url="http://user:pass@192.168.0.53/mjpg/video.mjpg" encoding="mjpeg"
```

working:
```
Webview item=cam1 icon="video" url="http://user:pass@192.168.0.53/mjpg/video.mjpg" height=480
```

As webview does other wonky things with format and is not necessarily for video streams, I would like to get Video working.

@belovictor any thoughts?

**Comment by lolodomo** [comment]
@eluder87 @xsnrg : I know your bug report is very old but I am very new in openHAB app dev. Could you please check what happens if you connect from the app to the OH server using HTTP rather than HTTPS. Does it help to render the video ?
