### ISSUE TITLE
Show timestamp of last refresh/state of item

### ISSUE THREAD

**Issue by siom79** [openhab/openhab-android#635]
In my setup OpenHAB is polling an HTTP resource (an ESP8266 that reports the state of a reed relay). When I look at the sitemap in the Android app, I would like to see the timestamp of the last refresh of the data as well as the timestamp of the last polling of the HTTP binding.

**Comment by mueller-ma** [comment]
You are talking about long polling between oh server and ESP8266? If yes, can you please open a thread in the forum? https://community.openhab.org

**Comment by siom79** [comment]
No, I am talking about the Android app. It should output for each item how
old the information is.

Imagine you are monitoring if a window is open or not. Currently I only see
"Window bathroom closed". But I don't know how old this information is.
What if the WiFi connection between the oh server an the device is broken?
Then the "closed" state could be outdated. Seeing instead "Window bathroom
closed (1 min)" I would know that it was closed one minute ago.

mueller-ma <notifications@github.com> schrieb am Fr., 12. Jan. 2018, 23:14:

**Comment by mueller-ma** [comment]
> What if the WiFi connection between the oh server an the device is broken?

Have you expirenced any network issues with the app? You should have a reload icon in the toolbar, when the app tries to reconnect.

Closing this in favor of #539. I dont think this feature would be very helpfull, when you can reload the page.

**Comment by siom79** [comment]
No, it is not about the reload between the app an the server, but about the
time the reed relay state was published to the server. When the HTTP
binding only gets updated every 5 minutes, I don't know in the app how old
the value is I see.

mueller-ma <notifications@github.com> schrieb am Fr., 12. Jan. 2018, 23:48:

**Comment by mueller-ma** [comment]
Ok, I also use this for one of my windows.
Items:
````
DateTime WINDOW_LAST_CHANGE
````

Rules:
````
rule "Time"
when
    Item WINDOW changed
then
    postUpdate(WINDOW_LAST_CHANGE, new DateTimeType())
end
````

I'm not sure if thats the best way, especially when you have more than one window. I remember that I have seen a scaleable solution for multiple windows with only one rule. Search in the forum or open a thread there.
