### ISSUE TITLE
Notifications fragment shows only up to 20 notifications

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab-android#644]
From what I see in the code the nofication fragment in the app shows only the first 20 notifications. This is probably enough for the latest notifications, however, if I want to see the history of messages or if I'm looking when a specific notification was sent, I've to navigate to the configured openHAB-cloud instance to see them.

It would be great, if the app would allow the user to show more than 20 notifications, e.g. by clicking "load more" or just by scrolling down.

**Comment by maniac103** [comment]
A prerequisite for this is the cloud connector actually obeying the limit and skip parameters: https://github.com/openhab/openhab-cloud/pull/174 (and that fix to be deployed in myopenhab)
