### ISSUE TITLE
Google Cloud Messaging connection state

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-android#649]
Hello,
the "About" section in my installation states that GCM registration was not successful. A user (but honestly also I) doesn't know what that means and if he has to do something, and what. Any ideas how to cope with that? Maybe we just need to enhance the error message.

**Comment by mueller-ma** [comment]
See #560

**Comment by ThomDietrich** [comment]
ups... I see, everything is under control 😃

**Comment by mueller-ma** [comment]
@ThomDietrich The string "GCM status" was changed to "Push notification status". It should be clear now, what it is does.

**Comment by ThomDietrich** [comment]
Nice ;)
