### ISSUE TITLE
Slider: Send state while holding

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#654]
I'm not sure if thats a good idea (because of the traffic), but I think its better, when the slider item is change, while the user is sliding.

**Comment by maniac103** [comment]
Traffic can be reduced by using a timeout: only send update if slider is not moved (but still held down) for e.g. 100ms.

**Comment by mueller-ma** [comment]
Code is done (https://github.com/mueller-ma/openhab.android/commit/a385626c3f60ad4153e5cea760e6af019667ccb8), but this causing tons of request, which is too much for e.g. the Tradfri binding. I'd close this feature request therefore.

**Comment by mueller-ma** [comment]
I added a timer, but a bit different: While sliding send updates not more frequently than every second.

https://github.com/openhab/openhab-android/compare/main...mueller-ma:openhab.android:654-slider
