### ISSUE TITLE
Mute ringtone is not mute

### ISSUE THREAD

**Issue by openschwall** [openhab/openhab-android#655]
Hi,
the mute ringtone ("Stumm" in German, I do not know the name used for it in the english version of the app) is not a silent tone but the standard ringtone of the phone. So I cannot mute the notifications. Quite annoying at night. :-(
This behavior has been confirmed by user sihui.
#

**Comment by mueller-ma** [comment]
In the ringtone list, the first one is "default ringtone" and the second one is "mute" (stumm)

**Comment by mueller-ma** [comment]
Can you try to switch to a different ringtone and check if that works?

**Comment by sihui62** [comment]
> and check if that works?

That works without any issues. Just the muting does not work: muting does switch to the standard phone ringtone.

**Comment by mueller-ma** [comment]
https://github.com/openhab/openhab-android/releases/tag/2.0.13-beta contains the fix, binaries show up in a few minutes.
