### ISSUE TITLE
sugestion: Send or show remote server status info/alert inside the app

### ISSUE THREAD

**Issue by dakipro** [openhab/openhab-android#656]
Hi,
Just had a thought related to recent maintenance announcement https://community.openhab.org/t/myopenhab-maintenance-today-3pm-pt/38988/2
maybe this could be shown inside the app itself somewhere somehow? 
I think it would improve reliability of the service, in a way that users would understand why is application offline or has some instability. I am not sure how often server (myopenhab f.eks.) is not reachable and if it is a simple thing to implement, I guess both the app and server need a dedicated communication channel of some sort. Or perhaps some basic public api, that could be checked from the app about the health status of the server or something, I think I've seen such report somewhere already. 
So if remote server is not responding, app could check some health-check api for confirmation (I guess this would have to be a variable field, expecting some predefined answer with a status, maybe even with a message about scheduled maintenance). 
I guess a push notification could be used, but it would be "spamming" people not using the app at the moment
For me app has been working all the time (thought I do not use my phone that often), so not sure how useful this would actually be vs. time needed to be implemented.

Happy coding! :)

**Comment by FlorianSW** [comment]
Hmm, having a dedicated "health" route would also be unavailable if the "main" app is offline, if it would be implemnted inside of openhab-cloud, wouldn't it? And what information would the health page contain, that could be helpful for the user in such a downtime?

However, I kind of like the idea of having the possibility to send "global" notifications from openhab-cloud (maybe only from the command line) to send a short message to all registered devices. In that way, a maintainer, who plans a downtime, or is working on the downtime, could at least send a notification to all registered devices. This, like you said already, could probably be a bit spammy for all users, who currently do not care, however, it would already be an improvement, wouldn't it?

**Comment by mueller-ma** [comment]
> Hmm, having a dedicated "health" route would also be unavailable if the "main" app is offline, if it would be implemnted inside of openhab-cloud, wouldn't it?

IIRC owncloud (and propably nextcloud) has a so called maintenance mode, where only the start page is available with a notice about the maintenance and in "oc/status.php" a json string signals that the mode is enabled. All clients check for that json object.
I haven't checked, but I think this maintenance page is always shown during the update.

Also see http://status.openhab.org/ but requiers external sources and therefore lowers privacy.

**Comment by dakipro** [comment]
It would be great if openhab-cloud could do some sort of self-check and report on some channel that there is f.eks. instability (usually if some process is taking longer then usually) or it is in maintenance mode  (triggered manually, or by update), or if it is down completely (some connections missing etc). 

http://status.openhab.org/ is what I was having in mind initially, as an independent service that monitors the health. There are also bunch of 3rd party software that monitor services like https://www.uptrends.com/tools/uptime or https://uptimerobot.com/ , but personally I do not think they would suit openhab/opensource.

Reusing status.openhab.org might be easier to start with, but I doubt that it can show "maintenance mode" or some manual value, can it? 

If it could, that would indicate the end user that "we put it down, come back in few minutes", rather then "Ah... just when I need to use myopenhab, it is not stable again".
MyOpenhab is otherwise very stable (for me at least), and the forum gives info about planned down periods, but I personally switched from domoticz to openhab (among other things) mostly due to lack of information and being "kept in the dark" about how and why things behave in such way, services are down etc. 

I believe that stability is very important aspect of home automation, and "simple" things like informing the user about the stability status greatly improves reliability and trust in the service.
