### ISSUE TITLE
Ringtone selector not themed

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#658]
Since this is a system dialog, I'm not sure if we can theme it.

Lineageos 14.1

**Comment by FlorianSW** [comment]
It seems, from a quick look, that this is a built-in preference, which can not be touched in any way by us. We could probably re-implement it's funtionality (it's a list of media files), however, the action of RingtonePreference could be finished by any other app/file manager, too, so I don't think we should do something like that. In my opinion, having this unthemed component there is the better solution? :)

**Comment by mueller-ma** [comment]
That's also what I tought, I just wanted to hear someones opinion on that.
