### ISSUE TITLE
Changing tablet orientation: fragment duplication

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#659]
Testing my SSE code, I discovered a big and annoying bug.
First I start the app. I can see, as expected, 1 onResume for OpenHABWidgetListFragment which finally leads to 1 async long polling HTTP call for the updates.
Then I change the orientation of my tablet, I can now see 2 onResume for OpenHABWidgetListFragment (same page) which finally lead to 2 async long polling HTTP call for the updates.
Then I change the orientation again, I can now see 3 onResume for OpenHABWidgetListFragment (same page) which finally lead to 3 async long polling HTTP call for the updates.
And so on.

It looks like fragments are not really cleared.

I have not yet found the solution but I can see that in one side onResume on the activity is updating the list of fragments using the state fragment and trigger a refresh. This refresh of the data source is triggering the call of onResume for each fragment which  loads the page and initialize the async long polling call.
I can see in parallel that each fragment is going through all its lifecycle: onAttach onCreate onCreateView onViewCreated onActivityCreated and finally onResume which again loads the page and initialize the async long polling call.

It looks like the state fragment is ok as I have the right number of fragments.
But apparently, onResume is still run for normally suppressed fragments.

**Comment by lolodomo** [comment]
When you change rotation, the main activity is destroyed and then created again. onCreate is called with a non null savedInstanceState.
When your tablet goes in sleep mode and then exits the sleep mode, the behaviour is different: onDestroy/onCreate are not called but only onResume is called.

If I replace in the method `protected void onCreate(Bundle savedInstanceState)` the call `super.onCreate(savedInstanceState);` by `super.onCreate(null);` the problem is fixed. I just don't know if this is the proper way to fix the problem.

**Comment by lolodomo** [comment]
This change is not satisfying as the change of orientation implies a return to the home page.

**Comment by maniac103** [comment]
Indeed, the saved instance state must not be discarded. It leads to the previously existing fragments being discarded (which probably is intended here, but still a hack), but also dumps any other activity state. Instead, whatever is adding the fragment duplicates needs to be fixed to only add new fragments when needed.
