### ISSUE TITLE
Check if device runs in data saver mode

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#660]
Data saver restricts background data. I haven't checked if apps know if data saver is on, but if that's the case, we could use this information to reduce data. Some ideas:
1. Hide images, videos, webviews, etc until the user taps on their placeholder
2. No auto refresh
3. Show default icon (e.g. temperature) if no icon for a specific state (e.g. temperature-40) is cached

**Comment by JohannesPtaszyk** [comment]
We should probably not do this without user interaction, because it could appear weird to the user. Changing the expected behavior is usually not a good option.
How about the idea of adding an option to the settings?
So the user can decide from something like this:
* always save data
* don't save data
* detect system datasaving (if we are able to get this)

**Comment by mueller-ma** [comment]
IMO it should be possible to restrict heavy data usage to wifi (click to show image items, no autorefresh of images and charts, no dynamic icons) and enable this setting if the device is on data saver mode.
If the user enables the system-wide data saver mode, he wants to save data without any additional interaction.

**Comment by JohannesPtaszyk** [comment]
Then we probably still should have some kind of opt-out option in the settings or should maybe give the user something like a footer/snackbar or different style of information, that we run in data saving mode, shouldn't we? 
But I mean, I could also start working on this and if we decide to give the user an option to opt-out or have some information for the user, we could create a follow up ticket.

**Comment by JohannesPtaszyk** [comment]
So, after some research I found out that there are multiple states for the datasaving option:
* Disabled
* Enabled
* Whitelisted
How should we handel the whitelist case? Just load the data? Or would you rather like to have the same behavior as when data saving is enabled? Or is there an other suggestion?
