### ISSUE TITLE
Notification time should be event time

### ISSUE THREAD

**Issue by redeye86** [openhab/openhab-android#663]
Currently, the time that is shown in the notifications is the time when the notification was received by the device not the actual event time.

How to reproduce:
Set device to flight mode, send notification, wait a minute, go back online.

It should be be enough to add a `.setWhen(time_in_millis)` in GcmIntentService. Event time should be part of the message already.

**Comment by maniac103** [comment]
@mueller-ma Can be closed as #685 is merged.

**Comment by mueller-ma** [comment]
I want to close this, when the server sends a timestamp and this timestamp is used in the app.

**Comment by maniac103** [comment]
Opened a PR for the missing properties against openhab-cloud: https://github.com/openhab/openhab-cloud/pull/175

**Comment by mueller-ma** [comment]
Great. Those two issues should be easily fixed, when you oh cloud fix is merged: #335 (sevirity) and #345 (notification channels on android 26+)

**Comment by maniac103** [comment]
I already have a patch locally for notification channels.

**Comment by mueller-ma** [comment]
Do you need this patch or just for testing? I've read that messages without channels will be displayed if target api is 25 or lower.

**Comment by maniac103** [comment]
It's not strictly needed, right, but the approach for it in #335 is a good idea.

**Comment by mueller-ma** [comment]
openhab-cloud sends the timestamp and the app will display it.
