### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#675]
> That may be true, but it's hard to follow code style if large parts of the existing code base don't follow it.
I can update my changes to fully conform, but I wonder whether it wouldn't be a better idea to turn off Stickler for now, merge the large, invasive PRs and afterwards do a cleanup of the code base first: fix whitespace, name variables consistently, remove unused code etc. ... then enable Stickler again afterwards. I volunteer to help with the cleanup, we just need to coordinate when to do it as PR rebase will become painful afterwards.

From https://github.com/openhab/openhab-android/pull/669#issuecomment-360900728

We should wait for

- [ ] #556 
- [x] #562 
- [x] #638 
- [x] #640 
- [x] #650 
- [x] #688

**Comment by mueller-ma** [comment]
I disabled stickler-ci for now until this is fixed.

**Comment by mueller-ma** [comment]
Also https://github.com/openhab/openhab-android/pull/688/files/4ba0627a3424d52a7677885f5f8b741e4a09c9dd#diff-07e4a6e281af02db331ff3f81d9f86d8

**Comment by mueller-ma** [comment]
@maniac103 Do you think it's time to enable Stickler?

I was thinking about Codecov: It's nice to see how much coverage the code has, but does anyone really use it? I don't and if you don't use it, I'm going to remove Codecov.

**Comment by maniac103** [comment]
I have a few general cleanup patches pending, will submit them tomorrow. After that I think enabling Stickler is fine. Is there a way to run it manually to make sure the current state of code matches its requirements?
About Codecov, I don't need/use it either.

**Comment by mueller-ma** [comment]
You can install checkstyle locally and run it with the config stickler/checkstyle.xml
