### ISSUE TITLE
Remove usage of ViewPager for Widgetlist fragments

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab-android#677]
In #640 @maniac103 suggested:

> Actually the ViewPager is used: for paging the fragments in multi-pane layout. Having two containers to insert the respective fragments into would likely be a much cleaner solution, though.

**Comment by mueller-ma** [comment]
Please wait for #675

**Comment by maniac103** [comment]
Too late: https://github.com/maniac103/openhab.android/tree/cleanup-fragment-management ;-)

(based on #650)

**Comment by maniac103** [comment]
Notification fragment is fine now; just need someone to test going to sitemap item via NFC
