### ISSUE TITLE
Value colors are not changed

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#690]
Following sitemap:
````
Text item=foo valuecolor=[OFF="red", ON="default"]
````

when chaning from OFF to ON, the text is still red. After reopening that subpage, the text has the default color again.

**Comment by mueller-ma** [comment]
Ok, I dont know where I saw "default", but its not in the docs, so I removed it:
````
Text item=foo valuecolor=[OFF="red"]
````

However the bug still applies.

**Comment by maniac103** [comment]
Is this before or after #650, or both?

**Comment by mueller-ma** [comment]
Tested with f6129946c3320fa1bee7d5c59094602e5f779d21, so after #650, but I haven't tested it before.

**Comment by lolodomo** [comment]
I would be very surprised if this is an old bug. I think it us something that I already tested in the past and was working.
I can check soon.

**Comment by lolodomo** [comment]
Confirmed, dynamic change to the default color is working well with the version in the play store.

**Comment by maniac103** [comment]
Hmm, strange. What I'd expect to happen is:
- changing value triggers data reload via long polling
- new widgets sent to adapter
- notifyDataSetChanged() triggers a rebind of the view holder
- https://github.com/openhab/openhab-android/blob/b819cb0d50e7c91e3ab99d2d3fc1c528ea5f4c88/mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java#L473 triggers the color update
