### ISSUE TITLE
Charts not correctly rendered when using the remote connection

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#694]
When using the remote connectrion, the charts are not rendered correctly, sometimes we only get an empty chart with the default white theme, sometimes the correct rendering.

There is not such a problem when using the local wifi connection. In this case, rendering is always good.

I am not sure if the problem is in the Android app or in myopenhab.

Lots of users have noticed that problem and you have several topics on the forum about this problem. Few users are even mentioning that all images are concerned, that is images, icons and charts.

**Comment by mueller-ma** [comment]
Did you have this issue before the myopenhab update?

**Comment by lolodomo** [comment]
Which update ? myopenhab has been updated recently ?

**Comment by MikeJMajor** [comment]
For me the issue occurred after the myopenHAB update.

**Comment by mueller-ma** [comment]
@lolodomo I'm not sure when it was and I didnt find a forum post, but it was about a month ago. Can you open an issue in openhab-cloud?

**Comment by kaikreuzer** [comment]
I am seeing the same problem, but the same happens on iOS, so it definitely is no bug in the Android app. I already asked @digitaldan to look into this.

**Comment by rmahnovetsky** [comment]
is there another issue created for this? can it be linked here or to the original forum post for tracking. https://community.openhab.org/t/charts-displaying-on-local-url-but-not-remote/39490/6

thanks :)

**Comment by kaikreuzer** [comment]
I hoped that @digitaldan would quickly find the issue and fix it, but as it seems to take much longer, I have created https://github.com/openhab/openhab-cloud/issues/163 for further tracking.
