### ISSUE TITLE
Charts have always the default theme

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#696]
### Actual behaviour
Charts have always the default theme

### Expected behaviour
Charts should be themed correctly

 
### Steps to reproduce
1. Look at a chart

### Can you reproduce the issue in demo mode?

Yes, under "Outside Temperature"

#### Client
* Android version: Android 7.1.2
* Device model: Oneplus X
* Stock or customized ROM: Lineageos 14.1
* App version : 2.0.9-beta
* Installation source : Github
* Device language: DE

#### App log
```
02-04 12:27:14.214 3142-3191/org.openhab.habdroid I/MyWebImage: fetched bitmap for http://demo.openhab.org:8080/chart?groups=Weather_Chart&period=h&random=476660647&dpi=384&theme=Allows the app to add, remove, change events that you can modify on your phone, including those of friends or co-workers. This may allow the app to send messages that appear to come from calendar owners, or modify events without the owners' knowledge.&w=1080&h=540
02-04 12:27:14.234 3142-3153/org.openhab.habdroid I/art: Background sticky concurrent mark sweep GC freed 2241(172KB) AllocSpace objects, 8(4MB) LOS objects, 19% free, 17MB/22MB, paused 5.961ms total 63.680ms
```

Pretty strange chart theme.

**Comment by maniac103** [comment]
Oops, looks like theme attribute resolution is off. I'll have a look into it.
