### ISSUE TITLE
When GCM failed, inform user

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#720]
Right now, when GCM registration fails, it's not transparent to the user. Only way to know is it send a message and wondering that none is received or in the About screen.

Maybe a warning badge on Notifications from the hamburger menu should be displayed.
My proposal would be:
- When GCM fails, add a warning badge to the hamburger menu and Notifications area
- When user opens Notifications, display a warning banner about GCM error (just like in the about screen)

What are your opinions?

**Comment by mueller-ma** [comment]
You're right, the current situation is not pretty good
What we should do to change that:

- Change "GCM Status" to something like "Notifications activated" (#709)
- Add information why gcm registration failed (#560)
- Your suggestion or some toast/snackbar as soon registration failed

**Comment by mueller-ma** [comment]
A warning next to the drawer entry could be shown. I haven't seen an api for the androidx drawer, so we'd have to migrate to a third-party drawer, like https://github.com/mikepenz/MaterialDrawer
@maniac103 WDYT?

**Comment by maniac103** [comment]
Personally I don't see the necessity for including such a large third party library just for this. Why not simply show a (error/red?) toast or SnackBar when registration fails?

**Comment by mueller-ma** [comment]
Ok, a toast is probably enough, see #1501.
