### ISSUE TITLE
Enable user to scan settings with QR code

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#721]
As discussed in #708, we should enable the user to scan settings by QR code - speeding up setup and reducing errors.

This should be enabled in https://github.com/openhab/openhab-cloud and https://github.com/openhab/openhab.ios to keep a consistent UX.

Suggested Workflow:
1. User registers with openhab-cloud
2. Creates his/her users
3. QR code is shown, openhab-apps offers scan
4. Code is scanned, Data is parsed and saved in settings

**Comment by JohannesPtaszyk** [comment]
What excactly is meant by data? 
Server, Username and Password?
I would like to implement that feature, but I am not really into web programming, so it would be nice to have someone who would help me with the webend.

**Comment by mueller-ma** [comment]
I'm going to close this issue since it needs some server-side work before implemented in the client.
