### ISSUE TITLE
Some svg look pixelated

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#728]
### Actual behaviour
![screenshot_20180223-174050](https://user-images.githubusercontent.com/22525368/36903802-0902adc4-1e2f-11e8-9b2e-3b72c20f5107.png)

### Expected behaviour
Person icon shouldn't be so pixelated, because it's SVG.

 
### Steps to reproduce
1. Use this icon:
````xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" baseProfile="full" width="24" height="24" viewBox="0 0 24.00 24.00" enable-background="new 0 0 24.00 24.00" xml:space="preserve">
	<path fill="#E7B48F" fill-opacity="1" stroke-width="0.2" stroke-linejoin="round" d="M 12,2C 13.1046,2 14,2.89543 14,4C 14,5.10457 13.1046,6 12,6C 10.8954,6 10,5.10457 10,4C 10,2.89543 10.8954,2 12,2 Z M 10.5,7.00001L 13.5,7.00001C 14.6046,7.00001 15.5,7.89544 15.5,9.00001L 15.5,14.5L 14,14.5L 14,22L 10,22L 10,14.5L 8.5,14.5L 8.5,9.00001C 8.5,7.89544 9.39543,7.00001 10.5,7.00001 Z "/>
</svg>
````
Source: https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/human-male.svg

2. Set icon format to svg.

### Can you reproduce the issue in demo mode?
No.

#### Client
* Android version: Android 7.1.2
* Device model: Oneplus X
* Stock or customized ROM: LineageOS 14.1
* App version : 2.0.15-beta
* Installation source : Github
* Device language: DE

#### Server
Client issue...

**Comment by maniac103** [comment]
Should probably scale the 24px size given in the SVG with the device's display density. This is how I solved it in the past: https://github.com/slapperwan/gh4a/blob/master/app/src/main/java/com/gh4a/utils/HttpImageGetter.java#L559
