### ISSUE TITLE
Add icons to settings menu

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#731]
Like in the android settings: https://cdn57.androidauthority.net/wp-content/uploads/2016/03/settings-revamp.jpg

**Comment by maniac103** [comment]
That idea seems pretty unusual for a preference list. It's usually only done for settings headers.

**Comment by mueller-ma** [comment]
I started working on this. WDYT?
![1 1](https://user-images.githubusercontent.com/22525368/42292198-2461c826-7fd1-11e8-9ee9-e43e6b2c8e0c.png)
![1 2](https://user-images.githubusercontent.com/22525368/42292199-2482b324-7fd1-11e8-8835-bd5012936c53.png)
