### ISSUE TITLE
Multiline text item values are shifted to the left and label disappears

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-android#756]
![screenshot_2018-03-08-11-30-35](https://user-images.githubusercontent.com/21967853/37163071-d952c948-22c4-11e8-9a56-eb4fe926af4b.png)

In landscape, everything looks better and the label reappears, but it's truncated (could these wrap?)...
![screenshot_2018-03-08-11-42-23](https://user-images.githubusercontent.com/21967853/37163541-109a410a-22c6-11e8-9b63-82419a5747da.png)

#### Client
* Android version: 5.1.1
* Device model: Alcatel Fierce XL
* Stock or customized ROM: stock
* App version : 2.0.19 beta
* Build flavor : apk (full)
* Device language: English

#### Server
* Server version: 2.3.0 snapshot 1224

**Comment by mueller-ma** [comment]
Does it work in basic ui?

**Comment by openhab-5iver** [comment]
BasicUI...
![image](https://user-images.githubusercontent.com/21967853/37233482-61180a9e-23c1-11e8-9334-e4129f64a511.png)

ClassicUI...
![image](https://user-images.githubusercontent.com/21967853/37233507-7c53ac96-23c1-11e8-8fda-145c408198f4.png)

It looks like they are both putting in a label, but it's getting overly truncated, and as expected, single-line.

**Comment by mueller-ma** [comment]
I guess multi line text items are not supported. Can you open an issue in eclipse/smarthome and request multi line support for text items? 
If they don't want to support it, we don't do it in the app as well.

**Comment by maniac103** [comment]
#540 ?

**Comment by mueller-ma** [comment]
Totally forgot about #540...

**Comment by mueller-ma** [comment]
I want to truncate it like the basic ui, but the text is now moved to the left:
![screenshot_2018-03-10-11-43-36](https://user-images.githubusercontent.com/22525368/37241411-cdaa63b8-2458-11e8-963c-32d8583e1f6e.png)
Before:
![screenshot_2018-03-10-11-45-29](https://user-images.githubusercontent.com/22525368/37241412-cdc617f2-2458-11e8-95f9-4bf510558f3a.png)

**Comment by openhab-5iver** [comment]
Personally, I much prefer the multiline. It just looks odd shifted to the left. I'd rather live with that than lose the display of multiline!

**Comment by maniac103** [comment]
Dupe of #676?

**Comment by openhab-5iver** [comment]
I believe you are correct. However, it is much better in the latest beta. But there's 1.5 characters being cut off on the right and no label displayed...

![Screenshot_2019-06-18-07-22-10](https://user-images.githubusercontent.com/21967853/59678344-2b5cbd80-919a-11e9-8693-c32f0c49ce85.png)
