### ISSUE TITLE
Sliders not displaying stateformat

### ISSUE THREAD

**Issue by kvolden** [openhab/openhab-android#767]
I have Dimmer items with the label "Lights [%d %%]", and Slider elements in my sitemap linking to these items. The stateformat is rendered correctly in Basic UI, showing the percentage of the dimmer, but ignored in the Android app which only show the name "Lights" and the slider widget.

**Comment by maniac103** [comment]
@mueller-ma I wonder whether we shouldn't handle labels + values in the base ViewHolder class. I noticed this kind of inconsistent handling of states during #650 already.

**Comment by kvolden** [comment]
I have also noticed that when the app does show the status, it is shown aligned next to the label in square brackets, while Basic UI shows it aligned with the control without square brackets. This is not directly related (and perhaps you prefer it like this, though I personally prefer the Basic UI way), but maybe this is something to consider when you're doing whatever change is necessary for fixing this bug.

**Comment by mueller-ma** [comment]
@maniac103 We also have to check if there are more elements with missing value

**Comment by maniac103** [comment]
Yeah, that's why I suggested to introduce common handling ;-)
