### ISSUE TITLE
support Flic

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-android#77]
I just found this very interessting Indigogo Project.
http://igg.me/at/flic/x/9988727
It basiclly just a button connected via bluetooh with your smartphone.

It would be great if HABdroid would support this out of the box.

Without HABdroid I would create some tasker actions like:
"click -> send item=ON via HTML"
"double click -> send item=ON via HTML"

But since HABdroid know the current status of each item you could toogle a switch.
"click -> change item from ON to OFF or vice versa"

Realizing this with tasker would result in a delay of some seconds, because you would need to get the current status of the item via REST first.

You can request a developer kit on the website.
##

**Comment by kaikreuzer** [comment]
I have backed the project myself and expect to receive my flics soon.
So I would be definitely interested as well in this support - not just HABDroid, but iOS could have the same.

Regards,
Kai

**Comment by hlat** [comment]
+1 --> backed the project too

**Comment by cribskip** [comment]
+1 and backed too, great as garage and/or house door opener in the car. 

With URI support, this may be an easy task. See #78

**Comment by cribskip** [comment]
Did someone contact flic support yet as offered in the FAQ:

 I want Flic to work with my app, what do I do?

Contact us at support@shortcutlabs.com

**Comment by belovictor** [comment]
Ok, I backed it too :-) But I bet I will start any work on that only when I get one :-)

**Comment by belovictor** [comment]
I wrote a letter to them, let's see how it works out!

**Comment by tlanfer** [comment]
Just FYI: I got a mail update a few minutes ago, looks like they published the development resources at https://developers.flic.io/
Here is an example for android: https://github.com/50ButtonsEach/android-boilerplate/blob/master/app/src/main/java/io/flic/demo/app/ui/MainActivity.java
Looks reasonably simple.

**Comment by cribskip** [comment]
Mine arrived yesterday. Works great but not as standalone as I thought - you need to register and the button settings are uploaded to flic's cloud. 

Anyway, there's a URL action available. Using this with the openhab:// scheme works great.

Of course would a better integration with openhab be nice.

**Comment by kaikreuzer** [comment]
The button needs to be registered in the cloud? What kind of crap is that...?

**Comment by hlat** [comment]
Via the phone? Hoped there is a chance to connect the flics via my raspberry with a Bluetooth Stick to openhab....

Von meinem iPhone gesendet

**Comment by hlat** [comment]
Got Mine right now - any ideas what to do with them?

**Comment by cribskip** [comment]
I had been a bit disappointed because Android URI-Handlers are not supported. By now, I see only one possibility to link Flic to openhab: Use IFFT as Gateway :(

**Comment by kaikreuzer** [comment]
And I am disappointed because I still haven't received mine...

**Comment by CWempe** [comment]
fyi: https://github.com/openhab/openhab/wiki/Flic-via-Tasker

**Comment by tlanfer** [comment]
Another update: https://github.com/50ButtonsEach/fliclib-linux-dist
As far as i can see it, it contains a seperate daemon which deals with the flics, and a couple of libraries in several languages to deal with either the deamon, or directly with flics.

**Comment by mueller-ma** [comment]
There's a tasker plugin now, so people can set up tasker to connect flic and openHAB.

**Comment by CWempe** [comment]
> There's a tasker plugin now, so people can set up tasker to connect flic and openHAB.

I think using the Tasker plugin is only a workaround.
The buttons should work, even when my phone is not active or at home.
Like for my family when I am at work.

Another approach/workaround might be using a gateway like <https://github.com/denwilliams/node-flic-mqtt>.

Just my 2 cents. I don't care about Flic anymore. 😄

**Comment by rkoshak** [comment]
> I think using the Tasker plugin is only a workaround.
The buttons should work, even when my phone is not active or at home.

Then the issue belongs in the openhab-addons repo and the request is to add a binding (or add to an existing binding, is the BT binding approved yet?) support for Flic. Adding support to the Android app will never support working when your phone isn't at home since Flic uses BT to communicate.
