### ISSUE TITLE
Dynamic Icons for switch-items not updated anymore

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab-android#781]
Dynamic icons for switch-items are not updated anymore (local & remote).

I went back a few versions to see the history:

2.0.27-Beta --> OK
2.0.30-Beta --> Not OK
2.0.31-Beta --> Not OK
2.0.32-Beta --> Not OK

Tested on Android 8 as well on an older Samsung-Tablet with same result:

![image](https://user-images.githubusercontent.com/20517474/37304907-3631311a-2633-11e8-9a0e-be4f8dc26574.png)

![image](https://user-images.githubusercontent.com/20517474/37304940-4a2ea300-2633-11e8-8c88-c7889a5b73d1.png)

I see this even if I just use the app in demo-mode

openHAB: Latest 2.3-snapshot

**Comment by maniac103** [comment]
Timing (thanks for the test!) suggests this regressed with #762.

I guess this is OH2? How does the respective sitemap item look like?

**Comment by michaeljoos72** [comment]
Yes --> OH 2.3

Item:
Switch myStrom8_SW "Luftbefeuchter" <switch>

Sitemap:
Switch item=myStrom8_SW

**Comment by maniac103** [comment]
Oh, I just saw it's also reproducible in demo mode...missed that before :-/
I'll have a look into it.

**Comment by mueller-ma** [comment]
@michaeljoos72 thanks for your testing and @maniac103 thanks for fixing it.

**Comment by michaeljoos72** [comment]
Working now. Thanks!
