### ISSUE TITLE
Adjust font size

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#795]
> I would love to see a zoom button. So I could set the size of the font and other things to my own wishes. Not everyone has big fingers like a sausage :wink:
> 
> I have a smartphone with 5.9" screen with resolution better than full HD, so I would love to make all a little bit smaller to get more information on a screen without much scrolling.
> 
> Only way to get this is to change Android dpi, but you need root for that…

From https://community.openhab.org/t/android-app-beta/41382/44?u=mueller-ma

**Comment by maniac103** [comment]
In fact, changing dpi (either by using the native controls for it in Nougat or hoping for the manufacturer to do it properly) is the right solution for this. I've yet to see a single app that allows manipulating its screen layouts to emulate different screen densities at runtime.

**Comment by mueller-ma** [comment]
When the font is too large in oh, it is too large in other apps as well. Android (or at least lineageos) has the ability to change the font and the layout size systemwide. I dont know which vendor roms have those two options. FireOS has at least the font size option.

**Comment by maniac103** [comment]
At least Google devices should have it. Font size is a thing since almost forever, layout size adjustment is mapped to the UI since Nougat (was only available via adb shell before).

**Comment by maniac103** [comment]
The problem with font size adjustments like these is that with those it's easy to break layout expectations (set large font size -> broken layout), and it may not be easy to adjust all layouts for that.
When setting the dpi globally (like mentioned above), layouts stay intact because the whole UI becomes smaller/larger, the size of the UI elements relative to each other stays the same.

**Comment by kojid0** [comment]
Any update on this issue? I have multipe devices with different system-wide font sizes and on the bigger ones, text gets cut

**Comment by mueller-ma** [comment]
There are no updates on this, but with the material design 3 rework of the sitemaps, there's more space for text now.

**Comment by mueller-ma** [comment]
The font size can be changed system-wide. If the font in openHAB is too small, it's also too small in other apps.
