### ISSUE TITLE
I need a sample of product list and detail by using Recyclerview with API in android. Please give me some example because I just new on android. Thank for your help.

### ISSUE THREAD

**Issue by Rrithysam** [openhab/openhab-android#796]
### Actual behaviour
Describe us what happens

### Expected behaviour
Describe us what should happen

 
### Steps to reproduce
1. Describe us how to reproduce the issue
2. Use a list for it

#### Client
* Android version: 
* Device model: 
* Stock or customized ROM: 
* App version : 
* Build flavor : 
* Device language: 

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: 
* Authentication method : 

#### App log
```
Insert your log here
```

#### openHAB Server log
```
Insert your log here
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here
```
```
Insert your reverse proxy access log here
```

**Comment by mueller-ma** [comment]
Hey @Rrithysam,
this is the issue tracker for openhab-android, not a general Android forum. There are a lot of forums for your post out there.
