### ISSUE TITLE
How to setup the android client to my local demo server?

### ISSUE THREAD

**Issue by cyberrob** [openhab/openhab-android#8]
In the setting I got openHAB URL & openHAB Remote URL, which one should I put the "http://xxx:8080/openhab.app?sitemap=demo" in? What's different between these two?
##

**Comment by MahdiELARBI** [comment]
i face the same problem and it dosent work. Any ideas please ?

**Comment by arcanon** [comment]
also seeing this problem :( where could we find debug info as to what is going wrong? Does my openhab instance need authentication setup for it to work?

**Comment by arcanon** [comment]
lol, stumbled onto a solution instead of http://x.x.x.x:8080 i used the actual name of the pi running the instance, so for me http://raspberrypi3.local:8080

**Comment by MarcSN311** [comment]
I'm trying to connect to my OpenHab instance, but neither the ip nor the Hostname works. Both work in the browser though.

**Comment by dextergiii** [comment]
I'm having challenges as well. The app will connect to the site and I can see "things" but when I select the sitemap I have configured the progress circle at the top continuously spins.

**Comment by mueller-ma** [comment]
I think the best way to solve this is a intro with three buttons:
1. Demo mode
2. Auto configure and add found instance to 
3. Manuall configure

**Comment by kaikreuzer** [comment]
I'd think that there wouldn't be much of an issue anymore once https://github.com/openhab/openhab.android/issues/179 has been implemented.

**Comment by mueller-ma** [comment]
I think #337 will fix this
