### ISSUE TITLE
Refresh/Reload of Icons

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab-android#804]
Hi

In my opinion the App should not refresh the icon each time the value has changed.
Especially for items with a low refresh reate (e.g. 5s) it's not very nice. Maybe it's possible to refresh after an App-Install (Setup) and "Clear Icon Cache"?

openHAB latest Snapshot
2.0.41-beta

Thanks
Michael

**Comment by mueller-ma** [comment]
Can you specify what you don't like about this feature?
The flicker on reload is a known issue (See #684).

**Comment by michaeljoos72** [comment]
Yes, I mean the flicker...Thanks for clarification!
