### ISSUE TITLE
MemorizingTrustManager doesn't show up anymore

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#809]
Since  #275 the user isn't asked anymore if he wants to trust _one_ certificate, if the app connects to server with an invalid certificate.
Once this is fixed, both "Ignore ... during ssl handshake" options should be removed, as they are a security risk, see #314

**Comment by maniac103** [comment]
When restoring this, the 'once' option should be killed though. With the amount of HTTP requests we're doing, accepting 'once' seems totally pointless.

**Comment by maniac103** [comment]
I've restored MTM in #819, but noticed our usage of it is broken in any case: We're using a years-old copy of its source, hacked it up and introduced issues by those changes; in particular we're leaking the activity instance after killing it due to the MemorizingTrustManager.setResponder() call which keeps the responder (= activity) in a static instance.

We probably should rewrite the parts of it we're actually using into a separate class in our own code at some point.

**Comment by mueller-ma** [comment]
MTM as gradle dependency would be a lot smarter, but I'm not sure if it's possible. The MTM Readme shows the integration via git submodule.

**Comment by maniac103** [comment]
> MTM as gradle dependency would be a lot smarter, but I'm not sure if it's possible.

It's not, as its developer would need to upload it to Maven (or similar) in order for that to work, which he seemingly doesn't do. Taking its source verbatim is problematic for us in any case anyway, as we'd need to adapt its dialog to our themes: https://github.com/maniac103/openhab.android/commit/4b70a508f6fda89af8bf02db68025eae2d53fa15 (after updating to upstream: https://github.com/maniac103/openhab.android/commit/6081879d09ec80c3e04b48c427fbbed17d661d3d)

**Comment by mueller-ma** [comment]
> It's not, as its developer would need to upload it to Maven (or similar) in order for that to work, which he seemingly doesn't do. 

Just FYI https://jitpack.io/ allows using every github repo as gradle/maven dependency.

**Comment by maniac103** [comment]
Good point, but still we'd have the problem of the styling changes (in particular applying our themes and using the support lib AlertDialog). I'm not sure yet what a solution for that that's upstreamable could look like :-/

**Comment by mueller-ma** [comment]
> I'm not sure yet what a solution for that that's upstreamable could look like :-/

The material-about-library and the AboutLibrary use custom attributes to theme their ui elements. The library user can just overwrite these attributes: https://github.com/openhab/openhab-android/blob/master/mobile/src/main/res/values/themes.xml#L49

**Comment by maniac103** [comment]
Yes, but the MemorizingActivity does not show any custom UI elements. All it does is showing an AlertDialog...
