### ISSUE TITLE
Ignore SSL certificate and domain settings do not applies

### ISSUE THREAD

**Issue by magd1978** [openhab/openhab-android#810]
2.0.43-beta seems to have a little bug: When you configure openHab beta settings, if you tell it to ignore SSL certificate and domain, the value is not applied until you completely close the application from the task manager and reopen it.

**Comment by maniac103** [comment]
I know about this, and have prepared a fix already. Will submit a PR once #775 is merged.

**Comment by maniac103** [comment]
This was fixed with #819.
