### ISSUE TITLE
2.1 version of app sitemap img item refresh doesnt work

### ISSUE THREAD

**Issue by alokin79** [openhab/openhab-android#851]
Having refresh command in sitemap on camera feed, now stops working on the 2.1 version Android app

**Comment by mueller-ma** [comment]
Sitemap file:
````
Image url="http://192.168.2.209:50417/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=admin&pwd=pass" 	refresh=3000
````

**Comment by maniac103** [comment]
I'll try to reproduce this.

**Comment by maniac103** [comment]
@alokin79 What exactly do you mean by 'stops working' BTW? No refresh at all?

**Comment by maniac103** [comment]
Note to self: https://www.cctvview.info/Cameras has a number of URLs suitable for testing this (and also MJPEG).

**Comment by alokin79** [comment]
correct, i get picture from camera but NO refreash at all,  i have 3 android devices at home 2 phones 1 tablet.
Works in basic UI,classic UI on chrome browser.

**Comment by mueller-ma** [comment]
> official app

Now :) I might take some time until everyone receives the update.
