### ISSUE TITLE
2.1 version of app : No sitemap available

### ISSUE THREAD

**Issue by phil2fer** [openhab/openhab-android#852]
After upgrade to 2.1, i can't see my sitemap

my (unique) sitemap name : _default.sitemap
I think is related to this PR : https://github.com/openhab/openhab-android/pull/578

I don't know why but if i get my sitemap with the REST API, i have 2 sitemap with the same name (_default)

```
[
  {
    "name": "_default",
    "label": "Menu principal",
    "link": "http://192.168.1.40:8080/rest/sitemaps/_default",
    "homepage": {
      "link": "http://192.168.1.40:8080/rest/sitemaps/_default/_default",
      "leaf": false,
      "timeout": false,
      "widgets": []
    }
  },
  {
    "name": "_default",
    "label": "Home",
    "link": "http://192.168.1.40:8080/rest/sitemaps/_default",
    "homepage": {
      "link": "http://192.168.1.40:8080/rest/sitemaps/_default/_default",
      "leaf": false,
      "timeout": false,
      "widgets": []
    }
  }
]

```

I think i can solve this issue by renaming my sitemap, perhaps it's a bug in this commit https://github.com/openhab/openhab-android/pull/578/commits/f0339797748f7aae280337d45cf1f82612b12194

**Comment by mueller-ma** [comment]
The sitemap "_default" is auto generated with values of your things. Please rename your sitemap to "default".
 Can you open an issue in eclipse/smarthome? It should throw an error when naming a sitemap "_default"

**Comment by maniac103** [comment]
Still (IMHO) we shouldn't remove more than one _default sitemap. It's obviously not possible to choose the 'right' one in that case, but still we should only remove one of those two.

**Comment by mueller-ma** [comment]
> Can you open an issue in eclipse/smarthome?

I'm wrong: The sitemap `_default` is not part of esh https://github.com/eclipse/smarthome/issues/3006#issuecomment-279691002

I created https://github.com/openhab/openhab-core/issues/336. If that is a bug, we shouldnt change the app.
