### ISSUE TITLE
Spoken text not displayed anymore when using speech input

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab-android#866]
### Actual behaviour
When using speech input via the microphone icon (both in-app and widget), the recognized text is not displayed in a toast anymore. Started to occur after the latest app update. 

### Expected behaviour
The recognized text should be shown in a toast (as before the update), as else it is impossible to know if the correct command was recognized.

 
### Steps to reproduce
* Use microphone widget or microphone icon on top right corner of app
* Say any text
* -> No feedback

#### Client
* Android version: 7.1.1
* Device model: BQ Aquaris X Pro
* Stock or customized ROM: Stock
* App version Version 2.1.0 - 20.03.2018
* Device language: German

#### Server
* Server version: openHAB 2.3.0 Build #1246
* Reverse Proxy: no
* Authentication method: None

#### openHAB Cloud
* openHAB Cloud version: 2.3.0-SNAPSHOT
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method User and Password

**Comment by maniac103** [comment]
This is a regression of #775.

Note to self: run Toast.makeText().show() in main thread.

**Comment by mueller-ma** [comment]
@dominicdesu Can you test the fix? [mobile-full-stable-debug.zip](https://github.com/openhab/openhab-android/files/1989161/mobile-full-stable-debug.zip)
