### ISSUE TITLE
Using speech input always shows info toast that audio input will be sent to google

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab-android#867]
### Actual behaviour
When using speech input via the microphone icon (both in-app and widget), the app always shows a message that the audio input will be sent to google and saved in my google account.
![grafik](https://user-images.githubusercontent.com/3878009/39407624-29f6f482-4bc9-11e8-9ee9-4cf1925c52cb.png)

### Expected behaviour
The message should be displayed at most once, not every time the speech input feature is used.

 
### Steps to reproduce
* Use microphone widget or microphone icon on top right corner of app
* -> Toast is displayed in addition to the window waiting for speech input

#### Client

* Android version: 7.1.1
* Device model: BQ Aquaris X Pro
* Stock or customized ROM: Stock
* App version Version 2.1.0 - 20.03.2018
* Device language: German

#### Server
* Server version: openHAB 2.3.0 Build #1246
* Reverse Proxy: no
* Authentication method: None

#### openHAB Cloud
* openHAB Cloud version: 2.3.0-SNAPSHOT
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method User and Password

**Comment by maniac103** [comment]
Both the window and the toast are shown by the/a Google app, which we just invoke via intent. I don't think we have any control over that toast.

**Comment by dominicdesu** [comment]
Okay, thanks!
