### ISSUE TITLE
How do you disable openhab android app from phoning home?

### ISSUE THREAD

**Issue by jcdutton** [openhab/openhab-android#876]
### Actual behaviour
Describe us what happens

### Expected behaviour
Describe us what should happen

 
### Steps to reproduce
1. Describe us how to reproduce the issue
2. Use a list for it

#### Client
* Android version: 
* Device model: 
* Stock or customized ROM: 
* App version : 
* Build flavor : 
* Device language: 

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method : 

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: 
* Authentication method : 

#### App log
```
Insert your log here
```

#### openHAB Server log
```
Insert your log here
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here
```
```
Insert your reverse proxy access log here
```

**Comment by mueller-ma** [comment]
What makes you think the app is sending information to openHAB?
In case of a crash some information (device manufactor, android version) are sent to firebase. If you install the app (or any other app) the publisher will see these information in the google play console.
If you want to be sure no data is transmitted to openhab, feel free to download, inspect the code and compile your own apk.

**Comment by jcdutton** [comment]
While at home on wifi, the application is trying to reach ....amazonaws.com
I don't know what information it is sending, but it is periodically trying again and again.
I have a firewall preventing it.

**Comment by maniac103** [comment]
You don't have a Webview item showing by any chance, do you?

The app definitely doesn't try to reach anything at AWS by itself. If anything, there must be some trigger for that in your sitemap.

**Comment by jcdutton** [comment]
Here is my sitemap file that reproduces the problem.
I doubt this is the cause.
I will take some time and compile my own version of the android app and see if I can narrow down the problem. I am good at reverse engineering, if I need to go to that level.


sitemap our_home label="Our Home" {
    Frame {
        Group item=Garage
    }

    Frame {
        Text label="Power Outlet" icon="poweroutlet" {
            Default item=Garage_Power label="Garage"
        }
    }
}

**Comment by jcdutton** [comment]
What I have discovered so far.
The openhab android app from google play store tried to get to https://...amazonaws.com
openhab from f-droid does not.
https://f-droid.org/repo/org.openhab.habdroid_50.apk

The f-droid web site says:
"The builds on F-Droid have map view support, GCM and crash reporting removed and will not be able to receive push notifications from openHAB Cloud."
Maybe one of those options is contacting amazonaws.com

**Comment by maniac103** [comment]
Map view support is a no-op if your sitemap doesn't have Mapview items. GCM is only active (= registers your device with GCM) if myopenhab.org or another openhab-cloud instance is configured as remote URL - is that the case for you?

Also, what's the full contacted URL?

**Comment by jcdutton** [comment]
Summary:
The way I have found to stop the app trying to contact the internet at ...amazonaws.com is to install the openhab android app from F-Droid and not from Google Play store.

**Comment by jcdutton** [comment]
I have looked at the IP addresses, and the associated DNS requests.
It appears that it is trying to get to:
"settings.crashlytics.com"
DNS resolves that to:
A 174.129.0.44, A 54.243.245.38, A 107.20.220.57, A 107.20.224.161, A 107.21.109.56, A 174.129.209.245, A 184.73.159.232, A 107.22.253.20
It attempts to reach all those IP addresses.

So, maybe providing an app "settings" option to disable that might be nice.
The F-Droid version has "crash reporting removed", so my guess is that is the cause.

**Comment by mueller-ma** [comment]
> So, maybe providing an app "settings" option to disable that might be nice.

I agree it might look scary when the app tries to connect to some third party server, however Crashlytics is owned by Google and you are running an operation system made by Google, so adding an option that disables Crashlytics doesn't add much privacy. They "could spy" you anyway.
If you want to have a Google free version of the app, please use the version from F-Droid.
