### ISSUE TITLE
Unable to get exit from the app.

### ISSUE THREAD

**Issue by Sammaz2** [openhab/openhab-android#877]
### Actual behaviour
When i opened the openHAB opensource android app and then i started using the app and after that when i tried to leave the app and i tried to get back to homescreen by clicking the back button twice. But unfortunately I was not able to get exit from the app.

### Steps to reproduce
* First you have to download the app from fdroid.

* Then install the app.

* Open the app.

* Then try to get back to the homescreen.

* Click the back button twice. But unfortunately you will not be able to get back to the homescreen.

https://youtu.be/3y25frtgWtA

* Android version: 7.1.2
* Device model: Redmi 4
* Stock or customized ROM: Android
* App version:2.1.5-beta
* Device language: English

**Comment by mueller-ma** [comment]
You have full screen mode enabled, right? When I enable this the app is exited after pressing back four times.

**Comment by maniac103** [comment]
Those '4 times' need to happen in quick succession though (it's the 'panic mode', added in Android 7 IIRC). Without that, one can only swipe out the app from recents to get out of it. It's more of a feature than a buf though AFAICT.

**Comment by mueller-ma** [comment]
Right, this is intentional behavior: https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java#L997

**Comment by mueller-ma** [comment]
We could add a snackbar saying "Press back again to exit the app" in full screen.
