### ISSUE TITLE
Correct copyright note?

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#901]
In the about screen the following copyright note is shown:
````
© 2012 - <current year> openHAB Foundation
````
1. The foundation didn't exist in 2012
2. It's called `openHAB Foundation e. V.`
3. Is the foundation really the copyright holder?
4. Is it ok to change the copyright note during runtime?

@kaikreuzer

**Comment by kaikreuzer** [comment]
1. correct
2. correct
3. No. We usually write "openHAB Community" as copyright holder.
4. !? Why during runtime?

**Comment by mueller-ma** [comment]
> !? Why during runtime?

The "until" year is generated during runtime. The app could be built in 2018 and will show "2012 - 2019 ..." next year.

**Comment by kaikreuzer** [comment]
ok, that would be fine for me.
