### ISSUE TITLE
Clearing default sitemap takes affect after restarting the app

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#902]
### Actual behaviour
Clearing default sitemap takes affect after restarting the app

### Expected behaviour
Should take affect w/o restarting

 
### Steps to reproduce
1. Select a default sitemap
2. Open settings
3. Clear default sitemap
4. Go back
5. You should be asked

### Can you reproduce the issue in demo mode?

No, only one sitemap

#### Client
* Android version: Android 7.1
* Device model: Oneplus X
* Stock or customized ROM: LineageOS 14.1
* App version : 2.2.0
* Build flavor : Full
* Device language: en

#### Server
Client issue

#### App log
```
Nothing to see after leaving settings
```

**Comment by mueller-ma** [comment]
I have a fix here, but it feels to low level and rather a hack then a fix: https://github.com/mueller-ma/openhab.android/commit/278b0cf657adbf0c278f62896e8aa736d616bcbb

**Comment by maniac103** [comment]
Yes, it is. I think the correct fix is to check for the default sitemap pref being empty in the onResume method of the main activity and re-show the selection dialog if it's empty (and a connection is present).
