### ISSUE TITLE
External URL leads to error 500

### ISSUE THREAD

**Issue by RemcoteWinkel** [openhab/openhab-android#903]
No change in configuration of openhab. Opening app using remote URL results in 500 error. Log says 'default sitemap not found'

Copied a existing sitemap to default.sitemap

Error is now: openhab loaded empty sitemap

**Comment by RemcoteWinkel** [comment]
Email takes a long time to arrice. Here are the contents for the impatient (and my piece of mind, I guess):

Sorry for deleting the template. I am on OpenHAB 1.8. Opening the sitemaps over the LAN gives no error. External URL is: http://x.y.z:8080/openhab.app OpenHAB is user/pwd protected for outside connections. Before the app update there were no problems accessing OpenHAB remotely. Problems started yesterday after update. My action is to open the app on a network outside my LAN. Consequently the errors follow.

I have two versions of the sitemap. Both share the same problem. I will post the briefest one although it is not set as standard:


--BEGIN--

sitemap jl20o label="<home address> (Esther)"
{
    Frame label="Weer" {
        Text item=Weather_Temperature  
        Text item=v_Weather_Temperature 
        }
    Text  item=sHulp label="Grafieken"  icon="chart"{
        Frame label="Buiten" {             Chart item=Weather_Temperature label="Buiten temperatuur" period=D refresh=300000 }
        Frame label="Binnen" {             Chart item=t_huiskamer_corrected label="Binnen temperatuur" period=D refresh=300000}
    }
    Frame label="Control" {
            Selection item=LichtScene icon="switch"  mappings=[0="Maak keuze...........", 1="Alles uit", 2="Woonkamer", 3="Zolder", 4="Alles aan"]
            Selection item=ScreenScene icon="rollershutter"  mappings=[0="Maak keuze...........", 1="Beneden dicht", 2="Beneden open", 3="Boven dicht", 4="Boven open", 5="Alles dicht", 6="Alles open" ]
           
        }
               
    Frame label="Thermostaat" {
            Setpoint item=aTarget step=0.3 minValue=15 maxValue=30   
            Switch item=aCL mappings=[1="Uit", 2="Medium", 3="Comfort", 4="Hoog" ]
            Text item=Thermostaat label="Verwarming"       
            }               
           
    Frame label="Begane grond" {
                // Text item=t_huiskamer_corrected
                Text item=sensor_2_temp  label="Temperatuur  [%.1f °C]" icon="temperature"
                Text item=sensor_2_humidity label="Vochtigheid    [%.0f %%]"           
                Switch item=lStaan1
                Switch item=lTable1
                Switch item=lStaan2
                Switch item=rScreenLinks
                Switch item=rScreenRechts
                Switch item=rKeuken
                Setpoint item=w_ac_st icon="temperature" step=1 minValue=16 maxValue=28
                Switch item=w_ac_p icon="climate" label="Power"
                 }
                 
    Frame label="Kamer Esther" {
                Text item=t_v_2   
                Text item=v_d_2
                Setpoint item=e_ac_st icon="temperature" step=1 minValue=16 maxValue=28
                Switch item=e_ac_p icon="climate" label="Power"
                }
               
    Frame label="Kamer Remco" {
                Text item=t_v_3
                Text item=v_d_3
                Setpoint item=r_ac_st icon="temperature" step=1 minValue=16 maxValue=28
                Switch item=r_ac_p icon="climate" label="Power"
                }           
                     
// Einde sitemap         
}

--END--

**Comment by mueller-ma** [comment]
Can you enable debug mode in the app and make a screenshot of the error message after obfuscating your password with Paint?

**Comment by RemcoteWinkel** [comment]
Debugmode helped me locate the problem. External URL is wrong in my settings:

Was http://x.y.z:8080/openhab.app but should be http://x.y.z:8080/ as it is using the REST interface.

Please close this issue.
