### ISSUE TITLE
HTML file wont load in android app

### ISSUE THREAD

**Issue by wookie666** [openhab/openhab-android#907]
I have a HTML link that loads fine using my sitemaps when loading it using google chrome.

But in the app, this HTML link does not load

Its a pre configured widget from darksky weather. I have an example.html file in /var/lib in the webapps and weather layouts. That all works well and updates when i change the file.

But nothing to do with the example.html file is loading using the android app. Is this is a limitation of the android operating system, the app, or what?

my html file literally has one line 
<script type='text/javascript' src='https://darksky.net/widget/default/-33.771000,150.906300/ca12/en.js?width=100%&height=350&title=Blacktown&textColor=ffffff&bgColor=transparent&transparency=true&skyColor=bfbfbf&fontFamily=Default&customFont=&units=ca&htColor=cccccc&ltColor=636363&displaySum=yes&displayHeader=yes'></script>

**Comment by mueller-ma** [comment]
Can you post your sitemap?

**Comment by wookie666** [comment]
Here is my sitemap.
It might be a mistake on my end, Is the app supposed to show HTML information
`sitemap weather label="Weather"
{
Frame label="Weather"
{
Webview url="/weather?locationId=home&layout=example&iconset=colorful" height=13
Text item=LastUpdate icon="time" valuecolor=[LastUpdate>120="orange", LastUpdate>300="red"]
}

Frame label="Temperature"
                {
                Text item=Temperature icon="temperature" valuecolor=[LastUpdate=="Uninitialized"="lightgray",LastUpdate>90="lightgray",>77="orange",>60="green",>40="aqua",<=40="blue"] $
                Text item=Temp_Max icon="temperature" valuecolor=[>77="orange",>60="green",>40="aqua",<=40="blue"]
                Text item=Temp_Min icon="temperature" valuecolor=[>77="orange",>60="green",>40="aqua",<=40="blue"]
                }


}
`

**Comment by mueller-ma** [comment]
Where did you place the html file? Webviews with a relativ path are unsupported by the app. Fix: https://github.com/mueller-ma/openhab.android/commit/2b5b1627459adfd3c80ac16e98fd55e4c54b64e4

**Comment by maniac103** [comment]
> Fix: mueller-ma/openhab.android@2b5b162

Relative URLs are not guaranteed to start with a slash. If we fix this after the image refactoring, we can use the new HttpClient.buildUrl() method for that purpose.

**Comment by wookie666** [comment]
You guys are talking a language I don't understand quite yet. Is there something I can do with my ipenhab files to rectify this right now. Or is this an app related thing

My html file is in var/lib/openhab2/web-apps/weather/data/layouts

**Comment by maniac103** [comment]
A viable workaround for the moment should be making the URL absolute: `http://localhost:8080/static/weather?...` (or something among those lines, untested). We'll fix the handling of URLs in the app at some point so that relative URLs will work as well.

**Comment by wookie666** [comment]
as soon as i change it to localhost, or even try and use my public IP address, it doesn't load when i use openhab on a PC website. Doesn't load using phone either.

But if i have it like this in my sitemap, it works on chrome on PC, but i just get nothing on the phone
`Webview url="/weather?locationId=home&layout=example&iconset=colorful" height=13
`

**Comment by wookie666** [comment]
If i use localhost, the error on the page is localhost refused to connect
if i use my public ip, it says static/weather. Reason Not Found.

So what folder structure should the example.html files be in for static to work?

**Comment by mueller-ma** [comment]
@wookie666 Can you try this apk? [mobile-full-stable-debug.zip](https://github.com/openhab/openhab-android/files/2055918/mobile-full-stable-debug.zip)

Result from my testing. All request are done in the local wifi:

| Sitemap entry | Works in app w/ patch | w/o patch | Works in browser on mobile device |
| --- | --- | --- | --- |
| Webview url="http://openhab.local/static/index.html" height=10| X | X | X |
| Webview url="/static/index.html" height=10| X |   | X |
| Webview url="/index.html" height=10|   |   |   |
