### ISSUE TITLE
Image refresh does not work anymore (cached forever)

### ISSUE THREAD

**Issue by RolandRosenfeld** [openhab/openhab-android#928]
### Actual behaviour
After upgrade from 2.2.0 (release) to 2.2.5-beta (and in the meantime to 2.2.7-beta), images (Image type in sitemap) are no longer refreshed but seem to be cached forever.

### Expected behaviour
I use the refresh= parameter in the sitemap Image set to 60000 (60.000 ms=60 s) and now expect, that the images are updated once per minute, at least if I refresh the page by swiping down.  But nothing happens, the images are still cached.

Only way to refresh the images is by invalidating the cache via menu entry clear image cache ("Bilder-Cache leeren" in German).
 
### Steps to reproduce
1. Add something like this to your sitemap:
`Image url="http://www.uedorf.de/webcam/images/latest.jpg" refresh=60000
` 
  This is a webcam that refreshes its content every minute.
2. Open the Android app with this sitemap entry the first time. You see a little image icon with an hour glass, which is replaced by the webcam image after a second.
3. Wait some minutes.
4. Open the Android app with the sitemap entry again.  This time the webcam image is shown without delay or the little hour glass icon. But as you can see in the timestamp of the webcam, there was no refresh of the image.

#### Client
* Android version: 7.1.1
* Device model: Moto Z Play
* Stock or customized ROM: stock
* App version : 2.2.7-beta (2.2.0 release does **not** have this issue!)
* Build flavor : Full
* Device language: German

#### Server
* Server version: 2.2.0
* Reverse Proxy: Apache
* Authentication method : user/password

Greetings
Roland

**Comment by maniac103** [comment]
I think I know what's wrong: https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.java#L278 should pass AVOID_CACHE if it's a refresh. Should drop mCachingMode and determine that in execute().

I'll submit a PR. Looking at this being not the first time of refresh being broken, I wonder whether we should have a unit test for this ... I'm not yet sure how exactly one would go implementing that.

**Comment by dakipro** [comment]
This re-appeared again (should I make a new issue?).
I have image that is 30min refresh interval (weather forecast) and I now see that it is being cached from 27 of November. Running last stable app 2.4.0 (same for openhab) on android Note 8
