### ISSUE TITLE
Clientside audio playback

### ISSUE THREAD

**Issue by tobiasamon** [openhab/openhab-android#93]
Is there a way to play audio streams on the client side at the moment? For example to play a sound in habdroid when an event on the server is fired?
##

**Comment by cribskip** [comment]
I was working on TTS triggered by openhab but lost my path. Currently, there is no such thing

**Comment by tobiasamon** [comment]
So is the OpenHAB server able to notify any client (and also habdroid) that a sound has to be played?

**Comment by belovictor** [comment]
No, there is currently no standard way to do this in openHAB Android app. The only thing which comes to my mind is to use notifications through my.openHAB together with some app which would pronounce text of those notifications, like this one:
https://play.google.com/store/apps/details?id=com.pilot51.voicenotify&hl=en
Then you can send notification from openHAB through my.openHAB to your Android device and it will be spoken by this app.

**Comment by cribskip** [comment]
I just drafted together a prototype for you. It enables habdroid to read aloud what came as a notification if the messages starts with "speak ".

Didn't yet create a pull request as I'd first like to discuss this one. Also, your initial request was to play "an audio stream" - can you specify your request a little bit to me? Would you like to playSound a sound from openhab (like in /sounds) to your habdroid?

**Comment by tobiasamon** [comment]
My idea was that habdroid (and also any browser) should be able to play a file from a remote server (the openhab server). Audio files would have to be accessible through the webserver. Habdroid and browser should play the audio file when they receive a notification.

If you share your prototype, I could check if it fits my needs and maybe we can include it in habdroid.

**Comment by kaikreuzer** [comment]
This sounds like a bigger topic that might actually fit well into https://bugs.eclipse.org/bugs/show_bug.cgi?id=463802 - i.e. habdroid could be a sink for audio streams that can be used within rules. I hence wouldn't necessarily see this in openHAB 1.x.

**Comment by cribskip** [comment]
So, after a few years, I guess this should be made possible by using the webaudio backend just like HABpanel and Paper UI.

If I find some time, I'll look into this and post a PR.

**Comment by cribskip** [comment]
Just investigating on how the WebAudio works for habpanel:

1. Subscribe to <OH URL>/rest/events
2. Listening for topic "smarthome/webaudio/playurl"
3. Downloading the URL (payload) and playing the WAV

Example of message (TTS to webaudio sink):
```
event: message
data: {"topic":"smarthome/webaudio/playurl","payload":"\"/audio/799bcf5e-a817-49ce-adad-fd39c91fefff\"","type":"PlayURLEvent"}
```

Seems pretty forward, will look into this. I think this should be a seperate service running in the background and selectable in the preferences.

I'll wait for #562 to be merged as I guess it will be smoother to implement then.

**Comment by mueller-ma** [comment]
Is anyone still interested in seeing this implemented?
