### ISSUE TITLE
REST API and plain text password

### ISSUE THREAD

**Issue by rolls01** [openhab/openhab-android#935]
### Actual behaviour
After open openHAB application shows HTTP 500 and you can notice
 REST API URL: https://myopenhab.org/rest/bindings
Username: plain text
Password: plain text
Exception stack: java.io.IOException: openHAB is offline

### Expected behaviour
As right now RPi 3 is disconnected, should show no connected devices.

 
### Steps to reproduce
1. Describe us how to reproduce the issue
2. Use a list for it
RPi is turned down or offline
run openHAB on android mobile phone
Details and print screen:
https://community.openhab.org/t/http-500-password-plain-text/46933/6

### Can you reproduce the issue in demo mode?
no

#### Client
* Android version: 8.0.0
* Device model: Galaxy A5 (2017)
* Stock or customized ROM: -
* App version 2.2.0
* Build flavor Full
* Device language: PL

#### Server
* Server version: 
* Reverse Proxy: 
* Authentication method 

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method 443, user and password

#### App log
```
Insert your log here
```

#### openHAB Server log
```
Insert your log here
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here
```
```
Insert your reverse proxy access log here
```

**Comment by maniac103** [comment]
The plain text password display is something you probably have enabled yourself - to disable, to go settings -> show debug messages (last item) -> uncheck.

**Comment by rolls01** [comment]
yes, that is workaround

**Comment by maniac103** [comment]
No, it's the actual fix. Why would you want to enable an option whose summary clearly states cleartext passwords will be shown if you fear cleartext passwords to be shown?

**Comment by mueller-ma** [comment]
I actually see two issues here:
1. Passwords can be made visible by enabling the debug mode. We cannot be more clear about the debug mode. The description says `Passwords will be shown in clear text!`. It can be discussed if enabling debug mode should clear passwords.
2. The generic error message is shown, when openHAB is offline. I'm working on a fix for that.
