### ISSUE TITLE
Sitemap not shown while in notifications

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#950]
### Actual behaviour
When trying to switch to a sidemap from the Side Menu while in notification list, this results only in the Side Menu being closed.

### Expected behaviour
When selecting a sitemap from the Side Menu, the app should exit the notification list and show the selected sitemap.
 
### Steps to reproduce
1. Open App, Enter Notifications from Side Menu
2. Try to switch sitemap from the Side Menu

#### Client
* Android version: 6.0.1
* Device model: Xiaomi Redmi 4 Prime
* Stock or customized ROM: Stock
* App version : 2.2.13-Beta
* Build flavor : Full
* Device language: German

#### Server
* Server version: 2.4.0~20180701105417-1
* Reverse Proxy: -
* Authentication method : user & passwd

#### openHAB Cloud
* openHAB Cloud version: ?
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method : user & passwd

**Comment by mueller-ma** [comment]
When in settings or about the drawer cannot be opened at all by swiping. I'd suggest to lock it here as well or unlock it in settings and about.

**Comment by cribskip** [comment]
From the UX perspective, I'd prefer to close the foreground activity (notificcations, settings, about) and display the selected sitemap as this is faster (less touches) than going back, opening the side menu and then select the sitemap.

**Comment by mueller-ma** [comment]
Also applies to habpanel now.
