### ISSUE TITLE
Sitemap icons flash when opening side menu

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#951]
### Actual behaviour
When opening the Side Menu, the icons of the sitemaps show, then quickly flash, then persist.
Upon the next opening of the Menu, this repeats.

### Expected behaviour
Icons should not flash up.
 
### Steps to reproduce
1. Open App
2. Open Side Menu

### Can you reproduce the issue in demo mode?
No. Maybe this issue only shows when multiple sitemaps are available and/or the sitemap icon is set.

#### Client
* Android version: 6.0.1
* Device model: Xiaomi Redmi 4 Prime
* Stock or customized ROM: Stock
* App version : 2.2.13-Beta
* Build flavor : Full
* Device language: German

#### Server
* Server version: 2.4.0~20180701105417-1
* Reverse Proxy: -
* Authentication method : user & passwd

#### openHAB Cloud
* openHAB Cloud version: ?
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method : user & passwd

**Comment by cribskip** [comment]
Installed 2.2-22 yesterday, Issue still exists

**Comment by mueller-ma** [comment]
I cannot reproduce this anymore with 2.3.3. @cribskip do the icons still flash on your phone?

**Comment by cribskip** [comment]
Just verified, not happening anymore. thanks
