### ISSUE TITLE
Random icon permutation

### ISSUE THREAD

**Issue by RolandRosenfeld** [openhab/openhab-android#955]
### Actual behaviour
Sometimes some icons are replaces by other icons.

### Expected behaviour
I expect that the correct icons are shown.
 
### Steps to reproduce
1. Install 2.2.16-beta APK. 
2. Open openHAB beta
3. Have a look at the icons.
4. scroll up/down, enter a submenu and return to main menu.
5. have a look a the icons, some may have changed.
6. repeat 4./5. and some of the icons may randomly change.

### Can you reproduce the issue in demo mode?
yes, see screenshot of the demo mode, where I pasted three views (with different shuffled icons) side by side: https://www.spinnaker.de/tmp/screenshots-openhab-2.2.16-iconshuffle.png

#### Client
* Android version: 8.0.0
* Device model: Moto Z Play
* Stock or customized ROM: stock
* App version: 2.2.16-beta
* Build flavor: Full
* Device language: German

**Comment by s0170071** [comment]
Same in 17 beta

**Comment by maniac103** [comment]
I can reproduce, will look at it as soon as I get to it.
