### ISSUE TITLE
Tablets landscape mode: open drawer/subpane automatically

### ISSUE THREAD

**Issue by curlyel** [openhab/openhab-android#96]
I'd like to share some ideas regarding automatically opening one of the drawers (if there are any) when launching the app or dependend on specific items. 

Current behaviour:
In landscape mode on tablets habdroid currently starts showing screen-wide rows of items. This layout is changing into a two-column design when one of the group items/drawers is selected.

It would be great, if this behaviour could be changed to:

Proposal #1:
If there is at least one item in the main menu representing a drawer/subpane, simply select the first of it and show its submenu/content in the second column.

Proposal #2:
Make the decision, which drawer is to be opened dependend on a string item ("drawer-selection-item", for example having the same name as the sitemap it refers to).

Proposal #3:
Observe changes of the "drawer-selection-item" indroduced in #2 permanently and switch automatically to that drawer regarding to the actual content of the item.

Implementing #3 will enable some use cases where wall mounted tablets may react quite smart on events like:
- doorbell is ringing: show controls for the door and the door video
- some alarm occurs: automatically show the relevant sub pane containing the status of all the sensors
- somebody enters the room: automatically switch to the pane containing the controls for that room.

I'd like to hear if others find it valuable too - or if I just missed the right clue and there is a way of solving it already ;-)
##

**Comment by mueller-ma** [comment]
What about just displaying two rows of items like the oh2 web ui does?
