### ISSUE TITLE
CHANGELOG.md is out of date n/t

### ISSUE THREAD

**Issue by Matrixcoffee** [openhab/openhab-android#971]

**Comment by mueller-ma** [comment]
Please see https://github.com/openhab/openhab-android/releases. I guess I should delete CHANGELOG.md

**Comment by Matrixcoffee** [comment]
Yes, I found that as well. Had a hard time figuring out what the meaningful difference between the stable versions is, though.

**Comment by mueller-ma** [comment]
The changes between stable versions are summarized and added to Google Play and the GitHub release. If you want to see the changes in detail, you can go through all changeslogs on the beta releases since the last stable

**Comment by Matrixcoffee** [comment]
I see. Thanks for explaining.
