### ISSUE TITLE
Image refresh broken

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#985]
### Actual behaviour
Image items without the refresh parameter doen't refresh, when swiped-to-refresh.

### Expected behaviour
They should refresh.

#### Client
* Android version: Android 7.1.2
* Device model: Moto G4
* Stock or customized ROM: LineageOS 14
* App version : 2.2.19
* Build flavor : Foss
* Device language: de

@maniac103 I experience this issue on multiple devices, but have no time to debug it right now.

**Comment by mueller-ma** [comment]
It seems that also images with a refresh parameter don't refresh. Usually I see a lot of these messages `I/WidgetImageView: Refreshing image at https://ip:8443/proxy?sitemap=demo2.sitemap&widgetId=00110000`, but after change device orientation or leaving and re-entering the subpage, those messages don't appear again.

**Comment by maniac103** [comment]
@mueller-ma Please give the above PR a try.

**Comment by mueller-ma** [comment]
Sure, will do so next week
